### ISSUE TITLE
avr/DA/DB/DD

### ISSUE THREAD

**Issue by nbnaudb** [knolleary/pubsubclient#1007]
Will the library work properly with the avr/DA/DB/DD ?

**Comment by knolleary** [comment]
Unlikely. This library was written for Arduino/ESP compatible devices. Someone may be able to get it working with other hardware, but that isn't something I'm able to help with.

**Comment by nbnaudb** [comment]
if he uses the dxcore core (Arduino core for AVR DA, DB,  DD-series)and the Arduino IDE, can it change the situation?

**Comment by knolleary** [comment]
I do not know. I have no experience with that. All I can suggest is to try it and see!
