### ISSUE TITLE
Arduino Mega R3 + w5100 ethernet schild/ pubsubclient  / Arduino 1.6.5

### ISSUE THREAD

**Issue by maxtox** [knolleary/pubsubclient#101]
Hi,

everytime , i get this compiling error message..

In file included from D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient\BDDTest.cpp:2:0:
D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient\trace.h:3:20: fatal error: iostream: No such file or directory
 #include <iostream>

is it "normal"??? never had that before (error with iostream)

Thanks in advance!

**Comment by knolleary** [comment]
How did you install the library? The files BDDTest.cpp and trace.h live under `PubSubClient/tests/src/lib`, so I'm not sure how it has ended up in the path your error message reports.

**Comment by maxtox** [comment]
ok...will check right now... hold on...

**Comment by maxtox** [comment]
looks better now...
i used up till now this code:

http://www.stall.biz/wp/wp-content/uploads/2015/07/hduino412_WLAN.zip

now i want to switch to MQTT with iobroker from iobroker.net using MQTT as client and as server... using node-red too!!!!

could you look into the code and tell if it is easy to convert it to MQTT?

I want to use arduino as a node and client in one! so i just need the MQTT server!

Thank you in advance!

**Comment by knolleary** [comment]
Have you resolve the compile issue then?

sorry, I'm not likely to have the time to pick through that code any time soon.

**Comment by maxtox** [comment]
some other errors...but i think it has another reason!!!

Thank you anyway!!!

**Comment by maxtox** [comment]
hi...

stil getting errors while compiling...
C:\Users\MAXTOX\Documents\Arduino\sketch_dec23d\sketch_dec23d.ino: In function 'void setup()':

sketch_dec23d:46: error: no matching function for call to 'PubSubClient::PubSubClient(const char [9], int, void (&)(char*, byte*, unsigned int))'

   client = PubSubClient(MQTT_SERVER, 1883, callback);

                                                    ^

C:\Users\MAXTOX\Documents\Arduino\sketch_dec23d\sketch_dec23d.ino:46:52: note: candidates are:

In file included from C:\Users\MAXTOX\Documents\Arduino\sketch_dec23d\sketch_dec23d.ino:2:0:

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:103:4: note: PubSubClient::PubSubClient(const char*, uint16_t, void (*)(char*, uint8_t*, unsigned int), Client&, Stream&)

    PubSubClient(const char*, uint16_t, MQTT_CALLBACK_SIGNATURE,Client& client, Stream&);

    ^

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:103:4: note:   candidate expects 5 arguments, 3 provided

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:102:4: note: PubSubClient::PubSubClient(const char*, uint16_t, void (*)(char*, uint8_t*, unsigned int), Client&)

    PubSubClient(const char*, uint16_t, MQTT_CALLBACK_SIGNATURE,Client& client);

    ^

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:102:4: note:   candidate expects 4 arguments, 3 provided

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:101:4: note: PubSubClient::PubSubClient(const char*, uint16_t, Client&, Stream&)

    PubSubClient(const char*, uint16_t, Client& client, Stream&);

    ^

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:101:4: note:   candidate expects 4 arguments, 3 provided

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:100:4: note: PubSubClient::PubSubClient(const char*, uint16_t, Client&)

    PubSubClient(const char*, uint16_t, Client& client);

    ^

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:100:4: note:   no known conversion for argument 3 from 'void(char*, byte*, unsigned int) {aka void(char*, unsigned char*, unsigned int)}' to 'Client&'

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:99:4: note: PubSubClient::PubSubClient(uint8_t*, uint16_t, void (*)(char*, uint8_t*, unsigned int), Client&, Stream&)

    PubSubClient(uint8_t *, uint16_t, MQTT_CALLBACK_SIGNATURE,Client& client, Stream&);

    ^

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:99:4: note:   candidate expects 5 arguments, 3 provided

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:98:4: note: PubSubClient::PubSubClient(uint8_t*, uint16_t, void (*)(char*, uint8_t*, unsigned int), Client&)

    PubSubClient(uint8_t *, uint16_t, MQTT_CALLBACK_SIGNATURE,Client& client);

    ^

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:98:4: note:   candidate expects 4 arguments, 3 provided

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:97:4: note: PubSubClient::PubSubClient(uint8_t*, uint16_t, Client&, Stream&)

    PubSubClient(uint8_t *, uint16_t, Client& client, Stream&);

    ^

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:97:4: note:   candidate expects 4 arguments, 3 provided

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:96:4: note: PubSubClient::PubSubClient(uint8_t*, uint16_t, Client&)

    PubSubClient(uint8_t *, uint16_t, Client& client);

    ^

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:96:4: note:   no known conversion for argument 3 from 'void(char*, byte*, unsigned int) {aka void(char*, unsigned char*, unsigned int)}' to 'Client&'

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:95:4: note: PubSubClient::PubSubClient(IPAddress, uint16_t, void (*)(char*, uint8_t*, unsigned int), Client&, Stream&)

    PubSubClient(IPAddress, uint16_t, MQTT_CALLBACK_SIGNATURE,Client& client, Stream&);

    ^

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:95:4: note:   candidate expects 5 arguments, 3 provided

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:94:4: note: PubSubClient::PubSubClient(IPAddress, uint16_t, void (*)(char*, uint8_t*, unsigned int), Client&)

    PubSubClient(IPAddress, uint16_t, MQTT_CALLBACK_SIGNATURE,Client& client);

    ^

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:94:4: note:   candidate expects 4 arguments, 3 provided

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:93:4: note: PubSubClient::PubSubClient(IPAddress, uint16_t, Client&, Stream&)

    PubSubClient(IPAddress, uint16_t, Client& client, Stream&);

    ^

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:93:4: note:   candidate expects 4 arguments, 3 provided

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:92:4: note: PubSubClient::PubSubClient(IPAddress, uint16_t, Client&)

    PubSubClient(IPAddress, uint16_t, Client& client);

    ^

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:92:4: note:   no known conversion for argument 3 from 'void(char*, byte*, unsigned int) {aka void(char*, unsigned char*, unsigned int)}' to 'Client&'

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:91:4: note: PubSubClient::PubSubClient(Client&)

    PubSubClient(Client& client);

    ^

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:91:4: note:   candidate expects 1 argument, 3 provided

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:90:4: note: PubSubClient::PubSubClient()

    PubSubClient();

    ^

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:90:4: note:   candidate expects 0 arguments, 3 provided

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:70:7: note: constexpr PubSubClient::PubSubClient(const PubSubClient&)

 class PubSubClient {

       ^

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:70:7: note:   candidate expects 1 argument, 3 provided

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:70:7: note: constexpr PubSubClient::PubSubClient(PubSubClient&&)

D:\03_Daten\07_Arduino\ORIGArduino\libraries\PubSubClient/PubSubClient.h:70:7: note:   candidate expects 1 argument, 3 provided

**Comment by knolleary** [comment]
Is this an active issue or can we close it?

**Comment by maxtox** [comment]
please close it!
Thank you!
