### ISSUE TITLE
MQTT using ESP8266 but on the Arduino not ESP8266 

### ISSUE THREAD

**Issue by AdamMiltonBarker** [knolleary/pubsubclient#102]
How do you run the client on the Arduino and not actually on the ESP8266, it took me about a week to work out how to get the ESP8266  connected to my network, built up the code to monitor all the sensors connected to my arduino only to find it doesn't seem possible. I am getting this error from trying to run the example. 

Build options changed, rebuilding all
mqtt_esp8266.ino:26:25: fatal error: ESP8266WiFi.h: No such file or directory
compilation terminated.
Error compiling.

Also I don't see anyway of adding username or password for authentication to the broker, really regretting getting the ESP8266.

**Comment by knolleary** [comment]
Hi,

The esp8266 example is for running on the esp itself, with no arduino involved. I've not looked at using it on  the arduino, making use of an attached esp.

How does the arduino control the esp? Presumably over its serial interface? The PubSubClient will work with any hardware that provides an implementation of the Arduino's Client.h header. If such a thing exists for when using the esp to provide network to the Arduino, then that is what you need.

**Comment by AdamMiltonBarker** [comment]
Hi just got the ESP8266 working basically as you say using the serial I am just looking to find a way of connecting to an mqtt broker once connection is established cannot believe something so simple can be so hard, do you have any ideas of how this can be done I am so held up by this it is untrue. This is the code:



#include <SoftwareSerial.h>
#define SSID        ""
#define PASS        ""
#define DST_IP      "220.181.111.85"    //baidu.com
SoftwareSerial dbgSerial(2, 3); // RX, TX

void setup()
{
   // Open serial communications and wait for port to open:
   Serial.begin(57600);
   Serial.setTimeout(5000);
   dbgSerial.begin(9600); //can't be faster than 19200 for softserial
   dbgSerial.println("ESP8266 Demo");
   //test if the module is ready
   Serial.println("AT+RST");
   delay(1000);
   if(Serial.find("ready"))
   {
     dbgSerial.println("Module is ready");
   }
   else
   {
     dbgSerial.println("Module have no response.");
     while(1);
   }
   delay(1000);
   //connect to the wifi
   boolean connected=false;
   for(int i=0;i<5;i++)
   {
     if(connectWiFi())
     {
       connected = true;
       break;
     }
   }
   if (!connected){while(1);}
   delay(5000);
   //print the ip addr
   /*Serial.println("AT+CIFSR");
   dbgSerial.println("ip address:");
   while (Serial.available())
     dbgSerial.write(Serial.read());*/
     //set the single connection mode
     Serial.println("AT+CIPMUX=0");
}
void loop()
{
 String cmd = "AT+CIPSTART=\"TCP\",\"";
 cmd += DST_IP;
 cmd += "\",80";
 Serial.println(cmd);
 dbgSerial.println(cmd);
 if(Serial.find("Error")) return;
 cmd = "GET / HTTP/1.0\r\n\r\n";
 Serial.print("AT+CIPSEND=");
 Serial.println(cmd.length());
 if(Serial.find(">"))
 {
   dbgSerial.print(">");
 }else
 {
 Serial.println("AT+CIPCLOSE");
 dbgSerial.println("connect timeout");
 delay(1000);
 return;
 }
 Serial.print(cmd);
 delay(2000);
 //Serial.find("+IPD");
 while (Serial.available())
 {
   char c = Serial.read();
   dbgSerial.write(c);
   if(c=='\r') dbgSerial.print('\n');
 }
 dbgSerial.println("====");
 delay(1000);
}
boolean connectWiFi()
{
   Serial.println("AT+CWMODE=1");
   String cmd="AT+CWJAP=\"";
   cmd+=SSID;
   cmd+="\",\"";
   cmd+=PASS;
   cmd+="\"";
   dbgSerial.println(cmd);
   Serial.println(cmd);
   delay(2000);
   if(Serial.find("OK"))
   {
     dbgSerial.println("OK, Connected to WiFi.");
     return true;
   }else
   {
     dbgSerial.println("Can not connect to the WiFi.");
     return false;
   }
}

**Comment by knolleary** [comment]
A quick Google search on my phone found this: https://github.com/semiotproject/SparkFun_ESP8266_AT_Arduino_Library which appears to provide the Client.h implementation you need in the shape of `SparkFunESP8266Client`

Pass an instance of one of those to PubSubClient and it may just work. I don't have a spare esp with the AT firmware on laying around to try it out, but hopefully it ought to just work if my cursory look at the SparkFun library is correct.

**Comment by knolleary** [comment]
Hopefully my previous comment has helped point you in the right direction - would be interested to hear how you get on. In the meantime, as this is not an issue with the library itself, I'm going to close this.

**Comment by AkSuganthan** [comment]
@AdamMiltonBarker 

 I am also facing the same problem.Did u solve it. 
 if yes
Pls share your code

**Comment by AdamMiltonBarker** [comment]
No sorry issue not closed yet. Have found out with Wifi101 it is due to the ca chain being from Comodo as they are too good for the current setup which is limited at 1.1 is the case here can you connect to a TLS 1.2 broker ?

**Comment by AdamMiltonBarker** [comment]
In comparison I now have apps on RPI, Intel Galileo, the web, Macs, PCs all able to connect through either Python or Node JS and either on port 8883 or 90001 for websockets so far every single arduino / esp8266 library I have found cannot connect.

**Comment by AdamMiltonBarker** [comment]
I got mixed up between which Issue I was on, I moved from trying to use the Arduino with ESP8266 to just working directly on the ESP8266 I did have some issues connecting to a secure broker but this was fixed with this article. 

http://www.radupascal.com/2016/04/03/esp8266-arduino-iot-hub
