### ISSUE TITLE
Cannot connect from Arduino with esp8266 wifi shield

### ISSUE THREAD

**Issue by Suxsem** [knolleary/pubsubclient#107]
Hi. I found an interesting comment (https://github.com/knolleary/pubsubclient/issues/102#issuecomment-167447871) suggesting that is possible to use the esp8266 as a wifi shield to the Arduino, and pass the ESP8266Client object to the PubSubClient constructor.

Unfortunately, when i try to connect, the command always fail.

(part of the) CODE:
```
#include <PubSubClient.h>
#include <SparkFunESP8266WiFi.h>

ESP8266Client wclient;
PubSubClient client(MQTTip, MQTTport, mqttDataCb, wclient);

void setup() {

  [stuff to start the esp8266 and connect to wifi]

  if (esp8266.status() > 0) { //wifi connected
      debugSerial.println("wifi connected");
      if (client.connect(MQTTid, MQTTuser, MQTTpsw, MQTTid "/status", 2, true, "0")) {
          debugSerial.println("mqtt connected");
      }
  }

}
```

Mosquitto log:
```
1451996248: New connection from 192.168.1.107 on port 1883.
1451996278: Socket error on client <unknown>, disconnecting.
```

I always get "wifi connected", but never "mqtt connected"

I'm using HARDWARE serial between arduino and the esp8266 with a 2400 baud rate (for a better communication and to prevent arduino serial buffer to fill)

The wifi library I'm using is the official sparkfun one (https://github.com/sparkfun/SparkFun_ESP8266_AT_Arduino_Library)

Any suggestion?
Thanks!

**Comment by Suxsem** [comment]
After a lot of digging a found two major problems:

1) the write method of the ESP8266Client object wants a null terminated string, also if size is provided as a second argument.

I fixed this, and now I can successfully connect to the broker.
I don't waste time publishing the fix due to problem (2):

2) incredibly the read method of the ESP8266Client object doesn't do anything more then returning Serial.read (that includes all the AT firmware responses, packets from other sockets and so on). This makes the SparkFun_ESP8266_AT_Arduino_Library completely unsuitable to provide a Client object that does something useful.

To fix the second problem something like this should be done:
- disable the multiple sockets support
- add a tcp buffer into the ESP8266Client object
- implement a real read() method that filters out all AT responses without breaking any command handshake

I will stop there and I will move my entire logic on the esp8266, using the Arduino only to read sensors and drive actuators, using a custom made serial communication protocol between the Arduino and the esp.

**Comment by knolleary** [comment]
So it sounds like `SparkFunESP8266WiFi` isn't as useful as I'd hoped. Thanks for digging into it - can reference back to this issue if anyone asks about this again.

**Comment by sharma-abhishek** [comment]
@knolleary Thanks for  reference to this issue#107. This was really helpful in connecting to MQTT.
Following the first point in @Suxsem comment, I am able to connect to MQTT broker. However, while publishing, it always fails. 

Any suggestions on this?

Thanks,
Abhishek

**Comment by knolleary** [comment]
@sharma-abhishek in his second comment, @suxsem quite clearly describes the issues with `SparkFunESP8266WiFi`. I don't think anything has changed with that.

**Comment by sharma-abhishek** [comment]
@knolleary Yup, looks like they havent made any changes since then. Thanks for the help, very much appreciated.

**Comment by lehighkid** [comment]
@knolleary while it appears that the SparkFunESP8266WiFi library won't work, I was curious if anyone has looked at the blynk library where they have an example using ESP8266 over hard & soft serial to send their data.  I haven't been able to make use of the connection yet but they do have a blynk.connectWiFi method.  Any thoughts on potentially using that?  Or would it be much of the same issue?

**Comment by knolleary** [comment]
@lehighkid it's quite simple. If they have an implementation of the standard arduino `Client.h` interface for network clients then it will work. If they don't have one of those, it won't work. I'm not familiar with the blynk library, but a quick look at https://github.com/blynkkk/blynk-library/blob/master/BlynkSimpleShieldEsp8266_HardSer.h shows it isn't a `Client.h` implementation.

**Comment by AkSuganthan** [comment]
@knolleary 
                 I am person who contact you over twitter. I follow your instructions but still I am face the Problem.
           
Note : I upload my code in arduino leonardo not in my esp8266

My code is

#include <WiFi.h>
#include <WiFiClient.h>
#include <WiFiServer.h>
#include <WiFiUdp.h>

#include <SPI.h>

#include <ESP8266wifi.h>

/*
 Basic ESP8266 MQTT example

 This sketch demonstrates the capabilities of the pubsub library in combination
 with the ESP8266 board/library.

 It connects to an MQTT server then:
  - publishes "hello world" to the topic "outTopic" every two seconds
  - subscribes to the topic "inTopic", printing out any messages
    it receives. NB - it assumes the received payloads are strings not binary
  - If the first character of the topic "inTopic" is an 1, switch ON the ESP Led,
    else switch it off

 It will reconnect to the server if the connection is lost using a blocking
 reconnect function. See the 'mqtt_reconnect_nonblocking' example for how to
 achieve the same result without blocking the main loop.

 To install the ESP8266 board, (using Arduino 1.6.4+):
  - Add the following 3rd party board manager under "File -> Preferences -> Additional Boards Manager URLs":
       http://arduino.esp8266.com/stable/package_esp8266com_index.json
  - Open the "Tools -> Board -> Board Manager" and click install for the ESP8266"
  - Select your ESP8266 in "Tools -> Board"

*/

#include <ESP8266WiFi.h>
#include <PubSubClient.h>

// Update these with values suitable for your network.

const char* ssid = "........";
const char* password = "........";
const char* mqtt_server = "m10.cloudmqtt.com";

WiFiClient espClient;
PubSubClient client(espClient);
long lastMsg = 0;
char msg[50];
int value = 0;
int BUILTIN_LED=13;
bool isconeccted=false;
void setup() {
  pinMode(BUILTIN_LED, OUTPUT);     // Initialize the BUILTIN_LED pin as an output
  Serial.begin(9600);
  Serial1.begin(115200);
  
}

void setup_wifi() {

  delay(10);
  // We start by connecting to a WiFi network
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);

/*  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());*/
    Serial.println("WiFi connected");
}

void callback(char* topic, byte* payload, unsigned int length) {
  Serial.print("Message arrived [");
  Serial.print(topic);
  Serial.print("] ");
  for (int i = 0; i < length; i++) {
    Serial.print((char)payload[i]);
  }
  Serial.println();

  // Switch on the LED if an 1 was received as first character
  if ((char)payload[0] == '1') {
    digitalWrite(BUILTIN_LED, LOW);   // Turn the LED on (Note that LOW is the voltage level
    // but actually the LED is on; this is because
    // it is acive low on the ESP-01)
  } else {
    digitalWrite(BUILTIN_LED, HIGH);  // Turn the LED off by making the voltage HIGH
  }

}

void reconnect() {
  // Loop until we're reconnected
  while (!client.connected()) {
    Serial.print("Attempting MQTT connection...");
    // Attempt to connect
    if (client.connect("36988521ESP8266Client","aighrtcv","fFX-Fv35IQNY"))
    {
      Serial.println("connected");
      // Once connected, publish an announcement...
      client.publish("outTopic", "hello world");
      // ... and resubscribe
      client.subscribe("inTopic");
    }
    else {
      Serial.print("failed, rc=");
      Serial.print(client.state());
      Serial.println(" try again in 5 seconds");
      // Wait 5 seconds before retrying
      delay(5000);
    }
  }
}
void loop() {
  if (Serial.available()) 
   {
     String str = Serial.readStringUntil('\n');
     str.trim();
     Serial.println("");
     Serial.println("You sent: " + str);
   
     if(str.equals("1"))
     {
      setup_wifi();
      client.setServer(mqtt_server, 13311);
      client.setCallback(callback);
      isconeccted=true;
     }
     else
      Serial1.println(str);
     
   }
   if (Serial1.available()) 
   {
    String ser0 = Serial1.readStringUntil('\n');
     ser0.trim();
     
     Serial.println(ser0);
   }
  
  if(isconeccted)
  {
    if (!client.connected()) {
    reconnect();
  }
    client.loop();

    long now = millis();
    if (now - lastMsg > 2000) 
    {
     lastMsg = now;
     ++value;
     snprintf (msg, 75, "hello world #%ld", value);
     Serial.print("Publish message: ");
     Serial.println(msg);
     client.publish("outTopic", msg);
    }
  }
}


Please help me in this

**Comment by AkSuganthan** [comment]
I am person who contact you over twitter. I follow your instructions but still I am face the Problem.

Note : I upload my code in arduino leonardo not in my esp8266

My code is
---------------------------------------------------------------------
#include <WiFi.h>
#include <WiFiClient.h>
#include <WiFiServer.h>
#include <WiFiUdp.h>

#include <SPI.h>

#include <ESP8266wifi.h>

/*
 Basic ESP8266 MQTT example

 This sketch demonstrates the capabilities of the pubsub library in combination
 with the ESP8266 board/library.

 It connects to an MQTT server then:
  - publishes "hello world" to the topic "outTopic" every two seconds
  - subscribes to the topic "inTopic", printing out any messages
    it receives. NB - it assumes the received payloads are strings not binary
  - If the first character of the topic "inTopic" is an 1, switch ON the ESP Led,
    else switch it off

 It will reconnect to the server if the connection is lost using a blocking
 reconnect function. See the 'mqtt_reconnect_nonblocking' example for how to
 achieve the same result without blocking the main loop.

 To install the ESP8266 board, (using Arduino 1.6.4+):
  - Add the following 3rd party board manager under "File -> Preferences -> Additional Boards Manager URLs":
       http://arduino.esp8266.com/stable/package_esp8266com_index.json
  - Open the "Tools -> Board -> Board Manager" and click install for the ESP8266"
  - Select your ESP8266 in "Tools -> Board"

*/

#include <ESP8266WiFi.h>
#include <PubSubClient.h>

// Update these with values suitable for your network.

const char* ssid = "........";
const char* password = "........";
const char* mqtt_server = "m10.cloudmqtt.com";

WiFiClient espClient;
PubSubClient client(espClient);
long lastMsg = 0;
char msg[50];
int value = 0;
int BUILTIN_LED=13;
bool isconeccted=false;
void setup() {
  pinMode(BUILTIN_LED, OUTPUT);     // Initialize the BUILTIN_LED pin as an output
  Serial.begin(9600);
  Serial1.begin(115200);
  
}

void setup_wifi() {

  delay(10);
  // We start by connecting to a WiFi network
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);

/*  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());*/
    Serial.println("WiFi connected");
}

void callback(char* topic, byte* payload, unsigned int length) {
  Serial.print("Message arrived [");
  Serial.print(topic);
  Serial.print("] ");
  for (int i = 0; i < length; i++) {
    Serial.print((char)payload[i]);
  }
  Serial.println();

  // Switch on the LED if an 1 was received as first character
  if ((char)payload[0] == '1') {
    digitalWrite(BUILTIN_LED, LOW);   // Turn the LED on (Note that LOW is the voltage level
    // but actually the LED is on; this is because
    // it is acive low on the ESP-01)
  } else {
    digitalWrite(BUILTIN_LED, HIGH);  // Turn the LED off by making the voltage HIGH
  }

}

void reconnect() {
  // Loop until we're reconnected
  while (!client.connected()) {
    Serial.print("Attempting MQTT connection...");
    // Attempt to connect
    if (client.connect("36988521ESP8266Client","My Id","My password"))
    {
      Serial.println("connected");
      // Once connected, publish an announcement...
      client.publish("outTopic", "hello world");
      // ... and resubscribe
      client.subscribe("inTopic");
    }
    else {
      Serial.print("failed, rc=");
      Serial.print(client.state());
      Serial.println(" try again in 5 seconds");
      // Wait 5 seconds before retrying
      delay(5000);
    }
  }
}
void loop() {
  if (Serial.available()) 
   {
     String str = Serial.readStringUntil('\n');
     str.trim();
     Serial.println("");
     Serial.println("You sent: " + str);
   
     if(str.equals("1"))
     {
      setup_wifi();
      client.setServer(mqtt_server, 13311);
      client.setCallback(callback);
      isconeccted=true;
     }
     else
      Serial1.println(str);
     
   }
   if (Serial1.available()) 
   {
    String ser0 = Serial1.readStringUntil('\n');
     ser0.trim();
     
     Serial.println(ser0);
   }
  
  if(isconeccted)
  {
    if (!client.connected()) {
    reconnect();
  }
    client.loop();

    long now = millis();
    if (now - lastMsg > 2000) 
    {
     lastMsg = now;
     ++value;
     snprintf (msg, 75, "hello world #%ld", value);
     Serial.print("Publish message: ");
     Serial.println(msg);
     client.publish("outTopic", msg);
    }
  }
}

**Comment by AkSuganthan** [comment]
@knolleary 

I am person who contact u over twitter.I follow all your instructions.But still I have Problem
----------------------------------------------------------------------------------------------------------
Note: I upload my code in my arduino leonardo not in my ESP8266
---------------------------------------------------------------------------------------------------------------
#include <WiFi.h>
#include <WiFiClient.h>
#include <WiFiServer.h>
#include <WiFiUdp.h>

#include <SPI.h>

#include <ESP8266wifi.h>

/*
 Basic ESP8266 MQTT example

 This sketch demonstrates the capabilities of the pubsub library in combination
 with the ESP8266 board/library.

 It connects to an MQTT server then:
  - publishes "hello world" to the topic "outTopic" every two seconds
  - subscribes to the topic "inTopic", printing out any messages
    it receives. NB - it assumes the received payloads are strings not binary
  - If the first character of the topic "inTopic" is an 1, switch ON the ESP Led,
    else switch it off

 It will reconnect to the server if the connection is lost using a blocking
 reconnect function. See the 'mqtt_reconnect_nonblocking' example for how to
 achieve the same result without blocking the main loop.

 To install the ESP8266 board, (using Arduino 1.6.4+):
  - Add the following 3rd party board manager under "File -> Preferences -> Additional Boards Manager URLs":
       http://arduino.esp8266.com/stable/package_esp8266com_index.json
  - Open the "Tools -> Board -> Board Manager" and click install for the ESP8266"
  - Select your ESP8266 in "Tools -> Board"

*/

#include <ESP8266WiFi.h>
#include <PubSubClient.h>

// Update these with values suitable for your network.

const char* ssid = "........";
const char* password = "........";
const char* mqtt_server = "m10.cloudmqtt.com";

WiFiClient espClient;
PubSubClient client(espClient);
long lastMsg = 0;
char msg[50];
int value = 0;
int BUILTIN_LED=13;
bool isconeccted=false;
void setup() {
  pinMode(BUILTIN_LED, OUTPUT);     // Initialize the BUILTIN_LED pin as an output
  Serial.begin(9600);
  Serial1.begin(115200);
  
}

void setup_wifi() {

  delay(10);
  // We start by connecting to a WiFi network
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);

/*  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());*/
    Serial.println("WiFi connected");
}

void callback(char* topic, byte* payload, unsigned int length) {
  Serial.print("Message arrived [");
  Serial.print(topic);
  Serial.print("] ");
  for (int i = 0; i < length; i++) {
    Serial.print((char)payload[i]);
  }
  Serial.println();

  // Switch on the LED if an 1 was received as first character
  if ((char)payload[0] == '1') {
    digitalWrite(BUILTIN_LED, LOW);   // Turn the LED on (Note that LOW is the voltage level
    // but actually the LED is on; this is because
    // it is acive low on the ESP-01)
  } else {
    digitalWrite(BUILTIN_LED, HIGH);  // Turn the LED off by making the voltage HIGH
  }

}

void reconnect() {
  // Loop until we're reconnected
  while (!client.connected()) {
    Serial.print("Attempting MQTT connection...");
    // Attempt to connect
    if (client.connect("36988521ESP8266Client","My Id","My password"))
    {
      Serial.println("connected");
      // Once connected, publish an announcement...
      client.publish("outTopic", "hello world");
      // ... and resubscribe
      client.subscribe("inTopic");
    }
    else {
      Serial.print("failed, rc=");
      Serial.print(client.state());
      Serial.println(" try again in 5 seconds");
      // Wait 5 seconds before retrying
      delay(5000);
    }
  }
}
void loop() {
  if (Serial.available()) 
   {
     String str = Serial.readStringUntil('\n');
     str.trim();
     Serial.println("");
     Serial.println("You sent: " + str);
   
     if(str.equals("1"))
     {
      setup_wifi();
      client.setServer(mqtt_server, 13311);
      client.setCallback(callback);
      isconeccted=true;
     }
     else
      Serial1.println(str);
     
   }
   if (Serial1.available()) 
   {
    String ser0 = Serial1.readStringUntil('\n');
     ser0.trim();
     
     Serial.println(ser0);
   }
  
  if(isconeccted)
  {
    if (!client.connected()) {
    reconnect();
  }
    client.loop();

    long now = millis();
    if (now - lastMsg > 2000) 
    {
     lastMsg = now;
     ++value;
     snprintf (msg, 75, "hello world #%ld", value);
     Serial.print("Publish message: ");
     Serial.println(msg);
     client.publish("outTopic", msg);
    }
  }
}

**Comment by AkSuganthan** [comment]
I am person who contact u over twitter.I follow all your instructions.But still I have Problem
-----------------------------------------------
Note: I upload my code in my arduino leonardo not in my ESP8266

------------------------------------------------------------------------

My code is

#include WiFi.h
#include WiFiClient.h
#include WiFiServer.h
#include WiFiUdp.h

#include SPI.h

#include ESP8266wifi.h

/*
 Basic ESP8266 MQTT example

 This sketch demonstrates the capabilities of the pubsub library in combination
 with the ESP8266 board/library.

 It connects to an MQTT server then:
  - publishes "hello world" to the topic "outTopic" every two seconds
  - subscribes to the topic "inTopic", printing out any messages
    it receives. NB - it assumes the received payloads are strings not binary
  - If the first character of the topic "inTopic" is an 1, switch ON the ESP Led,
    else switch it off

 It will reconnect to the server if the connection is lost using a blocking
 reconnect function. See the 'mqtt_reconnect_nonblocking' example for how to
 achieve the same result without blocking the main loop.

 To install the ESP8266 board, (using Arduino 1.6.4+):
  - Add the following 3rd party board manager under "File -> Preferences -> Additional Boards Manager URLs":
       http://arduino.esp8266.com/stable/package_esp8266com_index.json
  - Open the "Tools -> Board -> Board Manager" and click install for the ESP8266"
  - Select your ESP8266 in "Tools -> Board"

*/

#include ESP8266WiFi.h
#include PubSubClient.h

// Update these with values suitable for your network.

const char* ssid = "........";
const char* password = "........";
const char* mqtt_server = "m10.cloudmqtt.com";

WiFiClient espClient;
PubSubClient client(espClient);
long lastMsg = 0;
char msg[50];
int value = 0;
int BUILTIN_LED=13;
bool isconeccted=false;
void setup() {
  pinMode(BUILTIN_LED, OUTPUT);     // Initialize the BUILTIN_LED pin as an output
  Serial.begin(9600);
  Serial1.begin(115200);
  
}

void setup_wifi() {

  delay(10);
  // We start by connecting to a WiFi network
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);

/*  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());*/
    Serial.println("WiFi connected");
}

void callback(char* topic, byte* payload, unsigned int length) {
  Serial.print("Message arrived [");
  Serial.print(topic);
  Serial.print("] ");
  for (int i = 0; i < length; i++) {
    Serial.print((char)payload[i]);
  }
  Serial.println();

  // Switch on the LED if an 1 was received as first character
  if ((char)payload[0] == '1') {
    digitalWrite(BUILTIN_LED, LOW);   // Turn the LED on (Note that LOW is the voltage level
    // but actually the LED is on; this is because
    // it is acive low on the ESP-01)
  } else {
    digitalWrite(BUILTIN_LED, HIGH);  // Turn the LED off by making the voltage HIGH
  }

}

void reconnect() {
  // Loop until we're reconnected
  while (!client.connected()) {
    Serial.print("Attempting MQTT connection...");
    // Attempt to connect
    if (client.connect("36988521ESP8266Client","My Id","My password"))
    {
      Serial.println("connected");
      // Once connected, publish an announcement...
      client.publish("outTopic", "hello world");
      // ... and resubscribe
      client.subscribe("inTopic");
    }
    else {
      Serial.print("failed, rc=");
      Serial.print(client.state());
      Serial.println(" try again in 5 seconds");
      // Wait 5 seconds before retrying
      delay(5000);
    }
  }
}
void loop() {
  if (Serial.available()) 
   {
     String str = Serial.readStringUntil('\n');
     str.trim();
     Serial.println("");
     Serial.println("You sent: " + str);
   
     if(str.equals("1"))
     {
      setup_wifi();
      client.setServer(mqtt_server, 13311);
      client.setCallback(callback);
      isconeccted=true;
     }
     else
      Serial1.println(str);
     
   }
   if (Serial1.available()) 
   {
    String ser0 = Serial1.readStringUntil('\n');
     ser0.trim();
     
     Serial.println(ser0);
   }
  
  if(isconeccted)
  {
    if (!client.connected()) {
    reconnect();
  }
    client.loop();

    long now = millis();
    if (now - lastMsg > 2000) 
    {
     lastMsg = now;
     ++value;
     snprintf (msg, 75, "hello world #%ld", value);
     Serial.print("Publish message: ");
     Serial.println(msg);
     client.publish("outTopic", msg);
    }
  }
}

**Comment by knolleary** [comment]
Hi @AkSuganthan 

I didn't give you any instructions to follow. The issue is exactly as detailed both here and in #102 - until someone implements a proper Client.h library that can run on the arduino which uses the ESP, then it is not possible to use my library in this way.

The code you've pasted here is for running on the ESP, not on the Arduino.

**Comment by mararn1618** [comment]
Hi guys,

I have fixed several misimplementations of Sparkfuns ESP8266Client and ESP8266, so that I am able to connect and publish via PubSub.

 + Enabled ESP8266::write() to post binary payload instead of only terminated strings.
 + Introduced lookahead buffer between ESP8266Client and ESP8266, to filter AT commands from esp-responses. 
 + Misinterpreration and mixup of CIPStatus/status() within ESP8266Client will suggest no connection to PubSub

https://github.com/mararn1618/SparkFun_ESP8266_AT_Arduino_Library

**Comment by jjegla** [comment]
(old thread, but was kind of left hanging)

I just wanted to confirm that the fixes mararn1618 made and linked to are indeed the solution:  using their library, I am able to successfully publish to a Mosquitto MQTT broker from the combination of Sparkfun ESP8266 shield and Adafruit_MQTT library.  All I had to do was:

1. include the right libraries:

#include <SparkFunESP8266WiFi.h>
#include <SparkFunESP8266Client.h>
#include <Adafruit_MQTT.h>
#include <Adafruit_MQTT_Client.h>

2. create the objects

ESP8266Client _client;
#define WIFI_SSID "[whatever]"
#define WIFI_PASSWORD "[whatever]"
#define MQTT_SERVER "[whatever]"
#define MQTT_USERNAME "[whatever]"
#define MQTT_PASSWORD "[whatever]"
Adafruit_MQTT_Client _mqtt(&_client, MQTT_SERVER, 1883, MQTT_USERNAME, MQTT_PASSWORD);
#define MQTT_FEED "[whatever]"
Adafruit_MQTT_Publish _mqttFeed = Adafruit_MQTT_Publish(&_mqtt, MQTT_FEED, MQTT_QOS_1);

3. initialize the wifi connection (in setup())

  int wifiTest = esp8266.begin();
  if (wifiTest != true) {
    LogError(F("ESP8266 error"));
  }

4. connect to the MQTT server

(I just used the MQTT_connect() method from the Adafruit library examples)'

5. publish MQTT "datapoints"

  String json = "[whatever]";
  if (!_mqttFeed.publish(json.c_str())) {
    Serial.println(F("Publish failed"));
  } else {
    Serial.println(F("Published datapoint"));
  }


Thank you VERY MUCH, mararn1618!  Sparkfun, please fix your d*&m library officially!

**Comment by mararn1618** [comment]
You're welcome. I'm glad that my fix helped. ;)

**Comment by Curtis2012** [comment]
Hey @mararn1618, thanks for the library fix. I have an old ArduinoUno and SparkFun WiFi shield Im trying to put to use. I have MQTT almost working on it using your version of the library, but the MQTT connection is unstable. It connects, I can see it on the MQTT server, but then it drops after a few seconds. Same cycle repeats as the code tries to reconnect. 

Any troubleshooting suggestions or working example code using your library?
