### ISSUE TITLE
The last willmessage on server cann't be readed for callback function

### ISSUE THREAD

**Issue by r666t** [knolleary/pubsubclient#109]
If the esp is connect to the mqtt server and we publish a message on "inChannel" (where we are subscribe us to receive messages), the callback function read the message and we can process it. But, when in server there is a willmessage and the ESP connect to "inChannel", the last willmessage is publish on channel but the ESP don't read this "willmessage".
Anybody know how we can do for the ESP can read the last willmessage that exist on the channel????

Thanks a lot and Regards

**Comment by knolleary** [comment]
Hi,

the Will message is published when your client disconnected unexpectedly. When your client then reconnects and subscribes to the topic the Will message was published, it will only receive the will message if it had been published with the 'retained' flag set.

Does that answer your question?

**Comment by r666t** [comment]
Thanks, VERY FAST ANSWER!!!!.
The problem is that the ESP when connect and subscrib to inTopic and there is a "retained" message, the ESP don't read this message (this first instant message from server), all other messages that I send after the connection and subcription are received correctly.
The problem is that the retained messages.

Thanks in advance!

**Comment by knolleary** [comment]
Have you verified with another client that there really is a retained message on that topic? If you don't already have it, mosquitto_pub is a useful command line tool for checking this sort of thing.

**Comment by r666t** [comment]
Yes, we test with a Android client and others Windows clients and all received the retained messages exectp ESP that don't receive it.

Thanks knolleary!!!!!

**Comment by Suxsem** [comment]
Can you share your code so we can check it?

**Comment by r666t** [comment]
I checked the last weekend my problem and my mqtt server put extra chards. I solved the problem.
Thanks for your help.
Please close the issue and thanks again.
