### ISSUE TITLE
Connection works on old IDE but not current

### ISSUE THREAD

**Issue by bkenobi** [knolleary/pubsubclient#111]
I have tried Arduino IDE 1.6.1, 1.6.2, and 1.6.7.  In the older versions using the older versions of PubSubClient I can connect to my MQTT broker and send a packet with the mqtt_basic example.  If I try with the current IDE with the current examples, I can't get anything to work.  The output to serial is

Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-4 try again in 5 seconds
Attempting MQTT connection...failed, rc=-4 try again in 5 seconds

So it appears that the first time it fails to find the hardware and the following time out.

**Comment by bkenobi** [comment]
When I use 1.6.1, I can't simply open mqtt_basic, change the IP for client and server, and compile.  I have to change the type of variables server, ip, and callback(length) in order to avoid compile errors.  I don't understand what has changed as I have had an installation of the IDE with PubSubClient for around a year working without any issues.  However, no matter what IDE version/PubSubClient version combination I try, I can't get either the example sketches or my own code (that compiled fine previously) to compile and run.

Note: I had an installation that was working but deleted it last week when my ESP8266 arrived and I upgraded to 1.6.7.  At this point I can't go forward and I can't go back.

**Comment by knolleary** [comment]
I'm currently pulling down 1.6.7 to check - but it works fine with 1.6.5.

What version of PubSubClient have you got installed? The latest is 2.4.0.

**Comment by bkenobi** [comment]
I tried 1.6.7 with 2.4.0 and 2.2.0 (the oldest option).  I'm extracting 1.6.5 now and will give it a try.

**Comment by bkenobi** [comment]
Windows displays a dialog on first run of the IDE that asks if it should be allowed access to intranet and/or internet domains.  I have been leaving it set to default which is internet only.  I clicked past it before thinking about it this time so I'm not sure how I can change it or if that would even help.

As it is, I used a fresh 1.6.5 installation and installed PubSubClient 2.4.0 (everything else left to default).  I reloaded the IDE and opened the mqtt_basic sketch.  I changed 2 lines for my Arduino and Broker IP addresses but left everything else stock.

IPAddress ip(192, 168, 0, 70);
IPAddress server(192, 168, 0, 200);

My broker (Mosquitto on Linux/RPi) does not see anything coming from the Arduino with W5100 based Ethernet shield.  I was able to run 1.6.1 with PubSubClient 1.7 with this hardware (modifying the mqtt_basic as above as well as a couple type definitions for compilation) and my broker did see the "hello world" message.

**Comment by bkenobi** [comment]
I have continued testing.  For testing, I used the default mqtt_basic script included with PubSubClient 2.4.0 and Arduino IDE 1.6.5.  I set the server to test.mosquitto.org (85.119.83.194) and changed the topic to something unique (complexTopic).  I was able to connect to the server and publish a message which I saw when using Mosquitto as a subscriber.  I published a message to that same server and saw it on the mosquitto tool, but the Arduino did not print the topic/message.  For my needs I only need publish but I wanted to be thorough.

So, it appears that PubSubClient 2.4.0 will connect to a broker, but it does not appear to like the broker as I have it configured.  However, if I step back to PubSubClient 1.7 without modifying the broker, I can publish a message correctly.  Perhaps there is something else you might suggest to get this working in the current version of your library?

**Comment by bkenobi** [comment]
I have a configuration that will now compile my project and send data to the MQTT broker.  My combination that works is IDE 1.6.1 with PubSubClient 1.9.

That said, that's only half the solution.  I need to have my old version work, but my original goal was to get ESP8266 as the MCU rather than Arduino UNO + Ethernet shield.  I can't get PubSubClient to send data to the Mosquitto broker with any newer version of PubSubClient which means I can't even start with the ESP8266 (MQTT related anyway).

Do you have any thoughts on why the broker would be incompatible?  I have left it with stock settings but can change them if there were a reason to!

**Comment by chaeplin** [comment]
Here working sample with IDE1.6.7/esp8266(current git)/pubsubclient2.4/mosquitto/tls1.1/user.pass.
As of IDE 1.6.5 ~ 1.6.7, function prototype is not working well with esp8266.

(verifying fingerprint of server crt is not done yet)

https://github.com/chaeplin/esp8266_and_arduino/blob/master/_33-esp-12-WiFiClientSecure-mqtt-ssl/_33-esp-12-WiFiClientSecure-mqtt-ssl.ino

**Comment by knolleary** [comment]
@bkenobi have you got the 2.4 version working at all?

One significant thing that changed was that the library now defaults to the MQTT 3.1.1 version of the protocol. If the broker you are using doesn't support that, then it would fail to connect (although I'd possibly expect a different error code).

You can change it back to use MQTT 3.1 by changing the value of MQTT_VERSION here: https://github.com/knolleary/pubsubclient/blob/master/src/PubSubClient.h#L15

**Comment by bkenobi** [comment]
I attempted to change to MQTT 3.1 a few days ago.  Even though Mosquitto claims compatibility with 3.1.1, I figured it was worth a try to change back.  I probably didn't do it correctly as I believe I commented out line 20 and uncommented 19.  At that time, it didn't seem to make a difference, but I can look at it again.  I do want to get this working but have been busy this week with other things and haven't had time.

**Comment by bkenobi** [comment]
I updated my MQTT broker (Mosquitto 0.15 to 1.4.7) to support 3.1.1 and PubSubClient 2.4.0 now works.  Looks like the issue was simply default MQTT version changed after 1.9.  Issue can be closed.

**Comment by knolleary** [comment]
@bkenobi great - glad you got it working.

**Comment by chandini95** [comment]
I am using arduino IDE 1.6.4 and pubsubclient 2.6.0...mqtt connection kept on failing..so i tried with arduino ide 1.6.5 and pubsubclient all the versions starting from 2.2.0 to 2.6.0..everytime it fails..kindly tell me where am i going wrong..

**Comment by MazinAliKarar** [comment]
Dear @knolleary ,
I am having problems connecting to the MQTT server set up in my local machine. I am getting this error "Attempting MQTT connection...failed, rc=-2 try again in 5 seconds".

The broker is fine. I have a publisher and subcriber python codes and they are working properly.

Could you please help me?

**Comment by knolleary** [comment]
@mazinalikarar have you tried the HTTP Client example to verify your can get a network connection at all? Are you using DHCP or static IP addresses?

**Comment by MazinAliKarar** [comment]
Thanks for replying :)
I am done with the wifly module configuration. I even pinged it and it is well connected. 
I am using DHCP and gave me back the ip address of my arduinoClient.

**Comment by MazinAliKarar** [comment]
@knolleary, I download this library "HttpClient" from GitHub and I tried the "SimpleHttpExample". I hv chantged the mac address to my wifly mac address. But yeah, it turned out to give me this error "Error getting IP address via DHCP, trying again..."
