### ISSUE TITLE
Using this lib to AWS IoT

### ISSUE THREAD

**Issue by zarathon** [knolleary/pubsubclient#112]
How i use this lib to AWS IoT??? Any example???

**Comment by knolleary** [comment]
You will need a client library that supports full TLS authentication in order to connect to AWS IoT. The ESP8266 seems to have a WifiClientSecure network client that may work - https://github.com/esp8266/Arduino/issues/43

I don't have an example, but would welcome the contribution of one.

**Comment by zarathon** [comment]
Thanks... I will contribue soon.. ;)

**Comment by yash2607** [comment]
> How i use this lib to AWS IoT??? Any example???

Was you able to establish the connection? I need to do the same.
