### ISSUE TITLE
Support for SIM900 module

### ISSUE THREAD

**Issue by kaustubhagarwal18** [knolleary/pubsubclient#113]
I am trying to implement the sample Mqtt code with SIM900. I have tried numerous Libraries but none worked for me. Can someone help me?

**Comment by knolleary** [comment]
Hi,

is there a Client.h compatible library for SIM900? That is the only way to use this library. A quick search doesn't reveal anything obvious, so you may be out of luck with this library.

**Comment by kaustubhagarwal18** [comment]
I have searched a lot and wasn't able to find any

**Comment by knolleary** [comment]
Sorry about that - without that, I can't really help.

**Comment by satay99** [comment]
sim900Client.h can be found here https://github.com/vwochnik/sim900client. I am not sure if it helps.

**Comment by dmsherazi** [comment]
For those who are interested in this , Rmap project has implemented the pubsubclient with sim900/800 providing the client.h compatibility. i am using that and its great!.
https://github.com/r-map/rmap/tree/master/arduino/sketchbook/libraries
