### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by schokocappucino** [knolleary/pubsubclient#114]
I want to connect to a mqtt server which is only available over a websocket. Is this possible with this library?

**Comment by knolleary** [comment]
This library will work with any network client that implements the standard Arduino Client.h interface. I am not aware (nor does a quick Google reveal) of such library for WebSockets. Sorry!

**Comment by schokocappucino** [comment]
okay, thank you ;)

**Comment by derrgis** [comment]
Yes that is possible with PubSubClient , Mosquitto Broker and Paho JS
If you want websocket AND mqtt protocol you have to specify in the .conf file you use and launched with:
$ mosquitto -c path_to_the_file
that file should have:
listener 9001
protocol websocket
listener 1883
protocol mqtt

EVEN if the defaut port and protocol are 1883 mqtt !
