### ISSUE TITLE
Local Network

### ISSUE THREAD

**Issue by brunoudi** [knolleary/pubsubclient#116]
Hi,

I'm searching for a protocol/library to use in my prototype, and I'm thinking about something that I would like to hear some opinions.

How does mqtt works with a local network only?

As I understand, correct me if I'm wrong, with mqtt I can't get value of sensors in a network without internet connection. Considering that, I think in 2 options:

1) Not implement mqtt in all devices. Implement "my own protocol" based on UDP messages to get the values and send commands, and for remote I build a gateway.

2) Project a local broker, bridged to a remote. 

If I really have the only two options above to work with mqtt in a network without internet conection, I think the option 1 have a better cost vs benefit plus a lot less effort to create.

**Comment by knolleary** [comment]
Hi,

for this general sort of question, there is the [MQTT mailing list](https://groups.google.com/forum/#!forum/mqtt).

MQTT is a network protocol; It doesn't care if that network is a local private network or the entire internet. It's just about getting messages from a client to a server and then on to any subscribers efficiently.

You can run a broker anywhere you want - mosquitto is a great example of a really light weight broker you can run on a Raspberry Pi and up. With that in place, option 2 is pretty trivial to do.
