### ISSUE TITLE
Browser Client

### ISSUE THREAD

**Issue by Vitorbnc** [knolleary/pubsubclient#121]
Hi, 
Could you recommend a really fast MQTT browser client library? I currently have to use Socket.io on browser-side to talk to my Node server that handles the MQTT part. Besides, the packets also have to go through Mosquitto before reaching ESP8266.

**Comment by knolleary** [comment]
Hi, if you have general questions about MQTT that aren't specifically about this library, there is the MQTT google group - https://groups.google.com/forum/#!forum/mqtt

By browser client, that suggests a client that can connect via websockets straight into mosquitto? If so, there is one as part of the Eclipse Paho project - https://www.eclipse.org/paho/clients/js/

**Comment by jsiei97** [comment]
I know it is off-topic but you are probably looking for something like this:
http://jpmens.net/2014/07/03/the-mosquitto-mqtt-broker-gets-websockets-support/

**Comment by Vitorbnc** [comment]
Thanks! I read about this mosquitto feature, but we have to rebuild it to enable and the last time I tried it didn't work. Don't understand why the didn't enable this by default. I'll try building again soon.
