### ISSUE TITLE
Will this library work with the newer WiFi Shield 101?

### ISSUE THREAD

**Issue by deeley234** [knolleary/pubsubclient#122]
Hey

Probably a stupid question but I'm fairly new to this game. 

I assume the library works with the original WiFi shield but the new one uses an ATWINC1500. Will the library still work with this? I need to use a WiFi shield for a project I'm working on at university but I don't want to commit to buying the new version unless I know this library will work with it.

Thanks
Matt.

**Comment by deeley234** [comment]
Moreover, will it work with the Adafruit version of the shield? it uses the ATWINC1500...

http://makersify.com/products/adafruit-arduino-wifi-shield-101-ada2891?utm_medium=cpc&utm_source=googlepla&variant=10835737985&gclid=CLmgjoG3zcoCFcG6GwodcxkNDg

**Comment by knolleary** [comment]
The chip used is not relevant. What is important is whether there is a Client.h-compatible library provided for the shield. That is what this library depends on.

A quick search points at https://www.arduino.cc/en/Reference/WiFi101 - which is indeed a suitable client library for use with this library. So yes, it will work.

**Comment by deeley234** [comment]
Brilliant. Thanks so much dude.
