### ISSUE TITLE
Using constant or Variable for port number causes connection to fail (??)

### ISSUE THREAD

**Issue by VladimirAkopyan** [knolleary/pubsubclient#127]
I am programming Arduino mega with standard Ethernet shield and Visual Studio Micro.

When I create instance of PubSubusing a literal for port number, everything is fine. 
`PubSubClient MQTTclient(server, 1833, callback, Network.ethClient);
`
But if I use a variable or a constant, it will forever fail to connect: 
```
const uint16_t port = 1833; 
PubSubClient MQTTclient(server, port, callback, Network.ethClient);
```
This client will never connect to the intended target
```
MQTTclient.State() 
```
returns
```
MQTT_CONNECT_FAILED         -2
```

Demo: 
https://youtu.be/QnLXhcORdiY

How is this possible?

**Comment by Suxsem** [comment]
This is strange... Did you try to clean the project and rebuild from scratch? 
Seems a visual Micro sort of bug to me

**Comment by Suxsem** [comment]
For debug purpose you can try to change the return value of the connect method, returning the port number passed as argument. 
So you can check that the connect method is getting the right port number

**Comment by VladimirAkopyan** [comment]
![image](https://cloud.githubusercontent.com/assets/12278048/13178695/36b6c832-d718-11e5-9f90-0c08a2a71e19.png)


`Test 1
Port closed
Uploading to I/O board
Opening port
Port open
-2
11100101001

Test 2
Port closed
Uploading to I/O board
Opening port
Port open
0
11101011011

BAD 	1110 0101 001
GOOD 	1110 1011 011`

**Comment by Suxsem** [comment]
Sorry I don't understand what test did you do...can you explain better?
also, I noticed that in the bad test the decimal number is 1833, are you sure it's not a typo?

**Comment by Suxsem** [comment]
I saw the video again:
const unsigned int port = 1833;

it's definitely a typo

**Comment by Suxsem** [comment]
And when you do the double ctrl+z in the video you are actually changing from 1833 to 1883 :)

**Comment by VladimirAkopyan** [comment]
Oops. Embarrassing. 
All three of us couldn't see it. Thank you!

**Comment by Suxsem** [comment]
:+1:

**Comment by knolleary** [comment]
Well spotted @Suxsem - thanks for that. :eyes: :100:
