### ISSUE TITLE
iostrem error

### ISSUE THREAD

**Issue by gorlapraveen** [knolleary/pubsubclient#128]
while including PubSubClient getting error as
#include <iostream.h> //library isn.t there..please help me in resolving this while connecting to mqtt library using GSM.

**Comment by knolleary** [comment]
Sorry, but if you don't share the actual error or the code, we cannot begin to help.

**Comment by gorlapraveen** [comment]
In file included from gsmserverconnection.ino:2:0:
/home/praveen/sketchbook/libraries/pubsubclient5/trace.h:3:20: fatal error: iostream: No such file or directory
 #include <iostream>
                    ^
compilation terminated.
//THIS IS THE ERROR WHAT IAM GETTING

**Comment by knolleary** [comment]
How did you install the library? It is picking up code from the tests subdirectory, which indicates you haven't installed the library correctly.

**Comment by gorlapraveen** [comment]
I have installed it from github

**Comment by knolleary** [comment]
Ok, that still doesn't tell me how you did it, just where you got the files from. Rather than try to debug it, here's what you should do:

1. delete `/home/praveen/sketchbook/libraries/pubsubclient5`
2. use the arduino ide's built-in library manager, `Sketch->Include Library...->Manage Libraries` and search for PubSubClient and click Install.

**Comment by gorlapraveen** [comment]
#include <PubSubClient.h>


#include <SoftwareSerial.h>
SoftwareSerial mySerial(9, 10);
PubSubClient mqttClient(client);
 
void setup()
{
  mySerial.begin(9600);               // the GPRS baud rate  
  Serial.begin(9600);    // the GPRS baud rate
 
}
 
void loop()
{ startMqtt();
  datasend();
  mqttClient.loop()
}

void startMqtt()
{
  //client.setServer(server, 1883);
  mqttClient.setServer("mqtt.carriots.com", 1883);
  mqttClient.connect("myclientID");
  if(mqttClient.connected())
 {
   //connect with LWT
     byte willQoS = 0;
     const char* willTopic = "willTopic";
     const char* willMessage = "My Will Message";
     boolean willRetain = false;
 
     boolean a= mqttClient.connect("myClientID", willTopic, willQoS, willRetain, willMessage);
    //connect with username/password
     boolean b=mqttClient.connect("myClientID","myusername","mypassword")
     
     mqttpubsub();
 }
 else()
 {
     startMqtt();
 }
}


void datasend()
{
    mySerial.println("AT");
    delay(2000);
    ShowSerialData();
    mySerial.println("AT+CGATT?");
    delay(2000);
    ShowSerialData();
    mySerial.println("AT+CIPSHUT");
    delay(2000);
    ShowSerialData();
    mySerial.println("AT+CIPSTATUS");
    delay(2000);
    ShowSerialData();
    mySerial.println("AT+CIPMUX=0");
    delay(2000);
    ShowSerialData();
    mySerial.println("AT+CSTT=\"airtelgprs.com\",\"\",\"\" ");
    delay(1000);
    ShowSerialData();
 
    mySerial.println(" AT+CIICR ");
    delay(5000);
    ShowSerialData();
    mySerial.println("AT+CIFSR");
    delay(2000);
    ShowSerialData();
  //mySerial.println("AT+CMQTTSTART");
  //delay(1000);
  //ShowSerialData();
    //mySerial.println("AT+CMQTTACCQ=0,client1");
  //delay(1000);
  //ShowSerialData();
    //mySerial.println("AT+CMQTTCONNECT=0,tcp,test.mosquitto.org/ws.html:1883,20,1" );
  //delay(1000);
  //ShowSerialData();
  //mySerial.println("AT+CMQTTOPIC=0,13,praveen");
  //delay(1000);
  //ShowSerialData();
  //mySerial.println("AT+CMQTTPAYLOAD=0,62,hai");
  //delay(1000);
  //ShowSerialData();
 
 
    mySerial.println("AT+CIPSTART=\"tcp\",\"127.0.0.1\",\"80\"");
    delay(2000);
    ShowSerialData();
    mySerial.println("AT+CIPSEND? >");
    ShowSerialData();
  //mySerial.println("#026");
  //delay(2000);
  //ShowSerialData();
  //mySerial.println("AT+CIPSHUT");
  //delay(2000);
  //ShowSerialData();
  mySerial.println(startmqtt);
}
 
  void ShowSerialData()
{
  while(mySerial.available()!=0)
    Serial.write(mySerial.read());
}
	
void mqttpubsub()
{
 boolean c = mqttClient.publish("myTopic", "myMessage");
 boolean d = mqttClient.subscribe("INtopic"); 
 ShowSerialData();
}

///Below is the error










gsmconnection2.ino:6:1: error: ‘PubSubClient’ does not name a type
gsmconnection2.ino: In function ‘void loop()’:
gsmconnection2.ino:18:3: error: ‘mqttClient’ was not declared in this scope
gsmconnection2.ino:19:1: error: expected ‘;’ before ‘}’ token
gsmconnection2.ino: In function ‘void startMqtt()’:
gsmconnection2.ino:24:3: error: ‘mqttClient’ was not declared in this scope

gsmconnection2.ino: In function ‘void mqttpubsub()’:
gsmconnection2.ino:113:14: error: ‘mqttClient’ was not declared in this scope

**Comment by knolleary** [comment]
Have you reinstalled the library as I suggested?

If so, check you can successfully build one of the example sketches the library provides.

**Comment by knolleary** [comment]
Closing as this is an installer error, not an issue with the library.

If you are still having problems, please let me know on this issue.
