### ISSUE TITLE
Connection loop

### ISSUE THREAD

**Issue by roccomuso** [knolleary/pubsubclient#130]
I'm trying to connect my esp8266 nodemcu to my mqtt broker.
The connection seems to be enstablished. But the client loops over and over trying to connect again.

This is my code: http://pastebin.com/V23Sy7fb

and this is my serial console output:

```
Attempting MQTT connection...connected
Attempting MQTT connection...connected
Attempting MQTT connection...connected
Attempting MQTT connection...connected
Attempting MQTT connection...connected
Attempting MQTT connection...connected
Attempting MQTT connection...connected
Attempting MQTT connection...connected
Attempting MQTT connection...connected
Attempting MQTT connection...connected
Attempting MQTT connection...connected
Attempting MQTT connection...failed, rc=-4 try again in 5 seconds
Attempting MQTT connection...connected
Attempting MQTT connection...connected
Attempting MQTT connection...connected
. . .
```

**Comment by knolleary** [comment]
Do your broker logs provide any clues as to why the client is disconnecting?

I see you're using a client ID of `default` - do you have any other clients using that ID?

**Comment by roccomuso** [comment]
My broker is Mosca, a Node.js-based broker.

I got this on the broker's log:

```
- Client Disconnected:  default
- Client connected:  default
- Client Disconnected:  default
- Client connected:  default
- Client Disconnected:  default
- Client connected:  default
- Client Disconnected:  default
- Client connected:  default
- Client Disconnected:  default
```

**Comment by roccomuso** [comment]
What <code>client.loop();</code> exactly stands for? is it required?

**Comment by knolleary** [comment]
And you dont have any other clients already using the 'default' client id?

client.loop is required: http://pubsubclient.knolleary.net/api.html#loop

Have quickly are these connect/disconnect cycles happening? I see your code publishes after connecting - do you see that message arrive anywhere?

**Comment by roccomuso** [comment]
No the message doesn't arrive. Do I need to put any delay somewhere?

**Comment by roccomuso** [comment]
I've used the latest release... so weird.. can you try the code i've pasted above?

**Comment by roccomuso** [comment]
I've just discovered that. If i set no authentication on my broker, everything works fine. Using authentication, something goes wrong.
My broker is the node.js open source project called "Mosca".
I don't know if it is related to the Client or to the Broker.

**Comment by knolleary** [comment]
Have you tested the username/password work with another mqtt client? For example the mosquitto_pub command? I see your code retrieves the username/password from a json file - have you verified it is actually passing the values you expect to client.connect()?

**Comment by roccomuso** [comment]
The values expected are correct.

I've found the issue. Seems to be related to the publish authorization.
If I try to publish in a topic I'm not authorized to publish, the client disconnect and reconnect, the broker doesn't return the code <code>5 - "Connection Refused, not authorized"</code> expected or the client doesn't get it.

**Comment by knolleary** [comment]
That return code is only applicable in response to the Connect packet - there is no way in MQTT for the broker to send a failure code to the client in response to an invalid publish. All it can do is disconnect.

Glad you got to the bottom of it.

**Comment by roccomuso** [comment]
Alright, thanks :+1:
