### ISSUE TITLE
publish gpio state

### ISSUE THREAD

**Issue by pickeld** [knolleary/pubsubclient#132]
Hello, 
is it possible to publish the current state of the gpio (high or low)?

thank you.
David

**Comment by knolleary** [comment]
Yes, you can publish anything you want.

Read the state of the pin... call client.publish with the result.

**Comment by pickeld** [comment]
thank you for the quick replay!
can you please be more specific? how can i read the state of the pin? (im using gpio 2 on the esp8266)
thanks
David

**Comment by knolleary** [comment]
You can use the standard arduino `digitalRead` function. There's a basic introduction here: https://www.arduino.cc/en/Tutorial/DigitalReadSerial - focused on arduino, but should pretty much 'just work' on the esp8266.

See also http://arduino.esp8266.com/versions/1.6.5-990-gc8a63ce/doc/reference.html as a reference

**Comment by pickeld** [comment]
Hey Knollary
thank you from helping me.
im sharing my code so i can help other ppl.

`
void loop() {

  if (!client.connected()) 
  {
    reconnect();
  }
  client.loop();



  long now = millis();
  if (now - lastMsg > 2000) {
    lastMsg = now;

    val = digitalRead(2);
    if (val == 1)
    {
      client.publish("outTopic", "0"); // means on
    }
    else
    {
      client.publish("outTopic", "1"); // means on
    }
  }
}
`
 its meant to send a replay respond to mqtt light switch
