### ISSUE TITLE
ESP-13 (AT Command Firmware) + Arduino Due + MQTT Integration

### ISSUE THREAD

**Issue by sharma-abhishek** [knolleary/pubsubclient#136]
Hi Nick,

We are trying to integrate PubSubClient library in one of our project. We have the following setup: 

a) Arduino DUE 
b) ESP-13 ESP8266 WiFi chip having AT Commands Firmware.

We are trying to follow your example from GitHub for MQTT for 8266:
https://github.com/knolleary/pubsubclient/blob/master/examples/mqtt_esp8266/mqtt_esp8266.ino

But it uses the **ESP8266WiFi** library which is not ported for the Arduino Due Architecture (SAM Board).

We tried to integrate the **ESP8266wifi** library instead of the ESP8266WiFi library which your example code uses, but we are getting compile issues probably because the PubSubClient expects the **ESP8266WiFi** object instance.

Can you please help us out regarding the same so that we can use your MQTT example with Arduino Due Board + ESP-13 ESP8266 Module (AT Command Firmware) ?

Any help would be much appreciated.

Awaiting your reply.

Thanks,
Abhishek

**Comment by knolleary** [comment]
Hi,

please see #102 and #107 

There is no `Client.h` compatible library that I know of that can be used on the Arduino to access the ESP in AT mode. That's the missing piece that someone needs to write.

Nick
