### ISSUE TITLE
Not getting callback on subscribe

### ISSUE THREAD

**Issue by omkarg** [knolleary/pubsubclient#137]
Hi Knolleary,

I am able to publish the data on the topic and it is also subscribed to that topic but i do not receive any message in the call back , the call back function is not called. Could you help me with this

#include <ESP8266WiFi.h>
#include <PubSubClient.h> // https://github.com/knolleary/pubsubclient/releases/tag/v2.3

//-------- Customise these values -----------
const char* ssid = "username";
const char* password = "password";

#define ORG "myorg"
#define DEVICE_TYPE "trial"
#define DEVICE_ID "5CCF7FB8969"
#define TOKEN "hgsdfj234kjds)"
//-------- Customise the above values --------

char server[] = ORG ".messaging.internetofthings.ibmcloud.com";
char topic[] = "iot-2/evt/status/fmt/json";
char authMethod[] = "use-token-auth";
char token[] = TOKEN;
char clientId[] = "d:" ORG ":" DEVICE_TYPE ":" DEVICE_ID;

WiFiClient wifiClient;
PubSubClient client(server, 1883, callback, wifiClient);

void setup() {
 Serial.begin(115200);
 Serial.println();
 Serial.print("Connecting to ");
 Serial.print(ssid);
 WiFi.begin(ssid, password);
 while (WiFi.status() != WL_CONNECTED) {
 delay(500);
 Serial.print(".");
 } 
 Serial.println("");

 Serial.print("WiFi connected, IP address: ");
 Serial.println(WiFi.localIP());

}

int counter = 0;

void loop() {

 if (!!!client.connected()) {
 Serial.print("Reconnecting client to ");
 Serial.println(server);
 while (!!!client.connect(clientId, authMethod, token)) {
 Serial.print(".");
 delay(500);
 }
 Serial.println();
 }
 
 String payload = "{\"d\":{\"myName\":\"ESP8266.Test1\",\"counter\":";
 payload += counter;
 payload += "}}";
 
 Serial.print("Sending payload: ");
 Serial.println(payload);
 
 if (client.publish(topic, (char*) payload.c_str())) {
   if (client.subscribe("iot-2/type/+/id/+/evt/status/fmt/+"))
   {
    Serial.println("subscribed");
    client.setCallback(callback);
   }
   else
   {
    Serial.println("failed sub");
   }
 Serial.println("Publish ok");
 client.loop();
// delay(500);
// if (client.subscribe(topic)){
//  Serial.println("Successfully subscribed");
//}
 } else {
 Serial.println("Publish failed");
 }

 ++counter;
 delay(10000);
}

void callback(char* topic, byte* payload, unsigned int length) {
Serial.println("***************** data received *********************");
 Serial.println("callback invoked");
}

**Comment by knolleary** [comment]
Hi, there are a few issues with your code.

1. You need to subscribe to a topic you want to receive messages on before you publish to it. You appear to be subscribing to the topic after each successful publish - don't do that. Subscribe once after you connect.

2. You call client.loop which is good. But the. You delay for 10seconds. You must call client.loop regularly so it can maintain the connection and process and messages being sent to the client.

3. This looks like you are connecting as a registered device into the Watson IOT platform. So despite the above two issues, you need to understand there are restrictions as to what a device may subscribe to. It may only subscribe to its own command topic. It is not allowed to subscribe to the event topic as you are doing. I dont have a link to the device docs to hand as I'm on my phone here. But trying to subscribe to this topic will cause the server to kick your client off.
