### ISSUE TITLE
can not connect to mosquitto

### ISSUE THREAD

**Issue by gaojice** [knolleary/pubsubclient#139]
can not connect to mostquitto server,i print out the bytes client send to server when connect as follow,DEC:
![image](https://cloud.githubusercontent.com/assets/1241173/13624566/5dcc83ea-e5ea-11e5-92a8-878888920bed.png)
according to the mqtt protocal,i confused with the '0' at head three position.
where am i wrong?

**Comment by knolleary** [comment]
Hi,

without seeing your code, I can't say where those bytes are coming from. 
What hardware are you using and what network client library are you using? Those bytes must be being added by something outside of the `PubSubClient`.

**Comment by gaojice** [comment]
i dive into PubSubClient.cpp ,found that those bytes are in "buffer",but send to the network start from the fourth byte,that's ok.
thank u very much for your pationt.
