### ISSUE TITLE
Meta data of a message?

### ISSUE THREAD

**Issue by HW-Siew** [knolleary/pubsubclient#142]
Hi, is that possible to get the meta data of a message like the packet id, properties and headers of a message? Tq

**Comment by knolleary** [comment]
No, the callback only exposes the topic and payload.

The other properties of a message in the protocol are:
 - ID - if QoS 1 or 2
 - QoS
 - retain flag

What else were you thinking of?

**Comment by HW-Siew** [comment]
@knolleary , Thanks for the information. Is that possible to get the ID for qos1?

**Comment by knolleary** [comment]
No, the callback only exposes the topic and payload.

Typically, the id of messages is not exposed to applications as it is a protocol-specific detail and not something the application should rely on.
