### ISSUE TITLE
Extracting Data from Subscriptions

### ISSUE THREAD

**Issue by cadywompus** [knolleary/pubsubclient#146]
How do you extract the data among your subscriptions?

I am using IBM IoT platform and need to get the data stored in the events of my topic in order to display it on a screen. I've been able to successfully subscribe, and getting that data is the last step to get my project working.

**Comment by knolleary** [comment]
Have you looked at the example sketches that come with the library? They all demonstrate how to set a callback function that is called when a new message arrives on one of your subscriptions.

https://github.com/knolleary/pubsubclient/blob/master/examples/mqtt_basic/mqtt_basic.ino
