### ISSUE TITLE
mqtt_esp8266.ino -not working

### ISSUE THREAD

**Issue by kiralikbeyin** [knolleary/pubsubclient#149]
mqtt_esp8266.ino -not working in localhost / 127.0.0.1

**Comment by knolleary** [comment]
What about it isn't working? What have you tried? Are there any error messages you can share? Should I guess what your seeing?

**Comment by kiralikbeyin** [comment]
Sorry i thought you will try with an esp8266 and see ;

Attempting MQTT connection...failed, rc=-2 try again in 5 seconds

1.6.5 and 1.6.8 same result..

**Comment by knolleary** [comment]
Are you running an mqtt broker on the esp?

**Comment by kiralikbeyin** [comment]
Running mosquitto on localhost

mosquitto_pub -t topic/state -m "Hello World" - works fine...

**Comment by knolleary** [comment]
So 'local host' and 127.0.0.1 are both special addresses that refer to the computer running the code.

You are running mosquitto on your laptop and able to connect to it as localhost when running the mosquitto_sub command on the same machine.

But the esp is a different machine to your laptop. To it, localhost is itself, not you laptop.

You need to use the proper IP address of your laptop (or whatever is running mosquitto).
