### ISSUE TITLE
'WifiClientSecure' does not name a type

### ISSUE THREAD

**Issue by AdamMiltonBarker** [knolleary/pubsubclient#153]
Following this tutorial to try and solve issue with not being able to connect to broker with ESP9266 01 am getting the above error.

http://www.radupascal.com/2016/04/03/esp8266-arduino-iot-hub

So far seems to be only Arduino related libraries that are failing. Python and Node JS work fine. Any ideas anyone.

**Comment by knolleary** [comment]
Hi,

what version of the Arduino IDE are you using? Have you got the right board type selected? Have you tried googling that error message to see how other people have resolved it?

As this is not a problem with the PubSubClient, I'm going to close this issue.

**Comment by AdamMiltonBarker** [comment]
The latest, yes, yes and the only thing says use latest version I have the latest version.

**Comment by AdamMiltonBarker** [comment]
The issue was actually a spelling mistake in the code on the following article the F was lower case all good. 

http://www.radupascal.com/2016/04/03/esp8266-arduino-iot-hub
