### ISSUE TITLE
"Attempting MQTT connection...connected"  in an endless loop

### ISSUE THREAD

**Issue by dirkclemens** [knolleary/pubsubclient#155]
I am using the basic "mqtt_esp8266.ino" example as it is, no changes, except: 
- I connect to my local mosquito instance running on a raspberry pi 2 instead of "broker.mqtt-dashboard.com" 
- and I added different nodeIDs to the topic-string of each device.

This example works fine for each individual device, unless I run two esp8266 devices (Wemos D1 mini) with the same software (different topics) in parallel.
The Serial output is "Attempting MQTT connection...connected" in an endless loop and the broker logs messages from both devices permanently in an endless loop. 
Seemed to that both devices are calling each other and vice versa. 
Has anyone else experience with two esp8266 running in parallel with this mqtt-library? 
Any advice how to deal with it?

**Comment by knolleary** [comment]
It sounds like you haven't changed the client ID to be unique for each device? If so, then when the second one connects, it will cause the first to be kicked off - and so on as they each reconnect.

**Comment by dirkclemens** [comment]
thanks very much, you are perfectly right. Too obvious, should have see it myself
