### ISSUE TITLE
is pubsub library support softwareSerial?

### ISSUE THREAD

**Issue by shadababe04** [knolleary/pubsubclient#157]
#include <SoftwareSerial.h>
#include <PubSubClient.h>

SoftwareSerial esp(2, 3);// RX, TX
PubSubClient client(esp);

Error is:no matching function for call to 'PubSubClient::PubSubClient(SoftwareSerial&)'

**Comment by knolleary** [comment]
No. SoftwareSerial is not an implementation of the standard Client.h network library provided by the Arduino platform.

**Comment by shadababe04** [comment]
is there any way to use pubsub for MQTT on serial connection

**Comment by knolleary** [comment]
You would need to:

1. Create an Client.h compatible version of SoftwareSerial
2. Have something running in the other end of the serial link that understands what to do with the packets it receives ... Presumably forwarding them over TCP to a broker.

I'm not aware of anyone having done this.
