### ISSUE TITLE
MQTT publish issues

### ISSUE THREAD

**Issue by Pragadheeshraj** [knolleary/pubsubclient#164]
I have a issue when I publish certain message over MQTT
The message I am trying to publish is in JSON format 
It is in string and I converted it to a char array
{"switches":[{"schedule":{},"switch_id":"3"},{"schedule":{},"switch_id":"2"},{"schedule":{},"switch_id":"5"},{"schedule":{},"switch_id":"9"},{"schedule":{},"switch_id":"8"},{"schedule":{},"switch_id":"7"}],"mac_address":"5c:cf:7f:80:39:67"}

Code snippet:
 
topicpub.toCharArray(topicp,50);
response.toCharArray(resmsg,256);
client.publish(topicp,resmsg);

I have sent messages larger than this but I dont understand why this has happened

Reset Log:

Soft WDT reset

ctx: cont 
sp: 3fff1710 end: 3fff1aa0 offset: 01b0

>>>stack>>>
3fff18c0:  402223fa 00000000 3fff0444 4020feba  
3fff18d0:  3fff0282 3fff1960 3fff0444 4021100c  
3fff18e0:  00000001 00000000 3ffe8c08 00000000  
3fff18f0:  3fff37f0 4010683a 3fff1960 3fff0538  
3fff1900:  00000000 000000f0 3fff0634 4020d8d0  
3fff1910:  3fff0638 3fff04b8 3fff1960 40210e56  
3fff1920:  00000030 00000000 3fff1960 3fff19a0  
3fff1930:  00000030 3fff04b8 3fff0634 4020d909  
3fff1940:  3fff04b8 3fff0538 3fff1960 40210db0  
3fff1950:  00000030 3fff04b8 3fff0538 40208ba8  
3fff1960:  3fff3800 0000000f 0000000c 3ffea8ac  
3fff1970:  3fff19a0 0002c14d 3fff0634 4020d804  
3fff1980:  66636335 30386637 37363933 7165722f  
3fff1990:  3fffdc00 0002c14d 3fff0634 4020d734  
3fff19a0:  4020df01 00000001 3fff19e0 4020a4ea  
3fff19b0:  00000000 00000000 00080000 ffdfffff  
3fff19c0:  ffffffff 3fffc6fc 00000001 3fff0a6c  
3fff19d0:  3fffdc20 00000000 3fff0634 40209065  
3fff19e0:  3ffe8c08 00000000 000003e8 00000030  
3fff19f0:  00000000 00000000 3fff0948 40208fba  
3fff1a00:  3fff3870 0000000f 00000002 00000000  
3fff1a10:  00000000 00000000 00000000 6d530000  
3fff1a20:  68637469 3631765f 00000037 00000000  
3fff1a30:  00000000 00000000 00000000 00000000  
3fff1a40:  00000000 00000000 3fff3800 0000000f  
3fff1a50:  0000000b 00000000 00000000 00000000  
3fff1a60:  00000000 00000000 00000016 40101981  
3fff1a70:  4020def9 00000000 00000000 3fff0a6c  
3fff1a80:  3fffdc20 00000000 3fff0a64 4020df21  
3fff1a90:  00000000 00000000 3fff0a80 40100114  
<<<stack<<<

**Comment by knolleary** [comment]
What hardware are you running this on? Are you able to publish simple messages to a broker? Is it unique to this message?

**Comment by Pragadheeshraj** [comment]
I am running this on ESP8266 12E Module. Yeah all other types of messages I am able to publish. Yeah it is unique to this message

**Comment by knolleary** [comment]
I assume you've defined topicpub and resmsg to be large enough for the data you're copying into them?

**Comment by Pragadheeshraj** [comment]
Yeah I have checked them.

**Comment by Pragadheeshraj** [comment]
Can I know the maximum size of message I can send with ESP with this library ? How can I change it if required?

**Comment by Pragadheeshraj** [comment]
Please do let me know the exact difference between MQTT_MAX_TRANSFER_SIZE and MQTT_MAX_PACKET_SIZE . What are their maximum values ?

**Comment by knolleary** [comment]
http://pubsubclient.knolleary.net/api.html#configoptions

**Comment by Pragadheeshraj** [comment]
Each write call meaning every time I send data to the broker right ? Do you have any idea on the max packet size supported by ESP8266 ?

**Comment by knolleary** [comment]
It depends how much memory you want to dedicate to the buffer that handles the packets. I think you have 32KB of ram available for your sketch as a whole.

**Comment by Pragadheeshraj** [comment]
I can dedicate as much as 1KB. So to acheive this I need to change MQTT_MAX_PACKET_SIZE to 1024 right ?

**Comment by knolleary** [comment]
Yes

**Comment by Pragadheeshraj** [comment]
I tried changing it. Still no good. I cant send the above specified message

**Comment by knolleary** [comment]
What have you tried doing to debug this then? Have you tried different messages? Is it the length of the payload that's relevant? Is there a length at which it starts working?

**Comment by Pragadheeshraj** [comment]
Yeah it works at 
{"switches":[{"schedule":{},"switch_id":"3"},{"schedule":{},"switch_id":"2"},{"schedule":{},"switch_id":"5"},{"schedule":{},"switch_id":"9"}.

**Comment by knolleary** [comment]
So my guess is you're trying to dynamically allocate some memory somewhere and using too much. But without seeing your code I couldn't say for sure.

**Comment by Pragadheeshraj** [comment]
DynamicJsonBuffer  scheduleJson;
JsonObject& schroot = scheduleJson.createObject();
JsonArray& schswiar = schroot.createNestedArray("switches");
  
JsonObject& scharr = schswiar.createNestedObject();
JsonObject& schdet = scharr.createNestedObject("schedule");
JsonObject& scharr1 = schswiar.createNestedObject();
JsonObject& schdet1 = scharr1.createNestedObject("schedule");
JsonObject& scharr2 = schswiar.createNestedObject();
JsonObject& schdet2 = scharr2.createNestedObject("schedule");
JsonObject& scharr3 = schswiar.createNestedObject();
JsonObject& schdet3 = scharr3.createNestedObject("schedule");
JsonObject& scharr4 = schswiar.createNestedObject();
JsonObject& schdet4 = scharr4.createNestedObject("schedule");
JsonObject& scharr5 = schswiar.createNestedObject();
JsonObject& schdet5 = scharr5.createNestedObject("schedule");

Yeah I am using the JSON library to dynamically allocate memory

**Comment by Pragadheeshraj** [comment]
Decoding 21 results
0x402099d4: WiFiClient::write(unsigned char const*, unsigned int) at C:\Users\Pragadheesh Raj\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\libraries\ESP8266WiFi\src/WiFiClient.cpp line 342
0x4021f9ea: esf_buf_recycle at ?? line ?
0x4020d4b6: PubSubClient::write(unsigned char, unsigned char*, unsigned short) at C:\Users\Pragadheesh Raj\Documents\Arduino\libraries\arduino_191215\src/PubSubClient.cpp line 586
0x4021d9e8: ppRecycleRxPkt at ?? line ?
0x4020e46a: String::copy(char const*, unsigned int) at C:\Users\Pragadheesh Raj\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\cores\esp8266/WString.cpp line 175
0x4020e5f0: String::operator=(char const*) at C:\Users\Pragadheesh Raj\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\cores\esp8266/WString.cpp line 243
0x4010683a: malloc at C:\Users\Pragadheesh Raj\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\cores\esp8266/libc_replacements.c line 212
0x4020b584: PubSubClient::publish(char const*, unsigned char const*, unsigned int, unsigned char) at C:\Users\Pragadheesh Raj\Documents\Arduino\libraries\arduino_191215\src/PubSubClient.cpp line 586
0x4020e43a: String::reserve(unsigned int) at C:\Users\Pragadheesh Raj\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\cores\esp8266/WString.cpp line 146
0x4020b5bd: PubSubClient::publish(char const*, char const*) at C:\Users\Pragadheesh Raj\Documents\Arduino\libraries\arduino_191215\src/PubSubClient.cpp line 586
0x4020e394: String::~String() at C:\Users\Pragadheesh Raj\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\cores\esp8266/WString.cpp line 124
0x40208561: callback(char*, unsigned char*, unsigned int) at C:\Program Files (x86)\Arduino/InWiFiWebServerdemo6G.ino line 332
0x4020b4b5: PubSubClient::loop() at C:\Users\Pragadheesh Raj\Documents\Arduino\libraries\arduino_191215\src/PubSubClient.cpp line 586
0x4020b3e9: PubSubClient::loop() at C:\Users\Pragadheesh Raj\Documents\Arduino\libraries\arduino_191215\src/PubSubClient.cpp line 586
0x4020bb78: esp_yield at C:\Users\Pragadheesh Raj\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\cores\esp8266/core_esp8266_main.cpp line 43
0x40208a24: loop at C:\Program Files (x86)\Arduino/InWiFiWebServerdemo6G.ino line 212
0x40208972: setup at C:\Program Files (x86)\Arduino/InWiFiWebServerdemo6G.ino line 182
0x40101981: system_os_post at ?? line ?
0x4020bb99: esp_schedule at C:\Users\Pragadheesh Raj\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\cores\esp8266/core_esp8266_main.cpp line 43
0x4020bbc1: loop_wrapper at C:\Users\Pragadheesh Raj\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\cores\esp8266/core_esp8266_main.cpp line 43
0x40100114: cont_norm at C:\Users\Pragadheesh Raj\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\cores\esp8266/cont.

**Comment by Pragadheeshraj** [comment]
I tried decoding the stack and this is what I got

**Comment by Pragadheeshraj** [comment]
I have also used Strings in my sketch.. Could that also cause problems ?

**Comment by Pragadheeshraj** [comment]
I had just checked and I found that I cannot send String more than length 240

**Comment by knolleary** [comment]
I suspect you're running out of memory. Either way, this isn't an issue with the library so I'm going to close this issue.

**Comment by vortex314** [comment]
Encountered exactly the same issue, increasing message size parameters MQTT_MAX_TRANSFER_SIZE and MQTT_MAX_PACKET_SIZE, leads to the fact that WifiClient.write stalls and generates a Reset Soft WDT. 
Stack trace showed the same 2 routines generating this PubSubClient.write and the WifiClient.write.
