### ISSUE TITLE
Download PubSubclient 1.9 / help with older code

### ISSUE THREAD

**Issue by ballesjulian** [knolleary/pubsubclient#167]
hello ! 

i have an older code from 02.2016. [http://makezine.com/projects/building-a-home-automation-system-with-openhab-to-control-leds-wirelessly/](url)

but this doent work with the current version of pubsubclient. could someone give me the older version so i can make that code work ? 

thx!

**Comment by ballesjulian** [comment]
i think the version is 1.9 but im not sure...

**Comment by knolleary** [comment]
https://github.com/knolleary/pubsubclient/releases
