### ISSUE TITLE
Publish working good but unable to subscribe..

### ISSUE THREAD

**Issue by Akumar43** [knolleary/pubsubclient#168]
#include <ESP8266WiFi.h>
#include <Wire.h>
#include <PubSubClient.h>

#define wifi_ssid "iBall-Baton"
#define wifi_password "desd12345!"

#define mqtt_server "m12.cloudmqtt.com"
#define mqtt_user "f****db"
#define mqtt_password "M*************M7u"

#define humidity_topic "/test/topic"

void callback(char* topic, byte* payload, unsigned int length) {

Serial.print("Message arrived [");
  Serial.print(topic);
  Serial.print("] ");
  for (int i=0;i<length;i++) {
    Serial.print((char)payload[i]);
  }
  Serial.println();
}

WiFiClient espClient;
PubSubClient client(espClient);

void setup() {
  Serial.begin(115200);
  setup_wifi();
  client.setServer(mqtt_server,11523);
  client.subscribe("test/topic");
  client.setCallback(callback);
  
  delay(1500);
        }

void setup_wifi() {
  delay(10);
  // We start by connecting to a WiFi network
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(wifi_ssid);

  WiFi.begin(wifi_ssid, wifi_password);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());
}

void reconnect() {
  // Loop until we're reconnected
  while (!client.connected()) {
    Serial.print("Attempting MQTT connection...");
    // Attempt to connect
    // If you do not want to use a username and password, change next line to
    // if (client.connect("ESP8266Client")) {
    if (client.connect("ESP8266Client", mqtt_user, mqtt_password)) {
      Serial.println("connected");
    } else {
      Serial.print("failed, rc=");
      Serial.print(client.state());
      Serial.println(" try again in 5 seconds");
      // Wait 5 seconds before retrying
      delay(5000);
    }
  }
}

void loop() {
  if (!client.connected()) 
  {
    reconnect();
  }
  client.loop();
//client.publish(humidity_topic, "boo", true);
   
  }

**Comment by knolleary** [comment]
Sorry, you'll have to provide lots of more details if you want any help.

What happens when you try to subscribe?
