### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by ahuxtable** [knolleary/pubsubclient#17]
Hi, Great work on the library but would it be possible to introduce a connection timeout in the connect function? It currently seems to take about 30(?) or so seconds to timeout the connection and since this is a blocking function it holds up any other code unless interrupts are in use (which i can't use in my current project).

**Comment by swell-d** [comment]
Hi!
Has this problem been solved? 
I use my Yun as thermostat. So, if Wi-fi connection lost, I can't manage the temperature.

**Comment by knolleary** [comment]
Previously it reused the `MQTT_KEEPALIVE` value to timeout the connect. We've just added `MQTT_SOCKET_TIMEOUT` which lets you set how long it'll block on the socket when trying to read a packet. So whilst connecting is still a blocking function, you can reduce the timeout independently of the KEEPALIVE value. Hopefully that will provide what you want.
