### ISSUE TITLE
ESP8266 with https websocket connection?

### ISSUE THREAD

**Issue by elbowz** [knolleary/pubsubclient#176]
is it possible with this lib?

Something like:
```
// host and port overwritten at connect
var mqtt = new Paho.MQTT.Client("yourdomain.com", 9001, "");   

mqtt.connect({
    hosts: [ "wss://yourdomain.com:9001/" ],
    useSSL: true
});
```
in js with Paho JavaScript Client

thanks!

**Comment by knolleary** [comment]
This client uses whatever underlying network library you provide it. So the question is whether anyone created a websocket library that uses https and implements the standard Arduino Client.h library.

I have never come across such a library, so it probably isn't possible.

**Comment by elbowz** [comment]
mhhh, so with this lib (https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/src/WiFiClientSecure.cpp) should be works good?

Sorry but, I'm really noob on this stuff

**Comment by knolleary** [comment]
That library will allow you create a secure TCP connection - so you can use that with this library if you want to connect using TLS. It is not, however, a WebSocket library - so if that's important to you, this library isn't going to help.

**Comment by derrgis** [comment]
Yes that is possible with PubSubClient , Mosquitto Broker and Paho JS
If you want websocket AND mqtt protocol you have to specify in the .conf file you use and launched with:
$ mosquitto -c path_to_the_file

that file should have:
-
listener 9001
protocol websocket
listener 1883
protocol mqtt
-
EVEN if the defaut port and protocol are 1883 mqtt !

**Comment by elbowz** [comment]
The question was if it works on http over ask (ie https).

So works?

**Comment by derrgis** [comment]
Okay sorry.

**Comment by elbowz** [comment]
np...make me know if you'll able to enable https connection :+1:

**Comment by derrgis** [comment]
of course :)
