### ISSUE TITLE
proper handling of german umlaut in payload

### ISSUE THREAD

**Issue by macmeck** [knolleary/pubsubclient#188]
Is there a way to properly handle german umlaute in a payload when subscribing to topics? Iterating through the byte array as shown in the callback function from the examples does not seem to let me concatenate a String...
```

void mqttCallback(char* topic, byte* payload, unsigned int length) {

	String strPayload;

	// get the payload
	for (int i = 0; i < length; i++) {
		strPayload += (char)payload[i];
	}

	...

}
```

**Comment by knolleary** [comment]
You cannot use a 'char' type as it isn't a simple ASCII character. You need to use the String type provided by arduino - http://playground.arduino.cc/Code/UTF-8

This isn't something I have any experience of, but there ought to be plenty of samples online as this is not specific to this library.
