### ISSUE TITLE
Slow connect if broker is bad

### ISSUE THREAD

**Issue by hildar** [knolleary/pubsubclient#189]
I am developing a sketch on ESP8266 board. I wanted to make a program for LED driver with a physical switch, which could operate with the broker.

The problem is such that if the broker is available, the module is connected instantly (13ms). But if the broker is not available, the module tries to connect approximately 6 seconds. Accordingly, at this time the module does not respond to user input (e.g. physical switching switch).

Changing the MQTT_SOCKET_TIMEUT does not solve anything. Tried even assign a value of 0 - no result.

Below I put part of the message from the module to the Monitor port. Connection check occurs every 20 seconds.

> 
Time stamp reconnect server: 133440
WiFi connected
IP address: 
192.168.0.101
Time stamp to try connect Mosquitto: **133440**
Try Mosquitto to connect...
Time stamp the good connect Mosquitto: **133453**
Mosquitto connected

> 
Time stamp reconnect server: 113439
WiFi connected
IP address: 
192.168.0.101
Time stamp to try connect Mosquitto: **113439**
Try Mosquitto to connect...
Time stamp to failed connect Mosquitto: **119702**
failed connect Mosquitto, rc=-2

What can I change in the library, in order to reduce the connection time if the broker Mosquitto is not available?

**Comment by knolleary** [comment]
What network client are you using with the PubSubClient? All of that time will be spent within the network client trying to establish a connection.

There may be a configuration option in that network client to decrease whatever timeout it is using... but that is outside this library's control.

**Comment by hildar** [comment]
I use library <ESP8266WiFi.h>. Wi-Fi network. Router DIR-615. The network is fast. But the network is working. Disables only broker. Because I want to install it on a separate router and imitate him off.

So you want to say that the problem is in the client network library?
Hmm ..
Ie greatest time slot occurs at this stage:
[https://github.com/knolleary/pubsubclient/blob/master/src/PubSubClient.cpp#L123](url)

**Comment by knolleary** [comment]
Yes, that line is where the PubSubClient is waiting for the network client to create a TCP connection.

**Comment by hildar** [comment]
Many thanks!
