### ISSUE TITLE
Cannot edit header file?

### ISSUE THREAD

**Issue by hamfoo** [knolleary/pubsubclient#190]
I would like to change the value of: MQTT_MAX_PACKET_SIZE

If I replace 128 with say 200 and save, then build/compile, the value changes back to 128. 

I am using platformio to build&upload to ESP8266.

// MQTT_MAX_PACKET_SIZE : Maximum packet size
#ifndef MQTT_MAX_PACKET_SIZE
#define MQTT_MAX_PACKET_SIZE 128
#endif

**Comment by knolleary** [comment]
I believe in platformio you can use -D options when compiling in order to override those values... that is why we added the ifndef checks (see #124 and #119) - I don't know, I've not used it.

**Comment by hamfoo** [comment]
Of course! I also found an alternative way which is to rename the pubsubclient library files and add them as private libraries. Thanks!
