### ISSUE TITLE
pubsubclient interrupt

### ISSUE THREAD

**Issue by josep112** [knolleary/pubsubclient#192]
I'm using Pubsubclient and interruption to a dimmer. If I comment the loop.client () works perfectly but if you use it to receive data reset as below, anyone have any idea what can be already checked current source, resistors, appears to be probelma loop

#include <PubSubClient.h>
#include <ESP8266WiFi.h>      
#include <WiFiManager.h>         
#include <FS.h>
#include <ArduinoJson.h> 
#define zero_crosss_int  14
#define DEBOUNCE_TIME   6000
char blynk_token[33] = "CODIGO";
bool shouldSaveConfig = false;
//============================== CONFIGURACAO DE IP, SSID E SENHA  ========================
const char* host = "XXXXXXXXX"; 
String ip = "XXXXXXXXX:8085";
WiFiServer server(8085);
boolean wfconnected = false; // Verifica se tem conexao 
int result_hhtpCode = 0;
int tempo = 0;
String mac = WiFi.macAddress();
int cadastr_dispositiv = 0;
int AC_LOAD = 13;    // Saida triac
long dimming = 7300;  
int i = 0;
int x = 0;
int INTERRUPTOR =  5; 
int status = 0;
int httpCode;
String resultado;
unsigned long duracao = 0;
unsigned long inicio;
int cont = 0;
static uint32_t lastPulse = 0;
static uint16_t period    = 7000; //5ms - 50% for each half wave
static bool high = false;
//===============================Zero cross do dimmer ======================================
void onTimerISR()
{
  if(high)
  {
    digitalWrite(AC_LOAD, LOW);
    high = false;
  } 
  else 
  {
    digitalWrite(AC_LOAD, HIGH);
    high=true;
    timer1_write(400*5);
  }
}

void onPinISR()
{
  uint32_t now = micros();
  if(now - lastPulse < DEBOUNCE_TIME) return;
  lastPulse = now;
  timer1_write(dimming * 5);
  
}
//===================================CALLBACK DO CODIGO DE USUARIO==========================
void saveConfigCallback () 
{
  Serial.println("Should save config");
  shouldSaveConfig = true;
}     

void callback(char* topic, byte* payload, unsigned int length)
{
  char message_buff[100];
  Serial.println("zerocross");
  int i = 0;
   for(i=0; i<length; i++) 
     {
       message_buff[i] = payload[i];
      }
       message_buff[i] = '\0';
       String msgString = String(message_buff);
       Serial.println("Mensagem: " + msgString);  
       
if(msgString == "0")
      {
        //Serial.println("entrou no 00000");
        detachInterrupt(14);
      dimming = 7300;
      i=7300;
      x=0;
      }
       else if(msgString == "10")
          {
            attachInterrupt(digitalPinToInterrupt(zero_crosss_int), onPinISR, RISING);
          dimming = 6805;
          i=6805;
          x=1;
           } 
            else if(msgString == "20")
              {
                attachInterrupt(digitalPinToInterrupt(zero_crosss_int), onPinISR, RISING);
               dimming = 6310;
               i=6310;
               x=2;
               }
                else if(msgString == "30")
                  {
                    attachInterrupt(digitalPinToInterrupt(zero_crosss_int), onPinISR, RISING);
                  dimming = 5815;
                  i=5815;
                  x=3;
                  }
                   else if(msgString == "40")
                      {
                        attachInterrupt(digitalPinToInterrupt(zero_crosss_int), onPinISR, RISING);
                     dimming = 5320;
                     i=5320;
                     x=4;
                      }
                      else if(msgString == "50")
                         {
                          attachInterrupt(digitalPinToInterrupt(zero_crosss_int), onPinISR, RISING);
                        dimming = 4825;
                        i=4825;
                        x=5;
                          }
                           else if(msgString == "60")
                             {
                              attachInterrupt(digitalPinToInterrupt(zero_crosss_int), onPinISR, RISING);
                             dimming = 4330;
                             i=4330;
                             x=6;
                              }
                              else if(msgString == "70")
                                 {
                                  attachInterrupt(digitalPinToInterrupt(zero_crosss_int), onPinISR, RISING);
                                dimming = 3835;
                                i = 3835;
                                x=7;
                                 }
                                 else if(msgString == "80")
                                 {
                                  attachInterrupt(digitalPinToInterrupt(zero_crosss_int), onPinISR, RISING);
                                    dimming = 3340;
                                    i = 3340;
                                    x=8;
                                 }
                                    else if(msgString == "90")
                                     {
                                      attachInterrupt(digitalPinToInterrupt(zero_crosss_int), onPinISR, RISING);
                                     dimming = 2845;                                
                                      i = 2845; 
                                      x=9;
                                       }
                                       else if(msgString == "100")
                                       {
                                        attachInterrupt(digitalPinToInterrupt(zero_crosss_int), onPinISR, RISING);
                                           dimming = 2350;
                                           i = 2350;
                                           x=10;
                                       }           
} 
WiFiClient wifiClient;
PubSubClient client(host, 1883, callback, wifiClient);    
//===============================SETUP ============================== 
void setup() 
{
  Serial.begin(115200);  

  pinMode(AC_LOAD, OUTPUT);// LUZ I GPIO 13
  pinMode(zero_crosss_int, INPUT);
  pinMode(INTERRUPTOR, INPUT_PULLUP); // chave de pulso do dimmer
  timer1_attachInterrupt(onTimerISR);
  timer1_enable(TIM_DIV16, TIM_EDGE, TIM_SINGLE); 
   //attachInterrupt(digitalPinToInterrupt(zero_crosss_int), onPinISR, RISING);
  server.begin();

void interruptor_dimmer()
{          
            int Milliseconds;
            int deboucing;
            int status_botao = 0;
            if(digitalRead(INTERRUPTOR) == LOW) 
               {                                           
                        // Serial.println("valor do cont e:");
                        // Serial.println(cont);
                         Serial.println("valor de dimming e");
                         Serial.println(dimming);         
                    if (x == 0)
                      {
                         attachInterrupt(digitalPinToInterrupt(zero_crosss_int), onPinISR, RISING);
                         i=7300;   
                      }                                      
                           i-=495;
                           x++;
                       // Serial.println(i); // mostra o valor de i
                           dimming=i;    
                           status = 1;
                       //  Serial.println(x);
                       if(x == 11)
                        {
                         detachInterrupt(14);
                         dimming=7300;
                          i=7300;
                          x=0;
                         }
                          Milliseconds = millis()+250;      // Esse é do loop do dimmer
                          while (Milliseconds > millis()) ;                        
              }   
               
           }

//============================== LOOP  ========================
void loop() 
{             
  interruptor_dimmer();  
      client.loop();
}

**Comment by cennok** [comment]
I have a very similar application, and going through the same crashing issue here.

**Comment by josep112** [comment]
The problem was solved with the ICACHE_RAM_ATTR



void ICACHE_RAM_ATTR onTimerISR()
{
  if(high)
  {
    digitalWrite(AC_LOAD, LOW);
    high = false;
  } 
  else 
  {
    digitalWrite(AC_LOAD, HIGH);
    high=true;
    timer1_write(400*5);
  }

}

void ICACHE_RAM_ATTR onPinISR()
{
  uint32_t now = micros();
  if(now - lastPulse < DEBOUNCE_TIME) return;
  lastPulse = now;
  timer1_write(dimming * 5); 
}
