### ISSUE TITLE
Message too long?

### ISSUE THREAD

**Issue by eyp** [knolleary/pubsubclient#193]
Hi, just a question about this piece of code that checks if the message is too long to be published:

`if (MQTT_MAX_PACKET_SIZE < 5 + 2+strlen(topic) + plength) {
      // Too long
      return false;
  }`

MQTT_MAX_PACKET_SIZE is defined as 128. I think it's very limited, isn't it?. I know that you say in the 'Limitaitons' that it can be changed in the PubSubclient.h, but why by default is so small the size?

**Comment by knolleary** [comment]
Because when I wrote this library ~6 years ago, that was just about all you could get away with on the arduino. There is a case to be made to increase it to reflect what you get these days.

**Comment by eyp** [comment]
Ok, just was out of curiosity, and to not fork only the library to increase the value, but well, it's done. Thanks a lot for your work.
