### ISSUE TITLE
WifiClient problem

### ISSUE THREAD

**Issue by panagorn** [knolleary/pubsubclient#196]
Hello i am using pubsubclient to publish messages to mqtt and also i have a wificlient to get data from internet. When i put the code with the wificlient to get data from the web the pubsubclient is not working
[This is an example with wificlient make an http request](https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/examples/WiFiClient/WiFiClient.ino)

**Comment by knolleary** [comment]
I'm sorry to hear that... It works fine for me. Can't really help unless you want to share your code to look at.

**Comment by panagorn** [comment]
`#include <ArduinoJson.h>
#include <ESP8266WiFi.h>
#include <PubSubClient.h>

#define wifi_ssid "smarthome"
#define wifi_password "raspberry"

#define mqtt_server "192.168.10.31"


WiFiClient espClient;
PubSubClient client(espClient);
WiFiClient timeClient;

String TYPE = "MAGNETIC";

String clientName;
String roomTopic;
bool isActive;

int sensorPin = 2; // input pin number
int val = LOW;
int magneticState = LOW;

void setup() {
  Serial.begin(115200);
  setup_wifi(); // connect to wifi
  isActive = false; // set as not active
  getName(); // create esp module name with mac address
  client.setServer(mqtt_server, 1883);
  client.setCallback(callback);

  // setup pin as input
  pinMode(sensorPin, INPUT);
}

void setup_wifi() {
  delay(10);
  // We start by connecting to a WiFi network
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(wifi_ssid);

  WiFi.begin(wifi_ssid, wifi_password);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());
}

/**
   MQTT messages callback
*/
void callback(char* topic, byte* payload, unsigned int length) {
  Serial.print("Message arrived [");
  Serial.print(topic);
  Serial.print("] ");

  String top = String(topic);
  String msg = String((char *)payload);
  String sub = "/sensor/" + clientName; // subsciber link

  // personal message arrived in response of the
  // unregistered message. So subscibe to the given room
  if (top.equals(sub)) {
    char json[256];
    msg.toCharArray(json, 256);
    StaticJsonBuffer<256> jsonBuffer;
    JsonObject& root = jsonBuffer.parseObject(json);

    if (!root.success())
    {
      Serial.println("parseObject() failed");
      return;
    }
    isActive = root["active"]; // set active
    const char* sub = root["subscribe"];
    roomTopic = sub; // room topic to send data

    //subscribe at room topic
    String roomTopicSub = roomTopic + "/receive";
    client.subscribe((char*) roomTopicSub.c_str());
  } else if (top.equals(String(roomTopic + "/receive"))) { // have to send data
    String topic = roomTopic + "/send";
    sendData(val, topic);
  }

  Serial.println();
}


void reconnect() {
  // Loop until we're reconnected
  while (!client.connected()) {
    Serial.print("Attempting MQTT connection...");
    // Attempt to connect
    if (client.connect((char*) clientName.c_str())) {
      Serial.println("connected");
    } else {
      Serial.print("failed, rc=");
      Serial.print(client.state());
      Serial.println(" try again in 5 seconds");
      // Wait 5 seconds before retrying
      delay(5000);
    }
  }

  char buffer[256];
  StaticJsonBuffer<256> jsonBuffer;

  JsonObject& root = jsonBuffer.createObject();
  root["type"] = (char*) TYPE.c_str();

  root.printTo(buffer, sizeof(buffer));

  String sub = "/sensor/" + clientName; // subsciber link

  client.subscribe((char*) sub.c_str());
  client.publish("/sensor/unregistered", buffer, true); // send unregister message
}

/**
   Convert mac address to string
*/
String macToStr(const uint8_t* mac)
{
  String result;
  for (int i = 0; i < 6; ++i) {
    result += String(mac[i], 16);
    if (i < 5)
      result += ':';
  }
  return result;
}

/**
   Get module name based on
   the mac address
*/
void getName() {
  uint8_t mac[6];
  WiFi.macAddress(mac);
  clientName += macToStr(mac);
}

void loop() {
  if (!client.connected()) {
    reconnect();
  }
  client.loop();
  if (isActive) {
    String topic = "/data";
    val = digitalRead(sensorPin);
    if (val == HIGH) {
      if (magneticState == LOW) {
        Serial.println("Motion closed");
        magneticState = HIGH;
        sendData(magneticState, topic);
      }
    } else {
      if (magneticState == HIGH) {
        Serial.println("Magnetic open");
        magneticState = LOW;
        sendData(magneticState, topic);
      }
    }
  }
}


/**
   Send data back to the mobile app
*/
void sendData(int isOpen, String topic) {

  String stime = getTime();

  char buffer[256];
  StaticJsonBuffer<256> jsonBuffer;

  JsonObject& root = jsonBuffer.createObject();
  root["macAddress"] = (char *) clientName.c_str();
  JsonObject& nestedObject = root.createNestedObject("data");
  nestedObject["isOpen"] = isOpen;
  nestedObject["time"] = (char*)stime.c_str();

  root.printTo(buffer, sizeof(buffer));

  Serial.println((char*) topic.c_str());
  client.publish((char*) topic.c_str(), buffer, true);
}

String getTime() {
  const char* host = "httpbin.org";
  const int httpPort = 80;
  if (!timeClient.connect(host, httpPort)) {
    Serial.println("connection failed");
    return "";
  }

  // We now create a URI for the request
  String url = "/get";

  Serial.print("Requesting URL: ");
  Serial.println(url);

  // This will send the request to the server
  timeClient.print(String("GET ") + url + " HTTP/1.1\r\n" +
               "Host: " + host + "\r\n" +
               "Connection: close\r\n\r\n");
  unsigned long timeout = millis();
  while (timeClient.available() == 0) {
    if (millis() - timeout > 5000) {
      Serial.println(">>> Client Timeout !");
      timeClient.stop();
      return "";
    }
  }
  String line = "";
  // Read all the lines of the reply from server and print them to Serial
  while (timeClient.available()) {
    line += timeClient.readStringUntil('\r');
  }

  Serial.print(line);
  Serial.println();
  Serial.println("closing connection");

  return line;
}
`

**Comment by panagorn** [comment]
getTime function makes an http request. I am using this code on esp8266 if it is matter

**Comment by knolleary** [comment]
And what about it doesn't work? Have you tried the basic example that comes with the library? What steps have you taken to try to debug this?

**Comment by panagorn** [comment]
If i remove the getTime function the publish messages is received by the subscibers. if i put the getTime function then the published message is never sen

**Comment by knolleary** [comment]
There have been a number of reports of issues trying to make two network connections at the same time. This appears to be just that. Not a lot I can do about that if it's a limitation of the underlying hardware/platform.
