### ISSUE TITLE
Change the transmission buffer length

### ISSUE THREAD

**Issue by Gherma00** [knolleary/pubsubclient#204]
Hi 
I have a problem with the published message buffer length. A message like this:
 ex. {"meaning":"state","value":0} ,is properly published.
But if I send in a unique message with several Json (ex: [{"meaning":"state","value":0},{"meaning":"humidity","value":33.4},{"meaning":"noise","value":4576},{"meaning":"temperature","value":15}]) I can't, is too long.
How can i do?Can i change the transmission buffer length?How?
Thanks you.

**Comment by knolleary** [comment]
Hi,

please see http://pubsubclient.knolleary.net/api.html#configoptions - `MQTT_MAX_PACKET_SIZE`

You need to edit `PubSubClient.h` to change that value.
