### ISSUE TITLE
Read EEPROM before Setup in Arduino IDE

### ISSUE THREAD

**Issue by dnksavaliya** [knolleary/pubsubclient#207]
Hello sir, 

Is it possible to initialize global variable MQTTBroker from EEPROM before Setup in Arduino IDE?
as PubSubClient mqtt(MQTTBroker, port);   require values globally.
Thank you

**Comment by felipemfp** [comment]
You can use this approach:

```ino
#include <...>

EthernetClient ethClient;
PubSubClient client(ethClient);

void setup()
{
  // read `server` from EEPROM
  client.setServer(server, 1883);
}

```

**Comment by knolleary** [comment]
@dnksavaliya has the response from @felipemfp helped?
