### ISSUE TITLE
internet connectivity issue

### ISSUE THREAD

**Issue by kasisripada17** [knolleary/pubsubclient#208]
im using esp8266 as a wifi to serial bridge and mqtt bridge. is there any way know the internet status in esp8266? if there is no internet connectivity , esp tries to reconnect to the server .at that time tcp data was blocking. thanks in advance

**Comment by knolleary** [comment]
Hi, sorry, this isn't regarding this client library and I don't know the answer to your question. I'm sure a google search will help you out.
