### ISSUE TITLE
publishing is crashing ESP8266 when called by interrupt

### ISSUE THREAD

**Issue by elecherf** [knolleary/pubsubclient#209]
Hi, 

I want to publish something via an interrupt like
 
attachInterrupt(digitalPinToInterrupt(MY_PIN), irqmethod, RISING);

my irqmethod is doing a publish
 boolean result = mqttClient.publish(TOPIC, buffer);

And everytime, it is going into Exception (9): .....
And ESP rebooting.

Any idea ?
Thank you

**Comment by knolleary** [comment]
This library doesn't support publishing from an interrupt; a known limitation.

**Comment by elecherf** [comment]
Thank you for quick answer. Bad news for me, i need to change :-(
