### ISSUE TITLE
Allow class-based callback function

### ISSUE THREAD

**Issue by knolleary** [knolleary/pubsubclient#21]
Enable the callback function to be a class member. The following is not currently possible, but desirable:
```C
class MyMqttWrapperClass {
   byte server[] = { 10, 1, 1, 1 };
   PubSubClient *mqttclient;
   void mycallback(char* topic, byte* payload, unsigned int length) {
      //do something here
   }
   void init() {
      mqttlclient=new PubSubClient(server, 1883, this->mycallback, ethClient);
   }
}
```

**Comment by marvinroger** [comment]
@knolleary, why was this closed?
It should be pretty easy to implement with the help of `#include <functional>`.

```c++
typedef std::function<void(char*, uint8_t*, unsigned int)> MQTT_CALLBACK_SIGNATURE;
```

Then we could:

```c++
setCallback(std::bind(&MyMqttWrapperClass::mycallback, this)); 
```

I know `functional` is available for the ESP8266, not sure about original Arduinos though.

**Comment by knolleary** [comment]
I closed it because after 2 years of being open it had never proven to be needed and I wasn't confident of the side effects such a change would have.

If a pull request arrived that made this change in a 100% backward compatible way, for all platforms, then I'd certainly consider it.

**Comment by FredClement91** [comment]
Hi,
Even if the request is rather old, I find it interesting. I didn't find the way th use PubSubClient inside a class and use a method of that class as the callback.
