### ISSUE TITLE
how to add a unique ID like Chip ID to identify the nodes

### ISSUE THREAD

**Issue by gsmartnet** [knolleary/pubsubclient#213]
Dear Sir
Thanks for the code, it's really helpful.
how can I add a unique way (like ChipID) but the same topic to identify the nodes?
please help me out.

Best Regards

**Comment by knolleary** [comment]
Hi,
I'm not sure what you are asking. Can you explain a bit more what you want to do?

**Comment by gsmartnet** [comment]
I'm trying to connect more than one node(esp8266) but with a same topic an payload.  how can I identify them based on their chipID's?

**Comment by knolleary** [comment]
Each client must have a unique clientid. That is a requirement of MQTT. So to begin with, you'll need to ensure each uses some unique value like the chipID you mention as part of the clientid.

Then it is up to you how to structure your topics and payloads. For example, you could have each one publish to `mytopic/<clientid>` - so that an application subscribed to `mytopic/#` will receive all the messages and be able to identify which client it came from based on the full topic.

**Comment by vitasam** [comment]
Hi, I will need the same functionality.  I guess one should add it's own identification code nside the payload

Get Outlook for Android<https://aka.ms/ghei36>



On Wed, Nov 16, 2016 at 12:08 PM +0200, "gsmartnet" <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm trying to connect more than one node(esp8266) but with a same topic an payload. how can I identify them based on their chipID's?

-

**Comment by knolleary** [comment]
@vitasam more typically you would use the topic to help identify where a message came from.. but it is up to you. The actual content of the topic and payload is of no concern to this library.

**Comment by vitasam** [comment]
@khollear, yes that's what I was about to say :)

Get Outlook for Android<https://aka.ms/ghei36>



On Wed, Nov 16, 2016 at 12:15 PM +0200, "knolleary" <notifications@github.com<mailto:notifications@github.com>> wrote:


@vitasam<https://github.com/vitasam> more typically you would use the topic to help identify where a message came from.. but it is up to you. The actual content of the topic and payload is of no concern to this library.

-

**Comment by thebeswick** [comment]
There's a good thread here that covers this. 
https://github.com/knolleary/pubsubclient/pull/169/files#diff-0
