### ISSUE TITLE
KeepAlive timeout and Reconnect to Broker 

### ISSUE THREAD

**Issue by waqas-ogc** [knolleary/pubsubclient#221]
If KeepAlive timeouts , then should I manually reconnect to broker or library will reconnect automatically ? Also how can I keep checking if there is a KeepAlive timeout , using state() function ?

**Comment by knolleary** [comment]
The client does not automatically reconnect. You can use `Client.connected()` to check the state of the connection, as well as the return code of any function call you make.

The example sketches demonstrates this in action: https://github.com/knolleary/pubsubclient/blob/4c8ce14dada84af6783233d38d735958ff332362/examples/mqtt_basic/mqtt_basic.ino#L73
