### ISSUE TITLE
ESP8266 to RPi Mosquitto connection failed

### ISSUE THREAD

**Issue by bkenobi** [knolleary/pubsubclient#226]
My issue sounds similar to other posted issues, but since I don't know if it is identical I decided to open a new one rather than reopen or take over a different one.

In my case, I am using a Wemos D1 (also tried NodeMCU v3.0) connecting to a RPi running Mosquitto 1.4.10 and compiled using Arduino 1.6.4 and PubSubClient 2.4.  I am able to run a web server and publish to an online MQTT broker but cannot connect to an RPi based Mosquitto broker.

If I use the web server example (ESP8266WebServer/HelloServer), everything works great.  If I use the ESP8266 example (PubSubClient/mqtt_esp8266) example and connect to the default broker (broker.mqtt-dashboard.com), everything works great.  However, if I try to switch to connection to my RPi, I get the typical time out.
`Attempting MQTT connection...failed, rc=-2 try again in 5 seconds`
The only thing I changed from default was the following lines:
`const char* ssid = "Linksys_1";
//const char* password = "........";
const char* mqtt_server = "broker.mqtt-dashboard.com";
//IPAddress mqtt_server(35,156,71,85);
//IPAddress mqtt_server(192, 168, 0, 200);`
and
`  Serial.print("Connecting to ");
  Serial.println(ssid);
  WiFi.hostname("ESP8266");
  
//  WiFi.begin(ssid, password);
  WiFi.begin(ssid);`
I don't see where the issue lies since the IPAddress line works when connecting to the default server:
`.
WiFi connected
IP address: 
192.168.0.48
Attempting MQTT connection...connected
Attempting MQTT connection...connected
Attempting MQTT connection...connected
Attempting MQTT connection...connected
Publish message: hello world #1
Message arrived [inTopic] 0
Attempting MQTT connection...connected
Message arrived [inTopic] 0
Attempting MQTT connection...connected
Message arrived [inTopic] 0`
and I see it on the RPi as well:
`pi@raspberrypi ~ $ mosquitto_sub -h 35.156.71.85 -t "myTopic" -v
myTopic hello world
myTopic hello world
myTopic hello world
myTopic hello world
myTopic hello world`

Also, I did attempt to change the MQTT version from 3.1.1 to 3.1 in the PubSubClient.h file without success.  Changing the max packet size did not seem to help either.

I can provide any additional details that might help.  I've also tried newer versions of the IDE and it hasn't seemed to help, but I can give it a second chance.  I'll continue to look at this but a second set of expert eyes would certainly be appreciated.  You were easily able to help the last time I used your library (issue #111).

**Comment by bkenobi** [comment]
Upon further testing, I can publish abd subscribe to the broker from the RPI but not from other systems. I think Mosquito or the RPI are blocking the connection for some reason.  I'll continue digging but this may not be a Pubsubclient issue.

**Comment by bkenobi** [comment]
I determined that the issue was related to the Mosquitto broker having a bad configuration file.  It was corrected and the example now publishes correctly.

**Comment by amineBenguesmia** [comment]
what changes did u made ?

**Comment by bkenobi** [comment]
From memory, I deleted the bad one and started with a new one. I did nothing exotic though.

**Comment by amrutamagdum** [comment]
We are able to connect nodemcu to wifi but but no longer connected to cloud.arest.io.
Please guide us. What could be the problem??
