### ISSUE TITLE
Allow SSL/TLS support at the client side - Please help

### ISSUE THREAD

**Issue by ankitherocker** [knolleary/pubsubclient#23]
Please help in supporting SSL at the client side, this is very much required for the security measure. Also, will this SSL MQTT client work with ATMEGA 328?
Please help.

**Comment by d3str0y3rport** [comment]
How about on an arduino Zero?

**Comment by knolleary** [comment]
@d3str0y3rport no idea... suggest you ask in an arduino forum as I have never touched a Zero so would only be doing the same google searches you could.
