### ISSUE TITLE
PubSubClient client(server, 1883, callback, ethClient); causes a debug error

### ISSUE THREAD

**Issue by roquito** [knolleary/pubsubclient#24]
Hi, when I debug any of the examples, the line "PubSubClient client(server, 1883, callback, ethClient);" gets highlighted and the error is as follows, any ideas?

Arduino: 1.5.4 (Windows 7), Board: "Arduino Yún"

mqtt_publish_in_callback:30: error: 'PubSubClient' does not name a type
mqtt_publish_in_callback.ino: In function 'void callback(char_, byte_, unsigned int)':
mqtt_publish_in_callback:42: error: 'client' was not declared in this scope
mqtt_publish_in_callback.ino: In function 'void setup()':
mqtt_publish_in_callback:51: error: 'client' was not declared in this scope
mqtt_publish_in_callback.ino: In function 'void loop()':
mqtt_publish_in_callback:59: error: 'client' was not declared in this scope

**Comment by khalebios** [comment]
Same error for me.
Add new library and import the zip file solved i!

**Comment by pickeld** [comment]
same here i get error when trying to compile:

> WARNING: Category '' in library OneWire is not valid. Setting to 'Uncategorized'
> C:\Users\*****\Documents\Arduino\libraries\PubSubClient\examples\mqtt_esp8266\mqtt_esp8266.ino: In function 'void setup()':
> 
> mqtt_esp8266:44: error: 'setup_wifi' was not declared in this scope
> 
>    setup_wifi();
> 
>               ^
> 
> mqtt_esp8266:46: error: 'callback' was not declared in this scope
> 
>    client.setCallback(callback);
> 
>                       ^
> 
> exit status 1
> 'setup_wifi' was not declared in this scope

**Comment by klogdog** [comment]
For me the compiling error of setup_wifi(); not declared was solved by putting the setup_wifi() function above the setup function. (also had to put the callback function above the function it was being called from)

I am using a wemos mini d1 pro.

**Comment by sctv** [comment]
@klogdog I had the same problem.

**Comment by saintofinternet** [comment]
i am having the problem with Visual Studio Code.

Following Error:
```

src\main.cpp: In function 'void setup()':
src\main.cpp:33:3: error: 'client' was not declared in this scope; did you mean 'Client'?
   33 |   client.setServer(ThingsboardHost, 1883);
      |   ^~~~~~
      |   Client
*** [.pio\build\esp12e\src\main.cpp.o] Error 1
```

**Comment by knolleary** [comment]
@saintofinternet this is a closed issue. Not really the best place to ask a completely unrelated question.

**Comment by saintofinternet** [comment]
> 
> 
> @saintofinternet this is a closed issue. Not really the best place to ask a completely unrelated question.

sorry for the trouble. will delete it!
