### ISSUE TITLE
Problem with chunked packets.

### ISSUE THREAD

**Issue by GermanBluefox** [knolleary/pubsubclient#242]
Hello Nick,
please look at this [conversation](https://github.com/mqttjs/mqtt-packet/issues/24#issuecomment-277387905). The guys claim that the implementation here is wrong, because no chunked packets could be processed. I am agree with them, but I know the reality and can assume that this implementation is RAM optimized and so on and it can run on devices with very less RAM.

Now I have a dilemma:
- many ESP8266 images use this sketch for communication
- the implementation is wrong and I need a work around to communicate with them.

I can't change the MQTT implementation here (https://github.com/mqttjs/mqtt-packet) because guys are sure, that your code is wrong (e.g. [here](https://github.com/knolleary/pubsubclient/blob/master/src/PubSubClient.cpp#L252) the starting bytes of packet will be destroyed) 
and I can't force all ESP8266 images to use new (not yet existing) cpp sketch with chunking. 

Can you comment it? Is chunking allowed or not in MQTT over TCP? 
TCP is a stream and it is not guaranteed, that your bytes will come together. 

Greetings, Bluefox

**Comment by knolleary** [comment]
To draw someone's attention to an issue on GitHub, you just have to @-mention them. No need to raise an issue in their repository.
