### ISSUE TITLE
ESP-8266 mqtt client dont reconnect, if the connection is lost

### ISSUE THREAD

**Issue by robertgregor** [knolleary/pubsubclient#243]
Hello, it seems, there is serious issue to reconnect the mqttClient. It can't reconnect, even if the network connection is available. I have this code:

WiFiClient wclient;
PubSubClient mqttClient(wclient);

void disconnectMqttClient() {
  if (mqtt_server[0] == 0) return;
  mqttClient.disconnect();
}
void connectMqttClient() {
  if (mqtt_server[0] == 0) return;
  disconnectMqttClient();
  Serial.println(F("Trying to connect mqtt..."));
  if (!mqttClient.connected()) {
    //connect client
    Serial.println(F("Connecting..."));
    IPAddress mqttServer(getIpAddrFromArr(mqtt_server));
    mqttClient.setServer(mqttServer, mqtt_port);
    if (mqtt_user.length() == 0) {
      mqttClient.connect(mqtt_client_id.c_str());
    } else {
      mqttClient.connect(mqtt_client_id.c_str(), mqtt_user.c_str(), mqtt_pwd.c_str());
    }
    if (mqttClient.connected()) {
          Serial.println(F("Mqtt connected."));
          mqttClient.setCallback(callback);
          mqttClient.subscribe(mqtt_in_topic.c_str());
    } else {
          Serial.println(F("Mqtt not connected."));
    }
  }
}

void loop() {
  if (mqtt_server[0] != 0) {
    if (!mqttClient.connected()) {
      long now = millis();
      if (now - lastReconnectAttempt > 5000) {
        lastReconnectAttempt = now;
        // Attempt to reconnect
        connectMqttClient();
        if (mqttClient.connected()) {
          lastReconnectAttempt = 0;
        }
      }
    } else {
      // Client connected
      mqttClient.loop();
    }    
  }  
}

So as is seen, I have reconnect functionality in place - similar like in the example. But when the connection is lost, it never connects back:

Trying to connect mqtt...
Connecting...
Mqtt not connected.

If the module boots, it connect without any problem, but after while - sometimes 10 mins, sometimes an hour, it will loose the connection and never reconnects. I have tried to ping the device and it can be ping, so it has the network connection. Seems to me, that mqttClient can't be reused.

**Comment by robertgregor** [comment]
I think, I know, what is the problem: The code is fine, and library as well. The problem is, tha in the loop method, I did some heavy operations and it looks like, that this caused the problem with the stability of the socket. I have put to these heavy operation time to time delay(10) and seems it is working fine now. Seems, that this delay let the esp8266 fw to do the socket maint. job :)

**Comment by razvan-theodor** [comment]
Hello. I'm programming an esp32 and have the same problem. After I reboot the router and mqtt tries to reconnect, I always get connection failed (state -2). If you have resolved this, can you please post your code here?

**Comment by gokhantahil** [comment]
Did you solve it ? I had a same problem and now i solved it. I can help you if you want. @thrazu @robertgregor

**Comment by PixelSox** [comment]
Same problem, @gokhantahil can you help me?

**Comment by gokhantahil** [comment]
@PixelSox yes, pm me. I’ll help you asap.

**Comment by giovanne123** [comment]
@gokhantahil can you please post your solution. I have the same problem with the reconnects.

**Comment by gokhantahil** [comment]
@giovanne123 can you send me an email ?

**Comment by suraj9657** [comment]
@gokhantahil same problem, can you please post the solution.
