### ISSUE TITLE
using pubsubclient for connect to adafruit io

### ISSUE THREAD

**Issue by josb86** [knolleary/pubsubclient#256]
In Adafruit io tell that pubsubclient work whit its plataform of mqtt, [https://learn.adafruit.com/adafruit-io/arduino](url) but when I try cnonnect I recibe a error, failed, rc=5 , I am using the arduino due and the ethernet shield R3, an the code like this:

```
#include <SPI.h>
#include <Ethernet.h>
#include <PubSubClient.h>

#define ADAFRUIT_USERNAME           "xxxxx"
#define AIO_KEY                     "xxxxtxxtxtxtxtxtxtxtx"
#define FEED_PATH1                   "xxxxxx/feeds/onoff1/"
#define FEED_PATH2                   "xxxxxxx∕feeds∕onoff2/"

void callback (char* topic, byte* payload, unsigned int length) {
  Serial.println(topic);
  Serial.write(payload, length);
  Serial.println("");
}

byte mac[] = {0xXX, 0xXX, 0xXX, 0xXX, 0xXX, 0xXX};
byte ip[] = {192, 168, 10, 200};
EthernetClient ethClient;
PubSubClient mqttclient("io.adafruit.com", 1883, callback, ethClient);

void reconnect() {


  mqttclient.connect(ADAFRUIT_USERNAME, AIO_KEY, "");

  while (!mqttclient.connected()) {
    Serial.print("Attempting MQTT connection...");
    Serial.print(mqttclient.connected());
    if (mqttclient.connect(ADAFRUIT_USERNAME, AIO_KEY, "")) {
      Serial.println("MQTT Connected Adafruit");
      mqttclient.subscribe(FEED_PATH1);
      Serial.print("Suscrito a ");
      Serial.println(FEED_PATH1);
      mqttclient.subscribe(FEED_PATH2);
      Serial.print("Suscrito a ");
      Serial.println(FEED_PATH2);
      
    } else {
      Serial.print("failed, rc=");
      Serial.print(mqttclient.state());
      Serial.println(" try again in 5 seconds");
      delay(5000);
    }
  }

   
}

void setup(void)
{

  Serial.begin(115200);
  Serial.println("Iniciando....");
  Serial.println("Iniciando modulo ethernet");


  if (Ethernet.begin(mac) == 0) {
    Serial.println("Failed to configure Ethernet using DHCP");
    while(Ethernet.begin(mac) == 0){
      delay(200);
    }
  }
  delay(2000); //give the ethernet a second to initialize
  Serial.print("IP: ");
  Serial.println(Ethernet.localIP());  
  
}

void loop(void) {


  if (!mqttclient.connected()) {
    reconnect();
  }
  mqttclient.loop();
  delay(250);
}

```

mqttclient.connect(ADAFRUIT_USERNAME, AIO_KEY, ""); is ok?

**Comment by josb86** [comment]
now I change

mqttclient.connect(ADAFRUIT_USERNAME, AIO_KEY, "");

to

mqttclient.connect("", ADAFRUIT_USERNAME, AIO_KEY, "");

but now  show error failed, rc=6 and this error no exist in the list!

> int - the client state, which can take the following values (constants defined in PubSubClient.h):
-4 : MQTT_CONNECTION_TIMEOUT - the server didn't respond within the keepalive time
-3 : MQTT_CONNECTION_LOST - the network connection was broken
-2 : MQTT_CONNECT_FAILED - the network connection failed
-1 : MQTT_DISCONNECTED - the client is disconnected cleanly
0 : MQTT_CONNECTED - the cient is connected
1 : MQTT_CONNECT_BAD_PROTOCOL - the server doesn't support the requested version of MQTT
2 : MQTT_CONNECT_BAD_CLIENT_ID - the server rejected the client identifier
3 : MQTT_CONNECT_UNAVAILABLE - the server was unable to accept the connection
4 : MQTT_CONNECT_BAD_CREDENTIALS - the username/password were rejected
5 : MQTT_CONNECT_UNAUTHORIZED - the client was not authorized to connect

> 

>

**Comment by knolleary** [comment]
The `6` will be coming from the adafruit broker, not the client. You should check their docs for what that means as it isn't a standard MQTT return code and may identify a broker specific issue with your connection.
