### ISSUE TITLE
Two ESP8266 clients can not be connected at the same time

### ISSUE THREAD

**Issue by SuperMoran** [knolleary/pubsubclient#259]
MQTT Server is Apollo，In the Arduino IDE compiler, using two ESP8266 connected to the server, there will always be a squeezed out，Can you help me, thank you. @knolleary

**Comment by SuperMoran** [comment]
`#include <ESP8266WiFi.h>
#include <PubSubClient.h>

const char* ssid = "my_WiFi";
const char* password = "moran0810!";
const char *mqtt_server = "192.168.3.181";

WiFiClient mqttClient;
PubSubClient client(mqttClient);
long lastMsg = 0;
char msg[50];
int value;


void setup_wifi() {
  delay(10);
  Serial.print("Connection to ");
  Serial.println(ssid);

  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");
  Serial.print("WiFi connected");
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());
}

void callback(char* topic, byte* payload, unsigned int length) {
  Serial.print("Message arrived [");
  Serial.print(topic);
  Serial.print("] ");
  for (int i = 0; i < length; i++) {
    Serial.print((char)payload[i]);
  }
  Serial.println();
}

void reconnect() {
  while (!client.connected()) {
    Serial.print("Attemption MQTT connection...");
    if (client.connect("ESP8266Client", "admin", "password")) {
      Serial.println("connected");
      client.publish("chat", "hello");
      client.subscribe("chat");
    } else {
      Serial.print("failed, rc=");
      Serial.print(client.state());
      Serial.println(" try again in 5 seconds");
      // Wait 5 seconds before retrying
      delay(5000);
    }
  }
}

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  setup_wifi();
  client.setServer(mqtt_server, 61613);
  client.setCallback(callback);
}

void loop() {
  // put your main code here, to run repeatedly:
  if (!client.connected()) {
    reconnect();
  }
  client.loop();
  long now = millis();
  if (now - lastMsg > 2000) {
    lastMsg = now;
    ++value;
    snprintf (msg, 75, "hello world #%ld", value);
    Serial.print("Publish message: ");
    Serial.println(msg);
    client.publish("chat", msg);
  }
}`

**Comment by knolleary** [comment]
Each client you connect must have a unique client id. You have `ESP8266Client` in your code here. Are you changing that when you apply the code to your second device?

**Comment by SuperMoran** [comment]
Thank you very much for your help. The problem has been solved. @knolleary

**Comment by joao210180** [comment]
~~~~~~~~~~

**Comment by joao210180** [comment]
How to be a server and client at same sketch?  Does it work?

**Comment by knolleary** [comment]
@joao210180 please don't use closed issues on unrelated subjects as a way to ask questions.

This library only provides an mqtt client

**Comment by shamil-yazeen** [comment]
@knolleary 

Im having similar issue.when i connect multiple nodemcu to aws iot code ,only one is working.any solution``



#include <Arduino.h>
#include <ESP8266WiFi.h>
#include <PubSubClient.h>

extern "C" {
  #include "libb64/cdecode.h"
}

// Declare functions
void pushData(int detected);
void pubSubCheckConnect();
int b64decode(String b64Text, uint8_t *output);
void setCurrentTime();

const byte pirPin = 12;

// WiFi credentials
const char *ssid = "ClayWorks Create";
const char *password = "[ClayWorks*123]";

// AWS keys
const char *awsEndpoint = "xxxxxxxxx-east-2.amazonaws.com";

const String certificatePemCrt = //-----BEGIN CERTIFICATE-----
 R"EOF(
xxxxxxxxxxxxxxxxxxxxxxx
)EOF";
//  -----END CERTIFICATE-----

const String privatePemKey = //-----BEGIN RSA PRIVATE KEY-----

 R"EOF(
xxxxxxxxxxxxxxxxxxx
)EOF";
  //-----END RSA PRIVATE KEY-----

const String caPemCrt = //-----BEGIN CERTIFICATE----- 

R"EOF
xxxxxxxxxxxxxxxxxxxx

)EOF";
//-----END CERTIFICATE-----
    


WiFiClientSecure wiFiClient;

void msgReceived(char *topic, byte *payload, unsigned int len);

PubSubClient pubSubClient(awsEndpoint, 8883, msgReceived, wiFiClient);

void setup()
{
  Serial.begin(115200);

  // Connect to WiFi
  Serial.print("Connecting to SSID: ");
    Serial.println(ssid);

    WiFi.begin(ssid, password);
    WiFi.waitForConnectResult();

  Serial.print("Connection successful. IP address: ");
    Serial.println(WiFi.localIP());

  setCurrentTime();

    uint8_t binaryCert[certificatePemCrt.length() * 3 / 4];
  int len = b64decode(certificatePemCrt, binaryCert);
  wiFiClient.setCertificate(binaryCert, len);

    uint8_t binaryPrivate[privatePemKey.length() * 3 / 4];
    len = b64decode(privatePemKey, binaryPrivate);
    wiFiClient.setPrivateKey(binaryPrivate, len);

    uint8_t binaryCA[caPemCrt.length() * 3 / 4];
    len = b64decode(caPemCrt, binaryCA);
    wiFiClient.setCACert(binaryCA, len);
}

unsigned long lastPublish;

String mac(WiFi.macAddress());
int iteration = 0;
int detectionCount = 0;
int detected = 0;
unsigned long previousTime = 0;

int maxIterations = 6;
unsigned int delayVal = 10000;
int detectionPercentage = 50;

float minDetectionCriteria = (float)maxIterations * ((float)detectionPercentage / 100);


void loop()
{
  pubSubCheckConnect();
    unsigned long currentTime = millis();

  if (currentTime - previousTime >= delayVal) {
    if (iteration >= maxIterations)
    {
      if ((float)detectionCount >= minDetectionCriteria)
      {
        detected = 1;
        pushData(detected);
      }
      else
      {
        if (detected == 1)
        {
          detected = 0;
          pushData(detected);
        }
      }

      iteration = 0;
      detectionCount = 0;
    }

    if (digitalRead(pirPin) == HIGH)
    {
      detectionCount++;
    }

    iteration++;
    previousTime = currentTime;
  }
}

void pushData(int detected) {
  char jsonOutput[100];
 

   sprintf(jsonOutput, "{\"mac\" : \"%s\", \"Binary Key\" : %d}", mac.c_str(), detected);

  Serial.println(jsonOutput);
  
  // push to cloud
  pubSubClient.publish("outTopic", jsonOutput);
}


void msgReceived(char *topic, byte *payload, unsigned int length)
{
    Serial.print("Message received on ");
    Serial.print(topic);
    Serial.print(": ");

    for (int i = 0; i < length; i++)
    {
        Serial.print((char)payload[i]);
    }

    Serial.println();
}

void pubSubCheckConnect()
{
    if (!pubSubClient.connected())
    {
        Serial.print("PubSubClient connecting to: ");
        Serial.print(awsEndpoint);

        while (!pubSubClient.connected())
        {
            Serial.print(".");
            pubSubClient.connect("ESPthing");
        }
        Serial.println(" connected");
        pubSubClient.subscribe("inTopic");
    }

    pubSubClient.loop();
}

int b64decode(String b64Text, uint8_t *output)
{
    base64_decodestate s;
    base64_init_decodestate(&s);
    int cnt = base64_decode_block(b64Text.c_str(), b64Text.length(), (char *)output, &s);
    return cnt;
}

void setCurrentTime()
{
    configTime(3 * 3600, 0, "pool.ntp.org", "time.nist.gov");
    Serial.print("Waiting for NTP time sync: ");

    time_t now = time(nullptr);

    while (now < 8 * 3600 * 2)
    {
        delay(500);
        Serial.print(".");
        now = time(nullptr);
    }

    Serial.println("");

    struct tm timeinfo;

    gmtime_r(&now, &timeinfo);

    Serial.print("Current time: ");
    Serial.print(asctime(&timeinfo));
}

**Comment by shamil-yazeen** [comment]
@knolleary
// I'm facing the same issue ... I can't connect multiple devices to AWS IoT core.can you help me out``

//this is my code


Im having similar issue.when i connect multiple nodemcu to aws iot code ,only one is working.any solution``

#include <Arduino.h>
#include <ESP8266WiFi.h>
#include <PubSubClient.h>

extern "C" {
#include "libb64/cdecode.h"
}

// Declare functions
void pushData(int detected);
void pubSubCheckConnect();
int b64decode(String b64Text, uint8_t *output);
void setCurrentTime();

const byte pirPin = 12;

// WiFi credentials
const char *ssid = "xxxxx";
const char password = "xxxxxxxx";

// AWS keys
const char *awsEndpoint = "xxxxxxxxx-east-2.amazonaws.com";

const String certificatePemCrt = //-----BEGIN CERTIFICATE-----
R"EOF(
xxxxxxxxxxxxxxxxxxxxxxx
)EOF";
// -----END CERTIFICATE-----

const String privatePemKey = //-----BEGIN RSA PRIVATE KEY-----

R"EOF(
xxxxxxxxxxxxxxxxxxx
)EOF";
//-----END RSA PRIVATE KEY-----

const String caPemCrt = //-----BEGIN CERTIFICATE-----

R"EOF
xxxxxxxxxxxxxxxxxxxx

)EOF";
//-----END CERTIFICATE-----

WiFiClientSecure wiFiClient;

void msgReceived(char *topic, byte *payload, unsigned int len);

PubSubClient pubSubClient(awsEndpoint, 8883, msgReceived, wiFiClient);

void setup()
{
Serial.begin(115200);

// Connect to WiFi
Serial.print("Connecting to SSID: ");
Serial.println(ssid);

WiFi.begin(ssid, password);
WiFi.waitForConnectResult();
Serial.print("Connection successful. IP address: ");
Serial.println(WiFi.localIP());

setCurrentTime();

uint8_t binaryCert[certificatePemCrt.length() * 3 / 4];
int len = b64decode(certificatePemCrt, binaryCert);
wiFiClient.setCertificate(binaryCert, len);

uint8_t binaryPrivate[privatePemKey.length() * 3 / 4];
len = b64decode(privatePemKey, binaryPrivate);
wiFiClient.setPrivateKey(binaryPrivate, len);

uint8_t binaryCA[caPemCrt.length() * 3 / 4];
len = b64decode(caPemCrt, binaryCA);
wiFiClient.setCACert(binaryCA, len);
}

unsigned long lastPublish;

String mac(WiFi.macAddress());
int iteration = 0;
int detectionCount = 0;
int detected = 0;
unsigned long previousTime = 0;

int maxIterations = 6;
unsigned int delayVal = 10000;
int detectionPercentage = 50;

float minDetectionCriteria = (float)maxIterations * ((float)detectionPercentage / 100);

void loop()
{
pubSubCheckConnect();
unsigned long currentTime = millis();

if (currentTime - previousTime >= delayVal) {
if (iteration >= maxIterations)
{
if ((float)detectionCount >= minDetectionCriteria)
{
detected = 1;
pushData(detected);
}
else
{
if (detected == 1)
{
detected = 0;
pushData(detected);
}
}

  iteration = 0;
  detectionCount = 0;
}

if (digitalRead(pirPin) == HIGH)
{
  detectionCount++;
}

iteration++;
previousTime = currentTime;
}
}

void pushData(int detected) {
char jsonOutput[100];

sprintf(jsonOutput, "{"mac" : "%s", "Binary Key" : %d}", mac.c_str(), detected);

Serial.println(jsonOutput);

// push to cloud
pubSubClient.publish("outTopic", jsonOutput);
}

void msgReceived(char *topic, byte *payload, unsigned int length)
{
Serial.print("Message received on ");
Serial.print(topic);
Serial.print(": ");

for (int i = 0; i < length; i++)
{
    Serial.print((char)payload[i]);
}

Serial.println();
}

void pubSubCheckConnect()
{
if (!pubSubClient.connected())
{
Serial.print("PubSubClient connecting to: ");
Serial.print(awsEndpoint);

    while (!pubSubClient.connected())
    {
        Serial.print(".");
        pubSubClient.connect("ESPthing");
    }
    Serial.println(" connected");
    pubSubClient.subscribe("inTopic");
}

pubSubClient.loop();
}

int b64decode(String b64Text, uint8_t *output)
{
base64_decodestate s;
base64_init_decodestate(&s);
int cnt = base64_decode_block(b64Text.c_str(), b64Text.length(), (char *)output, &s);
return cnt;
}

void setCurrentTime()
{
configTime(3 * 3600, 0, "pool.ntp.org", "time.nist.gov");
Serial.print("Waiting for NTP time sync: ");

time_t now = time(nullptr);

while (now < 8 * 3600 * 2)
{
    delay(500);
    Serial.print(".");
    now = time(nullptr);
}

Serial.println("");

struct tm timeinfo;

gmtime_r(&now, &timeinfo);

Serial.print("Current time: ");
Serial.print(asctime(&timeinfo));
}

**Comment by thijsdebont** [comment]
Your answer is is the third post in this thread. You need to use unique client ID's per device. All your devices seem to use the same 'ESPthing' as their ID.
