### ISSUE TITLE
Problem with long topic string

### ISSUE THREAD

**Issue by joehui** [knolleary/pubsubclient#262]
Hi,

I am trying to use pubsubclient for an MQTT subscriber for devicehub.net using an ESP32 device.

I ran into a lot of problems with seemingly simple code.  After many trial and error, I found that if the topic string is too long (longer 109 characters), the client will not work.  By that, I meant the callbacks will not be called for new messages to that topic.  With devicehub.net, it is quite easy to get such long string.  For example, 

"/a/75ae2ce1-af0f-44b0-8a2c-d39b9c4d7da7/p/12345/d/5f650aba-f1f0-4069-a590-d2bcc6fcacdb/actuator/myActuator/state"

I am not sure if the problem is specific to ESP32 or not.  I hope the problem will get fixed soon.

Thanks,
Joseph

**Comment by knolleary** [comment]
Have you increased the max message size setting in PubSubClient.h? The default is 128 which won't leave you much room if your topic is 109 chars.

**Comment by joehui** [comment]
Thanks for the quick response.  Yes, that was the problem.  Increasing it to 512 solves this and some other problems I have!
