### ISSUE TITLE
Dead Link to API Docu and Question

### ISSUE THREAD

**Issue by chessweb01** [knolleary/pubsubclient#272]
The link to the [API documentation](http://pubsubclient.knolleary.net) is dead.

Question:
What is the default QoS for subscriptions and how can the level be changed?

**Comment by knolleary** [comment]
Link working fine here.

Default is 0, can specify 0 or 1 as the optional second argument to the subscribe function:

    boolean subscribe (topic, [qos])

This lib does not support subscribing at QoS 2.
