### ISSUE TITLE
Reviving topics when connecting

### ISSUE THREAD

**Issue by GeorgeDLake** [knolleary/pubsubclient#276]
Not sure if this is correct or not, but when my sketch connects (ESP8266) I get a topic, so every time it reconnects i get the topic. Is this normal? it seems there is data in the queue?

**Comment by knolleary** [comment]
Hi,
what do you mean by 'get a topic'? Do you mean you are receiving a message callback?
Does your client subscribe on connect? If so, is there a retained message on that topic? If so, that would be received each time your client connects and subscribes.

**Comment by GeorgeDLake** [comment]
Hi, as you mentioned, its not script related. I changed the topic and not the problem stopped. I one of my tests I must have selected retain.

Thanks! and love the lib!
