### ISSUE TITLE
CleanSession support

### ISSUE THREAD

**Issue by chkr1011** [knolleary/pubsubclient#281]
Hi,
I am interested in _CleanSession_ support for the _CONNECT_ message. I saw several tickets here which are already closed but I can't see why. 

In one ticket you are asking for an example why this feature is useful and should be implemented. Well here is one from my side:

I am developing a solution which uses the _Azure IoTHub_. The _IoTHub_ allows reusing of sessions which is controlled via the _CleanSession_ flag. If this flag is set to _false_, the client will receive all pending messages automatically which are published while the device was offline. For me this is a very important feature. I assume that this is only server side and there is no need for changes on your library instead of adding an overload with that parameter. Or am I wrong?

Taken from the original documentation:

> Note, that the device will not receive any messages from IoT Hub, before it has successfully subscribed to its device-specific endpoint, represented by the devices/{device_id}/messages/devicebound/# topic filter. After successful subscription has been established, the device will start receiving only cloud-to-device messages that have been sent to it after the time of the subscription. If the device connects with CleanSession flag set to 0, the subscription will be persisted across different sessions. In this case, the next time it connects with CleanSession 0 the device will receive outstanding messages that have been sent to it while it was disconnected. If the device uses CleanSession flag set to 1 though, it will not receive any messages from IoT Hub until it subscribes to its device-endpoint.

I hope you agree that this is a reasonable example 😃 

Best regards,
Christian

**Comment by maxim-kukushkin** [comment]
Totally agree that this feature is needed. I use my own patched version of PubSubClient for my devices at home that supports non-clean sessions. It's not as straightforward as it seems to be though - I'm currently experiencing issues with ACK's which are essential. I think I know what could be the problem and if I manage to fix it, I hope I'll find some time to create a pull request
