### ISSUE TITLE
Feature Request: Integrate OTA

### ISSUE THREAD

**Issue by Urs-Eppenberger** [knolleary/pubsubclient#286]
Hello
I checked the various MQTT clients in the Arduino IDE Library Manager. Currently I'm using yours. It's integrated in the library manager and works flawlessly for my sensors (ESP-201 and sonoff).
Since the number of sensors are growing and I still tune the software, I use OTA to keep them up to date. But it would be cool to use MQTT, since the sensors anyway listens to the broker and the code is exactly the same (device specific config is stored in spiffs).
There is an MQTT client which handles OTA: https://github.com/Imroy/pubsubclient
It seems that it is based on your code. It is not integrated in the Arduino IDE library manager.
I'd prefer to use your client. May I kindly ask you to have a look at it if it is possible to integrate what lmroy has done into your code?

**Comment by knolleary** [comment]
It would be nice to add this capability, but @lmroy's fork has diverged a long way from this library over the last couple of years. There's no quick solution to be had here - I don't know when I will have the time to spend on it.

**Comment by Urs-Eppenberger** [comment]
Thanks for your answer. I'm not a software developer, so I have no clue at all about the effort needed here. Since I'm also a user of node-red, I prefer to see you spending your time over there.
I'll close this issue then.

**Comment by rovale** [comment]
In this fork I got OTA updates over MQTT working: https://github.com/rovale/pubsubclient. It is actually a small change. For my use case it works fine but I would not know how to integrate it without breaking the current API.

**Comment by rovale** [comment]
Good news! I think OTA over MQTT is a very good approach. It appears to be really stable!
