### ISSUE TITLE
two way communication

### ISSUE THREAD

**Issue by Nikitha-Kondapalli** [knolleary/pubsubclient#288]
Can we communicate between two nodemcu's using mqtt protocol with mosquitto as a broker?

**Comment by knolleary** [comment]
Yes

**Comment by Nikitha-Kondapalli** [comment]
I am trying to communicate using mqtt protocol and trying to publish a string but subscribing from other nodemcu is not happening 


my codes:
1.ESP which is publishing data to mosquitto


#include <ESP8266WiFi.h>
#include <WiFiClient.h>
#include <PubSubClient.h>

char msg[50];

const char* ssid = "clickersoft";
const char* password = "kresit123";
const char* mqtt_server = "192.168.1.104";

WiFiClient espClient;
PubSubClient client(espClient);

int intensity;

void setup_wifi() {

  delay(10);
  // We start by connecting to a WiFi network
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);

  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());
}

void callback(char* topic, byte* payload, unsigned int length) {
  Serial.print("Message arrived [");
  Serial.print(topic);
  Serial.print("] ");
  for (int i = 0; i < length; i++) {
    Serial.print((char)payload[i]);
  }
  Serial.println();
}

void reconnect() {
  // Loop until we're reconnected
  while (!client.connected()) {
    Serial.print("Attempting MQTT connection...");
    // Attempt to connect
    if (client.connect("ESP8266Client")) {
      Serial.println("connected");
      /*intensity = map(analogRead(A0),0,1024,0,255);
      Serial.println("Light Intensity is :");
      Serial.println(intensity);
      delay(1000);
      if(intensity > 150)
       {
        //Serial.println("greater");
    //snprintf (msg, 75, "%d",intensity);
          client.publish("inten","true");
          //Serial.println("PUB_Gr");
       }
        else if(intensity <= 150 )
        {
          //Serial.println("lesser");
          client.publish("inten","false");
          //Serial.println("PUB_Le");
         }*/
     // client.publish("LDR","");  
      }
      else 
      {
        Serial.print("failed, rc=");
        Serial.print(client.state());
        Serial.println(" try again in 5 seconds");
        // Wait 5 seconds before retrying
        delay(5000);
    }
  }
}

void setup() {
  // put your setup code here, to run once:
  Serial.begin(9600);
  setup_wifi();
  client.setServer(mqtt_server, 1883);
  client.setCallback(callback);
}

void loop() {
  // put your main code here, to run repeatedly:
  if (!client.connected()) {
    reconnect();
  }
  client.loop();
  intensity = map(analogRead(A0),0,1024,0,255);
  Serial.println("Light Intensity is :");
  Serial.println(intensity);
  delay(1000);
  if(intensity > 150)
  {
    //snprintf (msg, 75, "%d",intensity);
    client.publish("inten","true");
  }
  else if(intensity < 150 )
  {
    client.publish("inten","false");
  }
}


2.ESP which is subscribing data from mosquitto

#include <ESP8266WiFi.h>
#include <PubSubClient.h>

const char* ssid = "clickersoft";
const char* password = "kresit123";
const char* mqtt_server = "192.168.1.104";

WiFiClient espClient;
PubSubClient client(espClient);

//#define BUILTIN_LED 2

void setup_wifi() {

  delay(100);
  // We start by connecting to a WiFi network
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);

  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());
}

void callback(char* topic, byte* payload, unsigned int length) {
  Serial.print("Message arrived [");
  Serial.print(topic);
  Serial.print("] ");
  for(int i=0; i<length;i++)
  {
    Serial.print((char)payload[i]);
  }
  Serial.println();
  if((char)payload[0] == 't'){
    Serial.println("ON");
    digitalWrite(D0,HIGH);
  }
  else if((char)payload[0] == 'f'){
    Serial.println("off");
    digitalWrite(D0,LOW);
  }
}
void reconnect() {
  // Loop until we're reconnected
  while (!client.connected()) {
    Serial.print("Attempting MQTT connection...");
    // Attempt to connect
    if (client.connect("ESP8266Client")) {
      Serial.println("connected");
      // Once connected, publish an announcement...
    //  client.publish("nikitha_out", "nikitha_kondapalli");
      // ... and resubscribe
     client.subscribe("inten");
     /*Serial.println(client.subscribe("rfid"));
     if(client.subscribe("rfid")){
        Serial.print("state = ");
        Serial.println(client.state());*/
     }
    else {
      Serial.print("failed, rc=");
      Serial.print(client.state());
      Serial.println(" try again in 5 seconds");
      // Wait 5 seconds before retrying
      delay(5000);
    }
  }
}


void setup() {
  // put your setup code here, to run once:
  Serial.begin(9600);
  setup_wifi();
  client.setServer(mqtt_server, 1883);
  client.setCallback(callback);

}

void loop() {
  // put your main code here, to run repeatedly:
  if (!client.connected()) {
    reconnect();
  }
  client.loop();  
  client.subscribe("inten");

}

**Comment by knolleary** [comment]
Both sketches use the same client id. Each client connecting to a broker must have a unique id.

    client.connect("ESP8266Client")
