### ISSUE TITLE
Random Disconnects

### ISSUE THREAD

**Issue by InvisiBug** [knolleary/pubsubclient#290]
I'm having an issue where  I get random disconnects. Everything is working fine then my wemos D1 mini randomly disconnects and cant reconnect unless i reset the module. Any ideas?

**Comment by programmer131** [comment]
I've also got similar issue, esp8266 disconnects a lot, but re connects automatically, same code with esp32 works perfect, not sure what is wrong.

**Comment by thefirstnutzo** [comment]
@programmer131 I have had a lot of problems with ESP8266 modules being unstable and currently don't trust them enough to put into use anywhere that stable functionality is required. Is your ESP8266 connecting and disconnecting (power on, connect, disconnect, connect) while staying on, or is it actually restarting (power on, connect, reset, boot, connect, reset, boot, connect)?

**Comment by programmer131** [comment]
@thefirstnutzo I've performed many tests today and seems problem resolved, I was using IO interrupt and was publishing to Mqtt from inside ISR, now I set a simple flag when IO Interrupt is triggered and handle flag inside main Loop, issue seems resolved, both 8266 and esp32 working normal.
