### ISSUE TITLE
Delivering a mutli-payload issue!

### ISSUE THREAD

**Issue by sjorsvanheuveln** [knolleary/pubsubclient#295]
When using the callback function when retrieving a payload I want to act on different characters from the byte datatype payload. Currently I have the code below, but strangely enough it is not executing the second if statement when I deliver the message '11'. However it does work when I send two messages with '1x' and 'x1'. Now the second statement is working fine. So what's going wrong here?
```

void callback(char* topic, byte* payload, unsigned int length) {
  Serial.print("Message arrived [");
  Serial.print(topic);
  Serial.print("] ");
  for (int i = 0; i < length; i++) {
    Serial.print((char)payload[i]);
  }
  Serial.println();

   //Set GPIO0 to HIGH or LOW on first character received in message
  if (payload[0] == '1') {
    digitalWrite(GPIO0, HIGH);   // Turn the relay on
    client.publish(getOutTopic().c_str(), "GPIO0 set to HIGH");
    Serial.println("GPIO0 switched to HIGH ");
  } else if (payload[0] == '0') {
    digitalWrite(GPIO0, LOW);  // Turn the relay off
    client.publish(getOutTopic().c_str(), "GPIO0 set to LOW");
    Serial.println("GPIO0 switched to LOW");
  }

  //Set GPIO2 to HIGH or LOW on first character received in message
  if (payload[1] == '1') {
    digitalWrite(GPIO2, HIGH);   // turn LED off. With High it is inactive  on the ESP-01)
    client.publish(getOutTopic().c_str(), "GPIO2 set to HIGH");
    Serial.println("GPIO2 switched to HIGH ");
  } else if (payload[1] == '0') {
    digitalWrite(GPIO2, LOW);  // Turn the LED on by making the voltage LOW
    client.publish(getOutTopic().c_str(), "GPIO2 set to LOW");
    Serial.println("GPIO2 switched to LOW ");
  }

}
```

**Comment by knolleary** [comment]
Hi @sjorsvanheuveln 

The client uses an internal buffer to store the incoming message AND for when you publish a message.

`payload` passed to your callback is a pointer to that buffer. Within your first `if` block, you are calling `client.publish` ... this will overwrite the internal buffer, so `payload` no longer contains the received message.

You should copy any data you want to reference out of `payload` before you call `client.publish`.

**Comment by knolleary** [comment]
The library includes a sample of what to do if you want to publish within the callback: https://github.com/knolleary/pubsubclient/blob/master/examples/mqtt_publish_in_callback/mqtt_publish_in_callback.ino

**Comment by sjorsvanheuveln** [comment]
Hi knolleary. Hmm no, this is not our problem. We can publish without problems. But somehow the second if statement is not being executed. But it should be executed.

**Comment by knolleary** [comment]
The publish will work fine. But payload will no longer contain the data you are wanting to test agaist, so neither condition will pass.

**Comment by sjorsvanheuveln** [comment]
Sorry, I missed your first post. Thanks so much, we'll try it.
