### ISSUE TITLE
esp8266 crash when callback fires too much

### ISSUE THREAD

**Issue by windymonkey** [knolleary/pubsubclient#296]
Hi all,
I'm currently using mqtt client (Pubsubclient lib) on my ESP8266 and i have installed a local mosquitto broker on my PC.
ESP still work fine until i try to send many commands rapidly from my app (3 commands each time). The callback function fires continuously cause esp8266 hangout then reset.
Can someone help me with this please?

Thanks.

**Comment by knolleary** [comment]
Try calling `client.loop` at the end of your callback function. That will allow the code to continue to service the network if there's more work to be done.

**Comment by windymonkey** [comment]
I tried to add client.loop at the end of my callback func, but nothing changed. After several time receiving command, it crashed.

**Comment by windymonkey** [comment]
OK, i added a list to queue commands then handle it later. It is a bit slow but at least no more hang out. Thanks.
