### ISSUE TITLE
Can't publish JSON message through client.publish

### ISSUE THREAD

**Issue by msnederland** [knolleary/pubsubclient#297]
Hi,

I found this [tutorial](https://techtutorialsx.com/2017/04/29/esp32-sending-json-messages-over-mqtt/) that explains how to buffer a JSON message and publish it through client.publish. The message doesn't arrive as expected. The code:

> else if (p0 == 'i') {
>     StaticJsonBuffer<200> jsonBuffer;
>     JsonObject& deviceInfo = jsonBuffer.createObject();
>     deviceInfo["firmware"] = "v1.0";
>     deviceInfo["deviceName"] = iotclient.getClientId();
>     deviceInfo["chipid"] = ESP.getChipId();
>     deviceInfo["topic"] = iotclient.getTopic();
>     char JSONmessageBuffer[100];
>     deviceInfo.printTo(JSONmessageBuffer, sizeof(JSONmessageBuffer));
>     Serial.println(JSONmessageBuffer);
>     if (client.publish(iotclient.getAdminTopic().c_str(), JSONmessageBuffer) == true) {
>       Serial.println("Success sending admin message");
>     } else {
>       Serial.println("Error sending admin message");
>     }
>      client.publish(iotclient.getAdminTopic().c_str(), "SOMETHING ELSE");
>   }
> 

I added the "SOMETHING ELSE" message in order to check if the first else if statement executes and the message is sent, and it does. The "JSONmessageBuffer" message returns "Error sending admin message". Any idea on how to fix this?

**Comment by knolleary** [comment]
The default packet size supported by this client is 128 bytes. My guess is you're exceeding that limit when you add up topic length and payload length etc.

You can increase this limit by editing the value of `MQTT_MAX_PACKET_SIZE` in `PubSubClient.h`.

**Comment by msnederland** [comment]
@knolleary Thanks for your response. 

I did check that in advance, and it was 99 bytes, but I forgot to include the topic in the calculation. Problem solved!

Do you think I can ramp up the max size to 150? Or will this harm stability?

**Comment by knolleary** [comment]
You can increase it to whatever you need as long as you have the ram space for it on your device.

**Comment by Iambecomeroot** [comment]
I can't seem to change the `MQTT_MAX_PACKET_SIZE` constant. I set it to 512 at the top of my file and I am printing it out right before the `publish` just to confirm, but my publishes are returning 0. If I truncate my payload to under 128, it works fine. Am I missing something?

**Comment by msnederland** [comment]
@Iambecomeroot Where are you trying to change the constant and how? For the time being I changed it directly in the pubsubclient library.

**Comment by Iambecomeroot** [comment]
I compile with platformio which allows me to specify flags to g++. I just added a definition to g++ that is applied early enough to work with this library.
