### ISSUE TITLE
Can't publish with a very long string. I'm using ESP8266 controller.

### ISSUE THREAD

**Issue by DGreat84** [knolleary/pubsubclient#298]
Hi everyone!

I have a project that i need to gather a chain of data which in my case the requirement is N = 512 samples. These samples are in an int array as shown below. I converted it to a string for mqtt publishing. My problem is it doesn't publish. When I change the number of samples to just 16 samples (N = 16), it is perfectly sent without a problem. Is there a limitation in pubsubclient library or just my ESP8266? The necessary codes are shown below. Hoping for your great ideas. Thank you!

int N = 512;

// code for recording the data
void Record
{
  for (int m = 0; m < N ; m++)
  {
    data = adc.readADC(0); // 
    dataarray[m] = data;
    delayMicroseconds(34); 
  }
}

// convert data to string
 for (int n = 0; n < N; n++) {
              datastring += ", " + String(dataarray[n]);
            }

//code for publishing
client.publish(Topic, String(datastring).c_str(), true);

**Comment by knolleary** [comment]
The default max packet size is 128 bytes.

You need to increase this value by editing PubSubClient.h - http://pubsubclient.knolleary.net/api.html#configoptions
