### ISSUE TITLE
First run mqttclient.loop() takes 15+ seconds

### ISSUE THREAD

**Issue by gjt211** [knolleary/pubsubclient#308]
I am using this library with a WiFi secure connection to my own dedicated server running Mosquitto.

After Wi-Fi is connected and secure connection made to my server, In my main loop, I test if mqtt is connected.
`if (!mqttclient.connected()) {
    reconnect();
  }`
Then in my reconnect function (which is really both a connect & reconnect function), I have the following code
```
while (!mqttclient.connected()) {
Serial.print("State:");
Serial.println(mqttclient.state());
    Serial.print("Attempting MQTT connection...");
    // Create the client ID
    String clientId = "SH-";
    clientId += String(s);
    // Attempt to connect
    if (mqttclient.connect(clientId.c_str())) {
      Serial.println("connected");
      Serial.print("Subscribe");
      mqttclient.subscribe (topicDO1);
      Serial.println(", Done");

      Serial.print("MQTT Loop");
      mqttclient.loop();
      Serial.println(", Done");
      Serial.print("State:");
      Serial.println(mqttclient.state());
    } else {
      Serial.print("failed, rc=");
      Serial.print(mqttclient.state());
      Serial.println(" try again in 5 seconds");
      // Wait 5 seconds before retrying
      for (uint16_t i = 0;i<500;i++){
        delay(10);
      }
      
    }
  }
  Serial.print("F: done in ");
  Serial.print(millis()-start_time);
  Serial.println(" mS");
```

When this code is run, the `mqttclient.loop();` it takes around 15 seconds to complete.
Previously this function did NOT have the mqttclient.loop() and was relying on the mqttclient.loop() inside the main program loop. I added it here as it was also taking 15 seconds in the main loop the first time the loop ran. As the mqttclient.loop() is blocking, at least performing the first call after an mqttclient.connect I have a little better control over it.

It is typically between 15100mS - 15800mS, however sometimes I have seen it as high as 40000mS.
Any ideas why this takes 15+ seconds?

**Comment by gjt211** [comment]
I have found that changing two lines in PubSubClient.h has varying effects as follows...
If I change both MQTT_KEEPALIVE and MQTT_SOCKET_TIMEOUT to 20, then the first time I run mqttclient.loop() it takes a little over 20 seconds. (Remember sometimes, maybe 1 in 20 or more it connects within a few hundred milliseconds).

Next I tried with KEEPALIVE 10, and SOCKET_TIMEOUT 5.
And it connected in 5441mS.

I then tried with KEEPALIVE 10, and SOCKET_TIMEOUT 15.
And it just keeps trying to reconnect.

**Comment by gjt211** [comment]
Anyone?
Why does the first time I run `mqtt.loop()` not complete until the SOCKET_TIMEOUT occurs, but subsequent calls are fine?

**Comment by jorgecis** [comment]
gjt211 Please try fix, at let met know if works you you

**Comment by stefanbode** [comment]
Hi, I'm using your library with the TASMOTO project here on github to work with the SONOFF devices. I can confirm, that the first .loop() take forever ~20 seconds. I just downloaded the version today Master branch and recompile everything. I do not see a change or better behavior. I will look into the change. Maybe I have an idea. I can confirm that after the first hang everything is working fine.

**Comment by stefanbode** [comment]
OK. after manual moving the change to my codebase it works.
