### ISSUE TITLE
MQTT_MAX_PACKET_SIZE doesn't seem to increase packet size

### ISSUE THREAD

**Issue by Iambecomeroot** [knolleary/pubsubclient#311]
I am trying to send a json string. Reading the docs and other issues it looks like all I have to do is increase the `MQTT_MAX_PACKET_SIZE` constant. I have done this, but my `publish` calls still return `0`.

```c++
#define MQTT_MAX_PACKET_SIZE 512

Serial.println(MQTT_MAX_PACKET_SIZE); // 512
client.publish("topic", longJSONString); // 0
```

It works perfectly if I send less than 128 bytes but fails for anything more. I am using an ESP8266.

**Comment by knolleary** [comment]
As per the docs you have to edit `PubSubClient.h` to change the value of `MQTT_MAX_PACKET_SIZE` - you cannot set it in your own sketch due to the way Arduino builds sketches.

**Comment by Iambecomeroot** [comment]
I see. I apologize. How do you handle updating the package then?

**Comment by Iambecomeroot** [comment]
Nevermind I'll just add a build flag.
