### ISSUE TITLE
Best MQTT for Arduino Yùn around there!

### ISSUE THREAD

**Issue by allbuilds** [knolleary/pubsubclient#317]
Just to share our enthusiasm with future adopters and to say thank you!

- not much AVR memory consuming
- not much Linino Bridge CPU consuming
- stable
- fast
- on LAN: typical 20 milliseconds to publish and /receive (round-trip-delay 40 milliseconds typical  and < 500 milliseconds)

**Comment by knolleary** [comment]
Thanks
