### ISSUE TITLE
Payload still buffered between each message

### ISSUE THREAD

**Issue by SebastianBar** [knolleary/pubsubclient#318]
I just found out that the payload doesn't "flush" between each message being received when you're subscribed.

Explanation:
If you're subscribed to something, and you receive this payload:
ZZZZZZZZZZ

The callback function is going to receive a length of 10, and the described payload. But, if you send another message after that one, like this:
A

The callback function is going to receive a length of 1, but the payload is going to be this:
AZZZZZZZZZ

(Is going to replace the first character, but leaving the remaining characters from the previous message).

I don't know if that's a bug, but I just found out that :)
Using v2.6.0

**Comment by knolleary** [comment]
Hi,

you are right that the internal buffer is not cleared between operations.

This is why you must pay attention to the `length` parameter passed in the callback - it tells you the length of the `payload` array for this message. If you access `payload` beyond `length` then you're accessing data unrelated to the message.
