### ISSUE TITLE
Getting retain to show for subscriber?

### ISSUE THREAD

**Issue by JSCSJSCS** [knolleary/pubsubclient#321]
Thank you @knolleary for your fine work!

I am using Arduino IDE. I am doing some testing. When I publish to a topic with retain set to true, the subscriber does not seem to show it as retained. I think it IS retained and sent to the subscriber on connect, but does not seem to show up that way in Putty.

If this is the publish command via Arduino IDE:

`client.publish("cmnd/garage/door2/opener", "1", 1);`

This is what is received by the subscriber (via Putty):

```
Client mosqsub/2092-core-ssh received PUBLISH (d0, q0, r0, m0, 'cmnd/garage/door2/opener', ... (1 bytes))
1
```
I would have thought that the 'r0' should have read 'r1' by the subscriber since the retain Boolean was set to true by the publisher .

I am not knowledgeable enough to know if this is just a misunderstanding of the way the transport works or an error in the way Putty portrays the data, or a bug in the PubSubClient.h for Arduino.

Can anyone shed some light on this?

**Comment by knolleary** [comment]
When you receive the message 'live' - as a direct result of the publish - the retain flag will always be 0 regardless of how it was published.

It is only set to 1 when you are receiving the retained message as response to subscribing to the topic.

**Comment by JSCSJSCS** [comment]
Thank you for the explanation! I searched and searched for the answer before posting.
