### ISSUE TITLE
PubSubClient does not handle Messages with QoS 1 or 2 send by broker

### ISSUE THREAD

**Issue by stefanbode** [knolleary/pubsubclient#324]
If the broker is configured to send messages with QoS 1 or 2 the client never return the required confirmation. Therefore the broker always resend the messages.

**Comment by knolleary** [comment]
This library does not support QoS 2 - that is a documented limitation.

It is not possible to subscribe at QoS 2: https://github.com/knolleary/pubsubclient/blob/dddfffbe0c497073d960f3b9f83c8400dc8cad6d/src/PubSubClient.cpp#L471
