### ISSUE TITLE
Concatenated string not working with pubsub

### ISSUE THREAD

**Issue by Buzd** [knolleary/pubsubclient#329]
Hi,
I am not quite sure why the following does not work other than it would appear that client.publish will not accept a concatenated string and will only accept text in quotations "text".
Or that I have no idea what I am doing, which is close to true ;-)
Any assistance / guidance will be greatly appreciated.

Below is a snippet of code that I am trying to get working
client.publish("senseIoT/A020A624A480",  data); <<< This works as expected
client.publish(pubstring,  data); <<< This does not work. Error below code.

      smac = String (WiFi.macAddress()); // Get ESP MAC Address
      String pubstring = "";
      String newmac = smac;   
      newmac.replace(":","");            // Strip colons from MAC Addresss
      pubstring += "\"senseIoT/";        // Start to build MQTT Topic
      pubstring += newmac;               // add stripped MAC to MQTT Topic
      pubstring += "\"";                 // Close MQTT Topic string
      Serial.println(pubstring);         // pubstring = "senseIoT/A020A624A480"
                                         // Publish data to MQTT
      client.publish(pubstring,  data);  // Causes ERROR below
      /* exit status 1
       * no matching function for call to 'PubSubClient::publish(String&, char [100])'                              
       * client.publish("senseIoT/A020A624A480",  data);  This works as expected but requries hard coding 
      */

**Comment by knolleary** [comment]
Hi,

the `publish` functions expect a `const char[]` type to be passed in. To convert a `String` to `char[]`, you have to use https://www.arduino.cc/en/Reference/StringToCharArray

**Comment by Buzd** [comment]
Thank you.
Your help is greatly appreciated.


Regards,
Stuart Hall
