### ISSUE TITLE
qos-1 and qos-2

### ISSUE THREAD

**Issue by shubhamsharmaa001** [knolleary/pubsubclient#333]
Can we expect support for qos-1 and qos-2 for publishing data?

**Comment by knolleary** [comment]
Unlikely. This library is pretty much in maintenance mode rather than active development.

The issues with supporting qos1 and 2 have been discussed many times on this list.

**Comment by shubhamsharmaa001** [comment]
can I implement these features by myself if I dig deeper? And space is not a big issue in my case.

**Comment by monte-monte** [comment]
@shubhamsharmaa001 you cal look at this https://github.com/knolleary/pubsubclient/pull/206 code, rather then writing your own from sratch
