### ISSUE TITLE
Payload issue

### ISSUE THREAD

**Issue by FasterThanX** [knolleary/pubsubclient#337]
Hi there.
Can you use something other than just a byte for payload from subscribed topics?

I have Arduino Mega 2560 with an Ethernet shield and I would like to control all of the pins (over 50) as an output but I am limited just to a single character to control them. 

Sample of my code:

```
// Callback function header
void callback(char* topic, byte* payload, unsigned int length);

EthernetClient ethClient;
PubSubClient client(server, 1883, callback, ethClient);

// Callback function
void callback(char* topic, byte* payload, unsigned int length) {
    
  //turn the LED ON if the payload is 'A' and publish to the MQTT server a confirmation message
  if(payload[0] == 'A'){
    digitalWrite(w2, HIGH);
    client.publish("outTopic", "Light On01"); }
    
  //turn the LED OFF if the payload is 'a' and publish to the MQTT server a confirmation message
  if (payload[0] == 'a'){
    digitalWrite(w2, LOW);
    client.publish("outTopic", "Light Off01");
    }


```

**Comment by knolleary** [comment]
The payload can be as long as you want - within certain limits. By default the library has a packet length limit of 128 bytes - something you can edit in `PubSubClient.h` if you need to go bigger.

The `length` parameter of the callback tells you how long the received payload is.

**Comment by FasterThanX** [comment]
Thank you for quick reply
I am just a beginner co please be patient :-)
My code stoped working when I change the payload to 'A1' and 'a2'.

What should I do?

`
// Callback function header
void callback(char* topic, byte* payload, unsigned int length);

EthernetClient ethClient;
PubSubClient client(server, 1883, callback, ethClient);

// Callback function
void callback(char* topic, byte* payload, unsigned int length) {
    
  //turn the LED ON if the payload is '1' and publish to the MQTT server a confirmation message
  if(payload[0] == 'A1'){
    digitalWrite(w2, HIGH);
    client.publish("outTopic", "Light On01"); }
    
  //turn the LED OFF if the payload is '0' and publish to the MQTT server a confirmation message
  if (payload[0] == 'a2'){
    digitalWrite(w2, LOW);
    client.publish("outTopic", "Light Off01");
    }`

**Comment by knolleary** [comment]
https://arduino.stackexchange.com/questions/33862/comparing-two-char-array

**Comment by FasterThanX** [comment]
Thank you

**Comment by FasterThanX** [comment]
I have tried twice and my code is not working. Could you tell me what have I done wrong?
```
// Callback function
void callback(char* topic, byte* payload, unsigned int length) {
    
  //turn the LED ON if the payload is '1' and publish to the MQTT server a confirmation message
  
  if(strcmp(payload[0], "B5") == 0){
    digitalWrite(w2, HIGH);
    client.publish("outTopic", "Light On01"); }
    
  //turn the LED OFF if the payload is '0' and publish to the MQTT server a confirmation message
  if(strcmp(payload[0], "B6") == 0){
    digitalWrite(w2, LOW);
    client.publish("outTopic", "Light Off01");
    }

```

The other one is 

```
// Callback function
void callback(char* topic, byte* payload, unsigned int length) {
    
  //turn the LED ON if the payload is '1' and publish to the MQTT server a confirmation message
  
  if(strcmp(payload, "B5") == 0){
    digitalWrite(w2, HIGH);
    client.publish("outTopic", "Light On01"); }
    
  //turn the LED OFF if the payload is '0' and publish to the MQTT server a confirmation message
  if(strcmp(payload, "B6") == 0){
    digitalWrite(w2, LOW);
    client.publish("outTopic", "Light Off01");
    }

```
