### ISSUE TITLE
Message character limit

### ISSUE THREAD

**Issue by timmo001** [knolleary/pubsubclient#340]
I am unable to send messages over a certain limit. I have looked at the docs and have already tried to redefine the max packet size:

> #define MQTT_MAX_PACKET_SIZE 512

I've even tried increasing the limit to ridiculous limits and still the message is ignored. The size of my message is 253 characters in compressed JSON format:

> { "code_gc": [ 38000,1,69,342,171,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,63,21,21,21,21,21,21,21,63,21,63,21,63,21,63,21,63,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,63,21,63,21,63,21,1829,342,85,21,3663 ] }

Does anyone have any ideas on what I should do to allow this message through?

**Comment by knolleary** [comment]
Where did you put that `#define`? Due to the way Arduino compiles sketches you *must* edit `PubSubClient.h` to change that define - you cannot redefine it in your own sketch.

**Comment by timmo001** [comment]
Ah OK, I edited the define in the source file and it now accepts my larger message
