### ISSUE TITLE
Not working with THINGSPEAK anymore...!

### ISSUE THREAD

**Issue by MarcFinns** [knolleary/pubsubclient#342]
Hello, 
My device using this lib has been running for months on the same firmware but it suddenly stopped on Friday September 29 at 1:49PM (GMT+2).
Most of the times it returns code **MQTT_CONNECT_UNAUTHORIZED**  5 and sometimes **MQTT_CONNECTION_TIMEOUT**   -4
Same behaviour with the demo sketch and even with the Thingspeak arduino example...
From Thingspeak I see the following, can it be related? The Will flag is set correctly, but the CleanSession flag cannot be set from the API.

_If you incorrectly configure your client to connect to the ThingSpeak™ MQTT broker, your connection request is rejected.

If you set the CleanSession flag to 0 on your MQTT client, any connection request to the ThingSpeak MQTT broker is rejected with a CONNACK status of "0x05 Connection Refused, not authorized".
If you set the Will flag to non-zero values on your MQTT client, any connection request to the ThingSpeak MQTT broker is rejected with a CONNACK status of "0x05 Connection Refused, not authorized"._

**Comment by knolleary** [comment]
Hi,

The CleanSession flag is hardcoded to 1 in the client as it does not support non-clean sessions. So that will not be the issue here.

I assume you're not setting a will message, so nor will that flag be set.

I suggest you try using another client, such as mqtt-spy, on a different machine to check you are able to connect using the client id/credentials you have.

**Comment by MarcFinns** [comment]
FYI - it seems to be an issue with ThingSpeak. Apparently they changed the server so that ClientID must be unique. Weird thing is that even then after a while it starts failing. Probably client and server disconnect get out of sync and the server believes there is still a client connected...
As a workaround, I have to generate a random ClientID each time i connect...! 
thanks for your time.
