### ISSUE TITLE
Two ESP8266-01 not able to publish to a Mosquitto MQTT server at the same time...

### ISSUE THREAD

**Issue by ddean6232** [knolleary/pubsubclient#346]
I have two ESP-01 modules installed with ESP8266WiFi. and PubSubClient.h with two different sets of code and on two different IPs and only one or the other can publish on the topic domoticz/in at a time.  I unplug power to the first one and the second is able to publish... I plug back in the first one and only the seond keeps on publishing .... I unplug power to the second one and the first one is able to publish.... Mosquitto is installed on a RPi Zero W....what am I missing?  I can post the code for both but I dont think thats the issue as both can publish to the topic and that is verified.  Is it a timeout or a conflict with some id or a port or pipe or..???.. please help... thx

**Comment by ddean6232** [comment]
Hooked up a third one and it takes over... seems to be talking on the same port/pipe/thread....????

**Comment by mdilger** [comment]
Have you got a unique client name for each device?

`client.connect("name")`  needs to be unique for each instance.

-Mike

**Comment by ddean6232** [comment]
Thanks Mike!!!  It was the WiFiClient and the PubSubClient that needed to be unique...
Wow... just saved me hours... Thanks again.

-Darren

**Comment by edorgeville** [comment]
@mdilger thank you so much ! My coworker and I have been kicking each other from the broker for the last hour without knowing it 😅
