### ISSUE TITLE
Callback not triggering on "long" message?

### ISSUE THREAD

**Issue by alc6379** [knolleary/pubsubclient#364]
I'm trying to publish a JSON message to a topic. I'm using ArduinoJson, which parses it fine in this form: 

`const char *testConfig = "{\"log-topic\" : \"device/test/log\", \"state-topic\" : \"device/test/state\", \"power-topic\": \"device/test/power\", \"all-power-topic\": \"device/all/power\", \"reset-topic\": \"device/test/config-timestamp\", \"monitor-topic\": \"device/test/monitor\", \"extra-topic\": \"extra\"}";`

I publish this to my MQTT broker, and other clients see it as this: 

`{"log-topic" : "device/test/log", "state-topic" : "device/test/state", "power-topic": "device/test/power", "all-power-topic": "device/all/power", "reset-topic": "device/test/config-timestamp", "monitor-topic":"device/test/monitor", "extra-topic": "extra"}`

Now... if I just publish a short message like "foo" to the topic, the callback triggers no problem. If I publish a shorter JSON message like... 

`{"log-topic": "device/test/log"}`

That also works fine. 

Any ideas? The message is something like 212 characters. It's well be low the limit of what an MQTT broker can handle, and other clients receive the message, just not this one using PubSubClient.

**Comment by knolleary** [comment]
Hi @alc6379 

The default maximum packet length supported by this client is 128 bytes.

You need to edit `MQTT_MAX_PACKET_SIZE` in `PubSubClient.h` to something big enough to accommodate the message size you want to handle - remembering that this comes straight out of your available memory on whatever device you're running on.

Also note this is packet size, not payload length. So it needs to be big enough to handle the combined length of the payload and topic as both are present in the MQTT publish packet.

**Comment by alc6379** [comment]
Awesome, thanks for the information. 

I'm fine with increasing the packet size for my particular application, because the application itself is relatively simple, and I've got the memory to spare.
