### ISSUE TITLE
using mqtt.local not working

### ISSUE THREAD

**Issue by martinschki** [knolleary/pubsubclient#367]
Hello and thank you for the lib. It's working perfectly!!

I do have one issue:
I'd like to use a local domain name for the client so I can use a standard software file for all clients and not worry about changes in my network.

This is not working although I'm able to ping the hostname (mqttserver01.local) from other devices...
(I'm using a arduino Nano 3.0 and a W5100 shield with the standard ethernet lib)
```
const char serverName[] = "mqttserver01.local"; // hostname raspi
.
.
.
client.setServer(serverName, 1883);

```

any help would be appreciated

**Comment by knolleary** [comment]
Hi,

using a local address such as `mqttserver01.local` relies on using the `mDNS` service.

I've not tried using mDNS on an arduino, but a quick google shows lots of examples - such as https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266mDNS

Sorry, that's about all the help I can provide at this point.

**Comment by martinschki** [comment]
thank you for your quick reply
i was afraid of that...
I'm using atmega328, so no price for me... ;-)
