### ISSUE TITLE
Convert long int to char* doesn't work.

### ISSUE THREAD

**Issue by jops425** [knolleary/pubsubclient#371]
Hi!
I'm using an Intel Galileo to read distances with an ultrasonic sensor, HC-SR04, and I'm trying to send them to a python MQTT client into a Desktop. 
I did convert the distance (long int) with successful to char*. The distance in char* appears on serial monitor and it works when I call "client.publish". The python client receive the MQTT message, but the message appears as a non recognizable character. What can I do? 
Thanks!

**Comment by knolleary** [comment]
Without the specific code, it's hard to suggest anything.

**Comment by jops425** [comment]
Sorry, I forgot.

[mqttComSensor.zip](https://github.com/knolleary/pubsubclient/files/1563324/mqttComSensor.zip)

**Comment by jops425** [comment]
Here the python code.
[MQTT.py.zip](https://github.com/knolleary/pubsubclient/files/1563339/MQTT.py.zip)

**Comment by knolleary** [comment]
Sorry, I'm not going to debug your whole code base. Please share just the relevant pieces around how you are generating your publish payload.

**Comment by jops425** [comment]
total = (distance * 2) / 100;
    message = ltoa(total, buf);
    Serial.print(message);
    Serial.println(" cm");

Ethernet.begin(mac, ip);
  if (client.connect("arduinoClient")) {
    client.publish("/softway/iot", message);
  }

**Comment by jops425** [comment]
in python:

def on_message(client, userdata, msg):
    print('Message received on topic: %s' % msg.topic)
    if msg.topic == TOPICO:
        print('Message: %s' % msg.payload)
    else:
        print('Tópico desconhecido.')

def loop():
    client = mqtt.Client()
    client.on_connect = on_connect
    client.on_subscribe = on_subscribe
    client.on_message = on_message
    client.connect(MQTT_ADDRESS, MQTT_PORT, MQTT_TIMEOUT)
    client.loop_forever()

**Comment by jops425** [comment]
When I upload the code on Arduino IDE, it works, but on python mqtt client, it appears:

![screenshot from 2017-12-15 14-52-45](https://user-images.githubusercontent.com/21229533/34052011-c05739a0-e1a7-11e7-9478-e205d623d3d3.png)

**Comment by asciiLord** [comment]
The value to publish needs to be converted to a char array. Here is a short example from a piece of code I use to measure distances with a ultrasonic sensor (SR04) :

```
	// distance in cm from a SR04T ping
	long distance_cm = ping();

	if (distance_cm != -1)
	{
		// Print a debug ouptut to SerialMon
		SerialMon.print("Ping: ");
		SerialMon.print(distance_cm);
		SerialMon.println(" cm");

		// Converting data to publishable payload
		String mqtt_publish_string = String(distance_cm);
		char mqtt_publish_payload[5];
		mqtt_publish_string.toCharArray(mqtt_publish_payload, mqtt_publish_string.length() + 1);

		// Publish data on MQTT
		mqtt.publish(topic_sr04t, mqtt_publish_payload);
	}
```

**Comment by jops425** [comment]
Thanks a lot!
