### ISSUE TITLE
Issue on Intel Galileo board

### ISSUE THREAD

**Issue by ppatierno** [knolleary/pubsubclient#38]
Hi Nick,
I have never used your library on Arduino but today I'm using it with an Intel Galileo board !
I have a question for you ...
The Arduino Ethernet and EthernetClient classes has some methods that receive in input an IPAddress instance but in your implementation you want a byte array for ip address.
On Intel Galileo board it seems not working : Ethernet.begin fails if I use a byte array for ip address but it works fine if I use IPAddress instance class. Do you have any idea ?

However, The library works fine but on Intel Galileo I removed "pgm_read_byte_near" in the publish method because we have a Quark x86 CPU and not an Atmel AVR.
I have to test better in the next few days !

Paolo.

**Comment by knolleary** [comment]
Spent today figuring some of this out having got my hands on a Galileo (finally! I hear you all cry).

I can't explain why passing the broker IP address as byte* fails, but was able to reproduce. I've now added functions that accept IPAddress and will update the docs to 'prefer' them as they work everywhere.

I've also put ifdefs around the progmem stuff - so it gets excluded when progmem isn't defined. That all works, but a bit more work needed to get that to work on the esp8266.

Expect a new release of the library this week.
