### ISSUE TITLE
Connection timeout with long username

### ISSUE THREAD

**Issue by webbcam** [knolleary/pubsubclient#385]
Connection times out when username is too long. 
I am using a jwt token for the username to connect to a mosquitto broker. It seems that when I use this token as the username, the client hangs and the connection times out. When I reduce the username to a smaller string (ie 'user') everything works fine.

I believe this is an issue as other client libraries (paho.mqtt and mosquitto_pub) work using this same exact token.

Any suggestions for a fix for this?

**Comment by knolleary** [comment]
You probably need to increase the value of MAX_PACKET_SIZE n PubSubClient.h to accommodate your long username.

**Comment by webbcam** [comment]
That worked, thanks!

**Comment by onionhammer** [comment]
@knolleary this probably should not just fail silently...

**Comment by knolleary** [comment]
It doesn't fail silently; the client disconnects.

Failing silently would be if the client continued on regardless.

If you have a suggestion for a different behaviour then please share.

**Comment by onionhammer** [comment]
@knolleary In the MACRO that exits;

```c++
#define CHECK_STRING_LENGTH(l,s) if (l+2+strlen(s) > MQTT_MAX_PACKET_SIZE) {\
   PRINT_SOMETHING("Line %d exceeds %d: %d\n", __LINE__, l+2+strlen(s), MQTT_MAX_PACKET_SIZE);\
   _client->stop();\
   return false;\
}
```

Or even print out which variable is too large by passing in a spot to the macro

**Comment by knolleary** [comment]
@onionhammer where does `PRINT_SOMETHING` come from? Is that a standard thing, or something you've made up? I can't find any reference to it, so I assume its made up. The question then becomes, what is the cross-platform definition for that which will do anything useful? We can't assume we can write to serial.

**Comment by onionhammer** [comment]
It’s just a pseudo thing. Lots of other libraries have the ability to do tracing / logging though. Could even make it overridable with an ifdef

**Comment by javipelopi** [comment]
This has been driving me crazy for a week, Google Core IOT uses JWT as the user for their MQTT so many people may need information about this issue.

It would be great to have onionhammer suggestion of logging or, at least, talking about it in the documentation. 

Thanks anyway because the library is great! Keep the good work!
