### ISSUE TITLE
Disconnect condition in Examples

### ISSUE THREAD

**Issue by krich11** [knolleary/pubsubclient#41]
The examples are very simple and basic, no doubt by design, however the example code can lead to a situation where the connection drops and is not handled.  

I had a project where the remote sensor that was publishing a value to an MQTT server worked fine on the bench, but at it's remote location, it was failing at seemingly random intervals, but usually within 24 hours of a reset.  This morning it failed within 15 minutes of a reset, so I knew something was wrong with the code.  The remote location is across a, somewhat unreliable at times, WiFi bridged connection.  (yep, need to fix that too...  :-)  )

As the example code stands, if the Arduino misses a PING packet exchange, it will disconnect.  In the example code, this disconnect is permanent.  This can happen on unreliable links (WiFi) or if the publisher is unable to communicate with the server for whatever reason (ISP outage).  The symptom is that all other code on the Arduino continues to operate normally, with the exception of the MQTT client functionality.

The good news is that the functionality is already in the library, it's just not shown in the examples.  Simply check the result of the client.loop() statement in the main loop and act upon it.

FALSE == we're disconnected so it's time to try reconnecting
TRUE == all is good.

In the examples, replace:

```C++
client.loop()
```

with

```C++
if(!client.loop()) client.connect("arduinoPublisher");
```

or, if want to check the client.connect() as well, use something like this:

```C++
  if (!client.loop()) {
    Serial.print("Client disconnected...");
    if (client.connect("arduinoPublisher")) {
      Serial.println("reconnected.");
    } else {
      Serial.println("failed.");
    }
  } 
```

I don't expect an update the library for this, but I did want to document this here on GitHub so that it might be useful to future users of your _excellent_ library.  Thanks Nick!!

**Comment by knolleary** [comment]
The basic example has been updated to include reconnect logic, and a new example of non-blocking reconnect logic added.

**Comment by Pfannex** [comment]
Hi,

I´m still trying to run the simple ESP8266 DEMO, but after awhile the MQTT connection seems to disconnect.

I use this Code:
```
/*
 Basic MQTT example 
 
  - connects to an MQTT server
  - publishes "hello world" to the topic "outTopic"
  - subscribes to the topic "inTopic"
*/

#include <ESP8266WiFi.h>
#include <PubSubClient.h>
#include "MySecret.h"


// Update these with values suitable for your network.
IPAddress server(192, 168, 1, 203);
long lastMsg = 0;

void callback(const MQTT::Publish& pub) {
  // handle message arrived
}

WiFiClient wclient;
PubSubClient client(wclient, server);

void setup() {
  // Setup console
  Serial.begin(115200);
  delay(10);
  Serial.println();
  Serial.println();

  client.set_callback(callback);
}

void loop() {
  if (WiFi.status() != WL_CONNECTED) {
    Serial.print("Connecting to ");
    Serial.print(ssid);
    Serial.println("...");
    WiFi.begin(ssid, password);

    if (WiFi.waitForConnectResult() != WL_CONNECTED)
      return;
    Serial.println("WiFi connected");
  }

  if (WiFi.status() == WL_CONNECTED) {

    if (!client.loop()) {
      Serial.println("### Client has disconnected...");
      client.disconnect();

      // add you code to reconnect here.
      if (client.connect("arduinoClient")) {
        Serial.println("MQTT-Client connected");
        //client.publish("outTopic","hello world");
        //client.subscribe("inTopic");
    }
  }

    
/*    
    if (!client.connected()) {
      Serial.println("MQTT-Client disconnected");
      
      if (client.connect("arduinoClient")) {
        Serial.println("MQTT-Client connected");
        //client.publish("outTopic","hello world");
        client.subscribe("inTopic");
      }
    }

    if (client.connected())
      client.loop();
*/
  
  }

    long now = millis();
  if (now - lastMsg > 300000) {
    lastMsg = now;
    client.publish("/30/Status/MQTT","on");
  }

}
```

I also post this Problem here:
https://github.com/Imroy/pubsubclient/issues/37

I hope, that someone got the same problem and solved it finally.......

Greetings from Hamburg
Pf@nne

**Comment by chaeplin** [comment]
@Pfannex use knolleary's mqtt_reconnect_nonblocking.ino https://github.com/knolleary/pubsubclient/blob/master/examples/mqtt_reconnect_nonblocking/mqtt_reconnect_nonblocking.ino

I have no recoonet at least one month now.
FYI:
https://github.com/chaeplin/esp8266_and_arduino/blob/master/_02-mqtt-sw-temperature/_02-mqtt-sw-temperature.ino
https://github.com/chaeplin/esp8266_and_arduino/blob/master/_03-hx711-scale/_03-hx711-scale-esp-12/_03-hx711-scale-esp-12.ino
(disable serial out also help)

**Comment by Pfannex** [comment]
@chaeplin,

thanks for your hints!

I modified knollearys mqtt_esp8266.ino example to the reconnect example.

https://github.com/Pfannex/pubsubclient/blob/master/examples/mqtt_esp8266/mqtt_esp8266.ino

But I always got a lot of disconnects!
```
MQTT disconnected....
MQTT disconnected....
MQTT disconnected....
MQTT disconnected....
MQTT disconnected....
MQTT disconnected....
```

Are you able to run my sketch on your hardware?

Which ESP-library do you use?


Thanks for your Help!

**Comment by chaeplin** [comment]
https://gist.github.com/chaeplin/2b69fb46479584a354b7

a modified one, no reconnect.

https://github.com/esp8266/Arduino, Stable version.

**Comment by Pfannex** [comment]
I got some reconnects again......
I think I used not the right ESP8266 library (Board)

![board](https://cloud.githubusercontent.com/assets/7262813/11170685/b0fe27a8-8bdb-11e5-86e7-826d2e90bbde.PNG)

**Comment by Pfannex** [comment]
Right now I saw that there is a specific board for my ESP8266-12e!

**NodeMCU 1.0 (ESP-12e Module)**

I changed the settings, now I´m waiting...... :-)

**Comment by chaeplin** [comment]
pubsubclient : git version / no modification
mqtt : mosquitto ver 1.3.4 / Debian
Arduino IDE 1.6.5 / with Board manager / OS X
esp8266 : esp12

Connecting to Myhome
...........
WiFi connected
IP address: 
192.168.10.112
failed, rc=-1
MQTT disconnected....
MQTT connected....
0
0
0
0
0
0
0
0
0
0
0
0

**Comment by Pfannex** [comment]
Still reconnects!

**mosquitto.conf**
```
# Place your local configuration in /etc/mosquitto/conf.d/
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

pid_file /var/run/mosquitto.pid

persistence true
persistence_locat

ion /var/lib/mosquitto/

log_dest file /var/log/mosquitto/mosquitto.log

include_dir /etc/mosquitto/conf.d
```
Looks like yours.....

**mosquitto version 1.4.4** on Debian Wheezy (Raspberry PI 2)

**Arduino IDE 1.6.5**
I´m not sure to use the right ESP-board,
does my board  looks like yours?
![esp](https://cloud.githubusercontent.com/assets/7262813/11189091/6d32e172-8c8e-11e5-8962-7dbd990c289f.PNG)

**Comment by chaeplin** [comment]
My board is generic ESP8266.
Do you have more codes than https://github.com/Pfannex/pubsubclient/blob/961700bc79c604bb187f8f62bd236a124339e369/examples/mqtt_esp8266/mqtt_esp8266.ino ?

Try to change MQTT_KEEPALIVE in PubSubClient.h from 15 to 60.
(Mine is 15)

**Comment by Pfannex** [comment]
You can find some more code here
https://github.com/Pfannex/AktSen

I changed MQTT_KEEPALIVE from 15 to 60 without success.
I also changed the ESP-12e into a ESP-12, also without success.

I´m very close to change the ESP against a W5100 wired controller.

What else can I do?
Where are I´m wrong?

**Comment by chaeplin** [comment]
@Pfannex 
I think board type is not a problem(flash size, serial speed...).

I have checked my code to mosquitto server(1.4.5/Wheezy) on pi B+ and 2. MQTT_KEEPALIVE is 15.
No reconnect at leat 10 mins.

tcp        0      0 192.168.10.138:1883     192.168.10.112:4097     ESTABLISHED 17310/mosquitto  off (0.00/0/0)

**Comment by chaeplin** [comment]
@Pfannex 
The following is log when I kill mosquitto in server. Infinite rc=-2(no delay).
-----------
0
0
0
0
0
failed, rc=-3
MQTT disconnected....
failed, rc=-2
MQTT disconnected....
failed, rc=-2
MQTT disconnected....
failed, rc=-2
MQTT disconnected....
failed, rc=-2
------------

Ping your esp8266 when disconnected to check network is ok.
Check mosquitto on server.

**Comment by chaeplin** [comment]
@Pfannex
Your log start with rc=-3, 

-3 : MQTT_CONNECTION_LOST - the network connection was broken
-2 : MQTT_CONNECT_FAILED - the network connection failed
-1 : MQTT_DISCONNECTED - the client is disconnected cleanly
0 : MQTT_CONNECTED - the cient is connected

https://cloud.githubusercontent.com/assets/7262813/11170690/f5f254ba-8bdb-11e5-9d6b-b8dd44ec5a8e.PNG

**Comment by Pfannex** [comment]
```
Ping your esp8266 when disconnected to check network(Wifi) is ok.
```
I have to check this out.
But I saw the in the disconnect state the ESP did not send any TCP-frames for a reconnect!
So I think, that there is no TCP-binding active.

Meanwhile I don't think, that the PubSubClient are the problem.
I think that the Ethernet-connection is the problem.

Is it possible to compile a Sketch and Flash it without Arduino?
So we can find a problem into my Arduino installation.

**Comment by chaeplin** [comment]
do ping test using this https://gist.github.com/chaeplin/72f7817bcf7f10bdbdff
(no pubsub, just wifi)

and how about using Staging version ?

**Comment by Pfannex** [comment]
I have disabled
**boolean reconnect() {** too.

I also run a simple WiFi sketch, I got about 3 disconnects a day.
But all disconnects were detected, a reconnect will start immediately.

What do you mean with "Staging version"?

Right now your test is running.....
Without any reconnects since 30 minutes.

Stay tuned.... :-)

btw. special thanks for your help so far

**Comment by chaeplin** [comment]
@Pfannex esp8266/Arduino has two version, stable and staging.

**Comment by Pfannex** [comment]
Right now your test is running.....
Without any reconnects since 60 minutes.

I canceled your test and installed "staging 2.0.0-rc1".
I run the previous Sketch.......

stay tuned.....

**Comment by Pfannex** [comment]
1h.......that's a long time!
I will report the overnight result tomorrow morning.

**Comment by Pfannex** [comment]
No reconnect or hanging since 8h....  pray....

**Comment by chaeplin** [comment]
@Pfannex 

My esps had random hang(reset) a month ago. So I dosabled "Serial.begin", no more hang.

#define DEBUG_PRINT 0

void setup() {
  if (DEBUG_PRINT) {
    Serial.begin(115200);
  }
}

**Comment by Pfannex** [comment]
20 hours!
I think, you solved the problem!
Great hint, thank you for your help!

I also disabled the RS232....... outside debugging

We will see if its stable, so stay tuned.....

**Comment by chaeplin** [comment]
@Pfannex tuned

**Comment by Pfannex** [comment]
The MQTT-Client works fine! 
No Problems so far!
Thanks...!

But now I got a Problem with the ESP-Board.
Did you heard something like that?

https://github.com/esp8266/Arduino/issues/1078

**Comment by orcema** [comment]
i resolved this problem by adding a delay(10); in the library's loop function as here below.
`boolean PubSubClient::loop() {
    if (connected()) {
    	delay(10);`

**Comment by AstarothPoD** [comment]
The delay(10); worked flawlessly for me too, 4 years later. Could it be added to the code?

**Comment by pierotoscano1496** [comment]
Hello everyone. I have this code, but I don´t know why the pubsubclient state is returning -1. I'm using a ESP32 devkit v1. I'm running Mosquitto on a Raspberry Pi for MQTT server with user and password. I'm sure the error is not in the server, because with a JavaScript client works perfectly. This is my code:

const char* ssid = "my_ssid";
const char* password = "my_network_password";
IPAddress mqttServer(192, 168, 1, 36); // The IP server
const int mqttPort = 9001;
const char* mqttUser = "user";
const char* mqttPassword = "pass";

void callback(char* topic, byte* payload, unsigned int length) {
  // My callback function
}

WiFiClient wifiClient;
PubSubClient client(mqttServer, mqttPort, callback, wifiClient);

void setup() {
  Serial.begin(9600);
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    Serial.println("Connecting to network...");
    delay(500);
  }
  Serial.println("Connected to network");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());
  Serial.println("==================================================");
  String clientId = "ESP32";
  clientId += String(random(0xffff), HEX);
  if (client.connect(clientId.c_str(), mqttUser, mqttPassword)) {
    Serial.println("MQTTClient connected");
  } else {
    Serial.println("MQTTClient can´t connect");
  }
}

void loop() {
  while (!client.connected()) {
    reconnect();
  }
  client.loop();
  // Rest of code
}

void reconnect() {
  Serial.println("Connecting to MQTT server...");
  String clientId = "ESP32";
  clientId += String(random(0xffff), HEX);
  client.connect(clientId.c_str(), mqttUser, mqttPassword);
  delay(10000);
  if (client.connected()) {
    Serial.println("MQTTClient connected");
    // Rest of code
  } else {
    Serial.println("Error code: ");
    Serial.println(client.state()); // It returns -1
    delay(5000);
  }
}

**Comment by thijsdebont** [comment]
@pierotoscano1496 double post. I replied to your issue in issue #203
