### ISSUE TITLE
PubSubClient.cpp  :::: if (qos < 0 || qos > 1) ::::

### ISSUE THREAD

**Issue by pippo-75** [knolleary/pubsubclient#410]
@ line # 473
warning: comparison is always false due to limited range of data type
if (qos < 0 || qos > 1) 

Note that in >> PubSubClient.h << @ lin # 136, it as been declared as
uint8_t, instead of 'int' or int8_t. 

Please correct me if I'm wrong, but I think it's a typo.

Anyway, thanks for Your time and this great job.

**Comment by knolleary** [comment]
Yes, this is fixed in the latest code in git - https://github.com/knolleary/pubsubclient/commit/f029640ee6365c58ebfe66ebf6bf1733d322f2ec

I haven't had time to publish a new release with it in.

**Comment by pippo-75** [comment]
i've got it and modified the file: thank you.
