### ISSUE TITLE
alternating connects from wemos

### ISSUE THREAD

**Issue by sscheffler** [knolleary/pubsubclient#413]
Hi. i have two wemos D1 which listening to the same topic on a mosquitto server (ubuntu server / docker container). while the one is connected the other looses the connection and vice versa. does someone know, what could be the problem?

Regards

**Comment by knolleary** [comment]
Each client must have a unique client id - the string you pass the connect function.

When an existing client id connects, the broker will disconnect an existing one with the same id.

**Comment by Paul-Reed** [comment]
But isn't the client ID randomized [here](https://github.com/knolleary/pubsubclient/blob/master/examples/mqtt_esp8266/mqtt_esp8266.ino#L90)
...so it should be different for each client?

**Comment by sscheffler** [comment]
Hi, i have an own *.ino file. not this one. i will try it. thanks for the hint
