### ISSUE TITLE
Publish to a different topic gets appended to the payload

### ISSUE THREAD

**Issue by shekhars271991** [knolleary/pubsubclient#443]
Hi,

I am trying to publish to some another topic as a response to a callback. Strangely Next time the call back is called, the payload gets appended with the repose which was published (to another topic!) also the client name is also getting appended. This is not happening if i don't send a response publish. Please see the following code.

```
void callback(char* topic, byte* payload, unsigned int length) {

  Serial.println();
  Serial.println("Callback Request.");
  Serial.print("Topic: ");
  Serial.println(topic);
  Serial.print("responseTopic: ");Serial.println(responseTopic);
  std::string payload_s( reinterpret_cast< char const* >(payload) ) ;// converting to string from byte array
  Serial.print("payload_s:");Serial.println(payload_s.c_str());
  char d= '-';
  /*Seperating Security token and actual Payload*/
  unsigned int delimiterIndex = payload_s.find(d);
  std::string payloadSecToken  = payload_s.substr(0,delimiterIndex);
  std::string actualPayload = payload_s.substr(delimiterIndex+1,delimiterIndex-1);
  Serial.print("actualPayload: ");Serial.println(actualPayload.c_str());
  Serial.print("payloadSecToken: ");Serial.println(payloadSecToken.c_str());

 if(payloadSecToken == secToken)
 {
   Serial.println("Security Token Validated");
   effectedPin = basePin+actualPayload[0]-48;
   Serial.print("effectedPin:");
   Serial.println(effectedPin);
  
    //turn the light on if the payload is '1' and publish to the MQTT server a confirmation message
    if(actualPayload[1] == '1'){
      Serial.print("Recieved: ");
      Serial.println(actualPayload[0]);
      digitalWrite(effectedPin, HIGH);
      Serial.println(responseTopic);
      client.publish(responseTopic, "=on");
  
    }
  
    //turn the light off if the payload is '0' and publish to the MQTT server a confirmation message
    else if (actualPayload[1] == '0'){
      Serial.print("Recieved: ");
      Serial.println(actualPayload[0]);
      digitalWrite(effectedPin, LOW);
      Serial.println(responseTopic);
      client.publish(responseTopic,"=off");
    }  
 }
 else
 {
  client.publish(responseTopic,"999"); // Security token mismatch
 }
}
```

This is the place here I connect to the server

```
if(WiFi.status() == WL_CONNECTED){
  // Loop until we're reconnected to the MQTT server
    while (!client.connected()) {
      Serial.print("Attempting MQTT connection...");
      // Generate client name based on MAC address and last 8 bits of microsecond counter
      String clientName;
      clientName += "xxxx-C001";//updated before each upload
      //if connected, subscribe to the topic(s) we want to be notified about
      if (client.connect((char*) clientName.c_str())) {
        Serial.print("MQTT Connected");
        client.subscribe(topic);
      }
      else{
      Serial.println("Failed");
      } 
    }       
  }
```

following is the serial output

Callback Request.
Topic: C001
responseTopic: C001_r
payload_s:XYZ-10
actualPayload: 10
payloadSecToken: XYZ
Security Token Validated
effectedPin:3
Recieved: 1
C001_r

Callback Request.
Topic: C001
responseTopic: C001_r
payload_s:XYZ-11offxxxx-C001
actualPayload: 11
payloadSecToken: XYZ
Security Token Validated
effectedPin:3
Recieved: 1
C001_r

as you can see in the second callback request, the payload is getting appended with the repose from the first callback and the client name.

Please help, im really stuck here. Dont mind my bad code, I am new to this language.

**Comment by trentbrown13** [comment]
Hello Shekhars271991,

Did you look at the "mqtt publish in callback" example given in the
library?

Here's a link to it

https://github.com/knolleary/pubsubclient/tree/master/examples/mqtt_publish_in_callback

**Comment by shekhars271991** [comment]
found the issue. Nothing is getting appended at the payload side while being sent to the callback function.

std::string payload_s( reinterpret_cast< char const* >(payload) ) ; this conversion is somehow appending the response. Im not sure how. but using other methods to convert works like charm.
