### ISSUE TITLE
Publish to MQTT fails, unclear why

### ISSUE THREAD

**Issue by brettks** [knolleary/pubsubclient#448]
I am using pubsubclient library to publish MQTT data to a broker. I have a script working and successfully publish the data every 20 seconds, however after a number of data transmissions, I am getting a failure to send the data.

My code to transmit the data is something like this:
Serial.println(client.publish( topicBuffer, msgBuffer ));

and I will initially get a "1" printed, but after a few minutes the client will print "0" on the serial and the data obviously isn't transmitted. I have confirmed that my wifi connection is still active with the ESP8266. How do I go about getting more information about the reason for the failure?

Thank you

**Comment by knolleary** [comment]
Is your script calling `client.loop()` regularly?

**Comment by brettks** [comment]
I've included below an excerpt of what my code looks like in what I think is the relevant area. It looks like I'm calling client.loop() on each loop, which is happening about every 20 seconds. Is that too infrequent for these calls? Maybe if I move that line outside of the block of code that is run after each sensor reading it would fix this.

```
void callback(const MQTT::Publish& pub) {
  // handle message arrived
}
WiFiClient wclient;
PubSubClient client(wclient, server);


void loop() {

...


if (WiFi.status() != WL_CONNECTED) {
        Serial.print("Connecting to ");
        Serial.print(ssid);
        Serial.println("...");
        WiFi.begin(ssid, pass);

        if (WiFi.waitForConnectResult() != WL_CONNECTED)
          return;
        Serial.println("WiFi connected");
        
      }

      if (WiFi.status() == WL_CONNECTED) { //if wireless is connected
        if (!client.connected()) { //and if MQTT client not connected
          Serial.println("Connecting to MQTT server");

          if (client.connect(MQTT::Connect("GreenhouseESP8266")
                             .set_auth("GreenhouseESP8266", "000"))) {
            Serial.println("Connected to MQTT server");
            client.set_callback(callback);
          } else {
            Serial.println("Could not connect to MQTT server");
          }
        }

        if (client.connected())
          client.loop();
          if (WiFi.status() == WL_CONNECTED) {Serial.println("Still connected to wifi");}
        // Create data string to send to ThingSpeak
        String data = String("field1=" + String(temp, DEC) + "&field2=" + String(humidity, DEC));
        int length = data.length();
        char msgBuffer[length];
        data.toCharArray(msgBuffer, length + 1);
        Serial.println(msgBuffer);

        // Create a topic string and publish data to ThingSpeak channel feed.
        String topicString = "channels/" + String( channelID ) + "/publish/" + String(writeAPIKey);
        length = topicString.length();
        char topicBuffer[length];
        topicString.toCharArray(topicBuffer, length + 1);
        Serial.println("Publish Result:");
        Serial.println(client.publish( topicBuffer, msgBuffer ));
        Serial.println("Published data to MQTT server");
      }
```

Serial output is:

```
Connecting to MQTT server
Connected to MQTT server
Still connected to wifi
field1=80.4740000000&field2=52.0200000000
Publish Result:
1
Published data to MQTT server


Still connected to wifi
field1=80.3660000000&field2=52.1100000000
Publish Result:
1
Published data to MQTT server


Still connected to wifi
field1=80.3480000000&field2=52.2100000000
Publish Result:
0
Published data to MQTT server

```

**Comment by knolleary** [comment]
Every 20 seconds should be okay - the default keepalive timeout is 15 seconds but brokers normally give a 2x grace period. What broker are you using? Do you have access to its logs to see what it says? Would help to rule out if it's a keepalive time out issue.

**Comment by brettks** [comment]
I'm using thingspeak. I think I could request the logs via their forums, but no easy access. However, I went ahead and moved the client.loop() to occur more frequently and that seems to have fixed the issue! Is running that command every loop too frequent? I don't want to DDoS them!

**Comment by knolleary** [comment]
Calling `client.loop()` allows the client code to check for any incoming messages (if you are subscribed to anything) as well as check its internal timer to see if it needs to send a ping to the broker to keep the connection alive. So calling it frequently will not cause any extra traffic (other than the ping packet once every 15 seconds or so).

On the other hand, we have seen that calling it too quickly (essentially with no delay at all) can effectively cause a DDoS of your own hardware.

If you're only publishing messages, so you don't need to receive inbound messages in a timely fashion, then just make sure you call it every few seconds.

**Comment by brettks** [comment]
Thanks for the help!
