### ISSUE TITLE
client.connect() too big crashes ESP8266

### ISSUE THREAD

**Issue by shaneyake** [knolleary/pubsubclient#454]
If I make the client.connect() to big with a lastwill message it crashes the ESP every time I receive a message. Any known fix?

**Comment by knolleary** [comment]
Hi,

just to clarify, you are connecting with a last will message. Then, whenever you received a message on a subscribed topic the ESP is crashing?

Does the crash happen if you connect without the will message?

How large are the messages you're dealing with?

**Comment by shaneyake** [comment]
Dude... Thanks so much. That fixed it. I didn't know about that setting before.
