### ISSUE TITLE
PubSubClient.h:72: error: section attribute not allowed for ‘<anonymous>’

### ISSUE THREAD

**Issue by ntruchsess** [knolleary/pubsubclient#46]
when compiling with Arduino IDE 1.0.6 you get the error:
PubSubClient.h:72: error: section attribute not allowed for ‘<anonymous>’

with Arduino IDE 1.0.5 it did compile just fine.

removing the 'PROGMEM' from this line solves the issue.
https://github.com/knolleary/pubsubclient/blob/master/PubSubClient/PubSubClient.h#L72

**Comment by jasonmhite** [comment]
Same error on 1.6.4...

**Comment by knolleary** [comment]
Bit long ago now, but what board were you targeting? It compiles fine for me against a regular arduino board definition.

**Comment by knolleary** [comment]
Fixed in the newly released 2.0 version

**Comment by niwantha33** [comment]
install this version 
https://github.com/heman4t/Arduino-pubsubclient
