### ISSUE TITLE
rc=-2 when connect

### ISSUE THREAD

**Issue by ChipTechno** [knolleary/pubsubclient#466]
Hello.
I have problem with setServer and connect function 
<pre>
client.setServer("192.168.1.214", 1883);
</pre>
with fixed parameter, i can connect to broker without problem.   

<pre>
char serverAddr[16]="192.168.1.214";
client.setServer(serverAddr, 1883);
</pre>
But when i set parameter from char array , the connect function return state -2

Thanks in advance!

**Comment by xdraylin** [comment]
Try it with 
`const char* serverAddr = "192.168.1.214"`

I could imagine your call of _connect()_ is out of the scope you are declaring _serverAddr_ in. Therefore the stack memory allocated by _serverAddr_ gets released upon leaving its scope and the pointer to it (which you gave to _setServer()_) is pointing to garbage.

**Comment by ChipTechno** [comment]
Thank you!
