### ISSUE TITLE
Support QoS2

### ISSUE THREAD

**Issue by FiReBlUe45** [knolleary/pubsubclient#470]
Hello,
I need to be able to use Publish with QoS = 2, is it supported?
If not, do you have another lib to offer?
I need QoS0,1,2, authentication support and TLS support.

thank you,

**Comment by knolleary** [comment]
No, this library does not support QoS 2 as clearly stated in the readme.

**Comment by knolleary** [comment]
Have a look at the embedded c client in the eclipse Paho project

**Comment by FiReBlUe45** [comment]
The Paho lib exists for the ESP8266?

**Comment by knolleary** [comment]
Sorry, I cannot comment on other libraries. I'm sure a Google search will help you find a library that meets your needs
