### ISSUE TITLE
mosquitto + nodered + pubsubclient +nodemcu callback function doesn't work anymore

### ISSUE THREAD

**Issue by rezahili** [knolleary/pubsubclient#474]
hi 
I used mqtt (mosquitto) and nodemcu(esp12-e) and node-red for my iot project . 
  i used  3 devices for connecting to node-red and everything was great and realtime .
but today when i try to uploading my code(old code that worked fine before),  received some exceptions on serial monitor and then i couldn't subscribe my commonds to esp  (callback function didn't work).
they are that codes i used & dint work :
`
#include <ESP8266WiFi.h>
#include <PubSubClient.h>
const char* ssid = "server";
const char* password = "123456789";
const char* mqtt_server = "192.168.1.100";
WiFiClient device1 ;//can change
PubSubClient client(device1);
void setup_wifi() {
  delay(10);
  // We start by connecting to a WiFi network
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");
  Serial.print("WiFi connected - ESP IP address: ");
  Serial.println(WiFi.localIP());
}

void callback(String topic, byte* message, unsigned int length) {
  Serial.print("Message arrived on topic: ");
  Serial.print(topic);
  Serial.print(". Message: ");
  String messageTemp;
  
  for (int i = 0; i < length; i++) {
    Serial.print((char)message[i]);
    messageTemp += (char)message[i];
  }
  if(topic=="room/lamp"){
      Serial.print("Changing Room lamp to ");
      if(messageTemp == "on1"){
        digitalWrite(14, HIGH);
        Serial.print("On 1");
                char* lamp1 = "light 1 is on";

      client.publish("light/status", lamp1);

      }
      if(messageTemp == "on2"){
        digitalWrite(12, HIGH);
        Serial.print("On 2");
                char* lamp2 = "light 2 is on";

      client.publish("light/status", lamp2);

      }
      if(messageTemp == "on3"){
        digitalWrite(16, HIGH);
        Serial.print("On 3");
                char* lamp3 = "light 3 is on";

      client.publish("light/status", lamp3);

      }
      else if(messageTemp == "off1"){
        digitalWrite(14, LOW);
        Serial.print("Off 1");
        char* light1 = "light 1 is off";
        client.publish("light/status", light1);

      }
      else if(messageTemp == "off2"){
        digitalWrite(12, LOW);
        Serial.print("Off 2");
        char* light2 = "light 2 is off";
        client.publish("light/status", light2);

      }
      else if(messageTemp == "off3"){
        digitalWrite(16, LOW);
        Serial.print("Off 3");
        char* light3 = "light 3 is off";
        client.publish("light/status", light3);

      }
  }
  Serial.println();
}

void reconnect() {
   while (!client.connected()) {
    Serial.print("Attempting MQTT connection...");
    // Create a random client ID
    String clientId = "ESP8266Client-";
    clientId += String(random(0xffff), HEX);
    // Attempt to connect
    if (client.connect(clientId.c_str())) {
      Serial.println("connected");
      // Once connected, publish an announcement...
     
      // ... and resubscribe
      //client.subscribe("room/lamp");
    } else {
      Serial.print("failed, rc=");
      Serial.print(client.state());
      Serial.println(" try again in 5 seconds");
      // Wait 5 seconds before retrying
      delay(5000);
    }
  }
}
void setup() {
  pinMode(14, OUTPUT);
  pinMode(16, OUTPUT);
  pinMode(12, OUTPUT);

   Serial.begin(115200);
  setup_wifi();
  client.setServer(mqtt_server,1883);
  client.setCallback(callback);

}
void loop() {

  if (!client.connected()) {
    reconnect();
      

  }
  if(!client.loop())
    client.connect("ESP8266Client");
    char* m ="54";
    char* s = "32";
client.publish("room/temperature", m);
    client.publish("room/humidity", s);
    delay(500);
    //
}

`
on the top worked greatly for  1 month :|
and this 
`
#include <ESP8266WiFi.h>
#include <PubSubClient.h>

// Update these with values suitable for your network.

const char* ssid = "server";
const char* password = "123456789";
const char* mqtt_server = "192.168.1.100";

WiFiClient espClient;
PubSubClient client(espClient);
long lastMsg = 0;
char msg[50];
int value = 0;

void setup_wifi() {

  delay(10);
  // We start by connecting to a WiFi network
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);

  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  randomSeed(micros());

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());
}

void callback(String topic, byte* message, unsigned int length) {
  Serial.print("Message arrived on topic: ");
  Serial.print(topic);
  Serial.print(". Message: ");
  String messageTemp;
  
  for (int i = 0; i < length; i++) {
    Serial.print((char)message[i]);
    messageTemp += (char)message[i];
  }
  if(topic=="room/lamp"){
      Serial.print("Changing Room lamp to ");
      if(messageTemp == "on1"){
        digitalWrite(14, HIGH);
        Serial.print("On 1");
                char* lamp1 = "light 1 is on";

      client.publish("light/status", lamp1);

      }
      if(messageTemp == "on2"){
        digitalWrite(12, HIGH);
        Serial.print("On 2");
                char* lamp2 = "light 2 is on";

      client.publish("light/status", lamp2);

      }
      if(messageTemp == "on3"){
        digitalWrite(16, HIGH);
        Serial.print("On 3");
                char* lamp3 = "light 3 is on";

      client.publish("light/status", lamp3);

      }
      else if(messageTemp == "off1"){
        digitalWrite(14, LOW);
        Serial.print("Off 1");
        char* light1 = "light 1 is off";
        client.publish("light/status", light1);

      }
      else if(messageTemp == "off2"){
        digitalWrite(12, LOW);
        Serial.print("Off 2");
        char* light2 = "light 2 is off";
        client.publish("light/status", light2);

      }
      else if(messageTemp == "off3"){
        digitalWrite(16, LOW);
        Serial.print("Off 3");
        char* light3 = "light 3 is off";
        client.publish("light/status", light3);

      }
  }
  Serial.println();
}

void reconnect() {
  // Loop until we're reconnected
  while (!client.connected()) {
    Serial.print("Attempting MQTT connection...");
    // Create a random client ID
    String clientId = "ESP8266Client-";
    clientId += String(random(0xffff), HEX);
    // Attempt to connect
    if (client.connect(clientId.c_str())) {
      Serial.println("connected");
      // Once connected, publish an announcement...
      client.publish("outTopic", "hello world");
      // ... and resubscribe
      client.subscribe("inTopic");
    } else {
      Serial.print("failed, rc=");
      Serial.print(client.state());
      Serial.println(" try again in 5 seconds");
      // Wait 5 seconds before retrying
      delay(5000);
    }
  }
}

void setup() {
  pinMode(BUILTIN_LED, OUTPUT);     // Initialize the BUILTIN_LED pin as an output
  Serial.begin(115200);
  setup_wifi();
  client.setServer(mqtt_server, 1883);
  //client.setCallback(callback);
  connectmqtt();
 
}

void connectmqtt()
{
  String clientId = "ESP8266Client-";
  clientId += String(random(0xffff), HEX);
  client.connect(clientId.c_str());
  {
      Serial.println("connected");
      // Once connected, publish an announcement...
     
      // ... and resubscribe
      client.subscribe("inTopic");
       client.publish("outTopic", "hello world");

       if (!client.connected()) 
  {
    reconnect();
   }
  }
}

void loop() {

  if (!client.connected()) {
    reconnect();
  }
  client.loop();
delay(1000);
  long now = millis();
  if (now - lastMsg > 2000) {
    lastMsg = now;
    ++value;
    snprintf (msg, 75, "hello world #%ld", value);
    Serial.print("Publish message: ");
    Serial.println(msg);
    client.publish("outTopic", msg);
  }
}
`

**Comment by rezahili** [comment]
nodered code : `
[{"id":"f0908e5b.28b11","type":"ui_switch","z":"fd5b6e22.3567e","name":"سبز","label":"سبز","group":"730bfc99.f2e8a4","order":0,"width":"0","height":"0","passthru":true,"decouple":"false","topic":"room/lamp","style":"","onvalue":"on1","onvalueType":"str","onicon":"","oncolor":"","offvalue":"off1","offvalueType":"str","officon":"","offcolor":"","x":316,"y":100,"wires":[["928540ee.1eeb6"]]},{"id":"928540ee.1eeb6","type":"mqtt out","z":"fd5b6e22.3567e","name":"room","topic":"room/lamp","qos":"2","retain":"","broker":"a5845f19.97c75","x":718.9999961853027,"y":136.99999809265137,"wires":[]},{"id":"19c1353a.13352b","type":"ui_switch","z":"fd5b6e22.3567e","name":"آبی","label":"آبی","group":"730bfc99.f2e8a4","order":0,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"room/lamp","style":"","onvalue":"on2","onvalueType":"str","onicon":"","oncolor":"","offvalue":"off2","offvalueType":"str","officon":"","offcolor":"","x":319,"y":164,"wires":[["928540ee.1eeb6"]]},{"id":"8ce4a14a.c8ada","type":"ui_switch","z":"fd5b6e22.3567e","name":"قرمز","label":"قرمز","group":"730bfc99.f2e8a4","order":0,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"room/lamp","style":"","onvalue":"on3","onvalueType":"str","onicon":"","oncolor":"","offvalue":"off3","offvalueType":"str","officon":"","offcolor":"","x":204.99999618530273,"y":233.00000190734863,"wires":[["928540ee.1eeb6"]]},{"id":"730bfc99.f2e8a4","type":"ui_group","z":"","name":"اتاق ۱","tab":"47a3867e.7be6b8","order":1,"disp":true,"width":"5","collapse":false},{"id":"a5845f19.97c75","type":"mqtt-broker","z":"","name":"","broker":"localhost","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","closeTopic":"","closeQos":"0","closePayload":"","willTopic":"","willQos":"0","willPayload":""},{"id":"47a3867e.7be6b8","type":"ui_tab","z":"","name":"کنترل وسایل","icon":"lightbulb_outline","order":2}]`

**Comment by Paul-Reed** [comment]
You need to be more specific, and isolate what the actual problem is before asking for support.
You can't expect contributors or developers to go through every part of your code & flow looking for possible problems, without getting some pointers what the problem is, or where the problem may originate.
What does your mosquitto log show?

**Comment by rezahili** [comment]
hi 
thank u for ur response .
sorry I'm novice  in asking question.
also used id for multiple devices .
`1533766087: mosquitto version 1.4.10 (build date Fri, 22 Dec 2017 08:19:25 +0000) starting
1533766087: Config loaded from /etc/mosquitto/mosquitto.conf.
1533766087: Opening ipv4 listen socket on port 1883.
1533766087: Opening ipv6 listen socket on port 1883.
1533766115: New connection from 127.0.0.1 on port 1883.
1533766115: New client connected from 127.0.0.1 as mqtt_c56b960f.3a9468 (c1, k60).
1533766330: New connection from 192.168.1.101 on port 1883.
1533766330: New client connected from 192.168.1.101 as ESP8266Client-4469 (c1, k15).
1533766425: Client mqtt_c56b960f.3a9468 disconnected.
`

**Comment by rezahili** [comment]
also i used this [site](https://randomnerdtutorials.com/esp8266-and-node-red-with-mqtt/) for all program except id for multiple devices (that was here)

**Comment by rezahili** [comment]
`Connecting to server
....
Exception (0):
epc1=0x60000600 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: sys 
sp: 3ffffdc0 end: 3fffffb0 offset: 01a0

>>>stack>>>
3fffff60:  4022ae00 3ffee778 3ffee7a0 60000600  
3fffff70:  0022613d 3ffee7a0 3ffee778 4022ae0d  
3fffff80:  4022ae52 3fffdab0 00000000 3fffdcb0  
3fffff90:  3ffee7b0 3fffdab0 00000000 40204dc7  
3fffffa0:  40000f49 40000f49 3fffdab0 40000f49  
<<<stack<<<

 ets Jan  8 2013,rst cause:1, boot mode:(3,6)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v4ceabea9
~ld`

**Comment by rezahili** [comment]
update the espcore frome 2.4.0 to 2.4.2 and exception fixed
