### ISSUE TITLE
Cannot publish two strings

### ISSUE THREAD

**Issue by gadjet** [knolleary/pubsubclient#477]
HI,
I'm using Pubsub with an ESP 826 and want to transmit a status message and a battery level, I try to publish them in the void reconnect() function but only one message will ever get sent or sometimes none will be sent when two are trying to be sent.
If I limit to one message, either one then it publishes fine can anyone see what I'm doing wrong?
```
 // Once connected, publish an announcement...
     client.publish("OutsideLight/2/Status", "Triggered");
     client.publish("OutsideLight/2/BatteryLevel", String(BattLevel).c_str());
      // ... and resubscribe
      // client.subscribe("inTopic");
```
Thanks for any help, I'm no expert in this coding just use existing examples and modify to suit.

**Comment by knolleary** [comment]
try adding a small `delay(100)` between the two `client.publish()` calls.

**Comment by gadjet** [comment]
Thanks, I had already tried delay(500); and it didn't work but 100 worked fine ... strange!
