### ISSUE TITLE
in the ESP8266 sample code, how does the Callback If loop work and why can't i compare string?

### ISSUE THREAD

**Issue by jyrenk** [knolleary/pubsubclient#479]
https://github.com/knolleary/pubsubclient/blob/master/examples/mqtt_esp8266/mqtt_esp8266.ino

Based on this sample code, i am trying to change ` if ((char)payload[0] == '1')` to something like `if ((char)payload[0] == 'teston')`

I tried` if (strncmp(payload, "teston") == 0)` but it won't compile without a error. I get thrown a error : `invalid conversion from 'byte* {aka unsigned char*}' to 'const char*'`

**Comment by rezahili** [comment]
hi 
use this loop in your callback function 
`String` `messageTemp;`
` for (int i = 0; i < length; i++) {
    messageTemp += (char)message[i];
  }`
and in if condition : 
`use` `if` `(` `messegeTemp` `==` `"` `something"` `)`

**Comment by company-ms** [comment]
@rezahili Thank you very much. I did search half the internet.
Before finding such an elegant answer!
