### ISSUE TITLE
UIPEthernet with pubsubclient

### ISSUE THREAD

**Issue by bikingbadger** [knolleary/pubsubclient#48]
Just like to know whether there is any support or way of using UIPEthernet instead of the standard Ethernet libraries as I am using a ENC28J60?

**Comment by ccfiel** [comment]
@lightcowboy are you successful using it with ENC28J60?

**Comment by zuhryfayesz** [comment]
I managed make it work ENC28J60 with Nano using UIPEthernet component via MQTT. Check my GitHub repo. 
Link: https://github.com/zuhryfayesz/Zuhry-MQTT-IoT

**Comment by tindaio** [comment]
@zuhryfayesz  is it stable? does not hang?

**Comment by mihaif3** [comment]
I have also used PubSubClient with UIPEthernet and ENC28J60 on various Arduino devices.
This works great sometimes, but unfortunately I am experiencing random hangs and persistent connection failures from time to time, which are very hard to reproduce and debug.

Do you guys have any idea what is the issue here ? Is it something in the libraries (thus fixable) or is it a problem with the ENC28J60 device ?

**Comment by consolacion** [comment]
I realize it might be an old topic, but I have been using the UIP lib as well and works very well. The random hanging that mihaif3 experienced might be caused by a program that is too big. The ENC28J60 does require some space, much more than the W5100 and that might make your program hang. 
The Arduino library usually gives an indication that the program might be unstable if too much memory/variables used

**Comment by vanbwodonk** [comment]
@consolacion i agree with you, just disable UDP to save 5Kb flash and some RAM. Disable it on utility/uipethernet-conf.h.

**Comment by consolacion** [comment]
Indeed, sadly not always possible. Even with the simplest of programs setting UIP_CONF_UDP to '0' to disable UDP generated errors in  the Ethernet.begin(mac)  statement:  undefined reference to `UIPEthernetClass::begin(unsigned char const*)'

But ofcourse this is  starting to fall beyond the scope of the pubsub clent

**Comment by dmak** [comment]
Interestingly, [`README.md`](https://github.com/knolleary/pubsubclient/blob/master/README.md) reads `The library cannot currently be used with hardware based on the ENC28J60 chip` which is not true as it is supported via [UIPEthernet](https://github.com/ntruchsess/arduino_uip).

**Comment by knolleary** [comment]
@dmak it was true when I wrote those words a long long time ago. Happy to have a PR to correct it.

**Comment by dmak** [comment]
I can create a PR, but I am not sure that UIPEthernet library works with all combinations of boards and ENC28J60-based shields...

**Comment by marcoavaccaro** [comment]
Hello guys,

I'm trying to use ENC28J60 with esp32. But i can't run the error: "Attempting MQTT connection...failed, rc=-2 try again in 5 second"

My code: 

```
#include <SPI.h>
#include <UIPEthernet.h>                                  // UIP Ethernet Library to support ENC28J60 ethernet module. 
#include <PubSubClient.h>                                 // MQTT publisher/subscriber client library                

byte mac[]      = {  0xDE, 0xED, 0xBA, 0xFE, 0xFE, 0xED }; // Set the mac address for the arduino nano mcu 
//byte server[] = { xxx, xxx, xxx, xxx };                  // Set MQTT broker server IP address
char server[]   = "broker.mqtt-dashboard.com";             // Set MQTT broker server domain address 
byte ip[]       = { 192, 168, 0, 108 };                    // Set the IP address for the arduino nano mcu 

//int LED = 6;                                               // Initialize digital pin 6 to LED variable 
String msgString;                                            // Initialize msgString variable

void callback(char* topic, byte* payload, unsigned int length) {
  char message_buff[100];
  int i;
  for(i=0; i<length; i++) {
    message_buff[i] = payload[i];
  }
  message_buff[i] = '\0';
  msgString = String(message_buff);
  Serial.println("message arrived: " + msgString);          // Serial output of received callback payload
}

EthernetClient ethClient;
PubSubClient client(server, 1883, callback, ethClient);     // Initialize a MQTT client instance

void reconnect() {
  // Loop until we're reconnected
  while (!client.connected()) {
    Serial.print("Attempting MQTT connection...");
    // Attempt to connect
    if (client.connect("arduinoClient")) {
      Serial.println("connected");
      // Once connected, publish an announcement...
      client.publish("outTopic","hello world");
      // ... and resubscribe
      client.subscribe("inTopic");
    } else {
      Serial.print("failed, rc=");
      Serial.print(client.state());
      Serial.println(" try again in 5 seconds");
      // Wait 5 seconds before retrying
      delay(5000);
    }
  }
}

void setup()
{
  Serial.begin(115200);                                       // Set the Serial Buad rate to 9600 
  Ethernet.begin(mac, ip);
  
  if (client.connect("arduinoClient")) {                    // Check the MQTT broker connectivity
     client.publish("topic","connected");                   // Publish ethernet connected status to MQTT topic
     client.subscribe("topic");                             // Subscribe to a MQTT topic
  }

}

void loop()
{
  if (!client.connected()){
    reconnect();
  }
  client.loop();
}
```

I managed to post a tweet with the EtherCard library but I didn't get anything with MQTT

**Comment by dmak** [comment]
Have you tried to look into `PubSubClient.h` sources? It reads:
```
#define MQTT_CONNECT_FAILED         -2
```
so I believe that if `EthernetClient` works fine with some other network application, then something is wrong with MQTT connectivity. First try to ping your ESP (`ping 192.168.0.108`) from your MQTT server. Do you have other remote devices which successfully connect to MQTT sever?
