### ISSUE TITLE
connection error 15

### ISSUE THREAD

**Issue by mstranne** [knolleary/pubsubclient#482]
Hey, I am not able to connect via the lib. I can start the server and mosquitto_sub and pub are working in terminal. But I am not able to connect to the local mosquitto broker using the library.

I am triing to connect like that:
```
		  int err = subscriber->connect("127.0.0.1",1883,60,NULL);
		  if (err == MOSQ_ERR_SUCCESS)
			  return 1;
		  if (err == MOSQ_ERR_INVAL)
			  return 0;
		  if (err == MOSQ_ERR_ERRNO) {
			  std::cout << "err " << err << std::endl;
			  char errmsg[100];
			  strerror_s(errmsg, 100, err);

			  std::cout << errmsg << std::endl;
			  return -1;
		  }
```

It always returns 15 

Anyone knowing what I am making wrong?

**Comment by JackGruber** [comment]
Wrong broker address, 127.0.0.1 is a Looback Address not the real network address of your mqtt broker.
