### ISSUE TITLE
Connection always fails to local broker

### ISSUE THREAD

**Issue by alwashe** [knolleary/pubsubclient#486]
I have no trouble to connect to: broker.mqttdashboard.com
But as soon as i try to connect to a local mosquito broker it fails.
Manual connection with MQTT.fx works fine
I tried to use passwords and without on my broker.

`#include <ESP8266WiFi.h>
#include <PubSubClient.h>
#include "DHT.h"

DHT dht(2, DHT22);

const char* ssid = "MYWIFI";
const char* password = "MYWIFIPASSWORD";

//This is Working
//const char* mqtt_server = "broker.mqttdashboard.com";

//This is not Working Error: connection...failed, rc=-2 try again in 5 seconds
const char* mqtt_server = "openhab1";
const char* mqtt_user = "openhabian";
const char* mqtt_pwd = "PASSWORD";

const char* mqtt_topic = "tempo";
String ClientId = "ESP8266_";
unsigned char mac[6];

WiFiClient espClient;
PubSubClient client(espClient);

long lastMsg = 0;
char msg[50];

String macToStr(const uint8_t* mac)
{
  String result;
  for (int i = 0; i < 6; ++i) {
    result += String(mac[i], 16);
  }
  return result;
}

void setup() {
  pinMode(LED_BUILTIN, OUTPUT);     // Initialize the BUILTIN_LED pin as an output
  Serial.begin(115200);

  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);
  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());

  WiFi.macAddress(mac);
  ClientId += macToStr(mac);
  
  Serial.println(ClientId);

  client.setServer(mqtt_server, 1883);
  client.setCallback(callback);
  dht.begin();
}

void callback(char* topic, byte* payload, unsigned int length) {
  Serial.print("Message arrived [");
  Serial.print(topic);
  Serial.print("] ");
  for (int i = 0; i < length; i++) {
    Serial.print((char)payload[i]);
  }
  Serial.println();
}

void reconnect() {
  // Loop until we're reconnected
  while (!client.connected()) {
    Serial.print("reconnect...");
    // Attempt to connect
    if (client.connect(ClientId.c_str(), mqtt_user, mqtt_pwd)) {
      Serial.println("connected");
      // Once connected, publish an announcement...
      client.publish(mqtt_topic, "halo world");

    } else {
      Serial.print("failed, rc=");
      Serial.print(client.state());
      Serial.println(" try again in 5 seconds");
      // Wait 5 seconds before retrying
      delay(5000);
    }
  }
}

void loop() {
  delay(5000);
  float h = dht.readHumidity();
  float t = dht.readTemperature();

  if (!client.connected()) {
    reconnect();
  }
  client.loop();
  snprintf (msg, 75, "%.1f" , t);
  client.publish(mqtt_topic, msg);
}`

**Comment by JackGruber** [comment]
Please use a FQDN (Fully qualified domain name) for your openhab server or a IP address!
The `openhab1 `can not be resolved to a IP address from your ESP.

**Comment by alwashe** [comment]
Thank you so much, i was working on this for days and could not figure it out.
