### ISSUE TITLE
ESP8266 fail to connect MQTT broker

### ISSUE THREAD

**Issue by adisazhar123** [knolleary/pubsubclient#488]
I am using NodeMCU dev board with ESP8266 WIFI.
Everytime I try to connect to my local broker it returns this error:
`failed, rc=-2 try again in 5 seconds`
I am using Ubuntu 18.04, my local brokers are Mosquitto and EQMTT. I tried both of them through pubsubclient library and it doesn't connect. Using MQTT Box works connecting to my local brokers. Connecting to my WiFi also works. When I connect to a  MQTT broker using pubsubclient e.g.  `mqtt://test.mosquitto.org:1883/` it works. It just doesn't seem to work with local broker. This is the code:
```
#include <ESP8266WiFi.h>
#include <PubSubClient.h>

// Update these with values suitable for your network.

const char* ssid = "mywifi";
const char* password = "password";
const char* mqtt_server = "127.0.0.1";

WiFiClient espClient;
PubSubClient client(espClient);
long lastMsg = 0;
char msg[50];
int value = 0;

void setup() {
  pinMode(D7, OUTPUT);     // Initialize the BUILTIN_LED pin as an output
  Serial.begin(9600);
  setup_wifi();
  client.setServer(mqtt_server, 1883);
  client.setCallback(callback);
}

void setup_wifi() {

  delay(10);
  // We start by connecting to a WiFi network
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);

  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());
}

void callback(char* topic, byte* payload, unsigned int length) {
  Serial.print("Message arrived [");
  Serial.print(topic);
  Serial.print("] ");
  for (int i = 0; i < length; i++) {
    Serial.print((char)payload[i]);
  }
  Serial.println();

  // Switch on the LED if an 1 was received as first character
  if ((char)payload[0] == '1') {
    digitalWrite(D7, LOW);   // Turn the LED on (Note that LOW is the voltage level
    // but actually the LED is on; this is because
    // it is acive low on the ESP-01)
  } else {
    digitalWrite(D7, HIGH);  // Turn the LED off by making the voltage HIGH
  }

}

void reconnect() {
  // Loop until we're reconnected
  while (!client.connected()) {
    Serial.print("Attempting MQTT connection...");
    // Attempt to connect
    if (client.connect("ESP8266Client")) {
      Serial.println("connected");
      // Once connected, publish an announcement...
      client.publish("outTopic", "hello world");
      // ... and resubscribe
      client.subscribe("inTopic");
    } else {
      Serial.print("failed, rc=");
      Serial.print(client.state());
      Serial.println(" try again in 5 seconds");
      // Wait 5 seconds before retrying
      delay(1000);
    }
  }
}
void loop() {

  if (!client.connected()) {
    reconnect();
  }
  client.loop();

  long now = millis();
  if (now - lastMsg > 2000) {
    lastMsg = now;
    ++value;
    snprintf (msg, 75, "hello world #%ld", value);
    Serial.print("Publish message: ");
    Serial.println(msg);
    client.publish("outTopic", msg);
  }
}
```

**Note:** The brokers are running, I can even connect it through MQTT Box (attached picture).
![mqttbox](https://user-images.githubusercontent.com/32903319/44795640-5ce9a580-abd5-11e8-8b32-30884c7a6aae.png)

**Comment by JackGruber** [comment]
> const char* mqtt_server = "127.0.0.1";
This is a loopback address an refers to the ESP self. Use the MQTT server ip address or DNS name.

**Comment by adisazhar123** [comment]
@JackGruber Hey yes! Sorry, I have replaced it to `192.168.100.3` after getting it from `hostname -I`. Unfortunately, it still shows `rc = 2`.

**Comment by JackGruber** [comment]
can you try a mqtt connection from a other client to your broker, i think its a firewall or configuration problem (listen only to locale connections) on your broker.

**Comment by adisazhar123** [comment]
thank you, its done.

**Comment by adisazhar123** [comment]
BTW if anyone goes through the same issue as me, try pinging the IP of esp device

**Comment by ambassadorSp0ck** [comment]
@adisazhar123 i faced a similar issue. And I'm new to this so please bear with me.

I have installed local mqtt broker and opened another terminal, and have subscribed to the topic mentioned in my esp8266 code. 

So if the code runs successfully, i should get the message sent in this terminal window, right?

Could you please clarify what ip I'll need to enter in the server variable? And how i can find that ip as localhost doesn't work.

**Comment by bimsarapathiraja** [comment]
pinging the IP of esp device - how this can be done

**Comment by adisazhar123** [comment]
> pinging the IP of esp device - how this can be done

Have it connect to your wifi, and have this portion of code that will print the IP of esp. 
```
Serial.println("IP address: ");
  Serial.println(WiFi.localIP());
```
You can then ping it via terminal.

**Comment by priyeshshah11** [comment]
I can ping my ESP8266 from the MQTT broker machine (macOS), but still getting the same issue.

**Comment by kulkarniatharv** [comment]
If anything mentioned above doesn't work, check if you have allowed (or disallowed) anonymous users to access your broker (mosquitto) in the config file using `allow_anonymous` command along with checking if listener(s) is(are) properly setup using the `listener` command. [https://mosquitto.org/man/mosquitto-conf-5.html](url) for docs on mosquitto config

**Comment by Normanras** [comment]
> > pinging the IP of esp device - how this can be done
> 
> 
> 
> Have it connect to your wifi, and have this portion of code that will print the IP of esp. 
> 
> ```
> 
> Serial.println("IP address: ");
> 
>   Serial.println(WiFi.localIP());
> 
> ```
> 
> You can then ping it via terminal.

This makes partial sense in the sense I already have the MAC address and IP of my ESP. But what are you suggested I adjust in the code to enable the connection? `mqtt_server` should point to the broker (or home assistant in this case) and then what use does having the ESP's IP do?

**Comment by themightywolfie** [comment]
Did you find a solution for this? because i am facing this exact same problem

**Comment by Yugo1885** [comment]
Thank you sir! I have the same problems, but it has still unsolved. When my arduino prints "WiFi.localIP", it means my esp8266 ip, right? I am using node red as my broker, I think the only problem is server ip of mqtt in node red. How can I fix it? Because I type the esp ip on there, it still can't connect.
