### ISSUE TITLE
Use a variable in client.publish

### ISSUE THREAD

**Issue by emeyedeejay** [knolleary/pubsubclient#49]
Hi Nick ... great library! I have a Q.

How would I publish the value of a variable in e.g.   client.publish("MIDJ/Temp","temperature"); 

I want to publish the value of the variable "temperature" not the string "temperature" if you know what I mean?

Thanks a stack!

void loop(){
  float temperature = getTemp();
  Serial.println(temperature);
  lcd.clear();
  lcd.setCursor(0, 0);
  lcd.print("Temp: ");
  lcd.print(temperature);
  lcd.print((char)223);
  client.publish("MIDJ/Temp","temperature");
  delay(5000); //read temp every 5 seconds
  client.loop();

**Comment by sindiddle** [comment]
@emeyedeejay may i see the changes on ur code after you add this? 
`char tempstring[20];
dtostrf(temperature,3,1,tempstring);`
