### ISSUE TITLE
getting retained from received messages

### ISSUE THREAD

**Issue by davejel** [knolleary/pubsubclient#498]
hi all
i have been using pubsubclient for a while and so far am really pleased with the way it works, thank you Nick
i am now in a situation where i need to know if received messages are retained or not. i have 'googled' and read through the library but the only mention i can find is while publishing.
am i missing something or is there another way to tell if a received message is retained.

thanks for any help
dave

**Comment by knolleary** [comment]
Hi,

No, the subscription callback function does not expose the retained flag. The library would have to be changed to support that.

**Comment by davejel** [comment]
ok thanks i'll close the issue
