### ISSUE TITLE
Support for SIM800 module

### ISSUE THREAD

**Issue by solankigithub** [knolleary/pubsubclient#503]
Hi,
Do you have any plans to add the SIM800 support for this library?

Thanks

**Comment by knolleary** [comment]
If there's a network client for the SIM800 that implements the standard `Client.h` interface defined by the arduino platform, then it will work with this library already.

Otherwise, no, I don't have any plans to do anything for SIM800.

**Comment by solankigithub** [comment]
Ok, i am in the process of building my own MQTT client library that works on SIM800.
What i observe is that the broker sends back the the publish packet to the client instead of PUBACK.

It sends the packet back to client with code 0x30. This actually interrupts to the messages i get after subscribing to a different topic. 
How can i stop broker sending the same publish packet back to the client rather it should send the PUBACK. I am sending packet with QOS=0.
Any help?

**Comment by knolleary** [comment]
Is you client subscribed to that topic? That is the only reason the broker would send a publish back to the client and it is perfectly valid for it to send the publish before sending the puback in response to the original publish from the client.

**Comment by solankigithub** [comment]
No, my client is not subscribed to that topic.
Please find the below link to visit the code library:
https://github.com/solankigithub/sim800mqtt

**Comment by solankigithub** [comment]
This doesn't just happen with the Publish packet, but it also happens with Connect and Subscribe packet.
So in Nutshell, whatever packet i am sending to the MQTT broker, i am getting the same message back in SerialEvent() . Not sure why such behavior.

**Comment by knolleary** [comment]
Sorry, I don't know what to suggest. Good luck with your client.

**Comment by solankigithub** [comment]
Thanks, but did you get the same issue with ESP and Ethernet. These both works on TCP. I am able to open the TCP connection with SIM800 and send the packet but receive the same packet in return.  As per my understanding there should not be further difference in the client (ESP, Ethernet, Sim800) once the TCP connection is open.
