### ISSUE TITLE
Lightweight Version

### ISSUE THREAD

**Issue by tstanescu1** [knolleary/pubsubclient#509]
This is an amazing library, it boasts everything is needed to work with MQTT, and more.

I was wondering if you could help me remove a bit of weight off this library so I can run a few sensors on my arduino leonardo. Please let me know if there are a few things I can remove from the library. 

I am only using very basic subscribe and publish.

Thanks again,
T

**Comment by knolleary** [comment]
Sorry, I'm unlike to be able to offer much help here. The library is already pretty minimal. You could strip off the functions you aren't using - although istr the compiler already does a pretty good job of that.
