### ISSUE TITLE
Question: How to change the port settings dynamically

### ISSUE THREAD

**Issue by marcelrv** [knolleary/pubsubclient#51]
Is there a way to set the port dynamically, meaning not directly at the initialization.
I am reading the server and the port int from eeprom, however then I'm no longer able to set the port settings. For the mqtt server it is still possible to change this later, but for the port not.

Is there another way other then introducing something like
void PubSubClient::setPort(uint16_t port) {
	this->port = port;
}

**Comment by knolleary** [comment]
Appropriate setter added
