### ISSUE TITLE
Can I use pubsubclient at wizfi250(speedstudio) or Yun Shield?

### ISSUE THREAD

**Issue by Lohanasy** [knolleary/pubsubclient#53]
I bought wizfi250(speedstudio). I was going to use the pubsubclient, but the fi250(libarary) had not client.h. In this situation can I use the pubsubclient at wizifi250?
And I am going to buy Yun Shield
(http://www.aliexpress.com/item/Linux-WiFi-Ethernet-USB-All-in-one-Shield-for-Arduino-Leonardo-UNO-Mega2560-Duemilanove/2011318517.html?s=p).
In this device, can I use pubsubclient? pls. help me.

(If you can't know what I say, give me the massage. My english is very poor.)

**Comment by knolleary** [comment]
As documented, as long as the hardware has a Client.h compatible library, it will work with this library. I can't find enough information about that device to say if it will work or not.
