### ISSUE TITLE
Need Guidance: How to publish to one server and subscribe to another

### ISSUE THREAD

**Issue by CaptClaude** [knolleary/pubsubclient#547]
Platform: ESP8266 (D1 Mini), Arduino IDE, latest everything.
I want to subscribe to the cheerlights feed on iot.eclipse.org and publish the `FreeHeap()` to a local instance of Mosquitto on a Raspberry Pi.  Pub & Sub to just the Pi work great.  Sub to iot.eclipse.org works fine by itself.  Without knowing any better, I am making the following assumptions:
Define both servers:
```
const char* PubServer = "192.168.1.80";  //RPi0W running Mosquitto
const char* SubServer = "iot.eclipse.org";
```
Declare two instances in the header
`PubSubClient SubClient(espClient); // for connecting to the server to which I subscribe`
`PubSubClient PubClient(espClient); // for connecting to the server to which I publish`

In setup:
`PubClient.setServer(PubServer, 1883);`
`SubClient.setServer(SubServer, 1883);`
`SubClient.setCallback(callback);`
Under the assumption that only need the callback for processing incoming data.

In loop():
```
    void loop() {
      if (!PubClient.connected()) {
        PubReconnect();
      }
      if (!SubClient.connected()) {
        SubReconnect();
      }
      SubClient.loop();
    }
```
The Pub/SubReconnect() routines do what you might expect and if Pub is first, publishing happens but Sub does not.  No rocket science in this function:
```
void SubReconnect() {
  // Loop until we're reconnected
  Serial.println("SubReconnect called");
  while (!SubClient.connected()) {
    Serial.println("Attempting subscription...");
    // Attempt to connect
    if (SubClient.connect(clientid)) {
      SubClient.subscribe("cheerlightsRGB");
    } else {
      Serial.print("subscription failed, rc=");
      Serial.print(SubClient.state());
      Serial.println(" try again in 5 seconds");
      // Wait 5 seconds before retrying
      delay(5000);
    }
  }
  Serial.print("Subscribed with Client ID: ");
  String strClient_ID = String(clientid);
  Serial.println(strClient_ID);
}
```
When starting, `PubReconnect()` is run and all of the `SerialPrintln` statements print to the serial monitor.  I see nothing from `SubReconnect()`.

When I reverse the order of the Pub and Sub in the `loop()`, I see the output from `SubReconnect()` but not `PubReconnect()` and nothing is published.
My publishing is done once every 5 seconds using `Ticker()`:
```
void Publish()
{
  int memcurr = ESP.getFreeHeap();
  snprintf (msg, 50, "current free heap %ld", memcurr);
  Serial.print("Publishing: ");
  Serial.println(msg);
  if ( PubClient.publish("cheerchristmas", msg) ){
    PubConnected = true;
    Serial.println("theoretically, publish succeeded");
  }else{
    PubConnected = false;
    Serial.println("theoretically, publish failed");
  }
}
```
I get output in the serial monitor that indicates the publish was successful:
```
Connecting to <my secret SSID>
.......
WiFi connected
IP address: 
192.168.1.94
SubReconnect called
Attempting subscription...
Subscribed with Client ID: CheerChristmas-005D31F3
Message arrived [cheerlightsRGB] #FF00FF
Publishing: current free heap 44896
theoretically, publish succeeded
Publishing: current free heap 44392
theoretically, publish succeeded
```
Either I am missing something fundamental or what I want to do is simply not possible.

Suggestions?

**Comment by knolleary** [comment]
Don't reuse the same `espClient` instance - each PubSubClient instance needs its own client object.

**Comment by CaptClaude** [comment]
Why didn't I think of that?  Problem solved. Thanks.
