### ISSUE TITLE
Catch the event when there is no message for the subscribed topic

### ISSUE THREAD

**Issue by Zeni241** [knolleary/pubsubclient#550]
After waking from periodic sleep, my sensor contact broker. If there is some message for the subscribed topic, callback is called, and it act accordingly. This is working fine.
I want the sensor to go to sleep again if there is no message for it. 
**My question is how can I catch the event when there is no message for the subscribed topic so that I could make it to go to sleep?**

**Comment by knolleary** [comment]
You would have to implement a timeout so if no message arrives within, say 10 seconds, then go back to sleep.

There is nothing built into this library to help you do that.

**Comment by Zeni241** [comment]
Thanks a lot man. That **WAS** quick. I am obliged!!
