### ISSUE TITLE
how to connect to a mqtt broker with username and password with arduino

### ISSUE THREAD

**Issue by BeastModz** [knolleary/pubsubclient#561]
i busy with a small project where i want to read out some data and send it to a mqtt broker. i found some example codes but they dont use a username and password
i need some thing like this

mqttServer = "******";

mqttPort = 1883;

mqttUser = "******";

mqttPassword = "***";

it would be great is somebody knows any examples.

**Comment by knolleary** [comment]
Hi @BeastModz 

the library provides the `mqtt_auth` example that shows how to provide a username and password with the `connect` call.

https://github.com/knolleary/pubsubclient/blob/master/examples/mqtt_auth/mqtt_auth.ino

**Comment by BeastModz** [comment]
> Hi @BeastModz
> 
> the library provides the `mqtt_auth` example that shows how to provide a username and password with the `connect` call.
> 
> https://github.com/knolleary/pubsubclient/blob/master/examples/mqtt_auth/mqtt_auth.ino

Thank's for the quick reply i will check it out thank you have a nice  day
