### ISSUE TITLE
Request: set hostname in connect method rather than constructor?

### ISSUE THREAD

**Issue by davidmonro** [knolleary/pubsubclient#58]
I've written some code which stores the DNS name in EEPROM, and then copies it from the EEPROM to RAM at runtime (so I don't have to recompile to change the hostname, just reflash the EEPROM). However the PubSubClient expects the hostname in the constructor, and I don't think (correct me if I am wrong) that arduino supports dynamic instantiation using new()?

Currently passing the constructor a pointer to the array that I fill in later from the EEPROM works, but only because the class just maintains a pointer to the array I've passed it; if it happened to make a copy of it internally my code wouldn't work. And relying on the internal implementation like this is horribly inelegant :)

Would it be possible to add a constructor variant which doesn't take the hostname and port as arguments, and then either provide a variant of the connect() method which takes those arguments, or alternatively a separate method to set them?

(I also store the ClientID in the EEPROM, but that is supplied to the connect() method and so doesn't suffer from the same issue).

Cheers

David

**Comment by knolleary** [comment]
Added a setServer function that allows you to set the domain/IP/port after the constructor is called.

New release coming this week (finally!)
