### ISSUE TITLE
Can't connect with String().c_str()

### ISSUE THREAD

**Issue by davrodfer** [knolleary/pubsubclient#584]
I have a program that connect to mosquitto with auth. If I put the credential as literals in code, the program work correctly, but if I put the credentials inside a String that is readed from a file and try to convert to c_str() the connect fail with state -2

--- this work ---
```
String host="mqtt.example.dev";
String port="2122";
mqttclient.setServer( host.c_str() , port.toInt());
if (!mqttclient.connect("id", "user","password)) {
  Serial.print("failed with state ");
  Serial.println(mqttclient.state());
}
```

-- this don't work, never get connection ---
```
String host="mqtt.example.dev";
String port="2122";
String user="anyuser";
String pass="anormalpassword";

mqttclient.setServer( host.c_str() , port.toInt());
if (!mqttclient.connect("id", user.c_str(),pass.c_str())) {
  Serial.print("failed with state ");
  Serial.println(mqttclient.state());
}
```

**Comment by GJGits** [comment]
Hi I'm facing the same problem with mqtt broker ip, how did you solve it?

**Comment by saqibmanan329** [comment]
Hello, I am facing the same problem did anyone of you got out of it successfully. Kindly help me out also?
@davrodfer @GJGits 
Thank you

**Comment by pdt590** [comment]
Same issue

**Comment by ppc52776** [comment]
Same issue, thanks for let me know `c_str()` problem!!

**Comment by lothian-craftworks** [comment]
I ran into this same issue and was banging my head against the desk as to why it doesn't work.

You are going to want to do something like this, and it should work:
`const char* brokerCString = strdup(broker.c_str());`

Hope this helps
