### ISSUE TITLE
ESP32 + Paho + Mosquitto Issue

### ISSUE THREAD

**Issue by imaniroman** [knolleary/pubsubclient#585]
Hello Everyone,
I am using an ESP32 with PubSubClient and Paho and Mosquitto (1.5.8) running on a Raspi 3 on Ubuntu. ESP32 and Raspi are on the same local network . PubSubClient's MQTT_MAX_PACKET_SIZE has been set to 256 bytes. Code used to work fine before but not anymore.

Error is "Attempting MQTT connection...failed, rc=-4 try again in 5 seconds"

The code running on my ESP32 is below. Setup is 2 Pro mins connected to IMUs over UART/Serial and a Temp sensor.

`#include <Wire.h>
#include <DallasTemperature.h>
#include <OneWire.h>
#include <WiFi.h>
#include <PubSubClient.h>

const char* ssid = "Me";
const char* password = "";

const char* mqtt_server = "192.168.1.124"; //ip address of the mqtt server

const char* mqtt_topic = "/hms/data";

#define ONE_WIRE_BUS 18 // D18 ESP32, use 4.7K pull up

WiFiClient espClient;

PubSubClient client(espClient);

void MQTT_connect();

OneWire oneWire(ONE_WIRE_BUS);
DallasTemperature temperatureSensor(&oneWire);
float temperature = 0.0F;

unsigned long prevTime = 0;

HardwareSerial proMiniIMU1(2); // RX1:23, TX1:22 on ESP32. 
                              // Edit the file 'HardwareSerial.cpp 'like in video.
    
HardwareSerial proMiniIMU2(2); // RX2:16, TX2:17 on ESP32. This is by default.

String imu1Data;
String imu2Data;

int BPM = -1;

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  proMiniIMU1.begin(9600);
  proMiniIMU2.begin(9600);

  connectWifi();
  client.setServer(mqtt_server, 1883);

  // temperatureSensor.begin();
}

void loop() {
  // put your main code here, to run repeatedly:
  if (!client.connected()) {
    reconnect();
  }
  client.loop();

  //temperatureSensor.requestTemperatures();
  //temperature = temperatureSensor.getTempCByIndex(0);

  if (millis() - prevTime > 1000) {
    //  publishData();

    displayData();

    prevTime = millis();

  }
}

void publishData() {

  char msg[200];

  sprintf(msg, "%.2f,%d,%s,%s",temperature, BPM,imu1Data,imu2Data);

  client.publish(mqtt_topic, msg);
  //Serial.println(msg);
}

void displayData() {
  Serial.println();
  Serial.println();
  Serial.print("Temperature = ");
  Serial.println(temperature);
  Serial.println();
  Serial.println("-----------------------[ IMU-1 ]-----------------------]");
  Serial.print(imu1Data);
  Serial.println();
  Serial.println("-----------------------[ IMU-2 ]-----------------------]");
  Serial.print(imu2Data);
  Serial.println();
}

void readIMU1() {

  proMiniIMU1.println("imu");

  if(proMiniIMU1.available())
  {
    imu1Data = proMiniIMU1.readStringUntil('\n');
    imu1Data.trim();
  }
}

void readIMU2() {

  proMiniIMU2.println("imu");

  if(proMiniIMU2.available())
  {
    imu2Data = proMiniIMU2.readStringUntil('\n');
    imu2Data.trim();
  }
}

void connectWifi() {

  // Connect to WiFi access point.
  Serial.println(); Serial.println();
  Serial.print("[*] Connecting to ");
  Serial.println(ssid);

  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
    yield();
  }
  Serial.println();

  Serial.println("[+] WiFi connected");
  Serial.print("    >> IP address : ");
  Serial.println(WiFi.localIP());
}

void reconnect() {
  // Loop until we're reconnected
  while (!client.connected()) {
    Serial.print("Attempting MQTT connection...");
    // Attempt to connect
    if (client.connect("ESP32_HMS")) {
      Serial.println("connected");
      // Subscribe
      //client.subscribe("Master/commands");
    } else {
      Serial.print("failed, rc=");
      Serial.print(client.state());
      Serial.println(" try again in 5 seconds");
      // Wait 5 seconds before retrying
      delay(5000);
    }
    yield();
  }
}`

**Using this python script on the Raspi to receive mqtt packets and save to CSV file**

`import paho.mqtt.client as mqtt
import json
import time
import csv
import os
from datetime import datetime

host_name = "localhost"
topic = "/hms/data"

def store_data(msg):
    file_path = "./hms-data.csv"

    csv_title = ["Timestamp","Temperature","BPM","IMU1-Accel-X","IMU1-Accel-Y","IMU1-Accel-Z",
                  "IMU1-Gyro-X","IMU1-Gyro-Y","IMU1-Gyro-Z","IMU1-Mag-X","IMU1-Mag-Y","IMU1-Mag-Z",
                  "IMU2-Accel-X","IMU2-Accel-Y","IMU2-Accel-Z","IMU2-Gyro-X","IMU2-Gyro-Y","IMU2-Gyro-Z",
                  "IMU2-Mag-X","IMU2-Mag-Y","IMU2-Mag-Z"]

    msg = [float(x.strip()) for x in msg.split(",")]
    msg.insert(0, str(datetime.now()))

    if os.path.isfile(file_path):
        with open(file_path, "a") as fp:
            csv_writer = csv.writer(fp, delimiter=',')
            csv_writer.writerow(msg)
    else:
        with open(file_path, "w+") as fp:
            csv_writer = csv.writer(fp, delimiter=',')
            csv_writer.writerow(csv_title)
            csv_writer.writerow(msg)

def on_message(client, userdata, message):
    print("message received ", str(message.payload.decode("utf-8")))
    print("message topic = ", message.topic)
    print("message qos = ", message.qos)
    print("message retain flag = ", message.retain)
    msg = str(message.payload.decode("utf-8")).strip()
    if(message.topic == "/hms/data"):
        store_data(msg)

mqtt_client = mqtt.Client("omega31")
mqtt_client.on_message = on_message

broker = mqtt_client.connect(host_name)

print("Subscribing to topic : {}".format(topic))
while(True):
    mqtt_client.loop_start()

    mqtt_client.subscribe(topic)

    mqtt_client.loop_stop()

`

**Please help as my thesis is due soon. Thank you!**

**Comment by eos1d3** [comment]
Try to set your server address in IPAdress, but not a string.

> server : the address of the server (IPAddress, uint8_t[] or const char[])

**Comment by imaniroman** [comment]
Turns out my Wifi hot stop and my Pi's wifi module was dead!!! Got it all running with a new pi!
