### ISSUE TITLE
-m message TYPE issue

### ISSUE THREAD

**Issue by derrgis** [knolleary/pubsubclient#602]
Hi there,

I'm using a MQTT Mosquitto broker on Ubuntu with ESP (arduino) Clients. 
The Arduino part uses PubSubClient lib. to get the payload.
I only send digits from my keyboard to the ESP.

It seems I only get ASCII values in place of the digits sent.

For example: if the key pressed is 5 the client receives 53.
Broker sending : mosquitto_pub -t my_topic -m 5 (or even "5")
Arduino Client receives : 53

I wonder if the Mosquitto MQTT treats digits as ASCII values or if the issue comes from my Arduino sketch.

Any idea is welcome.
Thank you for reading.

**Comment by knolleary** [comment]
Hi - this is a question about the mosquitto tools, not this library.

I have also just answered this same question on the MQTT mailing list.

**Comment by derrgis** [comment]
Yes, we received, thx.
And bravo for the PubSubClient :)
