### ISSUE TITLE
get hostname as topic subscription

### ISSUE THREAD

**Issue by derrgis** [knolleary/pubsubclient#610]
Hi there,
Hope to be in the right place for my question.

I'm trying to manage wildcards in a subscription.
I'm stuck with basic coding.

this works :
`client.subscribe(WiFi.hostname().c_str());`

But I want be able to select subtopics , unfortunat get compile errors with this
`client.subscribe(WiFi.hostname().c_str()/#);`

the callback should be something like:
`if (strcmp(topic, WiFi.hostname().c_str()/my_topic1) == 0) { //do something ...;}
else if (strcmp(topic, WiFi.hostname().c_str()/my_topic2) == 0) { //do something else...;}
...`

How do I use wildcards in the code syntax to select the relevant payload?

Hope to be somewhat clear.

**Comment by knolleary** [comment]
Hi - suggest you read this tutorial on joining strings together: https://www.arduino.cc/en/Tutorial/StringAdditionOperator

**Comment by derrgis** [comment]
Okay thank you , it helps to concatenete the subtopic path for subscription.
However I'm not able to subscribe to the variable with the /# added.

```
String clientID = WiFi.hostname().c_str();
char * defName = (char*)clientID.c_str();
char * defNameSharp = (char*)clientID.c_str() + '/' + '#';
```

This do not compile
```
 client.subscribe(defNameSharp.c_str());
 client.subscribe(defNameSharp);
```

So what is the way to manage wildcard subscription et callback function?
Is there some examples?

-
Mosquitto broker / Ubuntu 18.04
PubSubClient / ESP01S

**Comment by derrgis** [comment]
Okay thank you , it helps to concatenete the subtopic path for subscription.
I've done this:
'
String clientID = WiFi.hostname().c_str();
char * defName = (char*)clientID.c_str();

However this not seems good :
`client.subscribe(defName + '/' +'#');`

And then ...  how to get the payload on subtopic "pattern"? 
'
void callback(char* topic, byte* payload, unsigned int length){
  if (strcmp(topic, defName + '/' + "pattern" ) == 0) {
  my_var = (byte)payload[i];//do something
  }
}

**Comment by knolleary** [comment]
I would expect the following to work:

```
String clientID = WiFi.hostname(); // Dont call c_str at this point
String topicName = clientID+"/#";
client.subscribe(topicName.c_str());
```

And then in your callback. You will need to ensure `clientID` is declared outside of your `setup`/`loop` functions so it will be visible in the callback function:

```
void callback(char* topic, byte* payload, unsigned int length){
   if (strcmp(topic,(clientID+"/pattern").c_str()) == 0) {

   }
}
```
```

**Comment by derrgis** [comment]
Wow You're the one !
Indeed the right use of quotation marks does the working difference :)
Also for use of .c_str
Thanks for your help and tricks, saving 1 more day ...
Best to PubSubClient. Have a good day ;-)
