### ISSUE TITLE
client.connected() returns false

### ISSUE THREAD

**Issue by chpoklv** [knolleary/pubsubclient#611]
I guess _client.connected()_ returns false every time on the loop, can you help me find out why is this happen? 

_Message arrived [pn1/co2] 752_ happens every time despite actual mqtt message is published on broker only every 10 minutes.

Serial monitor in my case reconnects every second and spams the same old mqtt message:

```
Connecting to xxxxxxxx
.
WiFi connected
IP address: 
192.168.0.3
reconnecting
Attempting MQTT connection...
connected
subscribing..
Message arrived [pn1/co2] 752
reconnecting
Attempting MQTT connection...
connected
subscribing..
Message arrived [pn1/co2] 752
reconnecting
Attempting MQTT connection...
```

used code: 

```
#include <ESP8266WiFi.h>
#include <PubSubClient.h>

// Update these with values suitable for your network.

const char* ssid = "xxxxxxx";
const char* password = "xxxxxxxx";
const char* mqtt_server = "m21.cloudmqtt.com";
const int mqttPort = 13083;                       //MQTT broker port
const char* mqttUser = "xxxxxxxx";                //MQTT broker username
const char* mqttPassword = "xxxxxxxx";        //MQTT broker user password

#define SUBSCRIBED_TOPIC "pn1/co2"                  //subscribe to this topic

WiFiClient espClient;
PubSubClient client(espClient);
long lastMsg = 0;
char msg[50];
int value = 0;




void setup() 
{
  pinMode(BUILTIN_LED, OUTPUT);     // Initialize the BUILTIN_LED pin as an output
  Serial.begin(115200);
  setup_wifi();
  client.setServer(mqtt_server, mqttPort);
  client.setCallback(callback);
}


void setup_wifi() 
{
  delay(10);
  // We start by connecting to a WiFi network
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);

  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());
}


void callback(char* topic, byte* payload, unsigned int length) 
{
  Serial.print("Message arrived [");
  Serial.print(topic);
  Serial.print("] ");
  for (int i = 0; i < length; i++) {
    Serial.print((char)payload[i]);
  }
  Serial.println();
 

}


void reconnect() 
{
    Serial.println("Attempting MQTT connection...");
    // Attempt to connect
    if (client.connect("ESP8266Client", mqttUser, mqttPassword )) 
    {
      Serial.println("connected");
      // Once connected, publish an announcement...
//      client.publish("outTopic", "hello world");
      // ... and resubscribe
          Serial.println("subscribing..");
      client.subscribe(SUBSCRIBED_TOPIC);
    }
    else 
    {
      Serial.print("failed, rc=");
      Serial.print(client.state());
      Serial.println(" try again in 5 seconds");
      // Wait 5 seconds before retrying
      delay(5000);
    }
}

    

void loop() 
{
  if (!client.connected()) {
    Serial.println("reconnecting");
    reconnect();
  }
  client.loop();
}
```

**Comment by JacobChrist** [comment]
Is there more than one client name "ESP8266Client" connecting to the broker?

try:

client.connect("ESP8266Client2", mqttUser, mqttPassword ))

**Comment by chpoklv** [comment]
Thank you so much, I was using the same client name for sensor, my mistake.

**Comment by Aiversity** [comment]
Thanks For The Solution. I was automating my shop and previously was using a nodemcu with the same client id. Then as esp32s had more pins, I used it with the same client id. I read your solution and changed the client id and it works now!!!
I have a robotics channel.
YouTube Link: https://www.youtube.com/channel/UCa1hcqb6eUjeNae44DLP1lA
Website(still developing): http://aiversity.com/

**Comment by dusena** [comment]
Uma sugestão também, que ao invés dizer um id "hardcoded", podes usar uma variável qualquer. Geralmente de uso mais comum, o MacAdress do dispositivo.

**Comment by DougLeary** [comment]
Here it is 4 years later and I'm having the same problem with this code - client.connected() always returns false. But in my case the client name is not a duplicate, it is generated "Windy" + 4 random hex characters each time. In the success clause of client.connect() I changed Serial.println("connected") to:

      Serial.print(clientId);
      delay(1000);
      if (client.connected()) {
        Serial.println(" connected");
      } else {
        Serial.println(" NOT connected");
      } 

What I see is this:

Attempting MQTT connection...Windy3fb1 NOT connected
Attempting MQTT connection...Windyf5e8 NOT connected
Attempting MQTT connection...Windy7bd6 NOT connected . . .
