### ISSUE TITLE
Large payloads with Arduino Wifi Shield does not work

### ISSUE THREAD

**Issue by wollud1969** [knolleary/pubsubclient#62]
I ran into the problem that messages I published via PubSubClient using an Arduino Mega and an Arduino Wifi Shield which are large than about 80 octets did not appear at the broker. I found by googling that it is not possible to send more than 90 octets using the Wifi Shield and the related library at once: http://mssystems.emscom.net/helpdesk/knowledgebase.php?article=51
And that exactly what I experienced too: I increased the buffer size one by one and at 90 octets it stopped and the WiFi library lost the connection.

Furthermore I found that the WiFi library and the shield handles a `stop()` on a fresh client socket somewhat strange: The socket can not be open or will be closed immediately after opening. Since at least in my case I always give a fresh `WiFiClient` into the `PubSubClient` I removed the `connected()` call from the top of the `connect` method in PubSubClient.cpp. 

Since PubSubClient works as it is with the Ethernet Shield I suppose a fix in the WiFi library would be a better idea but I put a workaround into PubSubClient.cpp. Here is my diff against release 1.9.1. Maybe - as long as the WiFi library is not fixed - this fix/workaround should depend on the actual type of Client but this distinction of cases is not included in the patch. Will free to use it if you like.

```
wn@baikonur:~/Documents/workspace/WiModbusGateway/MQTT$ diff PubSubClient.cpp ~/Downloads/pubsubclient-1.9.1/PubSubClient/PubSubClient.cpp 
42,43c42
< //   if (!connected()) {
<    if (true) {
---
>    if (!connected()) {
217d215
<       // Serial.print("pub len: "); Serial.println(length-5);
219,220d216
<    } else {
<      // Serial.println("connection lost");
290,308c286
< 
< //   Serial.print("write len: "); Serial.println(length+1+llen);
< //   size_t olen = length + 1 + llen;
< //   rc = _client->write(buf+(4-llen),length+1+llen);
< 
<    const size_t SEND_AT_ONCE = 64;
<    size_t remains = length + 1 + llen;
<    // Serial.print("write len: "); Serial.println(remains);
<    const uint8_t *writebuf = buf + (4 - llen);
<    bool result = true;
<    while ((remains > 0) && result) {
<      size_t actuallySendChars = (remains > SEND_AT_ONCE) ? SEND_AT_ONCE : remains;
<      // Serial.print("tbs: "); Serial.println(actuallySendChars);
<      size_t sentChars = _client->write(writebuf, actuallySendChars);
<      result = sentChars == actuallySendChars;
<      remains -= sentChars;
<      writebuf += sentChars;
<    }
< 
---
>    rc = _client->write(buf+(4-llen),length+1+llen);
311,312c289
< //   return (rc == 1+llen+length);
<    return result;
---
>    return (rc == 1+llen+length);
357,362c334
<    //Serial.print("rc: "); Serial.println(rc);
<    if (!rc) {
<      //Serial.println("would stop");
<      _client->stop();
<      // while (true);
<    }
---
>    if (!rc) _client->stop();
wn@baikonur:~/Documents/workspace/WiModbusGateway/MQTT$ 
```

**Comment by ravikasyap1717** [comment]
Dear Sir,
I am also getting problem to publish the payload character more than 80. I have 140 character and trying to publish.It result is publish fail.How can i fix this issue.

**Comment by knolleary** [comment]
@ravikasyap1717 as you're trying to publish more than 128 bytes, have you changed the value of MQTT_MAX_PACKET_SIZE in PubSubClient.h?

https://github.com/knolleary/pubsubclient#limitations

**Comment by ravikasyap1717** [comment]
Dear Sir,
I am working with arduino wifi shield with arduino uno.


#include <SPI.h>
#include <WiFi.h>
#include <PubSubClient.h>

char ssid[] = "Connectify-me";      // your network SSID (name)
char pass[] = "test4444";   // your network password
int keyIndex = 0;                 // your network key Index number (needed only for WEP)
int status = WL_IDLE_STATUS;

byte mac[]    = {  0x78, 0xC4, 0x0E, 0x02, 0x99, 0xD5 };
char macstr[]="wifishield";

IPAddress server(54, 191, 2, 249);
//IPAddress server(192, 168, 0, 105);

WiFiClient wifiClient;
PubSubClient client(wifiClient);

void callback(char* topic, byte* payload, unsigned int length) {
  Serial.print("Message arrived [");
  Serial.print(topic);
  Serial.print("] ");
  for (int i=0;i<length;i++) {
    Serial.print((char)payload[i]);
  }
  Serial.println();
}
void reconnect() {
  // Loop until we're reconnected
  while (!client.connected()) {
    Serial.print("Attempting MQTT connection...");
    // Attempt to connect
    if (client.connect("wifishield")) {
      Serial.println("connected");
      // Once connected, publish an announcement...
      client.publish("ayaan","hello world");
      // ... and resubscribe
      client.subscribe("ayaan");
    } else {
      Serial.print("failed, rc= ");
      Serial.print(client.state());
      Serial.println(" try again in 5 seconds");
      // Wait 5 seconds before retrying
      delay(5000);
    }
  }
}




void setup()
{
  Serial.begin(9600);
  wifi_check();

  
   client.setServer(server, 5001);
   client.setCallback(callback);

}

void loop()
{
    if (!client.connected()) {
      reconnect();
  }
  client.loop();
}

void wifi_check()
{
 // check for the presence of the shield:
  if (WiFi.status() == WL_NO_SHIELD) {
    Serial.println("WiFi shield not present");
    // don't continue:
    while (true);
  }

  String fv = WiFi.firmwareVersion();
  if (fv != "1.1.0") {
    Serial.println("Please upgrade the firmware");
  }

  // attempt to connect to Wifi network:
  while (status != WL_CONNECTED) {
    Serial.print("Attempting to connect to SSID: ");
    Serial.println(ssid);
    // Connect to WPA/WPA2 network. Change this line if using open or WEP network:
    status = WiFi.begin(ssid, pass);

    // wait 10 seconds for connection:
    delay(100);
  }
}

and following error is coming.....
rc = 1 ,i changed the mqtt version from header file but same result.
I tried on different version on arduino and result is rc=-2. I tried previous with this header it was working but charcter length is les than 80. please help me to find the issue.

/*
 PubSubClient.h - A simple client for MQTT.
  Nicholas O'Leary
  http://knolleary.net
*/

#ifndef PubSubClient_h
#define PubSubClient_h

#include <Arduino.h>
#include "Client.h"
#include "Stream.h"

// MQTT_MAX_PACKET_SIZE : Maximum packet size
#define MQTT_MAX_PACKET_SIZE 500

// MQTT_KEEPALIVE : keepAlive interval in Seconds
#define MQTT_KEEPALIVE 15

#define MQTTPROTOCOLVERSION 3
#define MQTTCONNECT     1 << 4  // Client request to connect to Server
#define MQTTCONNACK     2 << 4  // Connect Acknowledgment
#define MQTTPUBLISH     3 << 4  // Publish message
#define MQTTPUBACK      4 << 4  // Publish Acknowledgment
#define MQTTPUBREC      5 << 4  // Publish Received (assured delivery part 1)
#define MQTTPUBREL      6 << 4  // Publish Release (assured delivery part 2)
#define MQTTPUBCOMP     7 << 4  // Publish Complete (assured delivery part 3)
#define MQTTSUBSCRIBE   8 << 4  // Client Subscribe request
#define MQTTSUBACK      9 << 4  // Subscribe Acknowledgment
#define MQTTUNSUBSCRIBE 10 << 4 // Client Unsubscribe request
#define MQTTUNSUBACK    11 << 4 // Unsubscribe Acknowledgment
#define MQTTPINGREQ     12 << 4 // PING Request
#define MQTTPINGRESP    13 << 4 // PING Response
#define MQTTDISCONNECT  14 << 4 // Client is Disconnecting
#define MQTTReserved    15 << 4 // Reserved

#define MQTTQOS0        (0 << 1)
#define MQTTQOS1        (1 << 1)
#define MQTTQOS2        (2 << 1)

class PubSubClient {
private:
   Client* _client;
   uint8_t buffer[MQTT_MAX_PACKET_SIZE];
   uint16_t nextMsgId;
   unsigned long lastOutActivity;
   unsigned long lastInActivity;
   bool pingOutstanding;
   void (*callback)(char*,uint8_t*,unsigned int);
   uint16_t readPacket(uint8_t*);
   uint8_t readByte();
   boolean write(uint8_t header, uint8_t* buf, uint16_t length);
   uint16_t writeString(char* string, uint8_t* buf, uint16_t pos);
   uint8_t *ip;
   char* domain;
   uint16_t port;
   Stream* stream;
public:
   PubSubClient();
   PubSubClient(uint8_t *, uint16_t, void(*)(char*,uint8_t*,unsigned int),Client& client);
   PubSubClient(uint8_t *, uint16_t, void(*)(char*,uint8_t*,unsigned int),Client& client, Stream&);
   PubSubClient(char*, uint16_t, void(*)(char*,uint8_t*,unsigned int),Client& client);
   PubSubClient(char*, uint16_t, void(*)(char*,uint8_t*,unsigned int),Client& client, Stream&);
   boolean connect(char *);
   boolean connect(char *, char *, char *);
   boolean connect(char *, char *, uint8_t, uint8_t, char *);
   boolean connect(char *, char *, char *, char *, uint8_t, uint8_t, char*);
   void disconnect();
   boolean publish(char *, char *);
   boolean publish(char *, uint8_t *, unsigned int);
   boolean publish(char *, uint8_t *, unsigned int, boolean);
   boolean publish_P(char *, uint8_t PROGMEM *, unsigned int, boolean);
   boolean subscribe(char *);
   boolean subscribe(char *, uint8_t qos);
   boolean unsubscribe(char *);
   boolean loop();
   boolean connected();
};


#endif

**Comment by ravikasyap1717** [comment]
the function client connect("wifi") is not working.What will be cliend id.

**Comment by ravikasyap1717** [comment]
Dear sir,
I using arduino wifi shield with Arduino Leonard and Compiler version is 1.6.6.
I use header file Pub client 2.0,but still problem it not publish more than 80 charcter.
I have to use 
const char apikey[] ="gGU2mN2hgMUCZN72CgMv1EP1hHtdyZ";
const char feedid[] ="BBMJ1viVca3cqi9lt/ObfjoL9qeGNZBHDtu"; and concating apikey,feedid and message to transmit using strcat

memset(str,'\0',200);
  strcat(str,"apikey:");
  strcat(str,apikey);
  strcat(str,",feedid:");
  strcat(str,feedid);
strcat(str,"Light,10|V1,11|V2,15|V3,17");

 int len= strlen(str);
  Serial.println(len);

Then i have to publish the message...
 boolean pubresult = client.publish("Ravi",str);
 
Result : Pubresult fail and not publish the message when i remove feedid,length is short and publish.
I Changed the header file as you periviously told.I checked the result in eclipse.paho.mqtt.utility-1.0.0(for simulation).
![capture1](https://cloud.githubusercontent.com/assets/14104387/9681620/09422df8-531d-11e5-8222-29a1c03f3e2f.PNG)

Have to any change in Pubclient.cpp .
Let me know why that problem is coming and how i can fix it.

Thanks !

**Comment by knolleary** [comment]
@ravikasyap1717 if you are hitting the same 80 character limit that was mentioned in the original issue, that was a restriction of the WifiShield, not an issue with this library. Any fix would be bespoke to the wifishield, with any calls to _client->write changed to break up any call > 80 characters long.

**Comment by ravikasyap1717** [comment]
Thanks For reply sir.
using Wfi Shield is not possible to publish more than 80 concate character ??.
have you idea of any wifi shield which donot have that limitation.

**Comment by wollud1969** [comment]
It is possible, with an ugly workaround. The workaround is described here: http://a385e-5.de/?p=588 <http://a385e-5.de/?p=588>

Cheers, Wolfgang

**Comment by ravikasyap1717** [comment]
Thanks Wolfgang.
But that patch in not  under stable. What that mean c or d (42,43c42,219,220d216).
In which line i have to change the code.
can i use that libarary,it will work???

https://github.com/knolleary/pubsubclient/blob/545d0045f984736eea96787845e2e35b1df8dae4/PubSubClient/src/PubSubClient.cpp

**Comment by knolleary** [comment]
I've found a WifiShield sat in the back of my cupboard (knew I had one somewhere...), and can recreate the issues described here.

I'm working on a couple fixes for the library, one of which will be a #define for the maximum transfer size the library should use - by default it'll be 'transfer everything', but you'll be able to set it to a smaller number as and when needed for particular hardware. Essentially what the example code in the original issue did with the `SEND_AT_ONCE` constant.

**Comment by knolleary** [comment]
@ravikasyap1717 just pushed the changes to the repository, will do a release after some more testing.

If you want to try it:

1. grab the latest PubSubClient.cpp/.h
2. in PubSubClient.h, uncomment the `MQTT_MAX_TRANSFER_SIZE` line

**Comment by knolleary** [comment]
Version 2.1 released - all should be working now
