### ISSUE TITLE
First message received is always "21"

### ISSUE THREAD

**Issue by JacobChrist** [knolleary/pubsubclient#620]
I'm using a slightly modified version the mqtt_basic sketch with version 2.7 of PubSubClient.

Connecting to test.mosquitto.org
Connection name of "ec6edffd-0":
Subscribing to: client.subscribe("outTopic");

While testing someone publishing to outTopic about once per second the message "hello world #XXXXXXXX", however the first message received is always "21" and this seems to be related to PubSubClient.

**Comment by JacobChrist** [comment]
This also happens when I use mosquitto to subscribe to this topic from Linux so it may have something to do with the broker they are currently running.

**Comment by knolleary** [comment]
Sounds like the topic has a retained message on it.

**Comment by JacobChrist** [comment]
Agreed, I didn't understand retains.  I was able to change it an the new message is now returned when connecting.
