### ISSUE TITLE
type mismatch in write method

### ISSUE THREAD

**Issue by wollud1969** [knolleary/pubsubclient#63]
I increased MQTT_MAX_PACKET_SIZE to 1024 and got issues with large payloads. I found: 

```
boolean PubSubClient::write(uint8_t header, uint8_t* buf, uint16_t length) {
   uint8_t lenBuf[4];
   uint8_t llen = 0;
   uint8_t digit;
   uint8_t pos = 0;
   uint8_t rc;
   uint8_t len = length;
```

```length```of type ```uint16_t``` is assigned to ```len```of type ```uint8_t```. Is this a bug or a feature?
Changing the type of ```len``` to ```uint16_t``` solved at least forehand my problem. Or have I got a new problem now I haven't discovered so far?

Thanks and Cheers, Wolfgang

**Comment by keyangithub** [comment]
Additional info:
/* Maximum packet size can be
 ((Maximum Tx(WiFi) buffer - other Tx data)- MQTT header and variable length field) = ((1520-166)-5) = 1349 */
My WiFi Tx buffer was 1520 bytes and WiFi header size was 166
Also it would be correct to make the following change in 'write ' function:
'uint8_t rc;' -> 'uint16_t rc;'
