### ISSUE TITLE
Publishing to AWS IoT Core update topic not working

### ISSUE THREAD

**Issue by telliottosceola** [knolleary/pubsubclient#633]
Hi everyone,

I've been using the PubSubClient successfully for several projects so far and I thought AWS wouldn't be a big deal either.  I got a TLS connection established with PubSub and thought all was on the up and up, however AWS has topics which you must publish to in order to update the thing shadow that begin with a $ such as `$aws/things/thingName/shadow/update`. I am having an issue publishing to that topic which causes the client to disconnect.  A call to publish returns true but the MQTT connection drops.  Also appears the publish never makes it to AWS.  Any insight on this?  I am able to publish to AWS using MQTT.fx but the pubsub client disconnects every time I try to publish to the topic.

**Comment by telliottosceola** [comment]
PubSub client state prior to publish to `$aws/things/thingName/shadow/update` is 0.  State of PubSub client right after publish is 0 as well.  However a check to PubSub client.connected() returns false and checking the state after that results in a -3.  This happens each time an attempt is made to publish to the topic.

**Comment by knolleary** [comment]
How large is the payload you are trying to publish? If the length of payload and topic is >128 bytes then have you also changed the value of MQTT_MAX_PACKET_SIZE to accommodate that?

**Comment by telliottosceola** [comment]
Hi @knolleary 

First off thank you for this fantastic library.  I've used it a lot and it's awesome.

Yes, I have modified MQTT_MAX_PACKET_SIZE to 512.  The packet I'm sending is no where near that though, it's around 197.

I should also mention this is definitely not a connection problem or a TLS issue with connecting to AWS as I am able to publish to topic  `things/thingName/shadow/update`. The only time I seem to run into this problem is when a $ precedes the topic.

**Comment by telliottosceola** [comment]
If there is any information I can provide so you can replicate the issue please let me know.  I am running on an ESP32.

**Comment by knolleary** [comment]
It certainly sounds like AWS is kicking you off when you try publishing to that topic. You say you can publish using another client - is that to exactly the same topic as you are trying here?

**Comment by telliottosceola** [comment]
Yes, I am able to publish to the same topic using the same credentials from MQTT.fx no problem and the shadow document updates on AWS so the publish is actually going through.  It seems specific to the PubSubClient for one reason or another.

I will try to put together a straight forward simple test that you could quickly implement and see for yourself.  Do you have an ESP32 handy by chance?  Also would it be simplest to publish to a local Mosquitto broker?  I'm going to try writing to the Mosquitto broker today to ensure this isn's something on the AWS side for some strange reason.

**Comment by telliottosceola** [comment]
Please disregard this for now.  It is an issue with AWS permissions.  Apparently my policy document for the AWS thing does not grant permissions for updating the thing shadow as I thought it should.  I'll update back here once I figure out the problem just in case anyone in the future runs into this issue.  Closing issue for now since it is not an issue with the PubSubClient.  I apologize for the wasted time @knolleary

**Comment by marcoavaccaro** [comment]
Hello guys, i'm trying to connect to AWS wich request:

wifiClient.loadCACert(ca);
wifiClient.loadCertificate(client_cert);
wifiClient.loadPrivateKey(client_key);

Via wifi i can do it with no problems. But the ethernet library present on arduino do not have these 3 classes above.

Someone know how to connect to AWS via ethernet shield using ESP32?

**Comment by telliottosceola** [comment]
If you figure out a way to do that let me know.  I went down that rabbit hole for a couple weeks and never got anywhere.  Currently to my knowledge there is no simple way to do this on an ESP32.  PubSub allows you to pass a WiFiClientSecure client to it which handles all the TLS encryption.  Unfortunately there is no EthernetClientSecure and extrapolating the required resources from WiFiClientSecure is near impossible since it is deeply rooted in the low level wifi interface drivers.
