### ISSUE TITLE
client.publish needs a delay(100) to work?

### ISSUE THREAD

**Issue by SteveRMann** [knolleary/pubsubclient#635]
Just wondering...

I have a Wemos D1 Mini with a ds18B22 temperature sensor and a capacitive moisture sensor.  But that's besides the point.  All of my code is executed in setup(), and the last thing I do in the setup() is to put the Wemos to sleep with ESP.deepSleep().

Everything works, but in order to get the client.publish() lines to execute I had to add a delay(500).  Is there a better way to test for for the client.publish() complete?  The delay is not a problem because the sleep is for 60 minutes, and timing isn't critical.

Here is the section of the code at the end of the setup() function.  Any tips would be appreciated.

```

  client.publish(temperatureTopic, String(fahrenheit).c_str());   // Publish temperature on temperature_topic
  int val = analogRead(0);                                        // Read the moisture sensor
  client.publish(moistureTopic, String(val).c_str());             // Publish moisture value on moisture_topic
  delay(100);                                                     // Publish never completes without a delay


  // ---------- Sleep ----------
  // Connect D0 to RST to wake up
  pinMode(D0, WAKEUP_PULLUP);
  digitalWrite(D2, LOW);                                          // Turn off LED- We're sleeping.
  Serial.print(F("Sleeping, "));
  Serial.print(sleepSeconds);
  Serial.println(F(" seconds."));
  ESP.deepSleep(sleepSeconds * 1000000);
}

```

**Comment by zvone141** [comment]
Hello,

you can look at publish returns. False means something went wrong and true means everything is OK. 

the code with changes, please try it:

``` c++
  client.publish(temperatureTopic, String(fahrenheit).c_str());   // Publish temperature on temperature_topic
  int val = analogRead(0);                                        // Read the moisture sensor
  bool rs = client.publish(moistureTopic, String(val).c_str());             // Publish moisture value on moisture_topic
  if(rs == true){                                                     

    // ---------- Sleep ----------
    // Connect D0 to RST to wake up
    pinMode(D0, WAKEUP_PULLUP);
    digitalWrite(D2, LOW);                                          // Turn off LED- We're sleeping.
    Serial.print(F("Sleeping, "));
    Serial.print(sleepSeconds);
    Serial.println(F(" seconds."));
    ESP.deepSleep(sleepSeconds * 1000000);
  }
  else{
    //Try again
  }
```

**Comment by SteveRMann** [comment]
Thanks for the tip.  I have been unable to duplicate the original problem, and since I don't use versioning, I can't go back to the exact sketch that produced the problem.  (I suspect it's because I was doing two client.publish() lines without checking for the an error return).

I will do further testing when time allows, but in the future I will always test the return boolean when I do a client.publish().
