### ISSUE TITLE
Connect to multiple mqtt servers?

### ISSUE THREAD

**Issue by finnishcolumbia** [knolleary/pubsubclient#636]
I am connected to cloudmqtt server and everything works great. Can I also connect to a local server? I did not see an example for that

**Comment by knolleary** [comment]
What do you mean by 'local'?

If it has an IP address, you can connect to it. Doesn't matter where it is physically as long as you can get to its IP address.

**Comment by finnishcolumbia** [comment]
Thanks for the reply.

I’d like to send messages from the esp32 to a server on my “local” lan as
well as to a server on the Internet.

I suppose I could  send everything to the local server and then forward
those messages to the internet server.

**Comment by gazialankus** [comment]
Create two `PubSubClient` instances and two `WiFiClient`s. Do not share a `WiFiClient` instance between multiple `PubSubClient`s.
