### ISSUE TITLE
How to publish a json

### ISSUE THREAD

**Issue by mixaobo** [knolleary/pubsubclient#638]
this is my code 
```
JsonObject ID = object.createNestedObject(String(header.from_node));
        ID["Temperature"] = pack0.temperature;
        ID["Humidity"] = pack0.humidity;
        ID["Soil"] = pack0.soil;
        ID[ "Battery"] = pack0.battery;
        serializeJson(object, Serial);

```
My json like this in serial monitor `{"1":{"Temperature":29.8,"Humidity":41,"Soil":2,"Battery":3292.593}}`
i use `(client.publish(pubTopic, object))` but it turned no match function. could any help me plz

**Comment by saloid** [comment]
You need to convert your json object to c string (char array). I suppose that you are using ArduinoJson library, so look how to do it [here](https://arduinojson.org/v6/doc/serialization/) (chapter 4.4):
