### ISSUE TITLE
receiving messages again and again on topic

### ISSUE THREAD

**Issue by akhtarusafzai** [knolleary/pubsubclient#642]
Hello, I have a .net client which publish messages to another client which is nodemcu. I want the message to be received just once on the nodemcu. Following is the code I am using;

> client = new MqttClient(BrokerAddress, 1883, false, MqttSslProtocols.None, null, null);
clientId = Guid.NewGuid().ToString();
client.Connect(clientId);
client.Publish(Topic, Encoding.UTF8.GetBytes(firmware.version), 
MqttMsgBase.QOS_LEVEL_EXACTLY_ONCE, false);
System.Diagnostics.Debug.WriteLine("Published");`

here is the nodemcu code;

> void callback(char* topic, byte* payload, unsigned int length) {
Serial.print("Message arrived [");
Serial.print(topic);
Serial.print("] ");
for (int i = 0; i < length; i++) {
    d[i] = (char)payload[i];
    Serial.print(d[i]);
  }
}
void loop() {
  if (!client.connected()) {
    reconnect();
  }
  client.loop();
    client.subscribe(mqtt_topic);
}

**Comment by knolleary** [comment]
So what is your question?

**Comment by akhtarusafzai** [comment]
I want the message to be received just once. currently if I publish a message to the nodemcu it received many time. The following message was send from .net client. 
![Uploading image.png…]()

**Comment by akhtarusafzai** [comment]
****
![image](https://user-images.githubusercontent.com/23333346/61451761-9c4aed00-a973-11e9-98a5-6d61e56ff904.png)

**Comment by knolleary** [comment]
You are subscribing in your main loop. Every time you subscribe, the broker will send any retained message in that topic.

Do not subscribe in your loop - subscribe once after you connect.

**Comment by akhtarusafzai** [comment]
Do I need to reset the device everytime?

**Comment by knolleary** [comment]
Why would you want to do that?

**Comment by akhtarusafzai** [comment]
Here is my code. I want the message just once. can you suggest where to subscribe here and when to call callback?
> #include <ESP8266WiFi.h>
>#include <PubSubClient.h>
>
>#include <ESP8266HTTPClient.h>
>#include <ESP8266httpUpdate.h>
>//=======================================================//
>#define SLEEP_DELAY_IN_SECONDS 60
>#define WAIT_BEFORE_SLEEP_IN_SECONDS 5
>#define REFERENCE_VOLTAGE_ADC 3.3
>
>//======================================================//
>
>// initializes or defines the output pin of the LM35 temperature sensor
>int outputpin = A0;
>
>///ADC_MODE(ADC_VCC);
>float readingIn = 0;
>String ssid1, pass1;
>String newv = "";
>String versions = "001";
>const char* ssid = "Akhtar";
>const char* password = "akhtar1234";
>const char* mqtt_server = "broker.hivemq.com";
>const char* mqtt_topic = "ser";
>char temperatureString[6];
>byte mac[6];                     // the MAC address of your Wifi shield
>String strMacAddress = "";  // String type of Mac address
>String d[7];
>String a = "";
>int count = 1;
>
>WiFiClient espClient;
>PubSubClient client(espClient);
>
>void setup_wifi() {
> Serial.println(espClient);
>  delay(10);
> // We start by connecting to a WiFi network
>  Serial.println();
>  Serial.print("Connecting to ");
>  Serial.println(ssid);
> WiFi.begin(ssid, password);
>  while (WiFi.status() != WL_CONNECTED) {
>    delay(500);
>    Serial.print(".");
>  }
>  Serial.println("");
> Serial.println("WiFi connected");
>  Serial.println("IP address: ");
>  Serial.println(WiFi.localIP());
>  WiFi.macAddress(mac);
>
>  strMacAddress = "";
>  Serial.print("MAC: ");
>  Serial.print(mac[5], HEX);
>  // strMacAddress = strMacAddress + mac[5];
>  Serial.print(":");
>  Serial.print(mac[4], HEX);
>  //strMacAddress = strMacAddress + mac[4];
>  Serial.print(":");
>  Serial.print(mac[3], HEX);
>  //strMacAddress = strMacAddress + mac[3];
>  Serial.print(":");
>  Serial.print(mac[2], HEX);
>  //strMacAddress = strMacAddress + mac[2];
>  Serial.print(":");
>  Serial.print(mac[1], HEX);
>  // strMacAddress = strMacAddress + mac[1];
>  Serial.print(":");
>  Serial.println(mac[0], HEX);
>  // strMacAddress = strMacAddress + mac[0];
>}
>void(* resetFunc) (void) = 0; //declare reset function @ address 0
>
>void callback(char* topic, byte* payload, unsigned int length) {
>  Serial.print("Message arrived [");
>  Serial.print(topic);
>  Serial.print("] ");
>  for (int i = 0; i < length; i++) {
>    d[i] = (char)payload[i];
>    Serial.print(d[i]);
>    newv = newv + d[i];
>    
>  //Serial.println();
>  //Serial.println("Firmware Version " + newv + " Recieved");
> // a = d[4] + d[5] + d[6];
>  //Serial.print (a);
>
> }
>  Serial.println();
>
> 
>}
>
>void setup() {
>  // setup serial port
>  Serial.begin(115200);
>  // setup WiFi
>  setup_wifi();
>  client.setServer(mqtt_server, 1883);
>  client.setCallback(callback);
>  client.connect("ESP8266Client");
>  
>
>}
>
>void reconnect() {
>  // Loop until we're reconnected
>  while (!client.connected()) {
>    Serial.print("Attempting MQTT connection...");
>    // Attempt to connect
>    if (client.connect("ESP8266Client")) {
>      Serial.println("connected");
>      //client.subscribe(mqtt_topic);
>    } else {
>      Serial.print("failed, rc=");
>      Serial.print(client.state());
>      Serial.println(" try again in 5 seconds");
>      // Wait 5 seconds before retrying
>      delay(5000);
>    }
>  }
>}
>
>
>void loop() {
>  if (!client.connected()) {
>    reconnect();
>  }
>  client.loop();
>  client.subscribe(mqtt_topic);
>  client.setCallback(callback);
>    if (a > versions) {
>      Serial.println("Dowlnloading new version "+newv);
>      t_httpUpdate_return ret = ESPhttpUpdate.update(espClient, "http://192.168.43.101/Blink.bin");
>  
>      switch (ret) {
>        case HTTP_UPDATE_FAILED:
>          Serial.printf("HTTP_UPDATE_FAILD Error (%d): %s\n", ESPhttpUpdate.getLastError(), >ESPhttpUpdate.getLastErrorString().c_str());
>          break;
>  
>        case HTTP_UPDATE_NO_UPDATES:
>          Serial.println("HTTP_UPDATE_NO_UPDATES");
>          break;
>  
>        case HTTP_UPDATE_OK:
>          Serial.println("HTTP_UPDATE_OK");
>          break;
>      }
>  
>  
>    }
>}

**Comment by knolleary** [comment]
This code already contains the following in the 'reconnect' function:
```
if (client.connect("ESP8266Client")) {
   Serial.println("connected");
   //client.subscribe(mqtt_topic);
} else {
```

For some reason, you have commented out the subscribe call.

In your `loop` function you have:
```
void loop() {
if (!client.connected()) {
reconnect();
}
client.loop();
client.subscribe(mqtt_topic);
client.setCallback(callback);
...
```

You should not be calling `subscribe` or `setCallback` in the main loop. You already call `setCallback` correctly in the `setup` function, you don't need to keep calling it.

Finally, the last line of your `setup()` function is a call to client.connect... you should replace that with a call to the `reconnect()` function so that the subscribe is done from there.
