### ISSUE TITLE
Support for  Qos > 0  for Publisher now ?

### ISSUE THREAD

**Issue by rajdeeprath** [knolleary/pubsubclient#644]
Hello Mr Nick, 

Does pub support Qos > 0 now? How to work around the issue of not having Qos 1 or 2 for publish?

Without acknowledgment and confirmation, it can be rather problematic to build things.

**Comment by knolleary** [comment]
No it doesn't support >0 publishing. Sorry.

**Comment by rajdeeprath** [comment]
> No it doesn't support >0 publishing. Sorry.

Thanks
