### ISSUE TITLE
client.publish error after long delay or millis()

### ISSUE THREAD

**Issue by Maxyct** [knolleary/pubsubclient#645]
Hi all,

I've tried to send two consecutive messages within 30 seconds between each other. The code is something like this:

....
client.publish(TOPIC, "test");
delay(30000);
client.publish(TOPIC, "test2");
...

both return true but the second message is NOT sent. If I reduce to 5 seconds the delay it works fine!

I also tried to change the delay with the following code:

...
while ((millis() - start_execution_time) <= water_duration_ms.toInt()) {//Do Nothing}
...

I've also tested that the wifi and MQTT server connections are alive.

It doesn't work as well.
do you have any idea?
Thanks,
Max

**Comment by knolleary** [comment]
Using delay(30000) will stop the whole device from doing anything. Likewise, your while loop will block anything else from happening. This prevents the message being written to the network.

You could try putting a call to yield() inside your while loop.

**Comment by Maxyct** [comment]
I don't think so. I'm running sequantial command so the second publis is done once the delay is finished and the ESP32 is free. 

By the way, currently the code is put on the setup function. The loop is not used. I tried to do the following and it worked fine. I contiser it as a "workaround" to this strange behaviour of the library.


....
client.publish(TOPIC, "test");
delay(30000);
client.disconnect();
mqtt_setup();
client.publish(TOPIC, "test2");
...

Any suggestion on how to put yeld() call in the code?

**Comment by knolleary** [comment]
Don't use long calls to delay. It's as simple as that. It blocks anything else from happening. For example, your client could well get timed out by the broker because you have not called client.loop in time to allow the keep alive processing to run.

**Comment by Maxyct** [comment]
I need to turn a relay on for 30s (if any conditions say that) and then put the ESP in deep sleep mode. How can i do it without using a delay?

**Comment by knolleary** [comment]
Set a flag to indicate the relay is on, then on each loop check if 30s has elapsed since you turned it on.

**Comment by Maxyct** [comment]
Being in the setup() function it means that I could put a while loop like I said before...Your proposal is to set a flag instead of calculating the time. What is the difference?

while ((millis() - start_execution_time) <= water_duration_ms.toInt()) {//Do Nothing}

Thanks,
Max

**Comment by knolleary** [comment]
I can't solve every thing for you. I have explained the problem. You are doing blocking loops. There are lots of established patterns for what you want to do. For example, you may need to move this logic to your loop function rather than do it in setup.

**Comment by knolleary** [comment]
Just to clarify, do not do while loops that block for a long time.

Set a flag and each time the main loop function is called, in that flag is set, check how long it has been since you set it and decide what action to take.

**Comment by Maxyct** [comment]
ok thanks for your help.
