### ISSUE TITLE
Problem with connecting 2 ESP8266 boards simultanounsely 

### ISSUE THREAD

**Issue by Mahdi-Fatemi** [knolleary/pubsubclient#648]
Hi, I have problems with connecting second ESP8266 to MQTT server after first one gets connected.
My code runs perfectly when I am working with only one ESP8266 and it passes all the tests, but when I run up next ESP8266, both of them get disconnected from the MQTT server. my main program checks the wifi connection and MQTT connection on each loop and tries to reconnect at the case of wifi disconnection or MQTT disconnection. I wrote a program to make sure that the problem isn't made by wifi network. so now I am totally sure that ESP8266 boards keep connected to wifi network through the whole process. here's the exact story :
I connect first ESP8266 and messages get published and subscribed without any problems, I connect next ESP8266 and both of them get disconnected from server, at the same time I can see the boards retrying to connect the MQTT server. the boards get connected for a moment and then they get disconnected. it seems when a board gets in the network, the other boards will be kicked out. and when the other boards tries to reconnect, the first one gets kicked and this process runs over and over.

**Comment by knolleary** [comment]
Every client must have a unique client ID. This is the string you pass the call to connect.

**Comment by Mahdi-Fatemi** [comment]
I can not find the string you're talking about, here's my function for connecting to MQTT server :
`void connectMQTT() {
  client.setServer(mqttServer, mqttPort);
  client.setCallback(callback);
  while (!client.connected()) {
    if (WiFi.status() != WL_CONNECTED) {
      connectWifi();
    }
    Serial.println("Connecting to MQTT...");
    if (client.connect("ESP8266Client", mqttUser, mqttPassword )) {
      Serial.println("Connected to MQTT server.");
      Serial.println("-----------------------");
    } else {
      Serial.print("failed with state ");
      Serial.print(client.state());
      delay(2000);
    }
  }
}`

could you please tell me where can I find that 'Client ID' ?

**Comment by knolleary** [comment]
As I said, it is the string you pass to the connect call. You have it hard coded to `ESP8266Client`:

```
client.connect("ESP8266Client", mqttUser, mqttPassword )
```

**Comment by Mahdi-Fatemi** [comment]
Got it ! thank you for all your great efforts. most of my projects base codes are written by you.
I appreciate your great answer and codes.
