### ISSUE TITLE
How to read last message after reconnect without retain

### ISSUE THREAD

**Issue by ajaybnl** [knolleary/pubsubclient#652]
How to read last message after reconnect (my android app does not support retain)

If anyone know how to do it. Pls tell me

Btw I have created a nodered script that does that. Mail me for info.

**Comment by knolleary** [comment]
Please provide more details on what you are asking.

When you reconnect, I assume you resubscribe. If you don't have any retained messages, then you won't receive anything until a new message has been published.

What do you mean by 'last message'?

**Comment by ajaybnl** [comment]
I want to use mqtt android app for RELAY switching.
If my power cuts then the esp8266 RELAY could get last sent value from the android mqtt app.

This is same as retain. But my app doesnt support retain.

I have done similer approach with nodered.

It saves all mqtt data to mysql and when i message FEED1/init , then it reads last message from mysql and sends as mqtt.

Thus the esp8266 RELAY gets its last state.

**Comment by knolleary** [comment]
I am not really clear what you are asking to be honest. If you can't use retain, then its up to you to figure out how to get messages resent to the client. Your esp would have to send a message requesting state and to have something listening for that are republishing whatever you want.

It isn't a question about this library specifically.
