### ISSUE TITLE
Character limit on payload 

### ISSUE THREAD

**Issue by jordankbeard** [knolleary/pubsubclient#66]
We are using a Arduino Uno board to communicate to a server via a MQTT message broker.
The board is connected to several sensors we are hoping to send multiple readings in one request.
Our request is being sent in JSON format and it's about 580 characters.
Unfortunately we are finding the device crashes when it tries to receive over 106 characters.
And simply cuts out most of the payload when we publish. We have increased the max packet size in the header file (no luck).

We are using the following client library to talk to the broker.

http://knolleary.net/arduino-client-for-mqtt/

I know that MQTT does not have a character limit this small.
Could it be that the library is setting a character limit?

Thanks in advance.

**Comment by knolleary** [comment]
Hi,

From that link you posted, under the Limitations heading:

    The maximum message size, including header, is 128 bytes by default.


This limit is configurable as described here: http://knolleary.net/arduino-client-for-mqtt/api/#configoptions

**Comment by oxivanisher** [comment]
For users finding this just now, the new link to the documentation is: https://pubsubclient.knolleary.net/api.html#configoptions
