### ISSUE TITLE
Timing for MQTT V5.0 support ?

### ISSUE THREAD

**Issue by mars000** [knolleary/pubsubclient#666]
A general question rather than issue.
Anyone know if and when V5.0 MQTT Client for ESP32 and ESP8266 is or will be available ?

**Comment by knolleary** [comment]
I have no current plans to add v5 support to this client. I don't have the time or need to do it. There are v5 c clients available, such as the Eclipse Pago project.

I may revisit this at some point, but no time soon.

**Comment by novski** [comment]
ping, needed.

**Comment by teckdev** [comment]
https://github.com/knolleary/pubsubclient/issues/1045#issue-2176218911

**Comment by knolleary** [comment]
Whilst that linked comment is true, even if I get this library out of maintenance mode, I still have no plans to implement v5 here. There are alternatives out there.
