### ISSUE TITLE
client.publish make wdt reset with using topic in variable

### ISSUE THREAD

**Issue by TheUserDead** [knolleary/pubsubclient#668]
Hello, thank you for really great library for mqtt protocol.
One of versions (sorry i don't remember which is) i use String variables for topics. In last update you removed using strings and require using char massive. 
Ok, i rebuild my code to work with char* but one problem is critical.
I using command>answer logic system on my code (for special requests) and that means i send command to Sometopic/Device-1/System request like "?" and receive some device info in this topic.
That means function callback is called and receive three params. After i try to recognize which topic is used for triggering function and answer in callback using "topic" chars for publich, but when i use this .

```
void callback(const char* topic, byte* payload, unsigned int length) {
  aS.p("<i> Message arrived [").p(topic).p("] ");
  for (int i = 0; i < length; i++) {
    aS.p((char)payload[i]);
    aS.pln(i);
  }
  Serial.println();
  char exPayload = (char)payload[0];
  if (String(topic) == remotes){ //remotes var is Sometopic/Device-1/Executebles as char massive [30]
    if(exPayload == '?'){
      snprintf (msg, 50, "RELAY1=%d:%d", relayState[0], relayState[1]);
      aS.pln(topic);
      aS.pln(client.state());
      client.publish(topic, msg); //problem here if i use topic variable (pointer?!)
      // client.publish("Sometopic/Device-1/Executables", msg); //works fine
    }
}
```

aS.pln - its defined function for serial print in advancedSerial lib
I added for test Serial outputs after each command and program stops in client.publish line
if I use a clear indication of a topic like "Sometopic/Device-1/Executables" everything works fine
If i use topic variable where i receive it as function parameter, esp going to reboot by WDT reset.
I try to print contained data in "topic" and connection state as you see in code. Everything is fine, topic correct and connection is 0 (connected)

So many changes in build sketch with debug outputs of everything and enable exeptions do not provide any information why this happens. It's just wdt reset while try publish.
Can you help me? Or give me true direction how to make this work.

**Comment by saloid** [comment]
Bad idea to publish something inside callback. Better copy received data to global var buffer in callback, leave callback and process this data in loop. Also, you are publishing to topic on which you are subscribed - so you will receive sent msg (at first I thought that it`s will be recursion, but it's not - callback will be triggered only inside client.loop() function).
But I still don't know why you code crashes. Could you please provide minimum sketch to reproduce this?

**Comment by saloid** [comment]
In this library input and output data stored in same buffer, so it wouldn't work properly if you are use pointer to input topic as output topic. If you don't want move publishing outside of callback, you can copy topic content to local variable and use this variable in publishing.

```C++
//You can use arduino strings
String topicToPublish = String (topic);
...
client.publish(topicToPublish.c_str(), msg);
```

```C
//or C strings (char array)
char topicToPublish [strlen(topic)+1];  //one extra place for string termination symbol
strcpy (topicToPublish, topic);  //copies string to topicToPublish from topic
...
client.publish(topicToPublish, msg);
``` 

Chose one of this ways

**Comment by TheUserDead** [comment]
Thank you very much! I am really frustrated before, because this feeling _everything works fine and after some updates it breaks_ now, maybe i need change my command answer logic as you told me (device  received own answer, and it's just ignore, but this is a parasite traffic).
I tried your advice's, and it's work perfect to me. 
I was a little uncertainty, whether necessary to understand is why the device freezes. Since the problem was solved with your help.

**Comment by saloid** [comment]
You are welcome).

**Comment by TheUserDead** [comment]
@saloid 
I see how you help others by doing a good thing. Some people really appreciate it. I would like to thank you at least a little. Perhaps this is unacceptable, but if you are interested, let me know. The address is in the profile.
