### ISSUE TITLE
Public method to increase max packet size.

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [knolleary/pubsubclient#672]
Can there be a public method with which we can increase max packet size. Because without this the changed max packet size will be changed only in my machine but when I compile the code in other systems it will be different.

**Comment by saloid** [comment]
Hello, you can use `-DMQTT_MAX_PACKET_SIZE=1000` as compilation flag.

**Comment by a-c-sreedhar-reddy** [comment]
I am using this library with arduino-esp32. How can I compile with this flag?

**Comment by saloid** [comment]
If you are using Arduino IDE, you can try to create file `platform.local.txt` near your .ino file and specify in it `compiler.cpp.extra_flags=-DMQTT_MAX_PACKET_SIZE=1000`. I wasn't tested it, but [here ](https://stackoverflow.com/questions/28037491/arduino-1-0-6-how-to-change-compiler-flag)is reference.
Also, I would recommend migrate to platformio, where build flags are specified in `platformio.ini` file

**Comment by saloid** [comment]
Also, you can try to add `#define MQTT_MAX_PACKET_SIZE 1000` before including this lib, but it will not always work.
