### ISSUE TITLE
binary data cutted by zeros

### ISSUE THREAD

**Issue by andonoc** [knolleary/pubsubclient#674]
Hi,
i build a lora Gateway with a pro mini with rfm95, esp32, mqtt with pubsubclient and nodered.
I want to send the raw HEX  data from the esp32 through mqtt to nodered and decode the message there because so i can stick the esp32 on top of a pole on the roof of my house and forget it, even if i change the code of the node.

my test struct looks like this:

struct dataStruct {
  uint8_t deviceID;
  float temp ;
  float hum;
  uint8_t counter;
  uint8_t finalizer;
} myData;

Everything works great, except when there are zeros in the message
like in the exemple below

2 33 33 AF 41 CD CC 74 42 A0 FF                    --> Serial monitor Esp32
<Buffer 02 66 66 ae 41 33 33 75 42 9b ff>      --> Node Red console.log

2 66 66 AE 41 0 0 74 42 A5 FF                        --> Serial monitor Esp32
<Buffer 02 66 66 ae 41>                                --> Node Red console.log

The data gets cutted off on the zeros.

Is there a workaround or maybe is this way the wrong one to use the pubsubclient library.

**Comment by knolleary** [comment]
Without knowing how you are publishing that struct, it is hard to say. 

If you are using: `publish(topic, payload)` then the library assumes `payload` is a null-terminated string - which would explain what you are seeing.

What you should use is `publish(topic,payload,length)` ([api docs](https://pubsubclient.knolleary.net/api.html#publish3))  and specify the correct length for the data you are publishing.

**Comment by andonoc** [comment]
Hi knolleary,
i found your api docs and i used the `publish(topic,payload,length)` method earlyon but it does not help.
Maybe the mqtt node from nodered cut the message?
I send you my messy code
Thank you nick


#include <WiFi.h>
#include <PubSubClient.h>
#include <RHDatagram.h>
#include <RH_RF95.h>
#include <SPI.h>
#include <Wire.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>

//////////rfm95//////////
#define SERVER_ADDRESS 0xAA


#define ESP32_DOIT

#ifdef ESP32_DOIT
#define SS 5
#define IRQ 4
#define led 2
#endif


RH_RF95 driver(SS, IRQ);
RHDatagram manager(driver, SERVER_ADDRESS);

//////////WiFi//////////
#define mqttClientID "ESP32LoRaGateway"

const char* ssid = "hofnetz";
const char* password = "5t4u*d4ch3r";
const char* mqtt_server = "192.168.1.201";

WiFiClient espClient;
PubSubClient client(espClient);

//////////datenstruktur//////////
struct dataStruct {
  uint8_t deviceID;
  float temp ;
  float hum;
  uint8_t counter;
  uint8_t finalizer;
} myData;

//////////oled display//////////
#define SCREEN_WIDTH 128 // OLED display width, in pixels
#define SCREEN_HEIGHT 32 // OLED display height, in pixels

// Declaration for an SSD1306 display connected to I2C (SDA, SCL pins)
#define OLED_RESET -1 // Reset pin # (or -1 if sharing Arduino reset pin)
Adafruit_SSD1306 display(SCREEN_WIDTH, SCREEN_HEIGHT, &Wire, OLED_RESET);

void setup()
{
  Serial.begin(9600);  // Debugging only

  //////////rfm95//////////
  if (!manager.init())
    Serial.println("init failed");

  driver.setFrequency(868.0);
  driver.setSpreadingFactor(10);
  driver.setTxPower(10);

  pinMode(led, OUTPUT);

  //////////WiFi//////////
  setup_wifi();
  client.setServer(mqtt_server, 1883);
  client.setCallback(callback);

  //////////oled display//////////
  if (!display.begin(SSD1306_SWITCHCAPVCC, 0x3C)) { // Address 0x3C for 128x32
    Serial.println(F("SSD1306 allocation failed"));
    for (;;); // Don't proceed, loop forever
  }
  display.setTextColor(WHITE);
  display.clearDisplay();
  display.println("initialise Server...");
  display.println("Max msg length: ");
  display.println(RH_RF95_MAX_MESSAGE_LEN);
  display.setTextSize(1);
  display.display();
  delay(1000);
}

void loop()
{
  //Serial.println("!");

  if (!client.connected()) {
    reconnect();
  }
  if (manager.available()) {

    client.loop();

    uint8_t buf[RH_RF95_MAX_MESSAGE_LEN];
    uint8_t buflen = sizeof(buf);
    uint8_t from;

    if (manager.recvfrom(buf, &buflen, &from)) // Non-blocking
    {
      digitalWrite(led, HIGH);

      driver.printBuffer("Got:", buf, buflen);

      char msg[buflen];

      for (int i = 0; i < buflen; i++) {
        msg[i] = (char) buf[i];
        Serial.println(msg[i], BIN);
      }

      int flag = client.publish("sensor", msg, sizeof(msg));
      Serial.print("publish done:");
      Serial.println(flag);

      memcpy(&myData, buf, sizeof(myData));

      showOnDisplay(from, buflen);

      digitalWrite(led, LOW);

      Serial.println("-----------------------------------------------------------------------------------");
    }
  }
}

void showOnDisplay(uint8_t _from, uint8_t _buflen) {
  display.clearDisplay();
  display.setCursor(0, 0);
  display.print("got msg from: ");
  display.println(_from, DEC);
  display.print("msg length: ");
  display.print(_buflen * 8);
  display.println(" bit");
  display.print("RSSI: ");
  display.print(driver.lastRssi(), DEC);
  display.display();
}

void setup_wifi() {

  delay(10);
  // We start by connecting to a WiFi network
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);

  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  randomSeed(micros());

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());
}



void reconnect() {
  // Loop until we're reconnected
  while (!client.connected()) {
    Serial.print("Attempting MQTT connection...");
    if (client.connect(mqttClientID)) {
      Serial.println("connected!!");

    } else {
      Serial.print("failed, rc=");
      Serial.print(client.state());
      Serial.println(" try again in 5 seconds");
      delay(2000);
    }
  }

}

void callback(char* topic, byte* payload, unsigned int length) {
  Serial.print("Message arrived [");
  Serial.print(topic);
  Serial.print("] ");
  for (int i = 0; i < length; i++) {
    Serial.print((char)payload[i]);
  }
  Serial.println();
  if ((char)payload[0] == '1') {
   
  } else {
  
  }
}

**Comment by andonoc** [comment]
Hi,
i changed from char to byte
Thank you
