### ISSUE TITLE
Can't connect with LWT Last Will and Testament

### ISSUE THREAD

**Issue by Zavy86** [knolleary/pubsubclient#678]
Hi, I'm trying to connect with a lwt on a ESP8266-01 but it doesen't work.

// definitions
const char* dev_hash="client";
const char* mqtt_hostname="192.168.1.10";
const char* mqtt_username="username";
const char* mqtt_password="password";
const char* mqtt_topic_lwt="/relays/lwt";
const char* lwt_message="offline";

// work
client.connect(dev_hash,mqtt_username,mqtt_password)

// doesen't work
client.connect(dev_hash,mqtt_username,mqtt_password,mqtt_topic_lwt,0,true,lwt_message)

**Comment by Zavy86** [comment]
Hi, solved increasing MQTT_MAX_PACKET_SIZE.
It is also possibile to increase without modify the PuSubClient.h file? like a parameter?

**Comment by jomo02** [comment]
Same problem here, even after increasing the buffer size with `setBufferSize(1024)`.

**Comment by kinsi55** [comment]
@jomo02 did you manage to find a solution?

**Comment by jomo02** [comment]
@kinsi55 Actually yes, by setting the buffer size to 1024*5 bytes. But I am also using the more powerful ESP32 now, not sure if this also works with the mentioned ESP8266.

**Comment by kinsi55** [comment]
Yeah I am also using an ESP32 so that works for me, thank you!

**Comment by moorthypnt** [comment]
> @kinsi55 Actually yes, by setting the buffer size to 1024*5 bytes. But I am also using the more powerful ESP32 now, not sure if this also works with the mentioned ESP8266.

Can you provide your ESP8266 working code portion which are relevant with lwt ??

**Comment by moorthypnt** [comment]
> Hi, I'm trying to connect with a lwt on a ESP8266-01 but it doesen't work.
> 
> // definitions const char* dev_hash="client"; const char* mqtt_hostname="192.168.1.10"; const char* mqtt_username="username"; const char* mqtt_password="password"; const char* mqtt_topic_lwt="/relays/lwt"; const char* lwt_message="offline";
> 
> // work client.connect(dev_hash,mqtt_username,mqtt_password)
> 
> // doesen't work client.connect(dev_hash,mqtt_username,mqtt_password,mqtt_topic_lwt,0,true,lwt_message)

If your mqtt broker is AWS IoT, your last will message has to be in proper json. 
So, change your  //   const char* lwt_message="offline";   // into proper json and connect again.
