### ISSUE TITLE
How can we reduce memory heap required ?

### ISSUE THREAD

**Issue by debendramodi** [knolleary/pubsubclient#679]
We are using the following functions and libraries-

Wifi (AP+STA)
MQTT (pubsubclient) with SSL/TLS
BLE (nkolban)

We find we run into memory heap issues and we fail to reconnect if it disconnects.  If I provide more memory say by removing BLE, the reconnection works fine.

We find that the pubsubclient library requires almost 100K heap available to reconnect. Are there any options to reduce the heap used by this library ?

**Comment by knolleary** [comment]
Hi, the PubSubClient doesn't use 100k of heap. That will be in use by whatever network client you are using underneath the library. That isn't something we have any influence or control over.

**Comment by debendramodi** [comment]
Thank you for your prompt response.

I am a newbie and the question may sound naive - 

Are there any options in your code that can be modified to reduce the heap usage ?

Or Can we rebuild the underneath network client with modified options with reduced functionality to reduce the heap usage ?

**Comment by debendramodi** [comment]
I setup the IDF build environment, adjusted the config options and built the Arduino core again.  I am now able to save almost 47KB of heap and everything works fine.

**Comment by LuchoManto** [comment]
Hello, i think i'm having this same issue. Could you walk me through your solution? i'm using Platformio to program an esp32.
