### ISSUE TITLE
Issues when using ESP's deep sleep

### ISSUE THREAD

**Issue by deadbird99** [knolleary/pubsubclient#690]
Hi.

I've been using your library lately for an IoT project, and ran into some weird problems. It took me a while to figure it out, but here's the thing: if the ESP will go into deepSleep, you MUST use PubSubClient::disconnect before going to deepSleep, or published message may never arrive.

I don't have any clue about what's going on as I didn't dive into PubSubClient's code.

**Comment by d0ct0rd-dalimo** [comment]
if you just send message before sleeping, let MQTT client work in loop for a little time:
```
unsigned long int new_millis = millis(); // Создание новой точки отсчета времени
  while(millis() - new_millis < 6000) {     
    mqtt.loop();
  }
```

**Comment by Narase33** [comment]
> 
> 
> if you just send message before sleeping, let MQTT client work in loop for a little time:
> 
> ```
> unsigned long int new_millis = millis(); // Создание новой точки отсчета времени
>   while(millis() - new_millis < 6000) {     
>     mqtt.loop();
>   }
> ```

Though this might work, when using your Arduino on a battery, this is not a good solution as every ms counts

**Comment by ccvca** [comment]
Thanks p-vernaeckt this is a very good solution. (Also for the MQTT-Broker)

This is the code of disconnect, i would guess that `_client->flush()` does the magic.
```c++
void PubSubClient::disconnect() {
    this->buffer[0] = MQTTDISCONNECT;
    this->buffer[1] = 0;
    _client->write(this->buffer,2);
    _state = MQTT_DISCONNECTED;
    _client->flush();
    _client->stop();
    lastInActivity = lastOutActivity = millis();
}
```
Maybe a line like this may be added to the limitations (https://github.com/knolleary/pubsubclient#limitations):
>To ensure all messages are published when using deep sleep `disconnect()` must be called before.
