### ISSUE TITLE
I Want QoS 2 in Subscribe 

### ISSUE THREAD

**Issue by ghostcoffins** [knolleary/pubsubclient#698]
is it possible to get QoS level in 2 in subscribe function ?? 
and please guide me if it is possible then is it possible to publish a message two times and get it delivered two times ?? or it will just be delivered only once in a life time if the topic is the same

**Comment by knolleary** [comment]
Hi - sorry, no. This library doesn't support QoS 2 subscriptions.

If you publish a message twice, in normal operation, it will be received twice, regardless of the qos.
