### ISSUE TITLE
Library doesn't compile for ESP8266

### ISSUE THREAD

**Issue by l-sch** [knolleary/pubsubclient#70]
Hello knolleary,

I'm referring to my [pull request](https://github.com/knolleary/pubsubclient/pull/69) on this topic.

I think that its, of course, better to check if PROGMEM is defined, instead of just checking if you are on that one platform, like the ESP8266.

The problem is: It doesn't work. PROGMEM seems to be still defined on an ESP8266. Your library would only compile, if I insert `#undef PROGMEM` in both the header and cpp-files.

Maybe, you could combine the two?

Thanks, l-sch.

**Comment by knolleary** [comment]
So what exact compiler error do you get when compiling? If progmem is defined, it ought to be valid code....

**Comment by l-sch** [comment]
This is the error I'm getting when compiling through the arduino-ide: (Using your lib inside another library called Espanol):

    /Volumes/homes/leons/Documents/Arduino/libraries/Espanol/utility/PubSubClient.h:97:46: error: section attribute not allowed for '<anonymous>'
        boolean publish_P(char *, uint8_t PROGMEM *, unsigned int, boolean);
                                                  ^

**Comment by knolleary** [comment]
Ok, got to the bottom of it - this wasn't to do with PROGMEM missing, it was a specific way the code was trying to use progmem. I think I've sort it - it compiles cleanly against an ESP8266 target now, but I don't have the hardware to test.

Let me know how you get on.

**Comment by tomn46037** [comment]
I just tested the latest release and I am able to compile it with the Arduino IDE v1.6.5.  I was able to upload it to an Adafruit Huzzah and subscribe and publish.. looks good to me.

Thanks for the work.. I use this for all my IOT stuff.. it's great!

**Comment by knolleary** [comment]
@tomn46037 Great! Want to do some more testing for some of the other changes I've made, but will get a new release done today.
