### ISSUE TITLE
PubSubClient client (<wifi and GSM client?>)

### ISSUE THREAD

**Issue by jh83** [knolleary/pubsubclient#707]
Im working on a project for which im in need to "roam" the pubsubclient over wifi (when connected to a wifi) or GSM/GPRS when wifi isn't in range.

Is there a way to declare ONE PubSubClient client() to work against multiple clients like Wifi, GSM, lan etc?

My workaround at the moment is to declare two pubsubclients and the connect, subscribe and publish to each depending on the wireless connection available. This creates lots of redundant code, and if the pubsubclient could roam between clients then it would be awsome.

`
WiFiClient wifiClient;
TinyGsmClient gsmClient(modem);

PubSubClient mqttGsm(gsmClient);
PubSubClient mqttWifi(wifiClient);
`

**Comment by knolleary** [comment]
No such feature exists in the library - each instance is tied to a single network client.

An alternative workaround is to create your own roaming network client that handles the failover between whatever network clients you want. That lets you have a single PubSubClient instance and move the roaming logic down into network client layer.
