### ISSUE TITLE
Using ESP8266 with an Arduino

### ISSUE THREAD

**Issue by ymaglaras** [knolleary/pubsubclient#71]
Hello. I am trying to use the PubSubClient library but instead of using an Ethernet shield, I would like use an ESP8266 module. In the readme, it is stated to be compatible. Which library should be used for the ESP8266?

The sample found here: https://gist.github.com/igrr/7f7e7973366fc01d6393 seems to address that, but the library used (ESP8266WiFi found here: https://github.com/sandeepmistry/esp8266-Arduino/tree/master/esp8266com/esp8266/libraries/ESP8266WiFi) seems to be written for the ESP8266 as a standalone. The other library (ESP8266wifi found here: https://github.com/ekstrand/ESP8266wifi) is not compatible with the original Ethernet library, so it doesn't work.

**Comment by knolleary** [comment]
Good question @ymaglaras 

@tomn46037 could you give some pointers on what lib you used on the esp8266? I can get that added to the docs.

**Comment by tomn46037** [comment]
I used the latest version of the Arduino IDE (1.6.5) and I installed the ESP8266 toolchain with the Board manager (Tools->Boards->Boards Manager) then search for ESP8266.  Mine shows that I have "ESP8266 Community version 1.6.5-947-g39819f0".

With this library, the ESP8266 Wifi uses the "client" interface the same as the ethernet shield.

I created a new repo with my test code.  It should compile and connect to the MQTT server.  It should subscribe and you should be able to publish to it.  Again, this is very rough.. but it does compile and will connect to the MQTT server and publish/subscribe and print incoming messages.  The repo is at 

https://github.com/tomn46037/ESP8266-AdafruitIO-PubSubClient-DeskLamp

**Comment by knolleary** [comment]
Thanks @tomn46037 

@ymaglaras : does that answer you questions?

**Comment by knolleary** [comment]
Closing as the info from Tom answers the questions. At some point, I'll add as ESP8266 example to the library - once I get some hardware of my own to test with

**Comment by kylegordon** [comment]
Using a clean install here, and the ESP8266 board isn't available by default. You need to go into Arduino Preferences, and add an appropriate board manager url to the list, such as https://github.com/toddtreece/esp8266-Arduino/releases/download/1.6.4/package_esptest_index.json

Only after doing this was the ESP8266 option available in the Board Manager.

Source info from https://github.com/esp8266/Arduino/issues/13
