### ISSUE TITLE
delay in LWT 

### ISSUE THREAD

**Issue by shaikabdulazeez** [knolleary/pubsubclient#710]
i am using "connect" function with LWT for showing "device offline" message.but i am getting LWT message after 25 to 30 sec.when i reconnect the device online message is showing within 10 sec.Same thing i did in mqttbox in this scenario LWT message showing immediately.

This is my reconnect function 
void reconnect() {
  // Loop until we're reconnected
  while (!client.connected()) {
    Serial.print("Attempting MQTT connection...");
    // Create a random client ID
    String clientId = "ESP8266Client1-";
    clientId += String(random(0xffff), HEX);
    // Attempt to connect
    if (client.connect(clientId.c_str(), "xxxx", "xxxx","device/status",1, true, "offline")) {
      Serial.println("connected");
      // Once connected, publish an announcement...
      client.publish("device/status","online",true);
      // ... and resubscribe
      client.subscribe("inTopic");
    } else {
      Serial.print("failed, rc=");
      Serial.print(client.state());
      Serial.println(" try again in 5 seconds");
      // Wait 5 seconds before retrying
      delay(5000);
    }
  }

**Comment by knolleary** [comment]
The default keepalive is 15 seconds, so I would expect the broker to wait around 30 secs before triggering the LWT (twice the keepalive).

You can change the keepalive value by changing the value of `MQTT_KEEPALIVE` in `PubSubClient.h`.
