### ISSUE TITLE
Connecting to IPv6 MQTT servers

### ISSUE THREAD

**Issue by CRCinAU** [knolleary/pubsubclient#716]
Now that the ESP8266 supports IPv6 natively, is there anything stopping PubSubClient from connecting to IPv6 clients?

I'm attempting to just change the IP to an IPv6 address in the `client.setServer` parameter, but this doesn't seem to work.

Any suggestions?

**Comment by knolleary** [comment]
Nothing I know of. As far as I know (from 30 seconds research), the IPv6 ip address is passed in as a `char*` - just as a domain name would be.

The alternative would be to connect the network client you are using with PubSubClient first, then call connect on the PubSubClient - skipping the `client.setServer` call entirely.

**Comment by theGeekyLad** [comment]
Sorry to necrobump but @knolleary are you sure it's as simple as passing a `char*` to the `setServer()`? I tried the `client.setServer("xxxx:xxxx:xxxx:xx:xxxx:xxxx:xxxx:xxxx", 1883)` but the connection just times out at `client.connect()`.

I've tried the following variants:
1. `client.setServer("xxxx:xxxx:xxxx:xx:xxxx:xxxx:xxxx:xxxx", 1883)`
2. `client.setServer("[xxxx:xxxx:xxxx:xx:xxxx:xxxx:xxxx:xxxx]", 1883)`
but to no avail.

`mosquitto_pub` and `mosquitto_sub` work on Linux from different clients pointing to the same IPv6 address which clarifies that the connections are in place.

Any suggestions? _(do let me know if I should open a new issue)_

**Comment by knolleary** [comment]
We pass it straight through to the underlying network client. If the TCP connection isn't being established, then that's outside the control of this library. You'd have to check the docs of the network client you're using to confirm the required format.

**Comment by theGeekyLad** [comment]
Oh, so you mean to say that since I use a `WifiClient`, I need to check if that supports IPv6?

**Comment by knolleary** [comment]
Yes. The network client you provide to PubSubClient is fully responsible for establishing the underlying network connection.

**Comment by d-a-v** [comment]
On esp8266/Arduino, IPv6 capability is not enabled by default.
It has to be selected in menu (or enabled in configuration).

**Comment by theGeekyLad** [comment]
Happy new year, everyone! @d-a-v any idea how to enable IPv6 on my NodeMCU ESP8266 (through the Arduino IDE)?

_Edit:_ Also @knolleary , I purchased a domain and added an AAAA record to my IPv6 address. `mosquitto_sub` and `mosquitto_pub` from the terminal are able to work with this domain name but the PubSubClient still says "connection failed". Any thoughts?

**Comment by d-a-v** [comment]
![image](https://user-images.githubusercontent.com/4800356/147938277-1091bfc9-ff9f-47d2-994b-c180621ed08b.png)

**Comment by theGeekyLad** [comment]
Super helpful, thank you! Everything works fine now.
