### ISSUE TITLE
What's the meaning of the first parameter of this code?

### ISSUE THREAD

**Issue by clothesack** [knolleary/pubsubclient#720]
What's the meaning of the first parameter of this code? You only need an account and password to connect to the matt server. Why add it? Or what's the point? I don't understand. Please let me know
 ` if (client.connect("arduinoClient", "testuser", "testpass")) {
    client.publish("outTopic","hello world");
    client.subscribe("inTopic");
  }`
The case code appears in the 'mqtt_auth. Ino' file

**Comment by knolleary** [comment]
The first parameter is the MQTT Client ID. This is used to unique identify the client to the broker. Every client that connects to a broker must have a unique client id.

See https://www.hivemq.com/blog/mqtt-essentials-part-3-client-broker-connection-establishment/#clientid for more information.
