### ISSUE TITLE
How change client's name?

### ISSUE THREAD

**Issue by Portia-Lin** [knolleary/pubsubclient#723]
I am using two esp8266 modules with your library. All modules are loaded with the same sketch. I'm having trouble with connecting the second module to the mqtt server. 

When I was browsing the log from the server, I noticed that the module names are the same:
`2020-03-19 22:35:14: New connection from 37.53.226.52 on port 10257.`
`2020-03-19 22:35:14: Client ESP8266Client already connected, closing old connection.`
`2020-03-19 22:35:14: Socket error on client ESP8266Client, disconnecting.`
`2020-03-19 22:35:14: New client connected from 37.53.226.52 as ESP8266Client (c1, k15, u'hreasxjy').`

How can I solve my problem. How to specify different names?

**Comment by knolleary** [comment]
The client id is the first argument you pass to the `connect` function.

You have it set to `ESP8266Client`, but it must be unique for each client you connect.

One approach is to generate a random number and store it in eeprom when the sketch starts and append that to the client id to help make it unique.

**Comment by Portia-Lin** [comment]
I do not quite understand what function is responsible for this. I did not specify a name in the sketch.

**Comment by Portia-Lin** [comment]
Sorry, I am inattentive. I found the function
