### ISSUE TITLE
understanding connection process

### ISSUE THREAD

**Issue by elgarbe** [knolleary/pubsubclient#730]
Hi, I'm working on SIM800L with arduino UNO and testing MQTT example. I just want to understand how connection to the server is managed. I've enabled debug mode and looking at serial monitor I saw 

```
AT+CIPSTART=0,"TCP","test.mosquitto.org",1883
OK
0, CONNECT OK
AT+CIPSEND=0,27
>MQTTGsmClientTest 
DATA ACCEPT:0,27
AT+CIPRXGET=4,0
+CIPRXGET: 4,0,0
OK
AT+CIPSTATUS=0
```
And after that a lot of 
```
AT+CIPRXGET=4,0
+CIPRXGET: 4,0,0
OK
AT+CIPSTATUS=0
```
What is the purpose of that CIPRXGET and CIPSTATUS?
Finally after some of those messages I see:
 ```
AT+CIPSTATUS=0
+CIPSTATUS: 0,0,"TCP","5.196.95.208","1883","CONNECTED"
OK
+CIPRXGET: 1,0
AT+CIPRXGET=4,0
+CIPRXGET: 4,0,4
OK
AT+CIPRXGET=2,0,4
+CIPRXGET: 2,0,4,0
 
OK
 success
```
So, that last CIPRXGET is the one that receive CONNACK packet. But what is the purpose of previous commands?

**Comment by knolleary** [comment]
I can't help you with all of the CIP commands. They are coming from whatever network client you are using underneath PubSubClient.
