### ISSUE TITLE
PubSubClient and WiFiClientSecure - Connecting with AWS IoT Core is blocking code

### ISSUE THREAD

**Issue by am-canes** [knolleary/pubsubclient#734]
I am using PubSubClient to connect ESP8266 to AWS IoT Core.
But I am facing a problem with PubSubClient and WifiClientSecure. When it is trying to connect to AWS my code is blocked for like 6 seconds or more depending on the response. But I have some critical proccess happening and my code can never be blocked.

I tried the spatnynick solution on #583 but it worked well just with a simple code. When I put in my existing code it blocks inside _connectSSL and never connect.

I also tried the brianrho solution on #640 but it still blocks my code for some seconds while connecting.

What could I do to make the process asynchronous? Anyone could help me?

**Comment by brianrho** [comment]
#640 itself doesn't block as far as I've tested; what *could* be blocking is the `Client::connect()` itself which depends on what Client you supply and how it sets up its TCP connection. Here, you're using the built-in ESP8266 `WifiClient` library and that is blocking, with a configurable timeout that isn't very useful for your case. This behaviour would be the same, regardless of which MQTT library you use. You need to find an MQTT client library that uses [asynchronous TCP](https://github.com/me-no-dev/ESPAsyncTCP) transactions instead, like [this one](https://github.com/marvinroger/async-mqtt-client).

**Comment by am-canes** [comment]
@brianrho Yes, WifiClientSecure library that is blocking my code.
I tried to use async-mqtt-client but it didn't work for me because I need TLS1.2 to connect with AWS and it is not supported by AsyncTCP.
I gave up AWS and I am looking for another cloud solution for ESP8266.

**Comment by jigneshk5** [comment]
@am-canes Use https://github.com/debsahu/ESP-MQTT-AWS-IoT-Core
Works fine with AWS IoT.

**Comment by am-canes** [comment]
@jigneshk5 I tried ESP-MQTT-AWS-IoT-Core too, but the problem is the same. It works, like PubSubClient, but it blocks my code for 6 seconds when it is connecting with AWS. Because it uses the same WifiClient library. Thanks

**Comment by brianrho** [comment]
What exactly does your code do that can't be blocked for so long? It may be possible to do it all from interrupts

**Comment by am-canes** [comment]
@brianrho I am reading and controlling critical sensors at 250ms and 300ms intervals. And my project can work with and without wifi connection. So the user can connect wifi at any time and ESP8266 will connect to AWS when it detects a succesfull wifi connection, and it means that the rest of the code is already running.
Another problem is if it loses connection with AWS and needs to reconect, because the 6 seconds blocking will occur again.
I tried to put the critical things inside hardware interrupt, but I have a state machine and a lot of code and when I tried this the PubSubClient can't connect anymore. And I know that put a lot of things inside interrupts isn't the best thing to do.

**Comment by cyberman54** [comment]
@am-canes use FreeRTOS tasks.

**Comment by am-canes** [comment]
@cyberman54 I'm using ESP32 now, it is dual core and solved my problem.

**Comment by marcoavaccaro** [comment]
Hello guys, i'm trying to connect to AWS wich request:

wifiClient.loadCACert(ca);
wifiClient.loadCertificate(client_cert);
wifiClient.loadPrivateKey(client_key);

Via wifi i can do it with no problems. But the ethernet library present on arduino do not have these 3 classes above.

Someone know how to connect to AWS via ethernet shield using ESP32?
