### ISSUE TITLE
Callback function get called during publish

### ISSUE THREAD

**Issue by wahibmichael** [knolleary/pubsubclient#736]
I have a publish topic strcuture 

device1/register
device1/status
device1/command

and subscribe topic structure
device1/#
then I use if condition in the callback to take action based on topic

my problem is that the callback function is called each time I publish on any topic and I receive the publish payload again in callback payload, is this due to the same buffer used?
and is there a solution for that?

**Comment by knolleary** [comment]
You are subscribed to `device1/#`. That matches all of the topics you say you are publishing to. So yes, you will receive all of those messages.

If you don't want to receive those messages, don't subscribe to the topic you are publishing them on.

**Comment by wahibmichael** [comment]
thank you then I'll probably change my topic structure to 
device1/out/register
device1/out/status
device1/out/command 

and subscribe to 
device1/in/#
or subscribe to specific topics
