### ISSUE TITLE
Cannot get Arduino to connect to Raspberry Pi MQTT broker

### ISSUE THREAD

**Issue by noemark1** [knolleary/pubsubclient#74]
I am having a problem connecting my Arduino to a Raspberry Pi 2 MQTT broker using the MQTTbasic.ino example.  I have changed the MAC address to that on my Arduino Ethernet Shield, input an IP address that is consistent with what the shield has been assigned from my router (192.168.1.67) and changed the server address to that of my Pi2 (192.168.1.87).  The serial monitor just says "attempting MQTT connection.... failed rc=-4 try again in 5 seconds" and sticks in an infinite loop.  I have verified that my MQTT broker works, as I can connect to it on my PC and send messages using M2MqttSpy via port 1883.  I also know that my Arduino system is functional because I can load the example Ethernet server and connect to it using my web browser on port 80.

Please help, as I am at my wits end here.  I am trying to construct the Uber Home Automation system with OpenHab, and the MQTT client sketch there didn't connect either, so I tried to diagnose the problem with a basic sketch here and have the same issue.  

Many thanks,

-Mark

**Comment by knolleary** [comment]
The rc=-4 means the client connected, but the server didn't respond to the connect request (http://knolleary.github.io/pubsubclient/api.html#state). This usually indicates the broker you're running doesn't support the 3.1.1 version of MQTT so doesn't know how to respond.

You should either upgrade your broker (assuming its mosquitto, you need at least v1.3, although the latest available is 1.4.3.

Otherwise, change the MQTT_VERSION header in PubSubClient.h to switch the library to use MQTT 3.1.

**Comment by noemark1** [comment]
I tried changing the MQTT_VERSION header in PubSubClient.h to use MQTT 3.1 by commenting out the 3.1.1 line and removing the comment from 3.1.  I restarted IDE and recompiled - same result.  How do I find out what version of mosquitto I am running on the Pi?  I installed it a few days ago using sudo apt-get install mosquitto mosquitto-clients python-mosquitto

Many thanks,

-Mark

**Comment by knolleary** [comment]
Running:
  $ dpkg -l mosquitto

should tell you something.

I haven't got a Pi to hand at the moment to check, but I suspect the version in the repositories may be slightly out of date. Some good instructions for installing latest/greatest here: http://jpmens.net/2013/09/01/installing-mosquitto-on-a-raspberry-pi/

**Comment by noemark1** [comment]
It claims it is running v 0.15, which is 3.1 compatible.  I am trying to download the newest version from the server at the link you provided me above, but the server is hanging.  Will try again later.

While I have you here , what are the other likely reasons for the -4 error?

Thank you for your help, as I am a relatively inexperienced user of Linux and the Arduino platform.

Many thanks,

-Mark

**Comment by knolleary** [comment]
Hmm, not sure what package version 0.15 maps to in terms of actual mosquitto version. Have a look under /var/log/ for any mosquitto related log files - it logs its version number on start up.

This is the only concrete cause of the -4 result I know of. I suggest you try changing the MQTT_VERSION value in PubSubClient.h - if I'm right about this being a version mismatch issue, that'll get things working.

It is still worth trying to get the newer version of mosquitto on there; lots of good bug fixes etc.

**Comment by noemark1** [comment]
And you are right sir - I just upgraded to version 1.4.3 and everything connects fine.  Thank you for your help.  Now to get all of my wireless nodes working...

Many thanks,

-Mark
