### ISSUE TITLE
How often .loop() needs to be called?

### ISSUE THREAD

**Issue by lg007** [knolleary/pubsubclient#756]
Hello,

I am using your library with an ESP32 and a SIM800L GSM module, together with the TinyGSM library (https://github.com/vshymanskyy/TinyGSM). Everything works fine, but I have a question for which I haven't found the answer anywhere, neither in the API nor in the issue register:  how often .loop() needs to be called? Does it have to be called once a second, or once every 100 mS? Could you please give some advice?

Regards,

**Comment by knolleary** [comment]
Calling `loop` does two things:

1. it lets the client do any keep-alive processing, such as sending a `ping` packet, to ensure the connection stays alive. The default keepalive is 15 seconds, so the client needs to do *something* within that sort of timeframe.

2. it checks to see if there is any incoming data to read from the network - such as a published message.

If your client is only publishing, then you can call `loop` once every few seconds to ensure the keep-alive processing is run.

If your client is subscribed and expects to receive messages, then you should decide how much of a delay you can cope with between a message being published and it triggering the callback in the client. 

I would *not* recommend calling it in a tight loop without any delay at all - I have seen that cause a mini denial-of-service on the network hardware as it constantly checks to see if there's anything to do.

**Comment by lg007** [comment]
Thanks for the really fast answer!

**Comment by JohnnyHandy** [comment]
@knolleary what would be the best practice to receive consecutively messages in a short interval?
My case is that I am trying to pwm control a led, just to make it increase or decrease its brightness. For this, I am using a web interface with a [range input  ](https://www.jqueryscript.net/images/Custom-Range-Input-Plugin-jQuery.jpg) that sends the value each time I am using it.
It happens that when I slide the range quickly it will send consecutively values, but I realized that through the serial monitor that each value is being received slowly, in an interval of 1 second between each of them. I tested with [MQtt.fx ](https://mqttfx.jensd.de/) to see if the values were really being sent at the rate that I ranged the slide, and they were.

Example: I slide the range from the value 1 to 50. The serial monitor will show 1, 2, 3, 4... 50 with a delay of a second between each of them. But at the MQtt.fx I see that much before the serial monitor reach the 3, 4, 5 values it already had sent the last value.

So, how can I set my code to receive more messages (in this case, the values) in a more quick manner, avoiding this delay between each message?

**Comment by knolleary** [comment]
@JohnnyHandy it only handles one incoming MQTT message per call to loop. So if you want to handle them quicker,  use a smaller value.

**Comment by JohnnyHandy** [comment]
@knolleary thank you for you explanation, I ended up finding a spare delay function that was making the main arduino loop to happen at 1 second rate... Fixed that and I having the proper response rate!

**Comment by martinrdrz** [comment]
@knolleary
Hi.
I tell you that I am using the TinyGsm library with the SubPubClient library for Mqtt, and I see that every 1 minute it sends automatically a "ping" message to the broker. Why is this message sent? Can this type of ping message be suppressed or sent over a longer time interval?
Thank you very much.
