### ISSUE TITLE
Pubsubclient to work with SparkFun CC3000 breakout board

### ISSUE THREAD

**Issue by zuhryfayesz** [knolleary/pubsubclient#76]
I'm wondering that is there any way to integrate pubsubclient library to work with SparkFun CC3000 breakout board. Much appreciated if you can provide a guide how make this thing work
Thank you.
![12072-01](https://cloud.githubusercontent.com/assets/1870594/9756211/01059c42-56f6-11e5-98ec-b579bc7c1fea.jpg)

**Comment by knolleary** [comment]
As documented, this library works with any hardware that provides a Client.h implementation. A quick look at the [library Sparkfun provides for this hardware](https://www.sparkfun.com/products/12072) shows it does provide a Client.h implementation - `SFE_CC3000_Client`.

So in the examples provided by the PubSubClient library, where it uses `EthernetClient`, you should use `SFE_CC3000_Client`. You'll have to refer to the examples provided by sparkfun for how to initialise the wifi connection and client.

**Comment by zuhryfayesz** [comment]
@knolleary ... Thanks for your guide. Its working like charm ... Happy !!!! :dancers:

**Comment by knolleary** [comment]
Great!

**Comment by zuhryfayesz** [comment]
Small problem again ... Call back function is not working ... publish is success from arduino to outside ..

**Comment by knolleary** [comment]
Can you share your code somewhere so I can see what you're doing?

**Comment by zuhryfayesz** [comment]
this is my code 

<iframe style="height: 510px; width: 100%; margin: 10px 0 10px;" allowTransparency="true" src="https://codebender.cc/embed/sketch:149812" frameborder="0"></iframe>

**Comment by knolleary** [comment]
@zuhryfayesz sorry, not seeing any code

**Comment by zuhryfayesz** [comment]
#include <SPI.h>
#include <UIPEthernet.h>
#include <SFE_CC3000.h>
#include <SFE_CC3000_Client.h>
#include <PubSubClient.h>

// Pins
#define CC3000_INT      2   // Needs to be an interrupt pin (D2/D3)
#define CC3000_EN       7   // Can be any digital pin
#define CC3000_CS       10  // Preferred is pin 10 on Uno

// Connection info data lengths
#define IP_ADDR_LEN     4   // Length of IP address in bytes



// Constants
char ap_ssid[] = "wifeye";                  // SSID of network
char ap_password[] = "kalutaradon123";          // Password of network
unsigned int ap_security = WLAN_SEC_WPA2; // Security of network
unsigned int timeout = 30000;             // Milliseconds
char server[] = "zuhryfayesz.github.io";        // Remote host site
char mqtt_server[] = "mqtt.devicehub.net";




void callback(char* topic, byte* payload, unsigned int length) {
	
	
  // handle message arrived
  char message_buff[100];
  int i;
  for(i=0; i<length; i++) {
    message_buff[i] = payload[i];
  }
  message_buff[i] = '\0';

  String msgString = String(message_buff);
  
  Serial.println("message arrived: " + msgString);
	
	
}


// Global Variables
SFE_CC3000 wifi = SFE_CC3000(CC3000_INT, CC3000_EN, CC3000_CS);
SFE_CC3000_Client sclient = SFE_CC3000_Client(wifi);

PubSubClient client(mqtt_server, 1883, callback, sclient);

void setup() {
  
  ConnectionInfo connection_info;
  int i;
  
  // Initialize Serial port
  Serial.begin(115200);
  
  Serial.println();
  Serial.println("---------------------------");
  Serial.println("SparkFun CC3000 - WebClient");
  Serial.println("---------------------------");
  
  // Initialize CC3000 (configure SPI communications)
  if ( wifi.init() ) {
    Serial.println("CC3000 initialization complete");
    
  } else {
    Serial.println("Something went wrong during CC3000 init!");
  }
  
  // Connect using DHCP
  Serial.print("Connecting to SSID: ");
  Serial.println(ap_ssid);
  if(!wifi.connect(ap_ssid, ap_security, ap_password, timeout)) {
    Serial.println("Error: Could not connect to AP");
  }
  
  
  
  // Gather connection details and print IP address
  if ( !wifi.getConnectionInfo(connection_info) ) {
    Serial.println("Error: Could not obtain connection details");
  } else {
    Serial.print("IP Address: ");
    for (i = 0; i < IP_ADDR_LEN; i++) {
      Serial.print(connection_info.ip_address[i]);
      if ( i < IP_ADDR_LEN - 1 ) {
        Serial.print(".");
      }
    }
    Serial.println();
  }
  
  if (client.connect("arduinoClient")) {
    client.publish("zuhry","connected");
    client.subscribe("zuhry");
  }
  
  // Make a TCP connection to remote host
  Serial.print("Performing HTTP GET of: ");
  Serial.println(server);
  if ( !sclient.connect(server, 80) ) {
    Serial.println("Error: Could not make a TCP connection");
  }
  
  // Make a HTTP GET request
  sclient.println("GET /index.html HTTP/1.1");
  sclient.print("Host: ");
  sclient.println(server);
  sclient.println("Connection: close");
  sclient.println();
  Serial.println();
}

void loop() {
	
	 client.loop();
  
  // If there are incoming bytes, print them
  if ( sclient.available() ) {
    char c = sclient.read();
    Serial.print(c);
  }
  
  // If the server has disconnected, stop the client and wifi
  if ( !sclient.connected() ) {
    Serial.println();
    
    // Close socket
    if ( !sclient.close() ) {
      Serial.println("Error: Could not close socket");
    }
    
    // Disconnect WiFi
    if ( !wifi.disconnect() ) {
      Serial.println("Error: Could not disconnect from network");
    }
    
    // Do nothing
    Serial.println("Finished WebClient test");
    while(true){
      delay(1000);
    }
  }
  
}

**Comment by knolleary** [comment]
@zuhryfayesz after your code connects the mqtt client and publishes, it then does this:

````
  // Make a HTTP GET request
  sclient.println("GET /index.html HTTP/1.1");
  sclient.print("Host: ");
  sclient.println(server);
  sclient.println("Connection: close");
  sclient.println();
  Serial.println();
````

This is sent straight to the mqtt server, which, as it isn't anything to do with mqtt, it kills the connection.

Once you pass sclient to the pubsubclient library, you cannot reuse it for other things.
