### ISSUE TITLE
Unable to connect to MQTT broker running on VM (Centos 7)

### ISSUE THREAD

**Issue by mitreviews** [knolleary/pubsubclient#766]
Hi,
I am running broker on my centos 7 which is running inside VM.
**Centos IP: 192.168.247.143**

**Started subscriber on one terminal in centos:**
mosquitto_sub -h 192.168.247.143 -d -u "centos" -P "centospass" -t test

**I am able to publish via other terminal:**
mosquitto_pub -d -h 192.168.247.143 -u "centos" -p 1883 -P "centospass" -t test -m "Hello"

**I am able to publish from my windows machine after i disable the firewall on centos:**
mosquitto_pub -d -h 192.168.247.143 -u "centos" -p 1883 -P "centospass" -t test -m "Hello"

Wrote the sample code for ESP8266:
Esp8266 IP after connecting to WIFI: **10.172.216.226**

**I am able to ping this Esp8266 IP from windows as well as centos.**

**But ESP8266 fails to connect to MQTT with message "failed with state -2" (MQTT_CONNECT_FAILED)**

Tried lot of things but nothing seems to be working. 
Need some help here.

**Comment by slavino** [comment]
dear network guru, please spend some additional time with debugging your network

LINUX/UNIX: traceroute 10.172.216.226
WIN: tracert 10.172.216.226

**Comment by mitreviews** [comment]
@slavino Thanks for your time.

Finally figured out the issue.
It was Network issue.
ESP8266 cant access my OS IP running on VM inside windows.
Did new MQTT Broker setup on windows and tried the same.
It worked this time.

**Comment by mitreviews** [comment]
Issue is resolved. Its more of network issue.
