### ISSUE TITLE
Using pubsubclient with WifiClient and making network connection to server.

### ISSUE THREAD

**Issue by nospam2k** [knolleary/pubsubclient#769]
I have the following:

```
...
WiFiClient net;
PubSubClient client(net);
...
```
when I:

```
net.connect(remote_rest, 80))
```

I lose my connection to mqtt server.

**Comment by knolleary** [comment]
`net` is the client being used by the PubSubClient.

If you tell it to connect to a different server then it will drop its existing connection to the MQTT server.

**Comment by nospam2k** [comment]
Thx. I figure it out earlier, I didn't realize you could have multiple instances of WifiClient.
