### ISSUE TITLE
api documentation needs to show default values

### ISSUE THREAD

**Issue by amitrao17** [knolleary/pubsubclient#771]
the api documentation shows that a parameter is optional, but does not indicate what the default value is. that would be pretty helpful. i'm willing to help if I knew where the api documentation source was located.

https://pubsubclient.knolleary.net/api

**Comment by knolleary** [comment]
The website is all in the `gh-pages` branch of this repo: https://github.com/knolleary/pubsubclient/tree/gh-pages

**Comment by amitrao17** [comment]
i see, thx. so is it valuable to others to see default values in the documentation? would you accept a pull request with this change to docs?

**Comment by knolleary** [comment]
I would happily review a PR that improved the docs.
