### ISSUE TITLE
If my esp32 reboot I only received the first retained message

### ISSUE THREAD

**Issue by erikk12** [knolleary/pubsubclient#773]
if you subscribe the a topic you only get the FIRST message send from the broker. Others got wiped for whatever reason. 
I have been trying to change the buffer size without effect.

Anyone knows how to fix that?

thank you!

**Comment by knolleary** [comment]
There is only ever one retained message on a topic.

If you publish A then B, both as retained messages, B will replace A as the retained message on the topic.

**Comment by erikk12** [comment]
Should I subscribe to multiple topics if I have more than one retained messages?

**Comment by knolleary** [comment]
It depends what you are trying to do. If you are trying to using retained messages to queue up messages whilst the client is disconnected, that is not the right thing to do.

To do that properly you need to:
- set the cleanSession flag to false in the call to client.connect.
- subscribe at QoS 1 (this library doesn't support qos 2)
- make sure the messages published to that topic are published at QoS 1 as well.

If that's all done correctly, the broker will queue up messages for those topics for the client to receive when it next connects and subscribes.

**Comment by erikk12** [comment]
Ok! Thank you!!
