### ISSUE TITLE
publish fails when including retained parameter

### ISSUE THREAD

**Issue by TotallyInformation** [knolleary/pubsubclient#78]
Hi Nick,

Just started using your MQTT library with the ESP8266 and the Arduino IDE.

All works well when using the short form of publish, e.g.:
```client.publish(topic, myIP);```
where the 2 variables are both char (string arrays).

However, when I try to use the extended form so that I can include the retained parameter:
```client.publish(topic, msg, 50, 1);```
It fails with:
```
\sketches\libraries\pubsubclient\src/PubSubClient.h:115:12: error:   initializing argument 2 of 'boolean PubSubClient::publish(const char*, const uint8_t*, unsigned int, boolean)' [-fpermissive]
    boolean publish(const char* topic, const uint8_t * payload, unsigned int plength, boolean retained);
            ^
invalid conversion from 'char*' to 'const uint8_t* {aka const unsigned char*}' [-fpermissive]
```
So it appears the parameter 2 is defined differently? My C skills are totally naff I'm afraid so I can't work out whether this is deliberate (and if so why). If it is, I'm uncertain how to convert from the string array to the uint8_t format. 

I'm also not sure why I need the length parameter just to set the retained flag?

Thanks for the library though, without it I'd still be struggling along with the NODEMCU firmware and LUA!

**Comment by knolleary** [comment]
Hi,

this is what you want:

   client.publish(topic, (uint8_t*)msg, 50, true);

There are so many data types and ways the client gets used, providing every combination of every type and argument wouldn't be manageable. That said, it seems reasonable to want to have a publish(string,string,boolean) function that does what you want without having to worry about the length field - I'll add one next time I'm updating the client.

**Comment by TotallyInformation** [comment]
Huzzah! Thanks Nick, told you my C was rubbish. I hate it with a vengence but at least it works when you can figure it out unlike NODEMCU/LUA which I was fighting every step of the way and gave up when I got an out of memory error on a simple program.

You've also answered my next question which was why my LWT message wasn't getting the retained flag - true not 1!

**Comment by TotallyInformation** [comment]
Hmm, always too complex!
```
      IPAddress myAddr = WiFi.localIP();
      snprintf (myIP, 16, "%s.%s.%s.%s", myAddr[0],myAddr[1],myAddr[2],myAddr[3]);
      client.publish(topic, (uint8_t*)myIP, 50, true);
```
is what finally worked. It publishes the IP address when the device connects to the broker. The LWT changes the same topic to "Offline".

**Comment by knolleary** [comment]
Have just released v2.3 that introduces a `publish(topic,payload,retained)` function.

**Comment by TotallyInformation** [comment]
Ha ha! Cheers, I'll grab it shortly.

**Comment by knolleary** [comment]
If you do stick with what you've got there, you'll want to use `strlen(myIP)` rather than `50` - as it won't be a 50 character string.

**Comment by Gendiaaa** [comment]
> If you do stick with what you've got there, you'll want to use `strlen(myIP)` rather than `50` - as it won't be a 50 character string.

hello Mr Knolleary

 i was not able to publish to topic using a retain flag and Qos as this function shows 
 boolean publish_P(const char* topic, const uint8_t * payload, unsigned int plength, uint8_t qos, boolean retained);
i follow the same same and got this error
C:\Users\gendi\OneDrive\Documents\Arduino\DosingEsp32working in edit\DosingEsp32working in edit.ino:1415:70: error: no matching function for call to 'PubSubClient::publish(char [60], uint8_t*, unsigned int&, int, bool)'
   client.publish(buf_topic,(uint8_t*) msg , arrSize, MQTTpubQos, true);
                                                                      ^
In file included from C:\Users\gendi\OneDrive\Documents\Arduino\DosingEsp32working in edit\DosingEsp32working in edit.ino:10:
c:\Users\gendi\OneDrive\Documents\Arduino\libraries\pubsubclient-master\src/PubSubClient.h:151:12: note: candidate: 'boolean PubSubClient::publish(const char*, const char*)'
    boolean publish(const char* topic, const char* payload);
            ^~~~~~~
c:\Users\gendi\OneDrive\Documents\Arduino\libraries\pubsubclient-master\src/PubSubClient.h:151:12: note:   candidate expects 2 arguments, 5 provided
c:\Users\gendi\OneDrive\Documents\Arduino\libraries\pubsubclient-master\src/PubSubClient.h:152:12: note: candidate: 'boolean PubSubClient::publish(const char*, const char*, boolean)'
    boolean publish(const char* topic, const char* payload, boolean retained);
            ^~~~~~~
c:\Users\gendi\OneDrive\Documents\Arduino\libraries\pubsubclient-master\src/PubSubClient.h:152:12: note:   candidate expects 3 arguments, 5 provided
c:\Users\gendi\OneDrive\Documents\Arduino\libraries\pubsubclient-master\src/PubSubClient.h:153:12: note: candidate: 'boolean PubSubClient::publish(const char*, const uint8_t*, unsigned int)'
    boolean publish(const char* topic, const uint8_t * payload, unsigned int plength);
            ^~~~~~~
c:\Users\gendi\OneDrive\Documents\Arduino\libraries\pubsubclient-master\src/PubSubClient.h:153:12: note:   candidate expects 3 arguments, 5 provided
c:\Users\gendi\OneDrive\Documents\Arduino\libraries\pubsubclient-master\src/PubSubClient.h:154:12: note: candidate: 'boolean PubSubClient::publish(const char*, const uint8_t*, unsigned int, boolean)'
    boolean publish(const char* topic, const uint8_t * payload, unsigned int plength, boolean retained);
            ^~~~~~~
c:\Users\gendi\OneDrive\Documents\Arduino\libraries\pubsubclient-master\src/PubSubClient.h:154:12: note:   candidate expects 4 arguments, 5 provided

exit status 1

Compilation error: no matching function for call to 'PubSubClient::publish(char [60], uint8_t*, unsigned int&, int, bool)'

any advice to how to publish Qos2 with retain flag set , i am using V2.8
