### ISSUE TITLE
Not receiving data subscribed from topic

### ISSUE THREAD

**Issue by ghost** [knolleary/pubsubclient#782]
Hi, I am using Arduino Uno and ESP-01 with
`AT version: 1.5.0`
`SDK version: 2.1 &` 
`Bin version : 1.5.1` 
 I am able to connect, disconnect, publish, subscribe and unsubscribe but not receiving data from MQTT server for the subscribed topic. I tried connecting using `MQTTBox` in that I am receiving data properly. So I think the mistake may be in the code I have written. So I have uploaded the code here
`I have not provided the domain, username and password for some reasons`
```
#include <SoftwareSerial.h>
#include <WiFiEsp.h>
#include <WiFiEspClient.h>
#include <PubSubClient.h>
#include "ArduinoJson.h"

#define WIFI_AP         "My AP"
#define WIFI_PASSWORD   "MyPASSWORD"
#define MQTT_BROKER     "iothub.domain.net" // Don't want to share
#define PUBLISH_TOPIC   "fwent/edge/inbound"
#define SUBSCRIBE_TOPIC "fwent/edge/outbound"

// Function decleration
void InitWiFi();
void callback(char* topic, byte* payload, unsigned int length);
void reconnect();

// Initialize
WiFiEspClient espClient;
SoftwareSerial esp01(9, 8); // RX, TX
PubSubClient mqtt(espClient);
DynamicJsonDocument jsonData(170);

char payload[170];
int status = WL_IDLE_STATUS, flag = 0;

void setup() {
  Serial.begin(9600);
  InitWiFi();

  // Connect to MQTT Broker
  mqtt.setServer(MQTT_BROKER, 1883);
  // Set callback to receive payload
  mqtt.setCallback(callback);

  // JSON payload
  jsonData["dev_eui"] = "123456789";
  jsonData["client_id"] = "123456789";
  jsonData["snr"] = "25%";
  jsonData["switch"] = "off";
  jsonData["battery_level"] = 62;
  jsonData["temperature"] = 60.5;
  jsonData["humidity"] = 85;

  serializeJson(jsonData, payload);
  Serial.println(payload);
}

void loop() {
  status = WiFi.status();
  
  if (status != WL_CONNECTED) {
    while (status != WL_CONNECTED) {
      Serial.print("Message: Connecting to ");
      Serial.println(WIFI_AP);
      
      // Connect to network
      status = WiFi.begin(WIFI_AP, WIFI_PASSWORD);
      delay(500);
    }
  }

  // Check for connection
  if (!flag && !mqtt.connected())
    reconnect();
 
  if (Serial.available()) {
    char ch = Serial.read();
    if (ch == 'p') {
      // Publish your data here
      if (mqtt.publish(PUBLISH_TOPIC, payload)) {
        Serial.print("Published: ");
        Serial.println(payload);
      }
    }
    else if (ch == 's') {
      // Subscribe to Topic
      if (mqtt.subscribe(SUBSCRIBE_TOPIC)) {
        Serial.print("Message: Subscribed to topic ");
        Serial.println(SUBSCRIBE_TOPIC);
      }
    }
    else if (ch == 'u') {
      // Unsubscribe from topic 
      if (mqtt.unsubscribe(SUBSCRIBE_TOPIC)) {
        Serial.print("Message: Unsubscribed from topic ");
        Serial.println(SUBSCRIBE_TOPIC);
      }
     }
     else if (ch == 'd') {
      flag = 1;
      mqtt.disconnect();
      Serial.println("Message: Disconnected from MQTT");
     }
     else if (ch == 'c')
      flag = 0;
  }

  mqtt.loop();
}

void InitWiFi() {
  // Initialize serial for ESP module
  esp01.begin(2400);

  // Initialize ESP module
  WiFi.init(&esp01);
  
  // check for the presence of the shield
  if (WiFi.status() == WL_NO_SHIELD) {
    Serial.println("Error: WiFi shield not present");

    // Blocking here only
    while (true);
  }
}

void reconnect() {
  // Loop untill reconnect
  while (! mqtt.connected()) {
    Serial.println("Message: Connecting to MQTT Broker...");
    //                 Client ID      User Name   Password
    if (mqtt.connect("123456789" , "mynamehere", "mypasshere"))
      Serial.println("Message: Connected to MQTT");
  }
}

void callback(char* topic, byte* payload, unsigned int length) {
  Serial.print("Message arrived [");
  Serial.print(topic);
  Serial.print("] ");
  
  for (int i = 0; i < length; i++) {
    Serial.print((char)payload[i]);
  }
  
  Serial.println();
}

**Comment by oCkiNkr** [comment]
> ## Limitations
>
> - It can only publish QoS 0 messages. It can subscribe at QoS 0 or QoS 1.
> - The maximum message size, including header, is **256 bytes** by default. This is configurable via `MQTT_MAX_PACKET_SIZE` in `PubSubClient.h` or can be changed by calling `PubSubClient::setBufferSize(size)`.
> - The keepalive interval is set to 15 seconds by default. This is configurable via `MQTT_KEEPALIVE` in `PubSubClient.h` or can be changed by calling `PubSubClient::setKeepAlive(keepAlive)`.
> - The client uses MQTT 3.1.1 by default. It can be changed to use MQTT 3.1 by changing value of `MQTT_VERSION` in `PubSubClient.h`.



 Does it work if you try increasing the buffer size?

> In the case of version  knolleary/PubSubClient@2.8
>
> Add `mqttClient.setBufferSize(1024);` to setup()
>
> ```sh
> mqtt.setServer(MQTT_BROKER, 1883);
> mqtt.setCallback(callback);
> mqttClient.setBufferSize(1024); // Set up a larger buffer.
> ```

> In the case of version  knolleary/PubSubClient@<=2.8
>
> Edit MQTT_MAX_PACKET_SIZE in `PubSubClient.h` 
>
> ```c
> #ifndef MQTT_MAX_PACKET_SIZE
> //#define MQTT_MAX_PACKET_SIZE 256
> define MQTT_MAX_PACKET_SIZE 1024
> #endif
> ```

**Comment by Next-93** [comment]
Hi friend I tried with these but same problem. Which version of AT Firmware are you using? Which version of PubSubClient you are using? Anyone who have working code can please share here

**Comment by ghost** [comment]
I got it working when I directly upload the sketch to ESP-01 using serial interface. By using Generic ESP8266 Module in Arduino Board Manager and by changing the header file to ESP8266WiFi.h instead of WiFiEsp.h and WiFiEspClient.h and with few code changes. Now receiving message from subscribed topic.
