### ISSUE TITLE
Method Publish

### ISSUE THREAD

**Issue by darlandc1998** [knolleary/pubsubclient#784]
Hello, can you confirm if this method of the library is synchronous or asynchronous?

```
boolean PubSubClient::publish(const char* topic, const char* payload) {
    return publish(topic,(const uint8_t*)payload, payload ? strnlen(payload, this->bufferSize) : 0,false);
}
```

Thanks hugs!

**Comment by knolleary** [comment]
It will pass all of the bytes to be sent to the network client before the call returns. What the network client does will be up to the client... Although most will write synchronously as far as I know.

**Comment by darlandc1998** [comment]
I understand thank you!

What I'm doing is the following, analyzing the time he makes the call to publish, as follows:

```
const t_started = micros();
client.publish(TOPIC, PAYLOAD);
const t_publish = micros() - t_started;
Serial.println(t_publish);
```
I would like to identify the time it took him to publish something on the topic, as far as I know the instability of the network can influence time. So I would like to know if this logic of mine for measuring time is valid.

Hugs!
