### ISSUE TITLE
Cannot create dynamic subscribe topics

### ISSUE THREAD

**Issue by amarotica** [knolleary/pubsubclient#785]
Hi there, I've been banging my head against the table for hours on this and believe I have exhausted every forum post and issue report out there.

I am trying to populate the client.subscribe(topic) call with a dynamically created topic (includes the devices unique mac address).
Below is a simplified code of what I've done:
```
String MAC = WiFi.macAddress();
String theTopic = "BaseTopic/Local/";
theTopic += MAC;

client.subscribe(theTopic.c_str());
```

This method does NOT throw errors during compilation, but does NOT work. As soon as client.subscribe is called, the MQTT connection is terminated with error -3.

I should also mention that I am using an esp32. Also, when I hard-code the topic, it works fine: client.subscribe("ThisIsAFakeTopic/here");

Thanks for any insight you might have!

**Comment by amarotica** [comment]
I should add that I cannot add static "unique" values as the MQTT topics within the firmware itself. I currently have ~85 devices deployed, and they provision themselves automatically from the same generic firmware, based on their hardware address and unique certs saved in spiffs. At least, that's how it's supposed to work.

**Comment by kpfleming** [comment]
The reason this fails is that `client.subscribe()` stores the pointer to the topic that you supply, and the `c_str()` function on the String object returns the address of the internal buffer in the Object... which may be destroyed immediately after. For this to work properly, you will either need to ensure that the String object stays alive the entire time that the client is subscribed to that topic, or use `new` to allocate a character buffer on the free store (heap). The first solution is probably the easiest.

**Comment by amarotica** [comment]
Thank you @kpfleming for the thoughtful explanation. I would have never came up with or guessed that issue on my own but it totally makes sense. I'll first try and make the String objects global variables and see if that solves it. If not, I'll check out the second option you explained.

Thanks again! I really appreciate it.

PS: Will close in ~2 days after I have time to test the proposed solution.

**Comment by kpfleming** [comment]
You're very welcome! As a long time C++ programmer I'm used to this sort of thing, but for reference, look here:

https://www.arduino.cc/reference/en/language/variables/data-types/string/functions/c_str/

**Comment by Heeyen** [comment]
Hello I have same problem as amarotica , sadly I don't get how to keep the string alive or use a buffer. Thanks in advance

**Comment by amarotica** [comment]
Realized I never replied or marked this as closed. As kpfleming pointed out, it is a very easy fix once you know what to do. Below is a simplified example...

String topicName = "Test/Topic";
client.subscribe(topicName.c_str(),0);

And bobs your uncle!
