### ISSUE TITLE
PubSubClient with publish QOS 1 or 2

### ISSUE THREAD

**Issue by krupis** [knolleary/pubsubclient#789]
![image](https://user-images.githubusercontent.com/22237034/97482444-d967a280-195e-11eb-87ba-377e8acf4a0e.png)
Hey. I have read the latest commit notes and I can see that Publish with OQS 1 or 2 are now supported. I had a look at pubsubclient source file at function prototypes but I cannot see where to pass an argument for QOS when publishing a message. 

Can someone clarify this for me please?

**Comment by knolleary** [comment]
Where exactly did you get that text from? I can't find it anywhere in the code base. Can you link to the commit in question?

**Comment by krupis** [comment]
Thats the first page it opened when I typed in google:
MQTT library for ESP32 with publish qos.
https://github.com/knolleary/pubsubclient/pull/100/files/4c9e59113e528fcd21573bf41bf87247e2235fa0

![image](https://user-images.githubusercontent.com/22237034/97488597-218ac300-1967-11eb-9d69-49758c0d2759.png)

**Comment by knolleary** [comment]
That is a pull-request where someone has proposed some changes to add qos 1/2 publish support. The changes have not be merged into the library.

This library does not support publishing at anything other than qos 0.
