### ISSUE TITLE
Crash when try to do pubsubclient.connect() but broker is not available

### ISSUE THREAD

**Issue by janvankeulen** [knolleary/pubsubclient#792]
At the moment the PubSubClient works perfect when everything goes how it should be. Even unplugging the Ethernet cable and replugging it restores the functionality, but...

When I stop the MQTT broker and try to reconnect (in the loop() I check if the connection is lost -> thus reconnect), instead of the expected true or false I should get from the connect() function, it hangs the system and reboots when the WDT is triggered. With the WDT disabled it hangs 'forvever'

I use these simple codes to Initialize and Connect

  ```
#ifdef USE_MQTT
    Serial.println("initMQTT");
    MQTTclient.setClient(ethPubSubClient);
    MQTTclient.setServer(MQTTbrokerIP, settingMQTTport);
    MQTTclient.setCallback(callback);
  #endif
}
//===========================================================================================
bool connectMQTT()
{
  #ifdef USE_MQTT
    Serial.println("doMQTTconnect");
    return MQTTclient.connect(settingMQTTclient, settingMQTTuser, settingMQTTpasswd);
  #endif
}
```

**Comment by antibarbie** [comment]
Maybe a shortened but complete example would help ?
By the way, what is "**WDT**" ?

**Comment by TuxTroll** [comment]
What does your Loop do? If you have prints, you need to add a little delay to Loop. Otherwise i had some issued in the past.
Call connect is no problem in my case.

**Comment by janvankeulen** [comment]
> Maybe a shortened but complete example would help ?
> By the way, what is "**WDT**" ?

Sorry, WDT is the Watchdog timer which expires and reboots the system when it doen not respond anymore.

**Comment by janvankeulen** [comment]
I have got a beta version for the NativeEthernet library and now the problem is solved. So it had nothing to do with the PubSubClient and everything with the NativeEthernet library
