### ISSUE TITLE
ESP32 cant recieve data from adafruit

### ISSUE THREAD

**Issue by ahmed1278** [knolleary/pubsubclient#797]
I tried to make small project that turns on/off the light just by a messenger message, and I used ESP32 -chatFuel-adafruit-IFTTT.
when I made a block(on/off button) in adafruit dashboard it works, how ever when i send a messenger message it doesnt work even though that i can recieve messages sent in my adafruit feed.
Here's my code:
#include <Adafruit_ESP8266.h>

#include <WiFi.h>
#include <dummy.h>

#include "Adafruit_MQTT.h"
#include "Adafruit_MQTT_Client.h"

#define d1 

String  Request;
#define AIO_SERVER      "io.adafruit.com"
#define AIO_SERVERPORT  1883
#define AIO_USERNAME  "ahmed1278"
#define AIO_KEY  "aio_XxDx97ujgVYdWK3GFkbCrAnqvKJN"
WiFiClient client;

Adafruit_MQTT_Client mqtt(&client, AIO_SERVER, AIO_SERVERPORT, AIO_USERNAME, AIO_KEY);

Adafruit_MQTT_Subscribe home = Adafruit_MQTT_Subscribe(&mqtt, AIO_USERNAME "/feeds/home");
boolean MQTT_connect();

boolean MQTT_connect() {
  int8_t ret;
  if (mqtt.connected()) {
    return true;
  } uint8_t retries = 9;
  while ((ret = mqtt.connect()) != 0) {
    mqtt.disconnect();
    delay(2000);
    retries--;
    if (retries == 0) {
      return false;
    }
  } return true;
}

void setup()
{
  Serial.begin(115200);
  Request = "";

  WiFi.disconnect();
  delay(3000);
  Serial.println("Start IoT");
  WiFi.begin("ORANGE_3C82", "HBJ5FEZJ");
  while ((!(WiFi.status() == WL_CONNECTED))) {
    delay(300);
    Serial.print(".");

  }
  Serial.println("Wifi Connected");
  Serial.println("Your IP is");
  Serial.println(( WiFi.localIP().toString() ));

  mqtt.subscribe(&home);

  
  pinMode(21, OUTPUT);

  
}

void loop()
{

  if (MQTT_connect()) {
    Adafruit_MQTT_Subscribe *subscription_name;
    while ((subscription_name = mqtt.readSubscription(5000))) {
      if (subscription_name == &home) {
        Request = ((char *)home.lastread);
        /*if (!strcmp((char*) home.lastread, "on"))
      {
        //Active low logic
        digitalWrite(21, HIGH);
      }
      if (!strcmp((char*) home.lastread, "off"))
      {
        //Active low logic
        digitalWrite(21, HIGH);
      }**/
        if (Request == "on") {
          digitalWrite(21, HIGH);
          Serial.println("light turn ON");
        }
       if (Request == "off") {
          digitalWrite(21, LOW);
          Serial.println("light turn off");
        }

      }

    }

  }

}

**Comment by vndk36** [comment]
Hi, I'm not speaking for the dev team, but it seams like you don't even use this library in your project.

**Comment by knolleary** [comment]
Closing as you aren't using the PubSubClient library this is the repository for. Sorry I can't help with other MQTT libraries.

**Comment by ahmed1278** [comment]
guys can explain with more details please? thanks

**Comment by knolleary** [comment]
@ahmed1278 your code is using `Adafruit_MQTT.h` to provide the MQTT functionality.

This repository is for an entirely different MQTT client - `PubSubClient`.

The repository for the client you are using is here: https://github.com/adafruit/Adafruit_MQTT_Library

**Comment by ahmed1278** [comment]
hellow! thanks for your attention but while installing the file u sent to
me I found that it already exists and Im using it

**Comment by knolleary** [comment]
@ahmed1278 

You are asking for help with your code in the wrong place. This repository is for the `PubSubClient` library. You are not using that library.
