### ISSUE TITLE
Problems with ESP8266 and username/password Secured MQTT Connection to Mosquitto

### ISSUE THREAD

**Issue by Charry2014** [knolleary/pubsubclient#806]
For a home automation project I have configured a Mosquitto broker (version 1.4.15) running in the AWS cloud. I have clients on my phone, a Raspberry Pi, and also using Node Red. These are all working fine using a username/password pair to log in and need no certificates. The MQTT broker does anyway have valid a certificate issued by Letsencrypt, but currently the other clients are not using it. I am now trying to connect an [ESP8266](https://www.az-delivery.de/en/products/nodemcu) the same way as the other clients... what could be so hard... Well, I cannot get it to work.

To test what I am doing I have been trying to connect the ESP8266 to the testing Mosquitto server available on test.mosquitto.org. Various ports are available - 1883 is unencrypted, 8883 is encrypted no certificate required and 8884 is MQTT, encrypted, client certificate required. The basic sketch works fine to 1883, sometimes with retries, see like below.

Here is my basic sketch - it is essentially a rehash of the examples found on the 'net:
```
#include <ESP8266WiFi.h>
//#include <WiFiClientSecure.h>
#include <PubSubClient.h>

/* secrets.h defines things that are - secret :-)
 * You can see fake values that it defines below
 */
#if 0
#include "secrets.h"

#else
#define WIFI_SSID "my_wifi_ssid"
#define WIFI_PASSWORD "super_secret"

#define MQTT_USER  "username"
#define MQTT_PASSWORD "Lets_hack_it_777"

// Test Mosquitto server, various ports available
// 1883 is unencrypted, 8883 is encrypted no certificate required
// 8884 : MQTT, encrypted, client certificate required
// https://test.mosquitto.org/
#define MQTT_SERVER "test.mosquitto.org"
#define MQTT_PORT 1883

#endif

// LED configuration - write HIGH to turn off, LOW to turn on
#define led_built_in_ESP 2
#define led_built_in_Node 16

// MQTT Test Topics
#define in_topic "/test/in"
#define out_topic "/test"


#if MQTT_PORT == 1883
// Unsecured MQTT
WiFiClient espClient;

#else
// WiFiClientSecure espClient;
BearSSL::WiFiClientSecure espClient;
#endif

PubSubClient client(espClient);
// PubSubClient client(MQTT_SERVER, MQTT_PORT, espClient);


void setup() {
  Serial.begin(115200);
  pinMode(led_built_in_ESP, OUTPUT);
  pinMode(led_built_in_Node, OUTPUT);
  digitalWrite(led_built_in_ESP, HIGH);
  digitalWrite(led_built_in_Node, HIGH);
 
  setup_wifi();
  
  client.setClient(espClient);
  client.setServer(MQTT_SERVER, MQTT_PORT);
}

void reconnect() {
  // Loop until we're reconnected
  while (!client.connected()) {
    Serial.print("Attempting MQTT connection to ");
    Serial.print(MQTT_SERVER);
    Serial.print(" on port ");
    Serial.println(MQTT_PORT);
    // Attempt to connect
#if MQTT_PORT == 1883
    // If you do not want to use a username and password
    if (client.connect("ESP8266_11")) {
#else
    if (client.connect("ESP8266_13", MQTT_USER, MQTT_PASSWORD)) {
#endif
      Serial.println("connected");
      client.publish("/test", "hello");      
      led_blink(led_built_in_Node, 5);
      digitalWrite(led_built_in_ESP, LOW);
    } else {
      Serial.print("failed, rc=");
      Serial.print(client.state());
      Serial.println(" try again in 5 seconds");
      led_blink(led_built_in_ESP, 15);
    }
  }
}


void setup_wifi() {
  delay(10);
  // We start by connecting to a WiFi network
  Serial.println();
  Serial.print("Connecting to ");
  Serial.print(WIFI_SSID);

  WiFi.mode(WIFI_STA);
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("");
  Serial.print("WiFi connected - IP address: ");
  Serial.println(WiFi.localIP());
}
```

And the output - connecting to unsecured Mosquitto on port 1883, it seems it does sometimes have to try twice to connect.

```
Connecting to Wifi_SSID.............................
WiFi connected - IP address: 192.168.88.234
Attempting MQTT connection to test.mosquitto.org on port 1883
failed, rc=-2 try again in 5 seconds
Attempting MQTT connection to test.mosquitto.org on port 1883
connected
```

Everything I have tried connecting to port 8883 and using just basic username & password security has resulted in rc=-2 errors.

My question - simple one first - how can I connect the ESP8266 to a secured Mosquitto broker using just username & password? Or do I have to dig in and find out about how to do it properly with certificates? Thank you in advance for any help.

**Comment by Charry2014** [comment]
So I was beginning to go a bit nuts with this and decided to bite the bullet and start to just understand certificates. On my way I got to the point of realising that even the espClient.connect was failing (either with the `BearSSL::WiFiClientSecure` or with the `WiFiClient`) and then everything stopped even before the certificates are checked.

Fortunately I discovered in passing this [gem](https://github.com/esp8266/Arduino/issues/4826) which seems to be the key that unlocks everything - and my credit to [brnyza](https://github.com/brnyza) for his one-liner 

`espClient.setInsecure();`

With this in place the ESP8266 connects, and publishes to the MQTT topics. Happy times. I will tidy up the code and post to GitHub.

**Comment by AdamMiltonBarker** [comment]
> So I was beginning to go a bit nuts with this and decided to bite the bullet and start to just understand certificates. On my way I got to the point of realising that even the espClient.connect was failing (either with the `BearSSL::WiFiClientSecure` or with the `WiFiClient`) and then everything stopped even before the certificates are checked.
> 
> Fortunately I discovered in passing this [gem](https://github.com/esp8266/Arduino/issues/4826) which seems to be the key that unlocks everything - and my credit to [brnyza](https://github.com/brnyza) for his one-liner
> 
> `espClient.setInsecure();`
> 
> With this in place the ESP8266 connects, and publishes to the MQTT topics. Happy times. I will tidy up the code and post to GitHub.

That, as the name of the function suggests, is highly insecure.
