### ISSUE TITLE
Check subscription status

### ISSUE THREAD

**Issue by HNJAMeindersma** [knolleary/pubsubclient#807]
Couple questions regarding subscriptions:
- Is there any way to check if the client is subscribed to a topic already? (like after a `client.connect()` when the connection was temporary lost according to `client.connected()`)
- Is it desirable to (re)subscribe every loop to make absolutely sure the client is subscribed to a specific topic? Or will this create an enormous amount of redundant network traffic and cause unwanted broker load?
- If subscribing multiple times to the same topic, will this result in multiple deliveries of a single topic? (not taking QoS into account)

**Comment by knolleary** [comment]
> Is there any way to check if the client is subscribed to a topic already?

No, you need to keep track of that in your code

> Is it desirable to (re)subscribe every loop to make absolutely sure the client is subscribed to a specific topic?

No. Do not do that. Subscribe once after you connect. Subscriptions do not disappear.

> If subscribing multiple times to the same topic, will this result in multiple deliveries of a single topic? 

No. You are either subscribed to a topic or not. The only scenario where you *might* get multiple messages is if you use wildcards in the topic and subscribe to two different topic filters that overlap in someway. For example `foo/bar` and `foo/+` will be separate subscriptions, but they overlap. It is then up to the broker as to whether you get one or two copies of a message - the spec allows for both behaviours.

**Comment by HNJAMeindersma** [comment]
Hypothetical situation: if my WiFi AP goes down my ESP8266 will lose network connection. Let's say for over 2 hours. Then the WiFi AP comes back online and the ESP8266 automatically reconnects to the network in its `void loop()`. Will MQTT subscriptions automatically be "restored" and will reception of subscribed topics automatically continue without resubscribing to them in the `void setup()`?

Note: I'm already calling `client.loop()` in every `void loop()`, FYI

**Comment by knolleary** [comment]
If the network connection is lost, you need to reconnect the MQTT client and resubscribe. The examples show how to check the connected state and trigger a reconnect when needed.

**Comment by HNJAMeindersma** [comment]
Meaning `if(mqtt_client.connected() != true || mqtt_client.state() != MQTT_CONNECTED) { client.connect(); }` I would also have to resubscribe after the (re)connect? Or are the subscriptions restored by the broker on a client ID/hostname basis?

**Comment by knolleary** [comment]
The client doesn't maintain any state for you. If it loses the connection, you need to resubscribe after reconnecting. Again, the examples provided show you how to do it. You don't need to test both `connected()` and `state()` ... Just use `connected()` and trigger a reconnect/resubscribe if it returns false.
