### ISSUE TITLE
Store Server-Adress to Spiffs

### ISSUE THREAD

**Issue by ghost** [knolleary/pubsubclient#815]
Hello, I am desperate about the following problem:
To change the MQTT server I have written a small website for my ESP8266. There the access can be changed and written to the Spiffs. This also works in principle.
The PubSubClient refuses to accept the server address read from Spiffs.
`const char* mqtt_server = "192.168.178.60";
  client.setServer(mqtt_server, myinputPort); Works!`
`String mqtt_server =  readFile(SPIFFS, "/inputServer.txt");
  client.setServer(mqtt_server.c_str(), myinputPort); Do not work!`

How can I convert the string to const char * so that the pub subclient accepts it?
Thanks!

**Comment by knolleary** [comment]
Have you checked the `String`  docs on how to convert it to a char buffer?

https://www.arduino.cc/reference/en/language/variables/data-types/string/functions/tochararray/

**Comment by ghost** [comment]
Solution:
`  IPAddress mqtt_server;
  if (mqtt_server.fromString(myinputServer)) {
    client.setServer(mqtt_server, myinputPort); 
    client.setCallback(callback);<br>
  }`
