### ISSUE TITLE
callback is triggered on start but there is no publish any message

### ISSUE THREAD

**Issue by karol93** [knolleary/pubsubclient#816]
hi,
Why callback function is triggered with topic param equals "someTopic" after call client.subscribe("someTopic")? is there correct behavior? I am not publishing any message on this topic

**Comment by knolleary** [comment]
Sounds like you have a retained message on the topic. You can check that by using a separate MQTT utility, like MQTT Explorer.

**Comment by karol93** [comment]
thx
