### ISSUE TITLE
pubsubclient error code 5

### ISSUE THREAD

**Issue by tophat17** [knolleary/pubsubclient#820]
Hello. 

I am trying to make a reconnect function for my program to handle any unexpected disconnects. 

```
void reconnect() 
{
  while (!client.connected())
  {
    client.disconnect(); // unsub and disconnect for good mesure. 
    client.unsubscribe(cmdTopic);
    client.setServer(broker, port);
    //client.setCallback(callback);
    Serial.print("Attempting MQTT connection... ");

    if (client.connect(cliantID)) 
    {
      Serial.println("reconnected!");
      client.publish(stateTopic, "connected");
      client.subscribe(cmdTopic);
    }

    else 
    {
      Serial.print("Failed to connect. Connection status: ");
      Serial.println(client.state());
      Serial.println("Attempting to reconnect in a few seconds.");
      delay(2000);
    }
  }
}
```
When I manually reset my wifi connection to test the functionality of the program, the "client.state()" function returns error code "-2" as expected. However, when the Wi-Fi comes back online, client.state() returns error code "5" and refuses to reconnect and return for the "reconnect()" function. 

If anyone is able to help me understand what error code "5" is and how I can solve it, that would be excellent.

**Comment by tophat17** [comment]
Error resolved. I still dont know what error 5 is, but changing `client.connect(cliantID)` to `client.connect(cliantID, mqttUser, mqttPassword)` solved my issue.

**Comment by knolleary** [comment]
The meanings of the error codes are documented here: https://pubsubclient.knolleary.net/api#state

An error code of 5 means `unauthorized` - so adding your username and password was the right answer.
