### ISSUE TITLE
Sparkplug support

### ISSUE THREAD

**Issue by JorivdKolk** [knolleary/pubsubclient#821]
Does the library support the use of Sparkplug for more redundant IIoT applications?

**Comment by knolleary** [comment]
There's nothing built-in specific to sparkplug. You are free to use whatever topic naming strategy you want.

**Comment by JorivdKolk** [comment]
would it be possible to implement the Sparkplug B specifications using the library?

**Comment by knolleary** [comment]
Sorry, I don't know enough about the sparkplug specification. As far as I know, sparkplug defines a set of topics and payload formats to use. This library is a generic MQTT client - it doesn't limit what topics/payload formats you use. So yes, I'm sure you could publish Sparkplug complaint messages with this library. But its up to you to determine those formats you want to use.

**Comment by JorivdKolk** [comment]
Thank you very much!
