### ISSUE TITLE
Is this lib abandoned?

### ISSUE THREAD

**Issue by sblantipodi** [knolleary/pubsubclient#822]
As title,
it seems that this lib has been abandoned.

There is no "real update" in the lib since years and there is no answers to issues.

Is the lib abandoned?

**Comment by knolleary** [comment]
Not abandoned as such. It's in stable maintenance mode. From my perspective it's feature complete for what it's intended to be. The code doesn't need to be constantly changing.

The vast majority of issues are user questions rather than bugs. Most are resolved outside of the library.

**Comment by sblantipodi** [comment]
ok, thanks for the answer.

**Comment by danilopinotti** [comment]
@knolleary I would like to suggest you close the old/deprecated PRs. Closing these PRs keeps a clean way to lib evolution, helps with the organization, encourages the contributors to evolve their suggestions and, as a result, it alleviates (a bit) the impression that the lib is abandoned.

This is the way that Laravel (PHP) framework team handles [their PRs](https://github.com/laravel/framework/pulls).
e.g https://github.com/laravel/framework/pull/38036
