### ISSUE TITLE
Problem in sending data to mqtt Using PubSubClient 

### ISSUE THREAD

**Issue by Eviothings** [knolleary/pubsubclient#837]
Hello, I am new, Using the MQTT protocol. My question is:- I have an array of 768, from the thermal sensor and able to display the array on Com Port.
Data from com Port:

Serial.print(mlx90640To[x],0); 

> 31,30,30,30,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,30,31,30,30,30,30,30,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,32,31,31,31,31,31,30,31,30,30,30,30,30,30,30,31,31,31,31,31,31,31,31,31,31,32,31,32,31,31,31,31,31,31,31,31,31,31,31,31,31,31,30,30,30,30,31,31,31,31,31,31,32,31,31,31,31,31,32,31,31,31,32,31,31,31,31,31,31,31,31,31,31,31,30,30,30,31,30,31,31,31,31,31,31,32,31,32,31,32,31,31,31,32,31,31,32,31,31,32,31,31,31,31,31,31,30,31,31,30,31,31,31,31,31,31,31,31,31,31,31,32,31,32,31,32,31,32,31,31,31,32,31,31,31,31,31,31,31,30,30,31,31,31,31,31,31,31,31,31,31,32,32,32,31,31,31,32,31,32,31,31,31,32,31,31,31,31,31,31,30,31,31,31,31,31,31,31,31,31,31,31,32,31,32,31,32,31,32,31,32,31,32,32,32,31,31,31,32,32,31,31,31,31,30,31,31,31,31,31,31,32,31,32,31,32,31,32,31,32,31,32,31,32,32,32,31,32,31,32,31,31,31,31,31,31,31,31,31,31,31,31,31,32,31,31,32,32,32,32,32,32,31,32,31,32,32,32,32,31,31,31,31,31,32,31,31,31,31,31,31,31,31,31,31,32,32,32,31,32,31,32,31,32,31,32,31,32,32,32,31,32,32,32,32,32,31,31,31,31,31,31,31,31,31,31,31,32,32,31,32,31,31,32,32,32,32,32,32,32,31,32,32,32,31,32,31,32,31,31,31,31,31,31,31,31,31,31,31,32,31,32,32,32,32,32,31,32,31,32,32,32,32,32,31,32,31,32,31,32,31,31,31,31,31,31,31,31,32,31,31,31,32,32,32,32,32,31,32,32,32,32,32,32,32,32,32,32,32,31,32,31,31,31,31,31,31,31,31,31,31,31,31,31,32,32,31,32,32,32,32,32,32,31,31,32,32,32,32,32,31,32,32,32,31,31,31,31,31,31,31,31,32,31,31,31,32,31,32,32,32,32,32,32,32,32,32,32,32,32,32,32,31,31,32,32,31,31,31,31,31,31,31,31,31,31,31,32,32,32,31,32,31,32,32,32,32,32,32,32,32,32,31,32,32,31,31,32,32,31,31,31,31,31,31,31,31,31,31,31,32,32,32,32,32,32,31,32,32,31,32,32,31,31,31,32,31,31,31,31,31,31,31,31,30,30,31,31,31,31,31,31,31,31,31,32,31,32,31,32,32,32,31,32,31,31,31,32,32,32,32,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,32,32,32,31,32,32,32,32,32,32,32,31,32,32,31,31,31,32,32,31,31,31,30,31,30,31,31,31,31,31,31,31,31,31,31,32,31,32,32,32,32,32,32,31,32,31,31,32,31,31,31,31,30,31,30,31,31,31,31,31,31,31,31,31,32,31,31,32,31,32,32,32,32,32,31,32,32,32,31,32,31,31,31,31,31,31,30,30,30,31,31,31,31,31,31,31,31,31,31,31,31,32,31,32,31,31,31,31,31,31,31,31,31,31,30,30,30,30,30,30,30,nan,31,31,31,31,31,31,31,31,31,31,32,32,31,31,31,31,31,31,32,31,31,31,31,31,31,31,30,31,

After that, I converted it to JSON Format and again read JSON format on the serial port I received JSON data.
JSON data on com Port:-
Serial.println(serializeJson(doc, Serial));
`

> {"device":"ESP32","sensorType":"T-Scanner","values":[30,30,30,30,30,30,30,31,30,30,31,31,31,31,31,31,31,31,31,31,30,31,30,31,30,30,30,30,30,30,30,30,30,30,30,30,31,30,31,30,31,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,30,30,30,30,30,30,30,30,30,30,30,31,30,30,31,31,31,31,31,31,31,31,31,31,31,31,31,30,31,31,30,30,31,30,30,30,30,29,29,30,30,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,30,30,30,30,30,30,30,30,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,30,30,30,30,30,30,30,30,31,31,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,30,30,30,30,30,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,30,31,30,30,30,30,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,30,30,30,30,31,31,31,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,30,30,30,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,30,30,30,31,30,30,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,30,30,30,30,30,31,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,30,30,30,30,30,30,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,30,30,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,30,30,30,30,31,30,31,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,30,30,30,30,30,30,31,31,31,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,30,30,30,30,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,30,30,30,30,30,30,31,31,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,30,31,31,30,30,29,30,30,31,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,30,30,30,30,30,30,30,31,31,31,31,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,30,31,30,30,30,30,30,30,30,30,31,30,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,30,30,30,30,30,29,30,30,30,30,30,31,31,31,31,31,31,30,31,31,31,31,31,30,31,31,31,31,31,30,30,31,31,30,30,29,30,30,30,30,255,30,30,30,30,31,30,31,30,31,31,31,31,31,31,31,31,31,31,31,30,31,31,30,30,30,30,30,30]}2359

`

Now before Publishing data to MQTT, I tried to read Char Buffer it only displays 249 Byte on the Com port.
Serial.println(JSONmessageBuffer);

> `{"device":"ESP32","sensorType":"T-Scanner","values":[30,30,29,30,30,30,30,30,31,30,30,30,31,30,31,30,31,30,30,31,30,31,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,31,31,30,31,31,30,31,31,31,31,30,30,30,30,30,30,30,30,30,30,30,30,30,29,30,30,30,30,30,30,31,31,31,31,31,30,31,31,31,31,31,31,31,31,31,31,30,30,30,31,30,30,30,29,30,30,30,30,30,30,30,31,31,31,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,30,31,31,30,30,29,30,30,30,30,31,31,30,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,30,31,31,30,30,30,30,30,30,30,31,30,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,30,30,30,30,30,30,30,30,30,31,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,30,30,30,30,30,30,30,31,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31`

Data display on Char Buffer same data Publish on MQTT Box.
if(client.publish(“ev8051/esp32/temperature”,JSONmessageBuffer,n) == true)
I had also change the value of **MQTT_MAX_PACKET_SIZE** in the **PubSubClient.h header.** 
But still facing an issue at the output only received 249 bytes of the array, is there some other modification that needs to do in the PubSubclient library.
Thanks in Advance...

**Comment by dawidchyrzynski** [comment]
Hi @Eviothings 

You need to increase the size of the buffer using `setBufferSize` method. The default size is 256 bytes.
