### ISSUE TITLE
mqtt connection

### ISSUE THREAD

**Issue by josefgull** [knolleary/pubsubclient#839]
i want to connect via the hostname instad of the ip. but it only works withe ip   if use the hostname in my broser i can reach the pc:/(/
works
  client=new EspMQTTClient (con.WifiName,con.WifiPass,"192.168.0.102",  "",  "",  con.Nodename, 1883 );
works not
  client=new EspMQTTClient (con.WifiName,con.WifiPass,"myhostname",  "",  "",  con.Nodename, 1883 );

**Comment by knolleary** [comment]
This isn't the repo for `EspMQTTClient`. I think you want https://github.com/plapointe6/EspMQTTClient

**Comment by josefgull** [comment]
i am sorry  i think i try your lib
