### ISSUE TITLE
messages larger than 256 sent but error reported

### ISSUE THREAD

**Issue by RalfJL** [knolleary/pubsubclient#85]
Hi,

great work.
I am trying to send a status message that is larger than 256 bytes.
So I increased
 #define MQTT_MAX_PACKET_SIZE 512
but method PubSubClient::write reports an error when sending messages larger than 256 bytes,  though messages are sent fine, and arrive at the broker complete.
I found that in line 412 the type of rc is uint8_t which is to small for the length. Changing that to uint16_t fixes the problem.

Please verify and change.

Thanks

Ralf

**Comment by roccomuso** [comment]
Thanks for reporting it.
