### ISSUE TITLE
Is possible send information about the device when is connecting?

### ISSUE THREAD

**Issue by DrakoPOD** [knolleary/pubsubclient#853]
For example, I have a device, that send temperature and humidity data, other that send Voltage and Current. I want that my server knows what kind of device it is before start publishing.
```javascript
//Device 1
  {
    name: 'device1',
    type: 'sensor',
    sensor: [ 'temp', 'hum' ]
  }
//Device 2
  {
    name: 'device2',
    type: 'sensor',
    sensor: [ 'volt', 'cur' ]
  }
```

**Comment by knolleary** [comment]
You can publish a message to a different topic with that information in.
