### ISSUE TITLE
Is this compatible with esp32-2.0.0-alpha1 development release 

### ISSUE THREAD

**Issue by Rp777** [knolleary/pubsubclient#856]
I am using this library in one of my hobby project.
I have been using this library for a couple of months now. 
It works fine with stable release for esp32 V1.0.6
Arduino IDE: V1.8.13

When I tried the same with V2.0.0-alpha1, I always get error code -2.
which is    -2 : MQTT_CONNECT_FAILED - the network connection failed
Using a MQTT broker without SSL using port 1883.

My connections work fine when i compile and connect with V1.0.6

But my connection is fine i am able to receive data from ntp server.

The reason I moved to alpha1 was because of FreeRTOS V10.2

Any pointers on this will be much appreciated.
Thanks in Advance.

**Comment by moelski** [comment]
Hi !
any news on this topic? 
Will pubsubclient work with the final 2.0 ESP32 release ? 

regards Dominik

**Comment by knolleary** [comment]
I do not have an ESP32 to test the library with. If any fixes or patches are needed, I am reliant on the community for any PRs needed.

**Comment by Rp777** [comment]
@knolleary Thanks.!
@moelski
 Yes it works.
I have tested it.

**Comment by hutje** [comment]
> @knolleary Thanks.! @moelski Yes it works. I have tested it.

How did you managed this?
