### ISSUE TITLE
How to set Exchange

### ISSUE THREAD

**Issue by SpaghettiCodeBoy** [knolleary/pubsubclient#876]
Is it possible to set the Exchange somehow? I get my messages published but it's not the right Exchange.

**Comment by knolleary** [comment]
What do you mean by Exchange? That isn't an MQTT term I recognize.

**Comment by SpaghettiCodeBoy** [comment]
For RabbitMQ there are Exchanges that route the messages. :/

**Comment by knolleary** [comment]
This is a pure mqtt client. It doesn't know anything about rabbit mq.

**Comment by SpaghettiCodeBoy** [comment]
Ahhh I just found out that, thank you very much. So only topics are supported? Sorry, I'm not very familiar with MQTT. What's the best way to transmit data between two devices then?

**Comment by knolleary** [comment]
You connect them both to an MQTT broker and publish/subscribe to topics.

**Comment by SpaghettiCodeBoy** [comment]
Ah ok, thank you very much!
