### ISSUE TITLE
Publish returns 1 in some cases even if client is not connected

### ISSUE THREAD

**Issue by dlyckelid** [knolleary/pubsubclient#885]
Hi!

We are having an issue with the publish function and we loose a couple of messages every time the wifi looses connection (If not all has been sent already)

We found this issue at a customer where they have som problems with their Wifi router and it fairly regurlary restarts and all clients loose connection. We have 10 devices and they all have the same problem. 
The program collects data in one core and stores it in a queue and then we have another core that works with sending the data. So if the publish returns 1 then the message gets removed from the queue. It seems like when the connection is lost during a send-operation it can still send 2-3 messages and get 1 in return but infact the messages was never recieved by the broker. Then it starts to return 0 and it jumps out and tries to reconnect but ofcourse the 2-3 messages are lost.
I thought that it could only be a succesfull publish if the broker answered but that seems to not be the case. Is there any settings that I can use that will demand answer from the broker?
Has this something to do with buffers in WiFi?
I use a esp32

**Comment by knolleary** [comment]
This library only supports qos 0 message - fire and forget - that doesn't include any acknowledgement from the broker that the message has been received. That can allow for messages to be discarded if there's any interruption in the network.

**Comment by dlyckelid** [comment]
> This library only supports qos 0 message - fire and forget - that doesn't include any acknowledgement from the broker that the message has been received. That can allow for messages to be discarded if there's any interruption in the network.

Ok. That was what I was afraid of. I will have to do an implementation myself then to make sure the message was recieved. In our usercase no message is allowed to be missed. We save it in local memory aswell incase of poweroutage or other issue so this is the last piece in the puzzle to make the information chain secure. Thank you for the responce so I can focus on the development instead of searching for issues.

**Comment by ruem2802** [comment]
@dlyckelid i have same issue, i connected mqtt but if Lost connection, client.connected() return true, publish ok. About 15s client.connected() return false and during 15 second i can't do anything: button can't press, led can't on/off. Can you show me how to check lost connection. check client.connected() not working in that time
