### ISSUE TITLE
connect timeout not working, ESP32 stuck if mqtt broker is not available

### ISSUE THREAD

**Issue by dsilletti** [knolleary/pubsubclient#887]
pubsubclient v2.8
ESP32 arduino core 2.0.0 RC1

in case the mqtt broker is not available, the connect function does not return a timeout error code but stucks

**Comment by dsilletti** [comment]
solved using setSocketTimeout()

**Comment by slavino** [comment]
This should work out of the box with default 15 seconds timeout. 

https://github.com/knolleary/pubsubclient/blob/2d228f2f862a95846c65a8518c79f48dfc8f188c/src/PubSubClient.h#L36

**Comment by dsilletti** [comment]
@slavino You are right, but was too much for my 5 seconds watchdog, I changed it to 2 seconds with setSocketTimeout(2), now the wdt is not triggered anymore. Hopefully 2 seconds will be enough in most cases.
