### ISSUE TITLE
pubsub over serial - Raspberry Pi / Arduino

### ISSUE THREAD

**Issue by scls19fr** [knolleary/pubsubclient#89]
Hello,

I would to subscribe from a Raspberry Pi to events that occured on an Arduino board (such a rising or falling edge). I would also like Arduino acquire data from analog digital converter and publish values on "topic".

I noticed that pubsubclient only support ethernet / wireless based Arduino board but maybe you have some tips to do this pub sub over USB serial.

Kind regards

**Comment by knolleary** [comment]
The library supports anything that provides an implementation of the arduino platform's Client.h interface. If you were to create a Serial implementation that adheres to this interface, then you could make use of the client. On the RPI end of the serial link you'd also need something that forwards the USB comms to a TCP connection to an MQTT Broker.

**Comment by scls19fr** [comment]
thanks for your quick reply

**Comment by MAbdelatti** [comment]
That is really helpful. I'm working on a similar project. What are possible ways to forward the USB comms to a TCP connection?
