### ISSUE TITLE
compatibility with opensensors.io?

### ISSUE THREAD

**Issue by metawops** [knolleary/pubsubclient#90]
According to the documentation for publishing messages on the publicly available MQTT installation at opensensors.io – available [here](http://support.opensensors.io/support/solutions/articles/6000025066-publishing-to-a-topic-using-mosquitto) – I need to send a *DeviceID* and a *DevicePassword* and a *Username*. 
How can I do this with your library?

**Comment by knolleary** [comment]
Hi,

the library supports providing all three of these properties, for example this call to `connect`: http://pubsubclient.knolleary.net/api.html#connect3

What they call _DeviceID_ is more commonly called _ClientId_ in the MQTT world. Username/Password are as you would expect.

**Comment by metawops** [comment]
Thanks so much for your super quick reply and the hint to *ClientId*! Will try ... :)
