### ISSUE TITLE
mosquitto not working

### ISSUE THREAD

**Issue by oe8bck** [knolleary/pubsubclient#91]
I have started a MQTT server on my server, it's http://mosquitto.org/. But this communication does not work:
---
1447361659: mosquitto version 0.15 (build date 2013-08-23 19:23:43+0000) starting
1447361659: Opening ipv4 listen socket on port 1883.
1447361659: Opening ipv6 listen socket on port 1883.
1447361660: New connection from 10.0.1.146.
1447361660: Invalid protocol "MQTT" in CONNECT from 10.0.1.146.
1447361660: Socket read error on client (null), disconnecting.
---
the wireshark dump:
---
00000000  10 19 00 04 4d 51 54 54  04 02 00 0f 00 0d 45 53 ....MQTT ......ES
00000010  50 38 32 36 36 43 6c 69  65 6e 74                P8266Cli ent
---
What's wrong?

KR,
Christof

(UAH, the style is ugly, how to set plain ASCII mode?)

**Comment by chaeplin** [comment]
Looks like your mosquitto is old one. Use mosquitto 1.3.4 at least.

**Comment by oe8bck** [comment]
Well, I used the one that is in the repository of my Ubuntu. Thanks for the hint, with test.mosquitto.org it works...
