### ISSUE TITLE
Char/Byte array with two zeros after each other, result in scrambled or cutoff of payload. 

### ISSUE THREAD

**Issue by andreasqlight** [knolleary/pubsubclient#929]
I have a msgpack payload message as a char array: 

`82 A1 73 A1 30 A1 6D 84 A1 30 94 CD 01 30 00 00 CA 43 64 66 66 A1 31 94 21 00 00 CA 43 64 66 66 A1 32 94 18 00 00 CA 43 64 66 66 A1 33 94 CC B9 00 00 CA 43 64 66 66`

It is a parsed JSON message, thus giving me possible double zeros `00 00` This seems to make pubsubclient think the message is already over.

When I send the message as a byte array with the proper length I get this on the receiver side:

`<Buffer 82 a1 73 a1 30 a1 6d 84 a1 30 94 cd 01 30 00 a5 a5 a5 a5 a5 03 00 00 00 a5 a5 a5 a5 a5 a5 a5 a5 a5 a5 a5 a5 a5 a5 a5 a5 a5 a5 a5 a5 a5 a5 a5 a5 a5 a5 ... 5 more bytes>`

When I just provide the char array directly I get:

`<Buffer 82 a1 73 a1 30 a1 6d 84 a1 30 94 cd 01 30>`

Can I get around this somehow? As it seems to send the byte array properly up until the double zeros.

Edit:

This would be the function I'm using atm with payload as byte array:
```
boolean PubSubClient::publish(const char* topic, const uint8_t* payload, unsigned int plength) {
    return publish(topic, payload, plength, false);
}
```

**Comment by knolleary** [comment]
If you are publishing as `char*` then it will determine the length based on the first null it finds - as all C strings do.

Given your payload is *not* a string, its a msgpack buffer, you should be using the `uint8_t*` type `publish` that also takes the `length` argument.

**Comment by andreasqlight** [comment]
This was on my end related to some transformation of the byte array
