### ISSUE TITLE
PubSubClient with 2 clients

### ISSUE THREAD

**Issue by mikeme2009** [knolleary/pubsubclient#931]
Hi

I need to declare PubSubClient depending on a pin status. If status is 1 I will use PubSubClient mqttClient(ethClient), if pin= 0 PubSubClient mqttClient(wifiClient). 
How can I do that?
I tried:
WiFiClient wifiClient;
EthernetClient ethClient;
PubSubClient mqttClient(digitalRead(22) == 0 ? wifiClient : ethClient);  - But error: no matching function for call to 'PubSubClient::PubSubClient(int)'

Thanks

**Comment by knolleary** [comment]
You can se the [`setClient` function](https://pubsubclient.knolleary.net/api#setClient) to set which network client the library uses as part of the `setup()` function:

Something like this:

```
WiFiClient wifiClient;
EthernetClient ethClient;
PubSubClient mqttClient;

...

void setup() {
    if (digitalRead(22) == 0) {
        mqttClient.setClient(wifiClient);
    } else {
        mqttClient.setClient(ethClient);
    }
}
```

**Comment by mikeme2009** [comment]
It worked!
Thank you
