### ISSUE TITLE
Publish stream with unknown length

### ISSUE THREAD

**Issue by AddioElectronics** [knolleary/pubsubclient#935]
Instead of serializing JSON data to a string, and then publishing, I am wanting to serialize to publish stream.
Problem is I do not know the length before hand, and do not want to calculate each value and key in the JSON document.

Is it ok to pass beginPublish() a length larger than what I send, and call endPublish prematurely?
Or would I have to send dummy data after?

My idea is something like this, just wondering if there is a right and a wrong way to do this.

```
bool success = false;
size_t docSize = document->capacity();

if (success = mqttClient.beginPublish(topic, docSize, deviceMqttSettings.retain))
{
	size_t size = serializeJson(document, mqttClient);

	while (docSize > size)
	{
		mqttClient.write((uint8_t)" ");
		size++;
	}

	success = mqttClient.endPublish();
}
```

**Comment by IronBamBam1990** [comment]
size_t len = measureJson(doc);
But you can do this at other way

**Comment by AddioElectronics** [comment]
Ahh thanks. 
Did not know that function exists.
