### ISSUE TITLE
subscribe using wildcard!

### ISSUE THREAD

**Issue by rozrabiak** [knolleary/pubsubclient#943]
Why this doesn't work?

mqttClient.subscribe("greenhouse/#");

Damn!

**Comment by IronBamBam1990** [comment]
You can try
const char *TOPIC = "greenhouse/#";
mqttClient.subscribe(TOPIC);

**Comment by rozrabiak** [comment]
> You can try const char *TOPIC = "greenhouse/#"; mqttClient.subscribe(TOPIC);

That's works!
Thank's so much!
