### ISSUE TITLE
ESP32 TTGO v1 cannot conect to mosquitto MQTT broker hosted by windows

### ISSUE THREAD

**Issue by miguelbidarra** [knolleary/pubsubclient#985]
Hello everyone! I've been struggling with this issue for quite a while and I can't seem to understand how to fix it.
I'm using an ESP32 TTGO OLED v1 to send temperature information through mosquitto MQTT to be displayed in node red, being the MQTT broker and node red hosted by my computer which is running windows 10.
As you can see in my code, I'm connecting my ESP to the WiFi (yes I change the password to the "real" password not the three dots) and then to the PC IP (192.168.1.74) which corresponds to the MQTT broker IP. Although node-red connects to the broker as you can see in the images, the ESP32 refuses to establish connection. Can someone help me find the solution to this problem?

This is the error I get from ESP:
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds

I've aso tried to allow listeners on the mosquitto.conf file and allow_anonymous but it is irrelevant as it continues to print out this error.

![dashboard](https://user-images.githubusercontent.com/77495092/209556064-58ea4346-a5ec-4f64-83ed-7c44ce9342c3.png)
![esp_error](https://user-images.githubusercontent.com/77495092/209556065-35cbae9e-310f-4ca0-958a-876a9cb352c1.png)
![mosquitto](https://user-images.githubusercontent.com/77495092/209556066-d911284d-6844-4edb-a235-db7bbae1f003.png)
![node-red](https://user-images.githubusercontent.com/77495092/209556069-306ef0ea-55b0-40bb-a014-f500c9bd4d16.png)
![wif](https://user-images.githubusercontent.com/77495092/209559311-f7c5a871-aec9-4a53-b776-600918209680.png)

I'm a bit desperate cause I've searched all the internet, all issues and none of the solutions fit my case. Thank you everyone :)

**Comment by miguelbidarra** [comment]
.

**Comment by vbercy** [comment]
Hello, I may have the same problem. How did you solve it ?
